### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#10]
Ajouter un bouton "Documentation" dans le menu qui renvoie à une page de documentation. Idéalement on devrait pouvoir la maintenir en accédant à un file html statique sur githb - ou en md... J'ai rédigé une première version disponible dans le fichier README.md. Une possibilité est juste de mettre un lien vers le README

**Comment by lakonis** [comment]
j'avais ajouté ta doc (`projet/doc.md`) en mettant à jour aussi la roadmap (projet/roadmap.md). Attention à ne pas confondre le readme.md de la racine qui est censé documenter le repo, et une documentation de l'outil en production. 
Il faut effectivement une doc, mais il faut décider de ce qu'on fait : 
1. une doc pour utiliser l'outil dans le cadre de la revue SP : avec pratiquement le protocole éditorial
2. une doc de présentation de l'outil et de son fonctionnement
3. une doc pour écrire un article en md

L'idée d'un article par défaut "pour démarrer" est une bonne idée, mais du coup une partie de ta documentation n'est peut-être pas utile. Tout en l'étant ailleurs.
