### ISSUE TITLE
Tag partagés?

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#1012]
Serait-il judicieux de créer des tags partagés dans les workspaces? 
Cas d'usage spécifique: on utilise des tags pour publier automatiquement des sites web d'une revue ou d'un projet (tous les articles qui ont le tag "publié" par exemple). Mais si on travaille en équipe, il faut que chaque membre de l'équipe crée le tag.

**Comment by RochDLY** [comment]
C'est un sujet que nous avons évoqué lors des tests des espaces de travail. cf [#813](https://github.com/EcrituresNumeriques/stylo/issues/813).

**Comment by ggrossetie** [comment]
Je cloture car on a déjà #813 qui existe. Je vais ajouter un commentaire avec le cas d'usage de Marcello.
