### ISSUE TITLE
Dysfonctionnement du filtre de sélection des collections de références bibliographiques Zotero

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#1014]
**Version de Stylo**

3.0.7

**Fonctionnement actuel**

Dans le gestionnaire de références bibliographiques d'un article Stylo, pour l'import d'une collection depuis "mon compte Zotero".
J'ai accès à un menu déroulant contenant toutes mes collections Zotero.

Pour réduire les collections affichées, il est possible de taper quelques lettres dans l'entrée du menu déroulant et filtrer les collections Zotero.

Néanmoins, lorsque je clique sur le nom d'une collection pour la sélectionner, ce n'est pas celle-ci qui est récupérée par Stylo mais la première de la liste sans le filtre (c'est-à-dire avec toutes mes collections).

Dans ce cas il n'est pas possible d'utiliser le filtre pour réduire les collections affichées dans mon gestionnaire de référence Stylo.

**Fonctionnement souhaité**

Une fois que le filtre réduit le nombre de collections affichées dans le menu déroulant, la sélection d'une collection devrait correspondre avec les informations que récupère Stylo dans le gestionnaire de références bibliographiques.

**Informations complémentaires**

![Peek 2024-07-24 12-43](https://github.com/user-attachments/assets/cbcc69f1-0bbf-4273-9dfd-6bb706d62934)

**Comment by thom4parisot** [comment]
Quand on filtre, ça renumérote l'index de chacun des items affichés.

Quand on clique sur le premier élément d'une liste filtrée, ça va donner l'index 0. C'est l'index 0 de la liste non-filtrée qui est utilisée.

**Comment by thom4parisot** [comment]
Il avait bientôt deux ans ce bug 🎂 dès sa mise en prod !
