### ISSUE TITLE
Créer un composant react pour le volet des métadonnées

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#1031]
Le composant des métadonnées est actuellement intégré dans le composant [`Write`](https://github.com/EcrituresNumeriques/stylo/tree/master/front/src/components/Write).

On en trouve des parties à différents endroits, cf. [`yamleditor`](https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/components/Write/yamleditor/YamlEditor.jsx), [`ArticleEditorMetadata`](https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/components/Write/ArticleEditorMetadata.jsx) et du [`scss`](https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/components/Write/articleEditorMetadata.module.scss). (Ce n'est peut-être pas exhaustif).

L'objectif est de séparer ces éléments de l'élément `Write` pour en faire un composant react à part entière qui puisse être appelé dans l'interface d'édition, mais aussi dans d'autres espaces de Stylo.

**Comment by ggrossetie** [comment]
Liste des tâches à faire : 

- [x] Le composant `Form` (formulaire dynamique à partir d'un schema) ne doit pas convertir les données en YAML (dans `handleUpdate`). La raison est que l'on souhaite enregistrer les métadonnées du corpus au format JSON.
- [x] Permettre de charger un schema et un UI schema
- [x] Remonter la notion de `basicMode` (et de choix du UI schema dans la YamlEditor)

**Comment by thom4parisot** [comment]
@ggrossetie la conversion peut se faire avec un `setter` Mongoose, non ? Pour l'instant c'est pas encore clair sur comment on interroge les données (cf. #1066 ; via des filtres Mongo ou si on rajoute une abstraction par-dessus 😱 ou [directement en utilisant un JSON Schema en requête](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/) ?). Ça éviterait d'empiler plusieurs manières de gérer les métadonnées pour l'instant.

**Comment by ggrossetie** [comment]
Je pense qu'on peut considérer cet ticket comme terminé avec une première étape de faite. On pourra créer des tickets plus précis pour ce qu'il reste à faire.
