### ISSUE TITLE
L'export génère une URL qui retourne une erreur

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#104]
Par exemple :

https://stylo-export.ecrituresnumeriques.ca/cgi-bin/exportArticle/exec.cgi?id=Test_1v0-2&version=5e6f2a6bc9a7060019fcd4f1&processor=xelatex&source=https://stylo.huma-num.fr/&format=html5&bibstyle=chicagomodified&toc=false

```
sed -i -e s/5e6f2a6bc9a7060019fcd4f1/Test_1v0-2/g Test_1v0-2.yaml pandoc --standalone --verbose --filter pandoc-citeproc --table-of-contents -f markdown -t latex --csl ../templates/chicagomodified.csl --pdf-engine=xelatex Test_1v0-2.md Test_1v0-2.yaml -o Test_1v0-2.pdf >> bash.log
Getting PDF file ready
Getting ZIP file ready
  adding: bash.log (stored 0%)
```

https://stylo-export.ecrituresnumeriques.ca/export/Test_1v0-2.pdf

**Comment by ggrossetie** [comment]
> Par exemple :
> https://via.hypothes.is/https://stylo.huma-num.fr/api/v1/htmlArticle/5e6cb960c9a7060019fcd4e2?preview=true

J'ai corrigé ce problème ce matin. Le conteneur Docker " export-stylo" expose maintenant le port 3060 sur le host et j'ai configuré NGINX pour faire un "proxy pass" sur `/api`.

> L'export pointe sur l'instance ecrituresnumeriques.ca : https://stylo-export.ecrituresnumeriques.ca/

Je pense qu'il faudrait créer une issue spécifique car ce problème n'est pas lié avec le problème ci-dessus.
D'après ce que j'ai pu comprendre, l'export utilise un script (des outils en ligne de commande comand `pandoc`) via `cgi-bin`.
Le problème est que j'ai l'impression que c'est installé à la main sur "stylo-export.ecrituresnumeriques.ca" car je n'ai trouvé aucune référence au script d'export dans le dépôt...

> Le lien vers la documentation pointe sur l'instance ecrituresnumeriques.ca : http://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!index.md

Même chose, je pense qu'on devrait créer une issue séparé non ?

**Comment by thom4parisot** [comment]
Ça roule pour une issue séparée. J'avais l'impression que ça pouvait être dû à des config hardcodée ou autre, mais ça n'est pas le cas visiblement.

**Comment by ggrossetie** [comment]
En y regardant de plus près ça n'a pas l'air d'être le cas, je vais créer les issues :wink:

**Comment by marviro** [comment]
L'export en effet est sur un serveur séparé. C'est un verveur apache qui fait tourner un script bash très artisanal - que j'ai fait moi même. On peut imaginer, à terme, qu'on fera un export plus propre sur les serveurs huma-num. Mais pas prioritaire pour le moment. Le code de l'export est ici: https://framagit.org/stylo-editeur/process (branch book)

**Comment by ggrossetie** [comment]
> L'export en effet est sur un serveur séparé. C'est un verveur apache qui fait tourner un script bash très artisanal - que j'ai fait moi même. On peut imaginer, à terme, qu'on fera un export plus propre sur les serveurs huma-num. Mais pas prioritaire pour le moment. 

Cela veut dire qu'il faut installer un serveur Apache sur le serveur https://stylo.huma-num.fr ?
En regardant rapidement, je pense que cela ne vas pas être si simple que ça car le script n'est pas "indépendant". Dans le script [exec.cgi](https://framagit.org/stylo-editeur/process/-/blob/master/cgi-bin/exportArticle/exec.cgi) on peut voir des références en dur à https://stylo.ecrituresnumeriques.ca

Est-ce qu'il y a une raison particulière d'utiliser un script cgi-bin plutôt que d’exécuter directement la ligne de commande (ou le programme Bash) à partir du backend Node.js ?

**Comment by marviro** [comment]
1. Pour le moment ne nous posons pas le problème: on reste sur ecrituresnumeriques. On décidera plus tard - ça demande une réflexion un peu poussée sur les exports et à qui ils seront destinés. Donc pas de serveur apache sur humanum.
2. Nous avions décidé de ne pas dépendre directement de stylo pour avoir une structure plus modulaire. On peut rajouter des exports ad hoc - pour des revues spécifiques par exemple - et les gérer indépendemment de stylo. On pourrait par contre déployer un autre serveur nodejs et éviter apache et bash qui sans doute ne sont pas ce qu'il y a de plus élégant - sauf que pandoc dans node a des limitations. Ici aussi: on verra. Il faut d'abord réfléchir aux besoins.
3. Les références en dur ne seraient pas un problème car le script va lire les paramètres de l'url et l'url source y est. C'est juste des restes de mon code sale ;) - En Réalité, par ailleurs, le script d'export générique (celui auquel fait appel Stylo quand on demande l'export) n'a pas d'écrituresnumeriques en dur): c'est l'exec.cgi dans exportArticle. Les autres sont des exports spécifiques pour des revues - qui pour le moment resteront sur l'instance Stylo.ecrituresnumeriques

**Comment by ggrossetie** [comment]
> Pour le moment ne nous posons pas le problème: on reste sur ecrituresnumeriques. On décidera plus tard - ça demande une réflexion un peu poussée sur les exports et à qui ils seront destinés. Donc pas de serveur apache sur humanum.

Ok.
Par contre, actuellement, j'ai l'impression que cela ne fonctionne pas.
Par exemple, ce lien, généré par l'instance https://stylo.huma-num.fr :

https://stylo-export.ecrituresnumeriques.ca/cgi-bin/exportArticle/exec.cgi?source=https%3A%2F%2Fstylo.huma-num.fr%2F&id=Test_1v0-2&version=5e6f2a6bc9a7060019fcd4f1&format=html5&bibstyle=chicagomodified&processor=xelatex

Le fichier zip contient uniquement un fichier `bash.log` et le lien vers le fichier d'export (pdf, html...) retourne une 404. Par exemple, https://stylo-export.ecrituresnumeriques.ca/export/Test_1v0-2.html

Peut être qu'il manque quelque chose sur https://stylo.huma-num.fr ? Comment est-ce qu'on peut analyser pour comprendre d'où vient le problème ?

> Nous avions décidé de ne pas dépendre directement de stylo pour avoir une structure plus modulaire. On peut rajouter des exports ad hoc - pour des revues spécifiques par exemple - et les gérer indépendemment de stylo. On pourrait par contre déployer un autre serveur nodejs et éviter apache et bash qui sans doute ne sont pas ce qu'il y a de plus élégant - sauf que pandoc dans node a des limitations. Ici aussi: on verra. Il faut d'abord réfléchir aux besoins.
> Les références en dur ne seraient pas un problème car le script va lire les paramètres de l'url et l'url source y est. C'est juste des restes de mon code sale ;) - En Réalité, par ailleurs, le script d'export générique (celui auquel fait appel Stylo quand on demande l'export) n'a pas d'écrituresnumeriques en dur): c'est l'exec.cgi dans exportArticle. Les autres sont des exports spécifiques pour des revues - qui pour le moment resteront sur l'instance Stylo.ecrituresnumeriques

Ok.

**Comment by marviro** [comment]
Je vais le debuguer quand j'ai un instant. Merci

**Comment by marviro** [comment]
> Par exemple, ce lien, généré par l'instance https://stylo.huma-num.fr :
> 
> https://stylo-export.ecrituresnumeriques.ca/cgi-bin/exportArticle/exec.cgi?source=https%3A%2F%2Fstylo.huma-num.fr%2F&id=Test_1v0-2&version=5e6f2a6bc9a7060019fcd4f1&format=html5&bibstyle=chicagomodified&processor=xelatex

Alors: mon script va chercher le fichier zip à cette adresse:
https://stylo.huma-num.fr/zipVersion/5e70bf1fc9a7060019fcd4fb

J'ai l'impression que l'endpoint ne fonctionne pas

Voici un exemple sur écrituresnumeriques:
https://stylo.ecrituresnumeriques.ca/zipVersion/5e6bb0104f58270018f9e03a

En principe donc ça dépend de Stylo et pas de l'export. Pourriez-vous regarder?

**Comment by thom4parisot** [comment]
> En principe donc ça dépend de Stylo et pas de l'export. Pourriez-vous regarder?

C'est _plus_ ou _moins_ important que la pagination Zotero ?

**Comment by marviro** [comment]
Moins ;)

**Comment by marviro** [comment]
Ok, j'ai une info qui peut peut-être aider. Actuellement stylo.huma-num sert les zip à cette adresse 

https://stylo.huma-num.fr/api/v1/zipVersion/versionId

stylo ecrituresnumerique sert aussi à

https://stylo.ecrituresnumeriques.ca/zipVersion/versionId

C'est probablement juste une question de redirection: il faut dire que /api/v1/ = /
Mais pas urgent. Je peux aussi adapter mon script pour prendre en compte que quand ça vient d'humanum il faut ajouter api/v1

**Comment by ggrossetie** [comment]
Effectivement il y a 3 endpoints pour le même service :
```js
app.get('/zipVersion/:id',exportVersionZip);

// New nomenclature
app.get('/version/:id/zip',exportVersionZip);

// Duplicate for old way
app.get('/api/v1/zipVersion/:id',exportVersionZip);
```

https://github.com/EcrituresNumeriques/stylo/blob/master/export/src/app.js

Pour le moment, le reverse proxy NGINX redirige uniquement `/api` vers le service "export".
Si on veut supprimer le préfixe `/api` il serait préférable d'utiliser un sous-domaine pour éviter les conflits et ne pas avoir une configuration NGINX alambiquée.
 
Personnellement, je pense qu'il est préférable de conserver un préfixe, cela simplifie l'installation de Stylo et donne la possibilité d'utiliser le même nom de domaine tout en conservant une configuration NGINX relativement simple.
Si le préfixe `/api` est trop générique, on peut utiliser `/export` car le service est dédié à l'export.

La nouvelle nomenclature me semble pertinente, on aurait donc:

```js
app.get('/export/version/:id/html',exportVersionHtml);
app.get('/export/version/:id/zip',exportVersionZip);
app.get('/export/article/:id/html',exportArticleHtml);
app.get('/export/book/:id/html',exportBookHtml);
app.get('/export/book/:id/zip',exportBookZip);
app.get('/export/tag/:ids/zip',exportBatchTagZip);
```

A noter qu'il est possible avec Express 4.0 de faire:

```js
var router = express.Router();
router.use('/version/:id/html', exportVersionHtml);
app.use('/export', router);
```

Dernière question, est-ce que le versioning est important ? C'est peut être dommage de supprimer la `v1` si cette API a vocation à être publique.

Après je pense que le script "cgi-bin" ne devrait pas dépendre d'un autre serveur mais être appelé avec l'ensemble des informations/données (en mode API). Sinon on est sur une intégration forte et les deux services sont étroitement liés.

Si c'est un sujet à traiter je peux créer des issues GitHub dédiés ?
Je vais déjà créer une issue pour rediriger les endpoints suivants vers le service "export" dans la configuration NGINX:

- `/htmlVersion`
- `/htmlArticle`
- `/zipVersion`
- `/htmlBook`
- `/zipBook`

**Comment by ggrossetie** [comment]
J'ai crée des tickets sur GitHub pour ne pas perdre nos discussion.

Le service d'export fonctionne maintenant avec l'instance https://stylo.huma-num.fr/login.

Je pense qu'on peut clôturer ce ticket et continuer la discussion sur les autres tickets quand le moment sera venu.
