### ISSUE TITLE
Les articles dans les workspace ne sont pas triés comme dans mon espace personnel

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#1056]
![image](https://github.com/user-attachments/assets/40dec05b-0d2e-4b6a-b77e-092c080f34c7)

**Comment by ggrossetie** [comment]
@thom4parisot Doublon avec https://github.com/EcrituresNumeriques/stylo/issues/1172 ? Je suppose que c'est corrigé avec https://github.com/EcrituresNumeriques/stylo/pull/1173 ?

**Comment by thom4parisot** [comment]
Ah ah oui carrément, bien vu merci 😅 j'étais persuadé d'avoir créé une issue mais je ne la retrouvais pas.

Duplicate of #1172
