### ISSUE TITLE
Documentation: les builds ne fonctionnent plus sur Netlify

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#1082]
Le [commentaire](https://github.com/EcrituresNumeriques/stylo/pull/1081#issuecomment-2454433004) de @RochDLY :

> a priori on aurait un problème avec node pour le build de la preview netlify (il faudrait la version >= 18) et une fonction ReadableStream() qui ne serait pas définie dans les versions précédentes. Lors du build on utiliser un versuin 16 de node.

Cela affecte la construction de la documentation sur Netlify.

Il faudrait probablement spécifier la version de Node à utiliser dans le compte de @ggrossetie (c'est sous son compte Netlify).

On pourrait aussir spécifier cela dans le `package.json` : 

```json
{
  "engines" : {
    "node" : ">=18.0.0"
  }
}
```

**Comment by loup-brun** [comment]
C'est clair que c'est une question de Node.js (la version 16 est EOL / fin de vie).

Les logs (ex. [Netlify deploy](https://app.netlify.com/sites/stylo-docs/deploys/6728a289ff018200081be50b)):

```
5:32:17 AM: Installing npm packages using npm version 8.19.4
5:32:18 AM: npm WARN EBADENGINE Unsupported engine {
5:32:18 AM: npm WARN EBADENGINE   package: 'cheerio@1.0.0',
5:32:18 AM: npm WARN EBADENGINE   required: { node: '>=18.17' },
5:32:18 AM: npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
5:32:18 AM: npm WARN EBADENGINE }
5:32:18 AM: npm WARN EBADENGINE Unsupported engine {
5:32:18 AM: npm WARN EBADENGINE   package: 'undici@6.20.1',
5:32:18 AM: npm WARN EBADENGINE   required: { node: '>=18.17' },
5:32:18 AM: npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
5:32:18 AM: npm WARN EBADENGINE }
5:32:18 AM: npm WARN EBADENGINE Unsupported engine {
5:32:18 AM: npm WARN EBADENGINE   package: 'whatwg-encoding@3.1.1',
5:32:18 AM: npm WARN EBADENGINE   required: { node: '>=18' },
5:32:18 AM: npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
5:32:18 AM: npm WARN EBADENGINE }
5:32:18 AM: npm WARN EBADENGINE Unsupported engine {
5:32:18 AM: npm WARN EBADENGINE   package: 'whatwg-mimetype@4.0.0',
5:32:18 AM: npm WARN EBADENGINE   required: { node: '>=18' },
5:32:18 AM: npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
5:32:18 AM: npm WARN EBADENGINE }
```

**Comment by ggrossetie** [comment]
> Navigate to [Site configuration > Build & deploy > Continuous deployment > Dependency management](https://app.netlify.com/sites/stylo-docs/configuration/deploys#dependency-management) in the Netlify UI and select from the major Node.js versions that Netlify currently supports. Once you change the version, you need to redeploy your site for it to take effect. Note that a NODE_VERSION environment variable, .node-version file, or .nvmrc file will override this UI setting.

https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

**Comment by ggrossetie** [comment]
J'ai modifié la version dans l'UI de Netlify et j'ai aussi positionné la version dans un `.node-version` ainsi que dans le `netlify.toml`
