### ISSUE TITLE
Écrire une documentation sur l'architecture technique

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#109]
Expliquer :
- les différents composants (front, service d'export,  base de données MongoDB, l'API GraphQL...)
- les liens et la communication entre les différents composants
- les différents conteneurs Docker

**Comment by PookMook** [comment]
Bonjour bonjour,
j'ai pas vraiment le temps de faire beaucoup pour stylo en ce moment mais je vais essayer de vous aider la dessus.
Si vous avez des questions spécifique, n’hésitez pas!
Le projet à pas mal évolué au fil des années (et la façon de coder à aussi beaucoup changer + aléas de l'administration fini par avoir quelque chose de semi-fait), et certains composants sont devenus part de stylo mais n'étaient pas nécessairement prévu pour, et il reste beaucoup de choses a faire, mais je vais tenter de vous faire un descriptif. 

ps: le code "utilisable" sans erreur d'ESLint à la compilation est dans le branche de dev

**Comment by ggrossetie** [comment]
Bonjour Arthur,

> j'ai pas vraiment le temps de faire beaucoup pour stylo en ce moment mais je vais essayer de vous aider la dessus.
Si vous avez des questions spécifique, n’hésitez pas!

Merci :smile: 

> Le projet à pas mal évolué au fil des années (et la façon de coder à aussi beaucoup changer + aléas de l'administration fini par avoir quelque chose de semi-fait), et certains composants sont devenus part de stylo mais n'étaient pas nécessairement prévu pour, et il reste beaucoup de choses a faire, mais je vais tenter de vous faire un descriptif.

Je pense que Thomas et moi on commence à avoir une bonne vision du projet. 
J'ai une question concernant le choix de Gatsby, est-ce que tu peux nous expliquer les raisons de ce choix ?

> ps: le code "utilisable" sans erreur d'ESLint à la compilation est dans le branche de dev

Est-ce qu'on peut fusionner la branche dev sur master sans risque ?

**Comment by thom4parisot** [comment]
Oui, l'idée c'est que Guillaume et moi écrivions cette documentation.
Si on te demande une relecture ça irait ?

Pareil que Guillaume pour la branche dev :) (surtout qu'elle a 8 commits d'avance par rapport à `master`).

**Comment by PookMook** [comment]
@Mogztter Désolé pour le réponse tardive, dev est sans risque à ma connaissance, juste des commits basique de j'avais fait avec Antoine, qui n'a finalement pas continuer sur le projet.

Pour Gatsby, honnêtement les raisons ne sont plus excellente aujourd'hui, le postulat de base était de faire la documentation et l'aide technique directement via markdown sur le front-end (d'où l'utilisation de gatsby) et de générer quelques pages statiques squelettes pour l'application
Ces squelettes finalement chargeraient les articles via une API quelconque (sails pour la preuve de concept, mais finalement pas suffisant pour nos besoin et trop difficile à maintenir, et ensuite graphQL très maison (les polices d’autorisation sont inexistantes par exemple car pas le temps d'implementer encore))
Aujourd'hui, la documentation est placé ailleurs, un CRA ou un nextjs pourraient faire la même chose, mais je ne pense pas que ce soit un gros gain de changer, à moins que vous soyez plus à l'aire avec une autre solution. 
Il faut voir que le projet cours sur un assez long moment, je pense qu'il a été démarré sur react 15.5 si je me souviens bien, et qu'il était fait comme un projet sur le coté de mon travail de jour. Il y a des plusieurs façons de faire, plusieurs époques /  degrés de connaissance de react mélangés (sans compter les projets qui ont été glués ensembles, comme le YAMLeditor), donc l'architecture peut paraître un peu surprenante également.
Je me gardais dans le coin de l'esprit la possibilité de générer des pages pour les articles publiés statiquement via l'interface graphQL de gatsby, mais il y a toujours eu quelque chose de plus pressant à faire.

@oncletom parfait pour une relecture pour moi, ne pas hésiter a m'envoyer un courriel en même temps, mes notifications github sont inondés
