### ISSUE TITLE
Supprimer les onglets dans le formulaires des métadonnées

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#1094]
Nous avons décidé de regrouper le "Basic mode" et le "Journal mode", notamment en permettant de replier certaines sections (voir #1093).

On garde la possibilité de passer en "Raw mode" (YAML). Peut être que l'on peut revoir le nommage et ajouter une icone indiquant qu'il s'agit d'un format YAML. "Voir le code source" ? "Voir les données brutes" ? "Éditer au format YAML". Peut être ajouter aussi un petit lien sur la syntaxe YAML (au passage je n'ai pas trouvé une ressource "officielle" qui explique rapidement la syntaxe YAML)

**Comment by RochDLY** [comment]
On peut peut-être afficher un lien vers la documentation de Stylo ? On a une page dédiée à la syntaxe YAML (<https://stylo-doc.ecrituresnumeriques.ca/fr/syntaxe-yaml/>). Attention, l'URL va changer au prochain déploiement du fait de la restructuration de la documentation (et on risque de changer le nom du fichier / slug).

**Comment by ggrossetie** [comment]
Ajout d'un toggle pour basculer entre le mode interactif (formulaire) et le mode YAML:

![Image](https://github.com/user-attachments/assets/cd8c23da-58ad-4cd7-a8e4-62a596944c3c)
