### ISSUE TITLE
Le fichier .env n'est pas pris en compte lors de npm run build

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#1097]
La fonction `loadEnv` s'attend à un chemin vers un fichier mais `import.meta.resolve('..')` retourne une URL (i.e., `file:///path/to/directory`)

https://github.com/EcrituresNumeriques/stylo/blob/779e50a4274bddaa3fa7f0889cde01feed4f86b5/front/vite.config.js#L9

Il faudrait convertir l'URL en path ou utiliser `import.meta.dirname` afin de donner un path à la fonction `loadEnv`. Il est aussi envisageable de proposer à Vite/dotenv de charger un fichier à partir d'une URL/URI ?

**Comment by thom4parisot** [comment]
On pourrait utiliser `import.meta.dirname` en bumpant la version de Node ; c'est pas gênant pour le front.

Sinon y'a aussi [`fileURLToPath()`](https://nodejs.org/api/url.html#urlfileurltopathurl-options) qui fait l'affaire sans bumper de version.

```js
import { fileURLToPath } from 'node:url'

//… 

const env = loadEnv(mode, fileURLToPath(import.meta.resolve('..')), 'SNOWPACK_')
```
