### ISSUE TITLE
Curseur instable en fin d'article

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#11]
Sur un article, on rencontre un problème de stabilité sur la fin d'un article. Plusieurs symptomes : 
1. il n'est plus possible de sélectionner du texte ou de coller du texte.
2. le sommaire semble avoir sauté, le bloc sommaire s'est élargit.
3. le problème se règle au bout de quelques minutes.... 

@ServanneMo pourra préciser et te partager l'article pour jeter un oeil. Ca ressemble à un bug de caractère spécial.

**Comment by ggrossetie** [comment]
@lakonis est-ce que ce bug est toujours présent? si c'est le cas, est-ce que tu as un id d'article pour qu'on puisse reproduire l'anomalie?

**Comment by lakonis** [comment]
Je suggère de fermer, c'est trop vieux.. Stylo a beaucoup bougé depuis.
