### ISSUE TITLE
Limiter la taille des images Docker

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#112]
Une bonne pratique Docker consiste à produire des "petites" images. Actuellement les images sont assez volumineuses...

```
stylo_export-stylo-prod       latest     db3ffe926d5d     2.33GB
stylo_front-stylo-prod        latest     ad17fb868dd6     1.12GB
stylo_graphql-stylo-prod      latest     909ee5c6350d     929MB
```

Généralement j'essaie de produire des images < 500 mo en utilisant des distributions comme Alpine.

**Comment by thom4parisot** [comment]
Yes, avec les multi-stage build c'est pratique pour n'installer que des outils systèmes qui sont "jetés" avant la création de l'image finale.

**Comment by thom4parisot** [comment]
Fait avec #223. Et à continuer spécifiquement sur le service `export` dans #226.

```
stylo_front-stylo                      latest                  9211bcec19a0      833MB
stylo_graphql-stylo                    latest                  4f512f400b52      141MB
```
