### ISSUE TITLE
Migration des métadonnées

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#1125]
"Meta issue" permettant de lister les points à réaliser/vérifier afin que la migration se passe bien : 

- [x] Tester le script de migration des données sur la base de données de stylo-dev
   - [x] Vérifier les articles/versions sur lesquels la transformation du YAML en métadonnées JSON n'a pas fonctionné
- [x] L'API GraphQL doit renvoyer les métadonnées au format YAML legacy sur le champ `article { yaml }` et `version { yaml }`. Permet de garantir la rétrocompatibilité avec l'API export
- [x] L'API GraphQL ne doit plus permettre de mettre à jour le champ `yaml` (il faut dorénavant mettre à jour le champ `metadata` en envoyant du JSON)
- [x] S'assurer que l'interface Stylo n'utilise plus le champ `yaml`
- [x] Modifier l'éditeur de métadonnées afin d'utiliser les données au format JSON
- [x] Vérifier le bon fonctionnement des champs calculés (`title`, `title_f`, `month`, `day`...). Est-ce qu'on conserve ce fonctionnement dans les métadonnées JSON ? 
- [x] Déplacer la logique `convertLegacyValues` dans une migration de base de données et supprimer le code : https://github.com/EcrituresNumeriques/stylo/blob/6bd84a22900647be29e5e153b16ee15eeb8df939/front/src/components/metadata/MetadataValues.js#L6
- [x] Lancer la migration sur un dump de la base de données de production afin de vérifier les articles/versions sur lesquels la transformation du YAML en métadonnées JSON n'a pas fonctionné
- [x] S'assurer que la migration se termine correctement (fermer la connexion à l'instance?)

#### Questions 

Est-ce qu'on conserve le "Default YAML" dans le profil utilisateur ?

![image](https://github.com/user-attachments/assets/090c69a9-8309-466c-a4ae-50bc20029026)

**Comment by ggrossetie** [comment]
> Est-ce qu'on conserve le "Default YAML" dans le profil utilisateur ?

Dans l'immédiat, on supprime cette fonctionnalité.

**Comment by thom4parisot** [comment]
Il y a 285 utilisateurs avec un champ yaml par défaut, avec 26 valeurs différentes.

```mongo
db.users.find({ yaml: {$ne: null} })

db.users.distinct('yaml').length
```

Y'a de fortes chances que c'était un des moyens de sauver des métadonnées particulières à des publications.

C'est ça le raisonnement qui nous dit de déplacer / supprimer cette fonctionnalité en faveur des modèles de métadonnées par publication ?

**Comment by ggrossetie** [comment]
Je pense qu'il y a plusieurs raisons : 
- fonctionnalité assez peu utilisée
- la majorité des valeurs renseignés sont soit invalides soit sont un reliquat de valeurs positionnées par défaut
- il n'y a pas de validation du format YAML (il est donc possible de bloquer son export si on fait une erreur de saisie)
- on pense que ce n'est pas le bon endroit (comme tu l'as dis on pense que les modèles de métadonnées par revue/publication est plus pertinent)
