### ISSUE TITLE
Pas d'Images

### ISSUE THREAD

**Issue by Pixflowave** [EcrituresNumeriques/stylo#1142]
Les images même via lien ne semblent pas pouvoir s'afficher...

**Comment by ggrossetie** [comment]
Bonjour,

Est-ce que vous pouvez détailler les actions que vous avez réalisez ? Je viens de faire un test avec l'image ci-dessous et elle s'affiche correctement dans la prévisualisation : 

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSItC97Cr7eWv_G-OAmufw7oL-pyB_zUrHk_Q&s"/>

```
![image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSItC97Cr7eWv_G-OAmufw7oL-pyB_zUrHk_Q&s)
```


## Article

<img width="671" alt="Capture d’écran 2024-12-10 à 08 57 34" src="https://github.com/user-attachments/assets/99f350be-248e-4896-a51b-93f13b6f0a73">

## Prévisualisation

<img width="610" alt="Capture d’écran 2024-12-10 à 08 57 02" src="https://github.com/user-attachments/assets/c64611cc-a2ed-435d-9a49-ca0a9d1c084d">

**Comment by Pixflowave** [comment]
Bonjour,

`![figure 3: Néguentropie : un espace de recherchecontributive du point gris de Paul KleeImage : E. Bozec,2023](https://do.doc.dev.pixflowave.fr/spaces/neguentropie/projects/printemps-des-cartes/3-figure.png){width="11.469cm"height="9.202cm"}`

dans l'éditeur 

![Capture d’écran 2024-12-10 à 12 19 20](https://github.com/user-attachments/assets/71d26624-8f2b-4d1a-a83a-05f6fe753e4c)


Prévisualisation
![Capture d’écran 2024-12-10 à 12 18 28](https://github.com/user-attachments/assets/ac1ce947-e476-4f31-b2dc-42b17aaa91d1)

le document est un export via Pandoc .odt -> .md

**Comment by thom4parisot** [comment]
L'erreur remontée dans la console est 

> The resource at “https://do.doc.dev.pixflowave.fr/spaces/neguentropie/projects/printemps-des-cartes/3-figure.png” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP).

**Comment by Pixflowave** [comment]
j'ai modifié le serveur mais je ne vois pas l'image de plus : 

cette image fonctionné mais ne fonctionne plus..

iframe width=“100%” height=“750” frameborder=“0” src=“https://observablehq.com/embed/([pixflowave/neguentropie?cells?](https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/6728ee5433b8f40011fac0d0?preview=true#ref-pixflowave/neguentropie?cells))=chartz”>/iframe> figure 1 : Schéma partiel du pharmakon Néguentropie - Cartographie de bifurcations Noétiques

**Comment by Pixflowave** [comment]
le souci vient de dodoc... je discute avec @louis-ev

**Comment by louis-ev** [comment]
Exact, c'est entièrement lié à la `Cross-Origin-Resource-Policy` de dodoc (réglé en `same-origin` par défaut).
Je suis un peu frileux pour la passer en `cross-origin`, je ne sais pas si je le fais d'office ou comme un réglage spécifique.

**Comment by ggrossetie** [comment]
Est-ce qu'il y a quelque chose que l'on peut améliorer côté Stylo ou est-ce qu'on considère qu'il n'y a rien à faire et qu'on peut clôturer cette issue ?

**Comment by Pixflowave** [comment]
J’ai trouvé une astuce avec une version de Do•doc qui a moins de contraintes (CROS). En revanche j’utilise régulièrement hackmd.io qui accepte directement les images dans la page… à un moment ils utilisaient imgur.com pour stocker les images..ça crée un lien automatiquement comme sur GitHub

**Comment by ggrossetie** [comment]
> En revanche j’utilise régulièrement hackmd.io qui accepte directement les images dans la page… à un moment ils utilisaient imgur.com pour stocker les images..ça crée un lien automatiquement comme sur GitHub

On avait évoqué l'idée de s'intégrer avec https://nakala.fr/ pour stocker des images. Je ne suis pas sûr qu'utiliser un service externe comme imgur soit en accord avec les valeurs de Stylo.

Est-ce que vous pouvez s'il vous plait créer une demande d'évolution (i.e., une nouvelle issue) avec le comportement souhaité et les arguments en faveur de l'ajout de cette fonctionnalité ?

Je cloture cette issue afin d'éviter de mélanger les deux sujets.
