### ISSUE TITLE
Suppression des entrées `senspublic.translations` et `senspublic.linkedArticle` du schéma des métadonnées

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#1148]
Il s'agit d'entrées héritées depuis plusieurs années. Nous avons eu confirmation qu'elles ne sont plus utilisées (pour les vieux articles qui les utilisent, garder les clef:valeur comme des entrées customisées).

**Comment by ggrossetie** [comment]
C'est déjà le cas, j'ai conservé les valeurs dans `senspublic.translations` et `senspublic.linkedArticles`:

https://github.com/EcrituresNumeriques/stylo/blob/6bd84a22900647be29e5e153b16ee15eeb8df939/graphql/helpers/metadata.js#L521-L525

Mais les champs ne sont pas déclarés dans le JSON schema (et donc non visible dans le formulaire): https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/schemas/article-metadata.schema.json
