### ISSUE TITLE
Rafraichir la Bibliothèque depuis Stylo

### ISSUE THREAD

**Issue by Pixflowave** [EcrituresNumeriques/stylo#1163]
Bonjour,
Serais-t'il possible d'avoir un bouton pour rafraichir la bibliothèque sans avoir à remplacer à nouveau par la même afin de récupérer les mises à jour ?

**Comment by thom4parisot** [comment]
Quelle différence(s) fais-tu entre remplacer la bibliothèque existante et la mettre à jour ? C'est dans le cas où t'aurais ajouté manuellement d'autres références (hors Zotero), que tu souhaiterais conserver ?

Peut-être en doublon de #729

**Comment by Pixflowave** [comment]
non, pour l'instant j'ajoute ou je corrige dans l'application Zotero mais pour retrouver les modifications je dois passer par "remplacer" ce qui finit par être contraignant. un petit bouton actualisation comme sur l'app ou un mode automatique serait le bienvenue.
![Capture d’écran 2024-12-13 à 14 28 32](https://github.com/user-attachments/assets/a429f0fc-cc57-4a24-8569-07a838de3e7e)

effectivement j'avais cherché rafraichir et non refresh pardon pour le doublon #729

**Comment by thom4parisot** [comment]
Aucun problème :) (je n'avais plus cette demande en tête non plus 😅)

**Comment by thom4parisot** [comment]
Duplicate of #729
