### ISSUE TITLE
Les articles des workspaces ne sont pas triés par date de modification

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#1172]
Contraitement aux articles du workspace personnel.

![image](https://github.com/user-attachments/assets/8bea0f50-aef8-4aa3-876b-27c279397b17)

Je ne comprends pas trop la logique de la méthode `workspaceResolver/articles()` : 

https://github.com/EcrituresNumeriques/stylo/blob/d699f900805dc12ace91b7ba438b2d5176a7b405/graphql/resolvers/workspaceResolver.js#L121-L126

Pourquoi ça fonctionne différemment de `articleResolver/articles()` ?

https://github.com/EcrituresNumeriques/stylo/blob/d699f900805dc12ace91b7ba438b2d5176a7b405/graphql/resolvers/articleResolver.js#L295-L303

**Comment by ggrossetie** [comment]
Je pense que c'est parce que les articles n'ont pas de lien avec les espaces de travail. On récupère la liste des identifiants des articles sur l'espace de travail et on charge les articles associés (jointure en mémoire avec les loaders).

Concernant le tri, je ne sais pas trop pourquoi on utilise la date de création plutôt que la date de modification, c'était peut être une demande ou une incohérence... 

Enfin, pour le filtre sur les articles supprimés, on devrait surement s'assurer qu'on supprime le lien avec le ou les espaces de travail quand on supprime un article. Et surement faire une migration pour s'assurer qu'on a pas ce cas dans la base de données.

```js
.filter((a) => a !== undefined) // remove deleted articles 
````

**Comment by thom4parisot** [comment]
Ah ouais, ok je comprends. Je vais regarder comment faire.

Y'a une raison qu'on gère le tags et les workspaces différemment ? Au sens où les tags sont des entités, et on les référence dans les articles. Alors que les workspaces référencent les articles.

**Comment by ggrossetie** [comment]
Les workspaces sont des conteneurs alors que les tags sont libellés qu'on appose sur des "objets". Je trouve ça plus logique d'avoir articles -> tags et workspaces -> articles.
Les articles sont aussi ordonnés dans le workspace, si on fait le lien au niveau des articles on ne perd cette notion d'ordre.
