### ISSUE TITLE
Utiliser une URL de connexion pour MongoDB dans le backend

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#122]
Permet de réduire le nombre de variables d'environnement: https://docs.mongodb.com/manual/reference/connection-string/

Actuellement, on utilise 3 variables : 

https://github.com/EcrituresNumeriques/stylo/blob/a189fa94b7479ee24209b643e10c642b81db9dc3/graphql/app.js#L17-L19

**Comment by ggrossetie** [comment]
Maintenant qu'on utilise convict on peut surement s'inspirer de https://github.com/mozilla/node-convict/issues/93#issuecomment-173534732

**Comment by thom4parisot** [comment]
C'est adressé dans #1046
