### ISSUE TITLE
Permettre de se connecter à Stylo sans utiliser HumanID

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#123]
Avec https://github.com/EcrituresNumeriques/stylo/pull/120 la connexion à Stylo se fait maintenant exclusivement via HumanID. 

Si on veut continuer de permettre à des utilisateurs d'installer Stylo sur leur infrastructure sans utiliser HumanID, il faut mettre en place un mécanisme permettant de choisir son mode d'authentification.

Ce mécanisme sera aussi utile en mode développement si on ne veut pas ou peut pas se connecter à l'instance de test HumanID (par exemple si un contributeur ne connait pas le client ID et le secret).

ping @marviro @antoinentl

**Comment by antoinentl** [comment]
Effectivement cela simplifierait (ou permettrait tout court) l'installation en dehors de l'environnement Huma-Num, mais ce point n'est pas prioritaire à ce stade.

Si cette fonctionnalité est simple et rapide à mettre en place @marviro et moi nous vous laissons choisir le moment opportun pour la déployer.

**Comment by ggrossetie** [comment]
Corrigé dans https://github.com/EcrituresNumeriques/stylo/issues/151
