### ISSUE TITLE
validation des mot-clé auteurs dans la version auteur du yamlEditor

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#13]
sur stylo.ecrinum.ca, les mots-clés auteurs ne s'affichent pas dans la preview html. J'ai l'impression qu'ils ne sont pas pris en compte dans le yamlEditor, même si j'ai quelque chose dans les champs.
Est ce qu'il manque un bouton de validation ?

**Comment by PookMook** [comment]
changé le CSS les boutons de validations devraient apparaitrent à nouveau!
![image](https://user-images.githubusercontent.com/14223903/39950971-860d0750-5553-11e8-88f0-4a77e4a04e01.png)
