### ISSUE TITLE
Automatiser le build de chaque image Docker

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#130]
Pour lever les erreurs, notamment de `gatsby build` qu'on découvre au dernier moment pour l'instant.

Ça ouvre la voie à : 

1. l'automatisation de la publication des images sur Docker Hub (#131)
2. ~~l'installation de Stylo en 1 seule ligne, en faisant un `wget` du `docker-compose.yml`, qui pull des images fonctionnelles du Hub~~

**Comment by ggrossetie** [comment]
> Pour lever les erreurs, notamment de gatsby build qu'on découvre au dernier moment pour l'instant.

Ce point a été traité : 
https://github.com/EcrituresNumeriques/stylo/blob/53be0af40247ac251b292d4fd2550951f57cc93a/.github/workflows/ci.yml#L21-L22

> l'automatisation de la publication des images sur Docker Hub

Je pense qu'on peut suivre ce point sur #131 

> l'installation de Stylo en 1 seule ligne, en faisant un wget du docker-compose.yml, qui pull des images fonctionnelles du Hub

Peut être qu'il faudrait changer le titre pour conserver uniquement ce point. Si je comprends bien : 

1. Publication des images sur Docker Hub (#131)
2. Simplification du déploiement

   * Dépose le fichier `docker-compose.yml` (avec la version des conteneurs) + configuration
   * Récupération des images à partir de Docker Hub (via docker-compose)
   * Redémarrage des conteneurs (via docker-compose)
