### ISSUE TITLE
Point sur l'application "migrate"

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#138]
Quel est le but de cette application ? Est-ce qu'elle est utilisée ? Fonctionnelle ? Est-ce qu'on peut la supprimer ?

Code : https://github.com/EcrituresNumeriques/stylo/tree/dev/migrate

ping @antoinentl @marviro

**Comment by marviro** [comment]
Malheureusement je n'en ai aucune idée... @PookMook ?

**Comment by PookMook** [comment]
migration sails -> graphQL pour le backend, petits changement de structure de la base de donnée, l'ORM de sails faisait des choses un peu bizarre. 
Safe pour suppression! @Mogztter

**Comment by ggrossetie** [comment]
> migration sails -> graphQL pour le backend, petits changement de structure de la base de donnée, l'ORM de sails faisait des choses un peu bizarre.
Safe pour suppression! @Mogztter

Ok merci pour ton retour @PookMook :+1:
