### ISSUE TITLE
Rendre les sidebars Menu et Metadata responsives

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#144]
On vise :

- un iPad en paysage + clavier
- un ordinateur 13"

Exemple de quand ça dérange : 

- quand on arrive sur un article, un des panneaux s'ouvre et masque le texte
- sur un macBook 13", quand on ouvre 1 ou 2 panneaux

**Comment by ggrossetie** [comment]
On peut aussi améliorer un peu le style pour gagner de la place. Actuellement les barres latérales font 400px chacune donc 800px de moins sur 1200px ça fait beaucoup !

J'ai fais un rapide redesign en m'inspirant de Bulma :

#### Actuel (400px de large) 

<kbd>![current](https://user-images.githubusercontent.com/333276/78817924-2fc9bf80-79d4-11ea-9d85-56b8f39603e3.png)</kbd> 

#### Nouveau (325px de large)

 <kbd>![redesign-right-menu](https://user-images.githubusercontent.com/333276/78817921-2e989280-79d4-11ea-8db6-d594310d6259.PNG)</kbd>

Si on fait la même chose de l'autre côté on peut gagner 150px.

**Comment by ggrossetie** [comment]
@maiwann je te ping sur cette issue car j'avais commencé un redesign (inspiré par Bulma: https://bulma.io/)  afin de gagner un peu de place en largeur.
À voir si on reprend l'idée sur #500

**Comment by maiwann** [comment]
Je ne suis plus sure de comment avancer sur la partie métadonnées,
ta proposition graphique est plus élégante et prends moins de place, donc on pourrait faire avec ça fait faire un pas en avant,

et en même temps, si on va retravailler cette partie, je ne voudrais pas qu'on mette ces modifications en place pour qu'ensuite on les change et que ça piétine ce que tu as fait…

(il faudrait aussi que je me rende compte si ça tranche avec les autres formulaires de Stylo, auquel cas ça ne serait pas forcément pratique car on perdrait en uniformité)

Tu le sens comment toi ?

**Comment by ggrossetie** [comment]
Je pense que ça peut venir dans un second temps. Mon idée était de progressivement améliorer graphiquement les formulaires en s'inspirant de Bulma (avec quelques touches de couleurs !).

Il faut juste garder en tête qu'on peut descendre à 325px de large an ajustant un peu les styles.

**Comment by ggrossetie** [comment]
On peut considérer que c'est fait dans #763 
Si besoin, créer des nouvelles demandes d'améliorations sur des points spécifiques.
