### ISSUE TITLE
Permettre de récupérer des collections privées Zotero

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#145]
Actuellement, Stylo récupère uniquement il faut que les collections publiques Zotero (car on utilise l'API en mode non authentifié).

L'idée serait de pouvoir préciser un token pour récupérer des collections qui sont accessibles uniquement lorsque l'on est authentifié. 

Documentation de référence OAuth Authentication sur Zotero: https://www.zotero.org/support/dev/web_api/v3/oauth

**Comment by GJaquet91** [comment]
Bonjour, 
J'essaie depuis quelques jours de synchroniser ma bibliothèque Zotero avec Stylo (je suis toutes les démarches prévues sur le site de support et sur la plateforme pour pouvoir proposer un article (mode publique de la collection, mise en forme dans l'URL) mais cela ne marche pas (il apparaît qu'une page vide). Je voudrais savoir si Stylo a des problèmes techniques à ce sujet ou si peut-être il se produit un problème dans mon ordinateur... 
Je vous remercie de l'attention!

> Actuellement, Stylo récupère uniquement il faut que les collections publiques Zotero (car on utilise l'API en mode non authentifié).
> 
> L'idée serait de pouvoir préciser un token pour récupérer des collections qui sont accessibles uniquement lorsque l'on est authentifié.
> 
> Documentation de référence OAuth Authentication sur Zotero: https://www.zotero.org/support/dev/web_api/v3/oauth

**Comment by marviro** [comment]
Actuellement il y a des bugs avec la synchro zotero. Stylo arrive à récupérer seulement les premières références (une vingtaine). Ça sera bientôt fixé.
Pour voir si c'est un autre problème, essayez de synchroniser avec une collection PUBLIQUE de maximum 15 références. Dans ce cas ça devrait fonctionner.

**Comment by GJaquet91** [comment]
Bonjour,

Merci de votre retour. C'était bien ça le problème, j'attendrai donc que toutes les références puisent être prises pour continuer l'édition chez Stylo.

Je vous remercie!

Cordialement

Gabriela

________________________________

**Comment by thom4parisot** [comment]
Et l'issue à suivre pour obtenir la complétude des références Zotero est #41 — cette présente page concerne les références _privées_ ; si toutes vos collections sont privées, ça expliquerait la liste vide.

**Comment by GJaquet91** [comment]
Bonjour,

Pardon, c'est quoi #41?

J'ai fait une collection et groupe publique pour les listes à synchroniser, le problème maintenant est que le système ne synchronise jamais plus que 24, d'un total de 68 pour moi... alors c'est très difficile de faire usage des réferences car il faut qu'elles soient là toutes en meme temps pour continuer l'affichage dans le texte.

Je vous remercie!
________________________________

**Comment by thom4parisot** [comment]
Ah oui pardon 🙂 #41 c'est [Récupération de l'ensemble des résultats via l'API Zotero](https://github.com/EcrituresNumeriques/stylo/issues/41), justement car comme Marcello l'indiquait, à l'heure actuelle Stylo récupère seulement une partie des collections. Ce qui explique que vous n'en ayiez pas plus de 24.

Quand les collections seront récupérées entièrement, le chemin sera ouvert pour récupérer les collections privées (issue #145).

**Comment by GJaquet91** [comment]
Merci.
Et vous avez déjà une prévision de la restauration de ce problème de synchronisation? 
Est-ce qu'il est possible d'importer des réferences autrement en attendant?

**Comment by marviro** [comment]
Nous travaillons à une version 2 de stylo qui sera lancée à l'automne. Pour le moment la meilleure manière est de :
1. exporter les références zotero en bibtex
2. les copier-coller dans stylo.
La procédure est décrite [ici](http://archive.sens-public.org/IMG/pdf/Utiliser_Zotero.pdf) - et [ici](http://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!pages/bibliographie.md)

Il est possible d'utiliser le plugin [bettebitex](https://retorque.re/zotero-better-bibtex/) pour tenir à jour automatiquement un fichier bibtex à partir d'une collection.

**Comment by GJaquet91** [comment]
D'accord. J'essaye maintenant d'exporter les references en bibtex pour les insérer manuellement mais je ne connais pas bien le système. Je suis les indications sur les liens, mais après avoir fait cela sur zotero, le document crée est d'un type que n'ouvre pas pour voir la clé "raw", et quand je clique sur lui il me renvoie à nouveau à zotero...

________________________________

**Comment by GJaquet91** [comment]
Je n'arrive nottament pas à ouvrir un fichier exporté de zotero, pour finelament avoir une bibtex raw et pouvoir la coller manuellement à stylo. Faut-il encore un autre programme por le faire?

________________________________

**Comment by marviro** [comment]
il faut un éditeur de texte quelconque. C'est du plain texte. À ouvrir par exemple avec textedit sous mac ou bloc notes sur windows - ou alors avec n'importe quel autre éditeur de texte

**Comment by GJaquet91** [comment]
Merci, je ne savais pas. Ça a marché!
________________________________

**Comment by GJaquet91** [comment]
Hello
Ça marche pour les références. Mais il y a-t-il un bug maintenant au niveau des visualisations en "preview" de stylo?
Merci!

________________________________

**Comment by marviro** [comment]
tout fonctionne. Il est possible que certaines de vos références soient mal structurées. Pour de questions de ce type, je vous invite à profiter de la permanence stylo en vidéoconférence tous les jeudis (hélas c'était aujourd'hui) à 11h de Montréal [ici](meet.jit.si/stylo). Sinon, veuillez documenter davantage le problème que vous avez.

**Comment by GJaquet91** [comment]
C'est toute la page de "preview" qui n'ouvre plus (elle marchait très bien jusqu'à 18h, maintenant seulement un onglet). De plus, même si les références sont mal structurées, le preview ouvrait et on pouvait justement voir les erreurs...

________________________________

**Comment by marviro** [comment]
Il suffit qu'il y ait une accolade non fermée dans le bibtex. Essayez d'enlever le bibtex et de reessayer. Si ça fonctionne, cela signifie que le bibtex a un problème de syntaxe. La meilleure manière est de refaire l'export depuis zotero en veillant à que toutes les références soient bien faites Le debug de la previw n'est pas optimal actuellement, je sais.

**Comment by marviro** [comment]
Si vous le souhaitez et si cela ne vous pose pas de problèmes, vous pouvez partager votre article avec moi et j'essayerai de voir d'où vien le problème. Pour éviter le partage, vous povez aussi faire un send au lieu qu'un share (j'aurai une copie de votre texte mais pas le même que vous). Mon adresse sur stylo est vitalirosati@gmail.com. Évidemment cela vaut si votre texte ne contient rien de confidentiel et que vous êtes à l'aise avec l'idée que je le voie.

**Comment by GJaquet91** [comment]
Marcello, merci beaucoup de votre attention. J'ai fait comme vous avez dit et ça a marché, uffa! J'avoue que c'est une aventure pour moi, mais voilà, problème reglé. En tout cas, c'est bien d'apprendre à l'utiliser. Merci de la patience!

________________________________

**Comment by marviro** [comment]
merci à vous d'utiliser stylo. Vos retour sont précieux. On sait que pour le moment c'est encore à l'état de prototype. On devrait améliorer le tout d'ici quelques mois.

**Comment by antoinentl** [comment]
Un retour concernant la gestion des collections privées :

- pour le moment si j'intègre une collection privée et que je supprime la clé d'accès à Zotero je conserve les items, @Mogztter tu me confirmes cela ? En soit cela ne me paraît pas gênant ou bloquant ;
- une fois une collection importée il n'y a pas de synchronisation : il s'agit d'un import à un moment donné, si la collection est mise à jour il faut re-sélectionner la collection. Peut-être qu'ajouter un bouton "Mettre à jour la collection" pourrait être un plus ? Dans ce cas on déborderait de la fonctionnalité initiale ;
- peut-être qu'il faudrait (et ce serait notre job) clarifier cette fonctionnalité : il s'agit d'un _import_ d'une collection privée.

**Comment by ggrossetie** [comment]
> pour le moment si j'intègre une collection privée et que je supprime la clé d'accès à Zotero je conserve les items, @Mogztter tu me confirmes cela ? En soit cela ne me paraît pas gênant ou bloquant ;

Oui c'est bien le comportement que nous avons développé.
De mon point de vue, je pense qu'il est préférable de ne pas supprimer les items.

> une fois une collection importée il n'y a pas de synchronisation : il s'agit d'un import à un moment donné, si la collection est mise à jour il faut re-sélectionner la collection. Peut-être qu'ajouter un bouton "Mettre à jour la collection" pourrait être un plus ? Dans ce cas on déborderait de la fonctionnalité initiale ;

C'est exact.
On peut d'ailleurs importer plusieurs collections privées.
Si on souhaite mettre en place une synchronisation, il y a plusieurs cas à prendre en compte :
- cas où l'utilisateur a des items renseignés manuellement ainsi qu'une collection synchronisée automatiquement
   * il faut pouvoir dissocier les items renseignés manuellement et ceux synchronisés automatiquement si on souhaite ne pas supprimer les items renseignés manuellement lors d'une resynchronisation
- cas où l'utilisateur veut synchroniser plusieurs collections privées
   * il faut enregistrer dans la base de données une *liste* d'adresses vers des collections privées
   * il faut pouvoir dissocier les items pour chaque collection

Je crois qu'actuellement Stylo enregistre uniquement le format brut BibTeX dans la base de données.
On ne sait donc pas faire la distinction entre les items importés et ceux renseignés manuellement (ni même faire le lien entre un item importé et une collection Zotero).

En résumé, actuellement il n'y a pas de notion de mise à jour, on supprime et importe à nouveau.
On peut mettre en place un système de synchronisation/mise à jour mais cela nécessitera un peu de travail.

> peut-être qu'il faudrait (et ce serait notre job) clarifier cette fonctionnalité : il s'agit d'un import d'une collection privée.

Oui c'est vrai que l'interface ne mentionne à aucun moment qu'il s'agit d'un import.
De la même façon, il faudrait avertir l'utilisateur si on décide que l'import/synchronisation efface l'ensemble des items avant d'importer/synchroniser à nouveau.
Si ce n'est pas le comportement attendu par l'utilisateur, il risque d'être assez mécontent d'avoir perdu ces données 😄
