### ISSUE TITLE
Déploiement d'une instance de développement

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#152]
Cette instance permettra de tester les prochains développements sans impacter l'instance de production.

Ce serveur sera mis à disposition par les équipes d'Huma-Num.

**Comment by thom4parisot** [comment]
Le serveur a été mis à disposition, on nous a transmis les détails de connexion.

**Comment by thom4parisot** [comment]
Le serveur a été mis à disposition, on nous a transmis les détails de connexion.
