### ISSUE TITLE
Mettre en production l'instance stylo.huma-num.fr

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#156]
Suite à l'arrêt de stylo.ecrituresnumeriques.ca, le serveur stylo.huma-num.fr devient l'instance de production.
Quid du service d'export https://stylo-export.ecrituresnumeriques.ca/cgi-bin

En lien avec https://github.com/EcrituresNumeriques/stylo/issues/119

**Comment by marviro** [comment]
> Quid du service d'export https://stylo-export.ecrituresnumeriques.ca/cgi-bin

Pour l'instant il reste où il est

**Comment by ggrossetie** [comment]
Donc le serveur où est installé le cgi-bin restera accessible ? Est-ce que l'URL changera ? Est-ce que le certificat sera toujours valide ?

**Comment by marviro** [comment]
Le service d'export se trouve sur le serveur de la Chaire et tout va rester pareil (URL etc.).

**Comment by ggrossetie** [comment]
On est en production ! :tada: :tada: :tada:

**Comment by antoinentl** [comment]
@oncletom @Mogztter :clap: :champagne:
