### ISSUE TITLE
Amélioration du YAML par défaut (et des champs du mode editor)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#157]
Le schéma YAML par défaut doit être amélioré et même corrigé sur certains points. Avant de commencer à intervenir sur les fichiers concernés, voici la liste des champs devant être modifiés/ajoutés.

## Modifications
Dans `graphql/data/defaultsData.js` :

- remplacer `publisher: Département des littératures de langue française` par `publisher:`
- remplacer `prod: Sens Public` par `prod:`
- remplacer `prodnum: Sens Public` par `prodnum:`
- remplacer `diffnum: Érudit` par `diffnum:`
- remplacer `issnnum: 2104-3272` par `issnnum:`
- remplacer `journal: Sens public` par `journal:`
- remplacer `forname: Marcello` par `forname:`
- remplacer `surname: Vitali-Rosati` par `surname:`
- remplacer `gender: male` par `gender:`
- remplacer `orcid: 0000-0001-6424-3229` par `orcid:`
- supprimer `id_sp: ''` et `id_sp: SP1234`

Dans `front/gatsby/src/components/Write/yamleditor/YamlEditor.jsx` :

- remplacer `target="issnum"` par `target="issnnum"` (il s'agit d'une erreur)
- le champ `typeArticle` doit devenir un champ texte et non un choix multiple, @oncletom ou @Mogztter je vous solliciterai pour cette modification précise en temps voulu

## Ajouts
Dans `graphql/data/defaultsData.js` :

- après `journal:` : `journalsubtitle:`
- après `journalsubtitle:` : `journalid:`
- `issueid`
- `ordseq`

Dans `front/gatsby/src/components/Write/yamleditor/YamlEditor.jsx` :

- après l'occurrence de `journal` : `{this.props.editor && <TextInput target="journalsubtitle" title="Journal Subtitle" state={this.state.obj} updateState={this.updateState}  readOnly={this.readOnly}/>}`
- après l'occurrence de `journalsubtitle` : `{this.props.editor && <TextInput target="journalid" title="Journal ID" state={this.state.obj} updateState={this.updateState}  readOnly={this.readOnly}/>}`
- après l'occurrence de `rights` : `<TextInput target="rightsauthors" title="Author(s) rights" state={this.state.obj} updateState={this.updateState}  readOnly={this.readOnly}/>`
- `{this.props.editor && <TextInput target="issueid" title="Issue ID" state={this.state.obj} updateState={this.updateState}  readOnly={this.readOnly}/>}`

Dans `front/gatsby/src/components/Write/yamleditor/People.jsx` :

- après l'occurrence de `forname` : `<TextInput target={props.keyState+"["+props.index+"].gender"} title="Genre" state={props.state} updateState={props.updateState} readOnly={props.readOnly}/>`

@marviro @lakonis Merci de corriger ou de compléter, j'espère avoir bien compris le schéma des données, et d'après mes recherches il n'y a pas de conflit avec les templates d'export.

**Comment by marviro** [comment]
Parmi les champs à modifier:

- `id_sp` doit devenir `id`

Une autre chose à modifier est, dans l'éditeur yaml, le champs typeArticle qui doit être un champ de texte et non un choix multiple. Il faudrait ensuite pouvoir avoir le choix multiple pour des revues particulières

**Comment by marviro** [comment]
@antoinentl et @lakonis, s'il y a des champs qui vous semblent indispensables pour un export revue générique (données indispensables en TEI ou erudit) svp ajoutez-les maintenant.

Question: est-ce qu'on ajoute le champs `logocredits` dont a besoin Sens public ou on le met seulement dans le yaml de SP?

**Comment by antoinentl** [comment]
@marviro Pour id_sp c'est un champ par défaut qui n'apparaît en fait... nulle part, et qui n'est utilisé nulle part non plus (sauf erreur de ma part), donc il faudrait plutôt le supprimer !

Pour le champs typeArticle ok pour le passer en champ texte, @marviro je te laisse regarder les modifications nécessaires pour le template SP.

J'ai ajouté des champs utiles pour certaines revues.

Je modifie mon message initial !

**Comment by thom4parisot** [comment]
Demande de clarification : 
> - après l'occurrence de `forname` : `<TextInput target={props.keyState+"["+props.index+"].gender"} title="Genre" state={props.state} updateState={props.updateState} readOnly={props.readOnly}/>`

Est-ce que c'est nécessaire d'informer du genre d'une personne ? Et si oui, est-ce que vous avez en tête autre chose qu'un choix binaire "femme/homme" ?

**Comment by lakonis** [comment]
Très bonne question.. cet ajout de genre est requise pour les exports Erudit, dont le schema XML est le suivant : 

```xml
<xs:attribute name="sexe">
  <xs:annotation>
    <xs:documentation xml:lang="fr">
      <table>
        <tr>
          <td>Étiquette:</td>
          <td>Sexe</td>
        </tr>
        <tr>
          <td>Description:</td>
          <td>Ensemble des caractéristiques anatomiques et des éléments fonctionnels distinguant l'homme et la femme.</td>
        </tr>
      </table>
    </xs:documentation>
  </xs:annotation>
  <xs:simpleType>
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="feminin"/>
      <xs:enumeration value="masculin"/>
    </xs:restriction>
  </xs:simpleType>
</xs:attribute>
```
Pas super à jour sur le plan sociétal... Si on veut faire simple, on remet ces deux valeurs uniquement. Sinon on ajoute une valeur neutre, qui ne générera une erreur que lors d'un export XML Erudit.

**Comment by thom4parisot** [comment]
Ah oui et on passe de "genre" à "sexe" au passage 🙃

La question suivante est : est-ce que ça apporte quelque chose d'avoir cette information "biologique" dans l'export Erudit ?

**Comment by lakonis** [comment]
> Ah oui et on passe de "genre" à "sexe" au passage :upside_down_face:

voilà...

Si je me souviens bien, la validation du schéma passe sans le sexe, mais les humains chez Erudit nous ont déjà fait revoir nos copies parce qu'il manquait cette donnée.

**Comment by marviro** [comment]
Malheureusement cette info est nécessaire dans le schéma érudit. Pour la petite histoire: elle sert pour envoyer des mails automatiques aux directeurs (Mme ou Monsieur). Certes, on aurait pu au moins utiliser "genre".

**Comment by thom4parisot** [comment]
Y'a des "Mme" dans les directeurs ? (je troll…)

Je repose la même question pour les emails, est-ce vraiment nécessaire d'entamer les emails par "Monsieur" ou "Madame" ?

**Comment by antoinentl** [comment]
Ta question est pertinente, et nous sommes d'accord que c'est absurde (voir bête), mais cet élément ne dépend pas de nous mais du [schéma d'Érudit](https://www.erudit.org/xsd/article/3.0.0/eruditarticle.xsd) comme l'a expliqué Nicolas. Cela peut faire l'objet d'une discussion avec Érudit.

**Comment by thom4parisot** [comment]
Ah oui OK, et ce schéma est _externe_, compris.

Et bien oui, comment on fait pour avoir cette discussion avec elleux ?

De mon côté, et en attendant la discussion, je ne suis pas très chaud pour maquiller "sexe" en "genre" dans le formulaire côté Stylo.

**Comment by antoinentl** [comment]
Pour avoir cette discussion tu peux écrire à Hocine (https://apropos.erudit.org/fr/erudit/equipe/) par exemple, je pense que tu as plus de recul et les mots justes pour demander si cela peut être modifié. Pour Stylo il faut effectivement trouver une solution (que je n'ai pas dans l'immédiat), on cherche !

**Comment by lakonis** [comment]
heu.... laissez tomber la discussion avec Erudit/Hocine (je suis sérieux). Ils n'ont absolument pas les moyens de changer un iota de leur usine pétrolière de traitement. Leur schéma est vieillissant, tant pis, on ne peut rien faire. Ils ont un chantier pour tout passer sur JATS, schéma plus récent et plus standard, tant mieux. 

Je pense qu'en bon québecois, ils ont déjà bien intégré la problématique du genre (est ce qu'il y a une seule université française qui s'est dotée d'une politique d'inclusion LGBTQ+... comme au Québec ?), seulement son implémentation n'est pas pour tout de suite.

Idéalement, pour résoudre notre issue, on pourrait indiquer dans le placeholder ou dans le label de la donnée quelque chose. 

exemples `label: [placeholder]`:
- `sexe (tel que requis par le schéma Érudit): ....`
- `sexe: [Erudit compliant]`
- `sexe: [en cas d'export Érudit]`

**Comment by ggrossetie** [comment]
> Ta question est pertinente, et nous sommes d'accord que c'est absurde (voir bête), mais cet élément ne dépend pas de nous mais du schéma d'Érudit comme l'a expliqué Nicolas.

Oui, je pense qu'on partage tous ce constat.

> heu.... laissez tomber la discussion avec Erudit/Hocine (je suis sérieux). Ils n'ont absolument pas les moyens de changer un iota de leur usine pétrolière de traitement. Leur schéma est vieillissant, tant pis, on ne peut rien faire. Ils ont un chantier pour tout passer sur JATS, schéma plus récent et plus standard, tant mieux.

On peut toujours demander ça ne coûte pas grand chose et peut être qu'ils auront une solution de contournement comme rendre le champ optionnel ou ajouter une valeur neutre... non ?

Si ce n'est pas possible, on peut aussi ne pas prendre la responsabilité de demander cette valeur tant qu'on ne fait pas un export Erudit.

Dans le cas d'un export Erudit, on vérifie que la valeur est présente et si non présente on explique qu'Erudit utilise un format qui exige de renseigner le sexe d'une personne avec deux choix possibles "feminin" ou "masculin".

> exemples label: [placeholder]:
sexe (tel que requis par le schéma Érudit): ....
sexe: [Erudit compliant]
sexe: [en cas d'export Érudit]

Cela revient quand même à ajouter un champ "sexe" alors qu'on est tous d'accord que ça n'a rien à faire là :disappointed:

**Comment by thom4parisot** [comment]
Super, merci beaucoup pour ces retours — je suis content d'en apprendre autant.
Je vous mettrai en copie du message envoyé à Hocine, tout en prenant la responsabilité du message.

**Comment by thom4parisot** [comment]
Voici la réponse d'Erudit, qui me semble très claire : 

> L'attribut "sexe" est un optionnel, de notre côté voici ceratins points concernant son utilisation :
> 
>  * Sur l'ancienne plateforme d'Érudit, on utilisait la valeur de cet attribut pour féminiser, au besoin, les fonctions des membres de l'équipe éditoriale d'une revue (éléments "directeur" et "redacteurchef" : directeur.trice.s et rédacteur.trice.s en chef). 
>  * L'affichage de la nouvelle plateforme ne se base plus sur la valeur de cet attribut, mais plutôt sur l'info. balisée sous l'élément "fonction"
>  * On l'utilise encore pour assurer une uniformité des données
>  * Cette métadonnée est aussi utilisée dans le cadre de certains projet de recherche en forage de données, exemple pour déterminer la place des femmes dans la recherche

J'en comprends 1) que le champ est facultatif, et que 2) le champ "fonction" prime aujourd'hui (qui peut être genré comme il faut).

Ma nouvelle proposition serait de supprimer ce champ du schéma.

**Comment by lakonis** [comment]
Merci Thomas pour le retour. Je suis (tellement) d'accord pour l'enlever en soi, et tenter d'utiliser le champ fonction à la place, mais nous ne sommes pas à l'abri d'un refus de notre copie si leur pipeline a besoin de cette donnée ("on l'utilise encore"). 

C'est ce qu'il s'était passé en ... 2017 ou 2018 je pense. On avait négocié à l'époque, mais on avait finalement été obligé de retoucher manuellement tous les yamls et à refaire les exports xml.. (je parle d'une archive de 1000 et quelques articles, soit pas loin de 5000 personnes à "genrer"). 

@marviro que décides tu ?

**Comment by thom4parisot** [comment]
> nous ne sommes pas à l'abri d'un refus de notre copie si leur pipeline a besoin de cette donnée ("on l'utilise encore")

Je suis partant pour leur poser la question. "Est-ce qu'il y a un risque qu'un article soit refusé si cette information facultative n'est pas renseignée ?"
Tu voudrais dire qu'il y aurait des règles éditoriales "cachées", qui s'appliquent en plus du schéma de métadonnées ?

**Comment by marviro** [comment]
Je suis d'accord avec Nicolas. Malheureusement ils vont réfuser nos articles si on leur donne pas l'info. Sinon il faut demander à Mathieu aussi - pas seulement Hocine. Sincèrement, je suis d'accord avec la remarque - je l'avais fait publiquement en hurlant dans une rencontre il y a 6 ans et j'avais dit que c'était une honte - mais concrètement j'ai pas envie de recommencer à produire des xml qu'ils ne savent pas mettre en prod

**Comment by ggrossetie** [comment]
@antoinentl Est-ce que `articleslies` est encore utilisé? Dans le YAML par défaut, on a :

```yml
articleslies:
  - url: ''
    titre: ''
    auteur: ''
```

Peut être qu'il faudrait la supprimer et on pourra toujours l'ajouter manuellement en "raw mode" si besoin?

**Comment by antoinentl** [comment]
J'ai découvert ce champ ce jour même, donc on peut le supprimer et on le rajoutera manuellement si besoin !
