### ISSUE TITLE
Message d'information pour la migration

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#170]
Voici une proposition de message à adapter (et à traduire en anglais également), merci par avance pour vos retours @marviro @lakonis @oncletom et @Mogztter 

📢 Pour des raisons de migration de serveurs Stylo sera coupé jeudi 21 mai 2020 à 2h (heure de Montréal UTC−04:00, soit 8h heure de Paris) pour une durée maximale de 12 heures. Pendant cette période nous vous recommandons de ne pas utiliser Stylo, nous ne pourrons pas garantir la sauvegarde de vos modifications. Merci de votre compréhension.

Due to a server migration, Stylo will be unavailable on Thurday, May the 21th at 02:00 AM (UTC−04:00) for approximately 12 hours.
During this period of time, we advise you not to use Stylo, as you might experience data loss. Thank you for your comprehension.

Ci-dessous une capture d'écran (date et heure à adapter) :

![Screenshot_2020-05-11 Stylo Login](https://user-images.githubusercontent.com/6869488/81578834-5e430d80-9379-11ea-8018-46502e8b68f3.png)

(Le message sera également affiché sur la documentation, je m'en charge.)

**Comment by ggrossetie** [comment]
On parle d'ajouter un message sur l'instance de production actuelle ? Comment est-ce qu'on déploie sur ce serveur ? Est-ce que c'est Arthur qui va s'en charger ?

**Comment by antoinentl** [comment]
@Mogztter Oui il s'agit d'ajouter ce message sur l'instance de production actuelle, donc ce sera forcément @PookMook qui devra s'en charger (le moment venu). C'est notre seul moyen de prévenir les utilisateurs et utilisatrices.

**Comment by ggrossetie** [comment]
La durée maximale dépend de la propagation DNS dans le cas où on fait pointer stylo.ecrituresnumeriques.ca sur le nouveau serveur.

Pour éviter d'attendre, on peut faire une redirection permanente sur le serveur de production actuelle vers le nouveau serveur, pendant que le DNS se propage.
Il faudra alors afficher une page de maintenance sur le nouveau serveur pour éviter que des utilisateurs fassent des changements pendant la migration de la base de données.

**Comment by antoinentl** [comment]
Merci pour cette indication @Mogztter :+1: Ce sera effectivement plus prudent de procéder ainsi !

**Comment by ggrossetie** [comment]
Top! Concernant le message ça me semble bien. Pour la traduction, je propose :

> Due to a server migration, Stylo will be unavailable on Monday, May the 25th at 02:00 AM UTC -4 for approximately 2 hours. 
During this period of time, we advise you not to use Stylo, as you might experience data loss. Thank you for your comprehension.

**Comment by antoinentl** [comment]
J'ai modifié les informations de mon message initial, merci pour vos retours et validations @marviro @Mogztter et @oncletom !

**Comment by antoinentl** [comment]
Merci :pray: @PookMook
