### ISSUE TITLE
Planification du déménagement

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#177]
Voici une proposition de planification à valider ensemble @marviro @oncletom @Mogztter :

1. lundi 18 mai 2020 12:00 (UTC−04:00) (20:00 au plus tard) : annonce de la coupure avec un message aux utilisateurs, voir #170 (doubler via Twitter ou autre ?)
2. mercredi 20 mai 2020 04:00 (UTC−04:00) : tests de mise en production avec les données (temporaires) dont nous disposons déjà
3. mercredi 20 mai 2020 18:00 (UTC−04:00) si les tests sont validés :
  - envoi des données à jour
  - coupure de l'instance actuelle de production (stylo.ecrituresnumeriques.ca)
  - communication sur Twitter, Mattermost et par mail auprès des utilisateurs et utilisatrices
4. jeudi 21 mai 2020 02:00 (UTC−04:00) :
  - mise en production de la nouvelle instance
  - activation des redirections DNS + serveur
5. jeudi 21 mai 2020 10:00 (UTC−04:00) si les tests sont validés :
  - communication
  - annonce d'un support pendant la permanence de 11:00 (UTC−04:00)

Quand nous nous serons mis d'accord je ferai passer à Arthur.

**Comment by ggrossetie** [comment]
Quelques remarques:

> mercredi 20 mai 2020 04:00 (UTC−04:00) : tests de mise en production avec les données (temporaires) dont nous disposons déjà

Si on fait un test de mise en production avec les données dont on dispose déjà on peut le faire plus tôt non ? (même si Thomas n'est pas disponible je pense pouvoir m'en sortir seul)

Pour le reste ça me semble bien :+1: 

Est-ce que tu as pu voir pour le nom de domaine https://ecrituresnumeriques.ca/ pour qu'on puisse récupérer les certificats en avance ?

**Comment by antoinentl** [comment]
@Mogztter Plus ce sera tôt mieux ce sera, je ne vois aucune contre indication de mon côté ! Pour ecrituresnumeriques.ca nous avons la main sur les DNS, c'est confirmé.

**Comment by ggrossetie** [comment]
> Plus ce sera tôt mieux ce sera, je ne vois aucune contre indication de mon côté

Ok, je peux remonter la sauvegarde 17 mai envoyée par Arthur sur stylo.huma-num.fr aujourd'hui.
A noter que le déploiement automatique ne fonctionne pas car les flux sont bloqués sur le serveur.
Nous avons envoyé un email à Laurent mais pour le moment nous n'avons pas eu de retour. 
On a potentiellement une solution de contournement qui nécessite un peu de travail supplémentaire de notre côté et qui sera un peu moins élégante...

> Pour ecrituresnumeriques.ca nous avons la main sur les DNS, c'est confirmé.

Top ! Est-ce que tu pourras me communiquer les informations pour qu'on puisse générer un certificat  pour le domaine ecrituresnumeriques.ca à partir de stylo.huma-num.fr? Our alors je te donne les informations à ajouter dans les entrées DNS.

**Comment by ggrossetie** [comment]
Déploiement en production fait: https://stylo.huma-num.fr/ :tada:
