### ISSUE TITLE
Le code de l'export ne permet pas de gérer plusieurs requêtes

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#181]
L'export utilise un répertoire unique pour faire sa conversion:

```js
shell.cd('src/data')
shell.exec(`rm ${id}*`)
```

Le code n'étant pas synchrone, si il y a un accès concurrent, il est possible de supprimer l'export de quelque d'autre !

**Comment by thom4parisot** [comment]
Corrigé par #213.
