### ISSUE TITLE
Conserve stylo.ecrituresnumeriques.ca car les annotations hypothes.is sont liées à ce nom de domaine

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#184]
Plusieurs scénarios pour le lien de preview, [via ](https://web.hypothes.is/help/how-hypothesis-interacts-with-document-metadata/), qui actuellement a la forme `https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/:id?preview=true` : 

<img width="810" alt="image" src="https://user-images.githubusercontent.com/138627/82820924-65067000-9ea3-11ea-8ff5-d2ec00e3466e.png">

- est-ce que `https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/:id?preview=true` redirigée en 301 vers `https://stylo.huma-num.fr/api/v1/htmlArticle/:id?preview=true` récupère les annotations ?
- est-ce que `https://stylo.huma-num.fr/api/v1/htmlArticle/:id?preview=true` avec un `<link rel=canonical>` vers ecrituresnumeriques.ca récupère les annotations ?
- ~~est-ce que `https://stylo.huma-num.fr/api/v1/htmlArticle/:id?preview=true` avec canonical (à huma-num.fr) et alternative (à ecrituresnumeriques.ca) récupère les annotations ?~~

Y'a deux cas :

- quand on accès directement à `https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/:id?preview=true`
- quand on clique sur un lien de preview d'un article `stylo.huma-num.fr` qui a été annoté précédemment sur `https://stylo.ecrituresnumeriques.ca`

**Comment by ggrossetie** [comment]
Avec #180 cela semble fonctionner, même si https://via.hypothes.is/ ajoute un canonical avec l'URL du document.

Pour tester que cela fonctionne : 
- créer un nouveau document
- prévisualiser le document (vérifier que l'URL commence par `https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca`)
- vérifier qu'il n'y a pas d'annotations
- ajouter une annotation
- remplacer le début de l'URL par `https://via.hypothes.is/https://stylo.huma-num.fr`
- vérifier que l'annotation est présente

Autre test à réaliser:

- prendre un document existant avec des annotations (sans lancer la prévisualisation !)
- vérifier que les annotations ne sont pas présentes sur le nouveau domaine: `https://via.hypothes.is/https://stylo.huma-num.fr/...`
- lancer la prévisualisation à partir de stylo
- vérifier que les annotations sont maintenant présentes sur le nouveau domaine

Si cela fonctionne, on peut créer un robot/script qui va naviguer sur l'ensemble des documents présents dans la base de données Stylo afin d'ajouter l'alias sur `https://stylo.huma-num.fr`. Une fois terminée, on pourra utiliser uniquement `https://stylo.huma-num.fr`.

//cc @oncletom @marviro @antoinentl @lakonis

**Comment by antoinentl** [comment]
Cela semble fonctionner pour les _nouvelles annotations_, en revanche je n'ai trouvé aucun moyen de récupérer/voir des annotations pour des documents Stylo créés avant le 20 mai.

**Comment by antoinentl** [comment]
Problème résolu avec #381.

**Comment by thom4parisot** [comment]
En fait on n'a jamais résolu ce problème : les identifiants sont _implicites_ — à savoir les URLs des documents. C'est pour ça qu'on maintient l'usage de `stylo.ecrituresnumeriques.ca`, y compris avec le nouveau système de preview.

Y'a un autre mécanisme dans Hypothes.is où l'identifiant de l'article est géré via une métadonnée, comme [indiqué dans le guide](https://web.hypothes.is/blog/guidance-for-web-publishers/). Cet identifiant permettrait de s'affranchir de l'URL… mais c'était pas gagné de savoir si cette bascule permettait de conserver les annotations.

**Comment by antoinentl** [comment]
Ok merci pour la précision. De mon point de vue le problème est tout de même en partie résolu, puisque pour l'utilisateur·trice désormais l'URL est la même pour l'application et pour la prévisualisation. Certes _derrière_ il s'agit encore d'une rustine (je ne dis pas ça pour décrédibiliser le super travail fait avec l'idée de l'iframe), mais ça avance bien :+1:

**Comment by thom4parisot** [comment]
Ah oui t'inquiète, je n'ai pas du tout interprété ça comme de la décrédibilisation. J'aurais aimé pouvoir dire qu'on se passait de la rustine 😅

**Comment by ggrossetie** [comment]
Je ne suis pas sûr qu'on puisse faire quelque chose à ce sujet (ou du moins je ne me souviens plus des derniers échanges).
Est-ce qu'on cloture ?

**Comment by antoinentl** [comment]
(Pour information le domaine `stylo.ecrituresnumeriques.ca` est embarqué dans la preview, donc les annotations sont conservées, c'est un détournement mais ça fonctionne et on reste là-dessus pour l'instant.)
