### ISSUE TITLE
Choisir entre 2 ou trois modèles de métadonnées

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#192]
Problématique en 2 points :

- Le modèle de métadonnées est utilisé dans l’export et donc on ne peut pas le modifier librement car autrement l’export ne marche plus.
- L’éditeur graphique de Yaml est lié à un modèle

Remarques :

- actuellement on peut définir un Yaml par défault dans son propre profil ou on peut choisir un yaml réduit (mode auteur)
- les revues ont leur propre export, donc elles peuvent avoir un modèle différent (par contre l’éditeur YAML doit s’adapter)
- l’auteur normal devrait pouvoir choisir entre 2 ou 3 modèles préfabriqués

**Comment by ggrossetie** [comment]
La pull request #230 met en place des composants techniques permettant de générer un formulaire à partir d'un modèle mais il reste encore du travail afin d'intégrer ces composants dans l'éditeur.

Voir #269

**Comment by maiwann** [comment]
Je commence à imaginer un début de solution : 

## Éditeur·ice : Créer un nouveau modèle de métadonnées
Pour l'ajout de nouveaux modèles, j'imagine qu'on pourrait démarrer en : 
- proposant un template (en yaml ou md) et un peu de documentation
- la personne remplit le template de son coté et
- vous le soumet
   - via une PR github
   - ou par mail (ce qui rediffuse le travail d'intégration de votre coté)

Et dans un second temps on pourrait imaginer une interface pour que ça se fasse en ligne de façon plus accessible que via github.

Je propose que l'interface se fasse dans un second temps seulement afin que l'on puisse récolter différents modèles et/ou sollicitations d'utilisateurs intéressées pour enquêter sur ce qui serait utile dans cette interface.

Et j'imagine qu'il y aura du boulot pour rendre le plus simple possible le remplissage d'un template :)

## Auteur·ice : Ajouter un modèle à mon article 

Pour démarrer, l'auteurice aurait une quantité restreinte de champ demandés dans la partie "Métadonnées" (l'équivalent du Basic mode) et pourrait ajouter un nouveau modèle via le bouton "Ajouter des métadonnées"


![Screenshot 2022-01-12 at 14-59-47 Stylo](https://user-images.githubusercontent.com/27999224/149168225-51179251-f5f2-482e-95e5-47f0b7a366a0.png)

Apparaitrait dans une modale (par ex) une liste déroulante (idéalement filtrable dans un second temps pour gagner du temps lorsqu'il y aura beaucoup de modèles) qui listerait tous les modèles, par exemple : 
- Article sans éditeur
- Devoir
- Livre
- Sens public
- RON
- Éditeur numéro 3
…


Et une fois sélectionné, les nouvelles métadonnées s'afficheraient dans l'onglet métadonnées : 

![Screenshot 2022-01-12 at 15-04-24 Stylo](https://user-images.githubusercontent.com/27999224/149168855-76aaf5cd-aea1-45e9-a66f-dd742ef5d1f0.png)

NB : J'ai écrit Sens critique mais bien sur c'est Sens public 😅

**Comment by maiwann** [comment]
Je suis preneuse de savoir ce que cette proposition ne résoud pas comme problèmes / pourrait poser comme nouveaux problèmes 😁
