### ISSUE TITLE
Bibliographie : coller une URL de collection

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#193]
Suite à #41 

Aujourd'hui le champ est "technique" (`[IDnumber]/collections/[IDcollection]`), et ne fonctionne que pour des groupes.

On devrait pouvoir 1) coller, 2) valider et 3) tester qu'une URL est OK avant de rendre cliquable le bouton "Submit". Genre : 

- https://www.zotero.org/oncletom/collections/649M53XD
- https://www.zotero.org/groups/2478772/stylo-test/collections/UGF4W4PZ

Sera utile après #145 ; notamment si le token OAuth a expiré, ou autre.

**Comment by antoinentl** [comment]
Le système actuel de connexion avec Zotero résout à mon sens ce problème.
