### ISSUE TITLE
Amélioration graphique du menu

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#196]
- Ajout d'un icone pour l'action de "Log out"
- Applique un style différent "Documentation" car contrairement il s'agit d'un lien externe vers la documentation et non d'une action sur l'application

![menu](https://user-images.githubusercontent.com/333276/86241597-7d089800-bba3-11ea-80b2-30945df0f3f9.png)

**Comment by antoinentl** [comment]
Sur le principe je valide.

Concernant le style du lien "Documentation", si on peut éviter le souligné c'est parfait (autrement on va croire qu'il n'y a que ce terme qui a un lien).

**Comment by ggrossetie** [comment]
> Concernant le style du lien "Documentation", si on peut éviter le souligné c'est parfait (autrement on va croire qu'il n'y a que ce terme qui a un lien).

C'est vrai que le souligné n'est peut être la bonne solution. Je voulais que visuellement on comprenne qu'il s'agit d'un lien externe. Comme solution alternative on peut ajouter un symbole après "Documentation" :

- → (unicode)
- 🔗 (emoji)
- ![external-link-symbol](https://user-images.githubusercontent.com/333276/87540402-ef976e80-c69f-11ea-9e21-d0c801c65e19.png) (image)

Pour le moment je vais supprimer le souligné.
