### ISSUE TITLE
Référence biblio par défault

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#20]
Il faudrait la changer (elle est très mal faite) et mettre à la place:

@book{goody_raison_1979,
	series = {Le sens commun},
	title = {La {Raison} graphique. {La} domestication de la pensée sauvage.},
	publisher = {Les Editions de Minuit},
	author = {Goody, Jack},
	year = {1979},
}

**Comment by PookMook** [comment]
Nettoyage, la ref par défaut est bien mise
