### ISSUE TITLE
Modifier le message d'explication pour la connexion avec Zotero

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#203]
Modifier le message qui indique comment connecter un article avec un groupe/une collection Zotero.

Actuellement :

> Please paste the URL of your Zotero library, so that it looks like https://www.zotero.org/groups/[IDnumber]/collections/[IDcollection]  
https://www.zotero.org/groups/

Deux pistes d'amélioration :

1. ne pas évoquer l'URL mais simplement les identifiants du groupe et de la collection
2. spécifier qu'il est possible d'indiquer uniquement un identifiant de groupe

**Comment by ggrossetie** [comment]
@antoinentl Est-ce que ça ne serait pas plus simple de gérer des URL complètes : 

```
https://www.zotero.org/groups/{groupId}/{groupName}/collections/{collectionId}
https://www.zotero.org/groups/{groupId}/{groupName}/library
https://www.zotero.org/groups/{groupId}/{groupName}
```

Comme ça on peut directement copier/coller l'URL affiché dans son navigateur quand on navigue sur un groupe ou une collection d'un groupe. Le message d'aide devra indiquer qu'on supporte les URLs d'un groupe _public_ de collections et les URLs d'une collection d'un groupe _public_.

En faisant des tests je viens de voir qu'on affiche pas de message d'erreur quand l'API Zotero retourne une erreur 403 Forbidden dans le cas où on veut importer un groupe privé.

**Comment by thom4parisot** [comment]
Ou bien on encourage à connecter son compte comme ça y'a plus de problème 😶 

(on a un composant de choix/autocomplétion qui peut faire le taf si besoin de quelque chose de plus fonctionnel qu'un `<select>` pas autocomplétable)

**Comment by antoinentl** [comment]
Je pense qu'il faut faire un choix clair, on vous revient là-dessus !
