### ISSUE TITLE
Problème d'importation d'une référence "thèse" sur la version prod de Stylo

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#207]
Tester avec la thèse de Serge Bouchardon (http://www.theses.fr/2005COMP1594).

**Comment by antoinentl** [comment]
Piste à explorer : le `type` semble poser problème, il faut vérifier la documentation BibTeX/Zotero. À tester sur la version de dev.

**Comment by thom4parisot** [comment]
Et sur la version de dev ? (on n'a pas déployé de choses liés au bibtex/citations en prod pour l'instant).

**Comment by ggrossetie** [comment]
@antoinentl Est-ce que tu pourrais s'il te plait refaire un test pour confirmer si le problème est toujours présent. Et si tel est le cas décrire comment reproduire l'anomalie.

**Comment by ggrossetie** [comment]
@antoinentl ping 🏓

**Comment by antoinentl** [comment]
Désolé pour la latence, c'est effectivement corrigé, merci !
