### ISSUE TITLE
[Biblio] Copier-coller ne fonctionne pas sur MacOS

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#21]
MacOS `10.12.6`, Firefox (`60.0`)

Avec l'article par défaut _How to_, sans avoir changé la bilbio.

Clic sur une référence de la biblio ne copie pas la référence (impossible de coller, par `cmd+v` ou via clic contextuel).

**Comment by lakonis** [comment]
urgent ! @PookMook

**Comment by loup-brun** [comment]
Ça semble résolu! Testé avec deux articles sur MacOS et FF `60.0.0`.
