### ISSUE TITLE
Précisions sur la procédure de test pour conserver les annotations suite au changement de domaine

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#210]
Concernant notre problème de conserver les annotations Hypothesis créées avec l'ancienne URL (stylo.ecrituresnumeriques.ca) et de pouvoir y accéder depuis les deux domaines (directement depuis stylo.huma-num.fr et en redirection depuis stylo.ecrituresnumeriques.ca), et pour pouvoir faire des tests correctement de mon côté, merci de me confirmer la marche à suivre :

1. création d'une page test domain.ca/avant/test-h avec comme métadonnées `<metadata="dc.relation.ispartof" content="domain.ca/avant" />` `<metadata="dc.identifier" content="test-h" />`
2. création d'annotations sur cette page
3. duplication de la page test domain.ca/avant/test-h avec comme URL domain.ca/apres/test-h, et comme métadonnées `<metadata="dc.relation.ispartof" content="domain.ca/avant" />` `<metadata="dc.identifier" content="test-h" />`
4. vérification de la conservation des métadonnées de domain.ca/avant/test-h en accédant à domain.ca/apres/test-h

À ce stade (et après trop de semaines à laisser ce problème de côté), j'aurai besoin d'éclaircissements de votre part @oncletom et @timoguic :pray:

**Comment by ggrossetie** [comment]
Cela fonctionnera car Hypothesis va prendre en compte `dc.identifier` et `dc.relation.ispartof`. Par contre les annotations "historiques" qui ont été ajoutées sur stylo.ecrituresnumeriques.ca sont associées uniquement à l'URL de l'article Stylo avec le domaine stylo.ecrituresnumeriques.ca.

Même chose avec les annotations qui ont été ajoutées avant l'introduction d'un `dc.identifier` et `dc.relation.ispartof` stable et unique.

En lien avec #564
