### ISSUE TITLE
bug sur le champ de contact lors d'un share sur Safari

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#214]
Le champ d'écriture pour ajouter un contact lors d'un partage d'article n'est pas actif sur Safari.

Pour reproduire le bug.

1. créer un article
2. partager l'article (share)
3. tenter d'écrire l'adresse courriel dans le champ dédié. > champs inactif.

**Comment by ggrossetie** [comment]
@lakonis Est-ce que tu peux s'il te plait nous préciser la version de Safari et nous joindre une capture d'écran avec la console des Developer Tools ouverte ? Merci 🤗

**Comment by lakonis** [comment]
je n'ai pas Safari, mais je passe la main à @spouyllau qui m'a fait remonter le bug.

**Comment by thom4parisot** [comment]
Je reproduis le problème sur Safari 14, y compris sur stylo-dev.

J'ai réussi à saisir 1 lettre, mais c'est comme si le focus dans le champ était "refusé". Ça roule avec Firefox.

**Comment by spouyllau** [comment]
Bonjour,
La version de safari que j'utilise pour ma part est : Version 14.0 (15610.1.28.1.9, 15610). J'ai donc le bug et c'est donc dans le champ en bleu qu'on ne peut ajouter des emails. Idéalement, il serait bien d'avoir une autocomplétion possible avec HumanID (voir avec Laurent C. à Huma-Num) : 
![Capture d’écran 2020-09-30 à 10 29 25](https://user-images.githubusercontent.com/12101515/94661795-d2218a80-0307-11eb-850f-2c08b49633f6.png)

**Comment by thom4parisot** [comment]
OK.

> Idéalement, il serait bien d'avoir une autocomplétion possible avec HumanID (voir avec Laurent C. à Huma-Num)

Je vous laisse gérer les besoins fonctionnels à prioriser en ayant une discussion avec @antoinentl et @marviro.

**Comment by antoinentl** [comment]
On repasse ce point en prioritaire, merci !

**Comment by ggrossetie** [comment]
@antoinentl Je viens de déployer un correctif sur https://stylo-dev.huma-num.fr. Apparemment c'était un problème de style CSS qui bloquait la sélection. Corrigé dans  https://github.com/EcrituresNumeriques/stylo/commit/719a75dbaf0fc73e7fb1593a95c41f358dd1ee19.

**Comment by thom4parisot** [comment]
Ça fonctionne comme prévu, merci @Mogztter !

**Comment by antoinentl** [comment]
Je confirme ! Merci.
