### ISSUE TITLE
Affichage et manipulation des références bibliographiques

### ISSUE THREAD

**Issue by pmartinolli** [EcrituresNumeriques/stylo#23]
Pour utiliser plus souplement les références:
- faire une saisie semi-automatique dans le texte dès qu'on commence à taper [@...
- afficher la boîte des réf. biblio. en haut (dessus Version), ainsi elle est toujours accrochée en haut au moins.
Merci, et bravo pour Stylo! Je commence à le tester dès aujourd'hui,
Pascal M

**Comment by ggrossetie** [comment]
Merci pour ce retour.
La saisie semi-automatique me semble une bonne idée et je crois que ce point est prévue dans la roadmap (ping @marviro @antoinentl).

> afficher la boîte des réf. biblio. en haut (dessus Version), ainsi elle est toujours accrochée en haut au moins.

Les onglets "Edition", "Versions", et "Table of contents" peuvent se rétracter :

![onglet](https://user-images.githubusercontent.com/333276/99500115-2ba64d00-297a-11eb-865c-027326c69e9a.png)

N'est-ce pas suffisant ?

**Comment by antoinentl** [comment]
Oui je viens de créer une issue dédiée.
