### ISSUE TITLE
Ajouter des références bibliographiques dans les métadonnées

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#231]

**Comment by thom4parisot** [comment]
Tu veux dire, dans des champs de type "textarea" ?

**Comment by antoinentl** [comment]
L'idée est de pouvoir ajouter une référence bibliographique via le balisage classique `[@bibtex_key_2020]`, je conserve l'issue pour en garder l'idée qui serait un peu longue à implémenter (à mon humble avis).

**Comment by thom4parisot** [comment]
Oui ok, mais _où_ dans les métadonnées : n'importe quel champ, des champs de texte multiligne, ou autre chose ?
