### ISSUE TITLE
Ajouter la possibilité de renommer les noms de version

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#234]
Il y a un problème dans la logique d'enregistrement des versions.

**Comment by ggrossetie** [comment]
Quel est l'intérêt de renommer une version ? Est-ce que c'est uniquement afin de s'y retrouver plus facilement dans l'historique ?

> Il y a un problème dans la logique d'enregistrement des versions.

Est-ce que tu pourrais s'il te plait expliciter ce problème ?

**Comment by ggrossetie** [comment]
En lien avec https://github.com/EcrituresNumeriques/stylo/issues/322
