### ISSUE TITLE
Éléments statistiques sur la page d'accueil des articles

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#240]
- nombre d'articles
- nombre de tags
- etc.

**Comment by ggrossetie** [comment]
Le nombre d'articles a été rajouté et est disponible actuellement sur stylo-dev.huma-num.fr

![image](https://user-images.githubusercontent.com/333276/156342751-1409f011-94f2-4c21-a6e7-43543113558b.png)


Le nombre de tags pourrait être ajouté dans le titre "Filter by Tags" : 

![image](https://user-images.githubusercontent.com/333276/156342941-5878f11e-619a-4c26-8676-914dc0d54281.png)


@antoinentl Est-ce que cette solution te convient ?

**Comment by ggrossetie** [comment]
> etc.

🤔

**Comment by antoinentl** [comment]
Pour l'instant oui c'est super :+1: Si je vois d'autres besoins je rouvrirai une issue ! Et désolé pour le "etc." qui était plus pour moi...

**Comment by ggrossetie** [comment]
À noter que le nombre de tags n'a pas été ajouté. Ma capture d'écran montre ce que cela pourrait donner. Si tu penses qu'il faut le faire, je te laisse réouvrir cet issue.

**Comment by antoinentl** [comment]
Non je pense que c'est très bien de se limiter au nombre d'articles, on verra si le besoin se fait ressentir pour les tags.
