### ISSUE TITLE
L'API d'export d'un article utilise l'id de la version comme nom de fichier plutôt que l'id de l'article (passé dans l'URL)

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#247]
J'ai pu utiliser le nouvel endpoint d'export zip à partir d'un id d'article, mais les fichiers contenus par le zip sont nommés selon l'id de la dernière version, et non selon l'id de l'article.

Par exemple, sur l'article `idArticle=5dc066cd21cedb001958b56e`, je lance `curl https://stylo.huma-num.fr/export/article/5dc066cd21cedb001958b56e/zip -o 1.zip`, mais les fichiers dans 1.zip sont nommés ainsi : 

```
  5f666018fd0417001a2e339f.bib  
  5f666018fd0417001a2e339f.md  
  5f666018fd0417001a2e339f.yaml  
```

ce qui correspond à l'idVersion de la dernière version de l'article.

L'idée d'utiliser l'idArticle était de ne plus se soucier de l'idVersion. Par exemple, ne connaissant pas l'idVersion, je ne peux pas renommer les fichiers simplement.

À moins qu'un autre endpoint fournisse la version en cours ?

**Comment by ggrossetie** [comment]
Je t'avoue que je n'ai pas regardé en détail l'implémentation.
D'après ce que je vois il suffirait de remplacer l'attribut id dans l'appel à `exportZIP`:

https://github.com/EcrituresNumeriques/stylo/blob/4ef33745d2415b9c484ddc8b9bf565a89844b862/export/src/export.js#L122

Actuellement on utilise `cleanedVersion._id` mais on pourrait plutôt utiliser `req.params.id` ou `article._doc._id`.

@lakonis Est-ce que tu veux faire une pull request pour modifier ça? Une fois fusionné sur `master`, tu pourras tester sur https://stylo-dev.huma-num.fr/ afin de t'assurer que les fichiers sont bien nommés dans le zip suite à cette modification.

**Comment by lakonis** [comment]
entendu, je tente qlq chose. Merci.

**Comment by lakonis** [comment]
Pour mes besoins immédiats, j'ai contourné le pb en traitant les fichiers nommés selon la version. Je veux bien faire la correction que je proposais, mais peut-être n'est-elle pas pertinente ? 

Que suggérez vous ? Cela peut aussi être utile ou cohérent avec le reste des endpoints de nommer les fichiers selon la derniere version. Y a t il une bonne pratique à ce sujet ? 
Est ce que l'api propose de récupérer l'idVersion à partir de l'idArticle ?

Merci.

**Comment by ggrossetie** [comment]
> Pour mes besoins immédiats, j'ai contourné le pb en traitant les fichiers nommés selon la version. Je veux bien faire la correction que je proposais, mais peut-être n'est-elle pas pertinente ?
Que suggérez vous ? Cela peut aussi être utile ou cohérent avec le reste des endpoints de nommer les fichiers selon la derniere version. Y a t il une bonne pratique à ce sujet ?
Est ce que l'api propose de récupérer l'idVersion à partir de l'idArticle ?

A ma connaissance, il n'y a pas vraiment de bonne pratique sur ce sujet.
Par contre, je pense que ce n'est pas une bonne idée d'utiliser une identifiant qui n'est pas connu par l'appellant comme nom de fichier.

Si on voulait faire une API un peu plus sémantique, on pourrait déclarer ce endpoint qui retourne un fichier `5dc066cd21cedb001958b56e.zip`:

```
https://stylo.huma-num.fr/export/article/5dc066cd21cedb001958b56e.zip
```

Le nom des fichiers à l'intérieur du zip pourrait être générique:
- `article.md`
- `citations.bib`
- `metadata.yml`

Je vois bien l'intérêt d'avoir un nom unique pour les fichiers afin de pouvoir dezipper dans le même répertoire plusieurs exports mais cela dépasse la responsabilité de l'API.
Cela peut éventuellement poser des soucis si demain on veut ajouter un nouveau fichier qui a la même extension qu'un fichier existant (par exemple, un fichier de configuration yml pour l'export):

- `article.md`
- `citations.bib`
- `metadata.yml`
- `export-config.yml`


Bref je m'écarte un peu du sujet original !

> Pour mes besoins immédiats, j'ai contourné le pb en traitant les fichiers nommés selon la version. Je veux bien faire la correction que je proposais, mais peut-être n'est-elle pas pertinente ?

@lakonis La solution que tu suggères est pertinente, si tu peux faire cette modification ça serait top.

**Comment by lakonis** [comment]
Nouveau bug que je ne m'explique pas en décryptant le code de export.js :  L'endpoint fournit un zip contenant 6 fichiers au lieu de 3 lorsqu'un article est en cours d'édition sans qu'une version mineure ou majeure n'ait été déclarée. Le zip contient alors les 3 fichiers de la version en cours + les 3 fichiers de la version précédente (j'imagine celle qui s'appelle cleanedVersion ?). Idéalement il ne faudrait avoir que la version en cours, comme le fait la preview html par exemple.

**Comment by ggrossetie** [comment]
J'ai un peu perdu le fil mais il me semble qu'on a corrigé l'ensemble des problèmes non ? Si ce n'est pas le cas @lakonis est-ce que tu peux s'il te plait réouvrir une issue par problème que tu rencontres encore ?
