### ISSUE TITLE
Ne pas modifier le BibTeX original quand le BibTeX est valide

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#251]
Nous constatons l'ajout de balisages lorsque nous utilisons la validation du BibTeX sur l'onglet Raw BibTeX.

Voici un item BibTeX original :

```
@article{aube-lanctot_liminaire_2012,
date = {2012},
title = {Liminaire},
number = {21},
journaltitle = {Jet d’encre},
author = {Aubé-Lanctôt, Amélie and Lamy, Jonathan}
}
```

Et le même item modifié dès que nous validons :

```
@article{aube-lanctot_liminaire_2012,
date = {2012},
title = {Liminaire},
number = {21},
journaltitle = {Jet d’encre},
author = {given={Amélie}, family={Aubé-Lanctôt} and given={Jonathan}, family={Lamy}}
}
```

Le problème est que Pandoc ne comprend pas cette syntaxe, il ne faudrait donc pas modifié le BibTeX original, et donc probablement corriger le parseur en conséquence.

**Comment by thom4parisot** [comment]
OK compris. Il s'appelle comment ce "balisage" dans BibTex d'ailleurs ?

Ça m'aiderait à comprendre des détails entre l'usage courant de BibTex, ce que la spécification dit et ce que certains outils comprennent (ou pas — comme Pandoc dans ce cas).

PS : et tu testes sur quelle version de pandoc ? (`pandoc -v`)

**Comment by antoinentl** [comment]
Le balisage n'a pas de nom spécifique, la seule documentation que je peux t'indiquer est celle-ci : https://www.economics.utoronto.ca/osborne/latex/BIBTEX.HTM

Je ne trouve rien de plus pertinent pour le moment.

Ce qui est important c'est surtout que le BibTeX original ne soit pas modifié.

**Comment by thom4parisot** [comment]
Compris, on va changer de stratégie : utiliser le parseur que pour la validation, et non pour parser puis recomposer le bibtex (donc on ne modifiera, ni ne perdra aucune info).

**Comment by antoinentl** [comment]
Ok ce serait super. Désolé pour le temps perdu là-dessus je n'avais pas compris que le parseur réécrivait les données.

**Comment by antoinentl** [comment]
Je me permets d'insister, cette fonction est trop instable, nous avons de gros problèmes d'édition à cause de cette fonctionnalité. La désactiver pour le moment sur l'instance de production vous semble trop lourd ou compliqué ?

**Comment by ggrossetie** [comment]
> Je me permets d'insister, cette fonction est trop instable, nous avons de gros problèmes d'édition à cause de cette fonctionnalité. La désactiver pour le moment sur l'instance de production vous semble trop lourd ou compliqué ?

Non je pense que c'est faisable, tu souhaites désactiver complètement la fonctionnalité ? Aucune validation et aucune transformation lors de l'édition du BibTeX ? Autrement dit, on repasse sur le mode de fonctionnement d'un champ "texte libre".

**Comment by ggrossetie** [comment]
Ping @antoinentl pour avoir ta confirmation avant de désactiver la fonctionnalité.

**Comment by antoinentl** [comment]
Oui désactivons sur la production, nous testerons sur la version de dev pour s'assurer que tout se passe bien. Merci pour le rappel :hugs:

**Comment by ggrossetie** [comment]
> Non je pense que c'est faisable, tu souhaites désactiver complètement la fonctionnalité ? 

Je reviens un peu sur ce que j'ai dis, ce n'est pas forcement simple de désactiver cette fonctionnalité car d'autres fonctionnalités reposent sur le parser.
Par exemple, dans le panneau latéral, on affiche les références bibliographique de manière structurée. Si on désactive le parser, ce n'est plus possible de le faire. Il faut alors qu'on remette en place l'expression régulière qui faisait plus ou moins office de parser. Sauf que cette méthode avait des bugs notamment lorsqu'une référence bibliographique était vide...

Bref, ça demande un peu de temps de développement et pas mal de tests afin de s'assurer qu'on n'introduit pas des nouveaux bugs.

Je pense qu'on va passer presque autant de temps à revenir en arrière qu'à fiabiliser la solution. Je serais donc plutôt d'avis de travailler sur les deux problèmes remontés par @Mmellet https://github.com/EcrituresNumeriques/stylo/issues/257 et https://github.com/EcrituresNumeriques/stylo/issues/258

@antoinentl Qu'est-ce que tu en penses?

**Comment by thom4parisot** [comment]
Après inspection, ce problème apparait quand on supprime une entrée dans l'onglet "Citations". On réécrit cette partie, pour que ça supprime la portion, sans toucher au reste de la bibliographie.

**Comment by antoinentl** [comment]
Testé et approuvé, aucun problème rencontré avec les scénarios suivants :

- ajout d'une référence via Raw BibTeX ;
- modification d'une référence via Raw BibTeX ;
- suppression d'une référence via Raw BibTeX ;
- suppression d'une référence via Citations ;
- import d'une bibliographie avec Zotero puis tests précédents.
