### ISSUE TITLE
Afficher la bibliographie et le YAML sur les versions antérieures d'un article en lecture seule

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#252]
Nous avions accès à la bibliographie et au YAML de chaque version d'un article, ces données étaient affichées à la suite du texte de l'article.

Est-ce que vous vous souvenez avoir désactivé cette fonction ?

**Comment by thom4parisot** [comment]
On n'y a pas touché directement, mais ça touche à la bibliographie donc peut-être qu'on a indirectement altéré l'affichage.

Quelles actions on doit faire dans l'interface pour accéder à une version et constater ce comportement inattendu ?

**Comment by ggrossetie** [comment]
@antoinentl est-ce que c'est toujours d'actualité ? si oui, est-ce que tu peux s'il te plait nous fournir des informations supplémentaires, sinon on peut fermer.

**Comment by antoinentl** [comment]
Je ne suis plus sûr de l'identification du problème initial... En tout cas nous avons accès aux différentes versions du texte, du YAML et de la bibliographie donc pour moi tout est beau. @Mmellet si tu vois quelque chose qui manque je te laisse rouvrir et documenter, merci !

**Comment by Mmellet** [comment]
J'ai réouvert l'issue : actuellement lorsque nous cliquons sur une version de l'article, le volet des métadonnées est éditable (ce qui me paraît bizarre), et les références dans le volet bibliographie sont cliquables (ce qui est aussi bizarre) sans donner d'accès au manage de la biblio donc impossible de voir le bibtex des références. 

Je pense que le yaml et la biblio des anciennes versions ne doivent pas être cliquables ou éditables, mais juste consultables.

**Comment by antoinentl** [comment]
Je me permets des précisions :

- il faut que nous puissions afficher les données relatives à n'importe quelle version :
    - métadonnées :heavy_check_mark: c'est déjà le cas en version interface et données brutes avec l'accès au YAML ;
    - bibliographie : nous ne voyons que les références dans le panneau latéral, **il faudrait que nous puissions accéder au BibTeX raw** pour chaque version ;
- il ne faut pas que les données puissent être éditables (c'est actuellement le cas avec le volet des métadonnées), le risque est de créer de la confusion : si nécessaire je peux ouvrir une issue dédiée pour ce point précis.

@oncletom @Mogztter dites moi si vous avez besoin de précisions !

**Comment by ggrossetie** [comment]
Je pense que c'est clair, cela rejoint https://github.com/EcrituresNumeriques/stylo/issues/392 où il faudrait surement avoir des indications visuelles afin de comprendre qu'on consulte un article en lecture seule.

Cela rejoint aussi https://github.com/EcrituresNumeriques/stylo/issues/69 où on pourrait ajuster les informations disponibles (ou non) dans le volet latéral.

> métadonnées heavy_check_mark c'est déjà le cas en version interface et données brutes avec l'accès au YAML ;

Est-ce qu'ont peut afficher uniquement le raw mode en lecture seule ?
D'ailleurs on pourrait surement activer la coloration syntaxique quand on consulte le YAML en lecture car dans ce cas le YAML est forcement valide. Je pense que cela faciliterait surement la lecture.

De la même façon, on pourrait aussi avoir de la coloration syntaxique sur le raw BibTeX.
