### ISSUE TITLE
Remplacer shelljs par des API natives/module rimraf

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#253]
C'est dans la lignée de #213.

L'utilisation de `shelljs.echo(...).to(...)` du fichier `export.js` génère des logs énormes, en plus de créer des processus système de courte durée.

- [ ] remplacer la lecture/écriture de fichiers par de la lecture/écriture asynchrone/streamée
- [ ] remplacer `rm ...` par `rimraf`
- [ ] remplacer `mkdir ...` par `fs.mkdir(..., {recursive: true})`
- [ ] remplacer `sed ...` et `shell.sed(...)` par un `yaml.replace(/.../gm, ...)`
- [ ] remplacer `shell.exec('pandoc ...')` par un `child_process.promises.exec(...)`

**Comment by ggrossetie** [comment]
:100:
