### ISSUE TITLE
Repenser le design de la gestion des comptes

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#256]
Actuellement pour éditer dans Stylo il faut se créer/se connecter aux comptes suivants : Huma-Num, Zotero, Hypothesis.
Comment permettre une création/gestion/connexion plus simple ?

**Comment by ggrossetie** [comment]
Zotero et Hypothesis étant des services indépendants je ne vois pas vraiment de solution (sauf ce services décident de supporter HumanId).

Zotero permet de se connecter avec OpenID mais ce standard n'a pas l'air très populaire 😞 (Il suffit de regarder les captures d'écrans sur le site : https://openid.net/start-using-your-openid/).
Côté Hypothesis, il faut se créer un compte, on ne peut pas utiliser un compte externe.

**Comment by thom4parisot** [comment]
En pratique on pourrait se connecter à Stylo en utilisant son compte Zotero, en complément ou à la place d'Huma-Num (ça fournirait le même service).

On pourrait causer (à nouveau) avec Hypothesis pour que Stylo soit une [application OAuth reconnue](https://h.readthedocs.io/en/latest/api/using-oauth/) et proposer ainsi la même facilité de connexion à l'interface.

En plus, ça aiderait à intégrer le client d'annotation à même la page, et d'auto-connecter la personne si elle a relié _une fois_ son compte Stylo à Hypothesis.

**Comment by thom4parisot** [comment]
Les suites dans #1068 et #1069.
