### ISSUE TITLE
Impossible d'ouvrir un article avec un BibTeX erroné

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#257]
Si un article avant nouvelle version avait un bibtex erroné - le correcteur bibtex le bloque : exemple ED1484-broke

**Comment by ggrossetie** [comment]
Oui c'est le comportement attendu.
Je ne comprends pas l'exemple "ED1484-broke", de quoi s'agit il ? Est-il possible d'ajouter en commentaire le BibTeX qui ne passe pas afin que je puisse confirmer si le validateur fait bien son travail (ou si il s'agit d'un cas non prévu qui ne devrait pas bloquer)

**Comment by Mmellet** [comment]
Le ED1484-broke est le nom d'un article dans stylo qui a connu ce soucis. Le validateur fait bien son travail, le bibtex de cet article en exemple était bien erroné, mais comme ce dernier l'était avant l'arrivée du  validateur dans stylo, l'article se trouve bloqué : il n'est plus possible de l'éditer, d'éditer le bibtex pour corriger l'erreur, etc. 

Est-ce que c'est plus clair ?

**Comment by ggrossetie** [comment]
Bonjour @Mmellet 👋 

Oui c'est plus clair, merci.
Quelques questions complémentaires :

> Le ED1484-broke est le nom d'un article dans stylo qui a connu ce soucis. 

Est-il possible d'avoir l'identifiant de l'article (contenu dans l'URL), par exemple: https://stylo.huma-num.fr/article/5f71d764a066a800112f18ae

>  Le validateur fait bien son travail, le bibtex de cet article en exemple était bien erroné, 

Ok 👍 

> l'article se trouve bloqué : il n'est plus possible de l'éditer, d'éditer le bibtex pour corriger l'erreur, etc.

Ça ce n'est pas normal.
En théorie, il devrait être possible de corriger l'erreur dans l'éditeur BibTeX et cela ne devrait pas bloquer l'édition de l'article.

**Comment by Mmellet** [comment]
Voici l'url de l'artcile ED1484-broke : https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/5cc1d219972e5900191acd92?preview=true

Merci !

**Comment by ggrossetie** [comment]
@Mmellet Je viens de déployer un correctif, l'article est de nouveau visible : https://stylo.huma-num.fr/article/5cc1d219972e5900191acd92

Le problème était que deux citations n'ont pas de titre:

```
@misc{lode_sd,
  author="{LODE: Linked Open Data Enhancer}",
  url={https://github.com/linkedhumanities/lode},
  urldate={2020-06-19}
}

@misc{internet_sd,
  author="{Internet Philosophy Ontology (InPhO) Project}",
  url={https://www.inphoproject.org/},
  urldate={2020-06-19}
}
```

Comme on pensait que le titre était obligatoire (et donc systématiquement présent) on ne faisait pas de verification.

Avec #260 le validateur BibTeX ne déclenchera plus d'exception si le `title` est manquant.

Je te laisse valider et clôturer ce ticket si c'est tout bon de ton côté :smile:

**Comment by Mmellet** [comment]
Merci !!
