### ISSUE TITLE
Dans certains cas, le validateur BibTeX déclenche une exception qui force à quitter la page de l'article

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#258]
unstabilité du bibtex éditeur : force à quitter la page de l'article sans enregistrement des modifications dans le bibtex

**Comment by ggrossetie** [comment]
Bonjour @Mmellet 
Est-ce que tu peux s'il te plait détailler les opérations effectuées qui ont conduit à cette instabilité. Il nous faudrait aussi l'identifiant du document pour que l'on puisse reproduire l'anomalie afin de comprendre d'où vient le problème.

Est-ce que tu pourrais aussi nous donner la version de ton navigateur ? 

Merci!

**Comment by Mmellet** [comment]
Cette anomalie a été repérée dans le 1525 (mais elle me semble générale). 

Relisant à l'intérieur de l'éditeur bibtex pour corriger les erreurs de la bibliographie, j'ai fait plusieurs modifications minimales à la volée (mettre des majuscules, ajouter des espaces dans des "title" d'entrées bib), mais lorsque que je fais des modifications un peu plus intrusive (mettre une lettre en exposant en incluant la lettre concernée entre $^{ et }$ ) avant que j'ai pu terminer d'écrire ce code, la page se bloque : elle devient toute blanche. Lorsque j'actualise la page, je me retrouve sur mon compte utilisateur et en revenant sur l'article, aucunes des modifications effectuées dans le bibtex (minimales comme plus grandes) n'ont été maintenues. 

La version de mon navigateur est 81.0 (64 bits)

**Comment by ggrossetie** [comment]
> Cette anomalie a été repérée dans le 1525 (mais elle me semble générale).

Je pense que 1525 est le nom de l'article ? Est-il possible d'avoir l'URL de cet article ?

> Relisant à l'intérieur de l'éditeur bibtex pour corriger les erreurs de la bibliographie, j'ai fait plusieurs modifications minimales à la volée (mettre des majuscules, ajouter des espaces dans des "title" d'entrées bib), mais lorsque que je fais des modifications un peu plus intrusive (mettre une lettre en exposant en incluant la lettre concernée entre $^{ et }$ ) avant que j'ai pu terminer d'écrire ce code, la page se bloque : elle devient toute blanche.

Merci pour la procédure détaillée, cela va simplifier la reproduction de l'anomalie.

> Lorsque j'actualise la page, je me retrouve sur mon compte utilisateur et en revenant sur l'article, aucunes des modifications effectuées dans le bibtex (minimales comme plus grandes) n'ont été maintenues.

Le fait que la page se bloque est anormale, mais le fait de rafraichir la page (à raison dans ce cas pour débloquer la situation) va perdre toutes les données en mémoire. Autrement dit, les modifications sur le BibTex sont enregistrées uniquement lorsque l'on clique sur le bouton "Save".
Autre cas, si on ferme la fenêtre contextuelle permettant d'éditer sa bibliographie sans avoir cliquer sur "Save" toutes les modifications seront perdues.

Je vais essayer de reproduire cette anomalie.

> La version de mon navigateur est 81.0 (64 bits)

Chrome et Firefox ont quasiment les mêmes numéros de versions maintenant, mais je suppose qu'il s'agit de la dernière version de Firefox ? 🦊

**Comment by Mmellet** [comment]
Oui en effet le 1525 est le nom d'un article (pardon j'aurai dû le préciser), voici son url : https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/5e17e4b24f58270018f9cce5?preview=true

Qudn tu dis reproduire l'anomalie, vas-tu aller dans l'article ? C'est juste pour savoir car cet article étant en édition, il se peut que des personnes travaillent dans l'interface d'édition en ce moment même. Si besoin je peux dupliquer l'article et te le partager. 

Oui pour Firefox :) 

Merci à toi !

**Comment by ggrossetie** [comment]
> Qudn tu dis reproduire l'anomalie, vas-tu aller dans l'article ? C'est juste pour savoir car cet article étant en édition, il se peut que des personnes travaillent dans l'interface d'édition en ce moment même. Si besoin je peux dupliquer l'article et te le partager.

Pas d'inquietude je ne ferais pas de modification 😉

**Comment by ggrossetie** [comment]
Normalement le code du validateur BibTeX est maintenant plus robuste.
J'ai modifié les citations de l'article https://stylo.huma-num.fr/article/5e17e4b24f58270018f9cce5 dans l'onglet Raw BibTeX *sans enregistrer* et je ne reproduis plus l'erreur.

@Mmellet Est-ce que tu peux s'il te plait refaire des tests de ton côté afin de valider que l'anomalie est bien corrigée ?

**Comment by Mmellet** [comment]
De mon côté tout semble bon ! Mercii

**Comment by ggrossetie** [comment]
Parfait!
Je cloture, si tu constates le problème à nouveau, n'hésite pas à réouvrir :wink:
