### ISSUE TITLE
Erreur 502 sur les preview/annotate html de versions antérieures à la dernière

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#26]
exemple : https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/5b10f9c31267c100115e9c45?preview=true

**Comment by lakonis** [comment]
le bug n'est pas systématique. est ce que ce peut être certaines écritures en base qui ne se font pas ? pourtant les versions sont bien accessibles.

**Comment by lakonis** [comment]
autre exemple : https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/5b155961ae7622001745667f?preview=true

**Comment by lakonis** [comment]
le second exemple donne une erreur 504.
Hypothèse discutée avec @marviro  : 
1. les erreurs 502 sont des erreurs de format: bibtex notamment qui n'est pas contrôlé/validé comme le yaml. Dans ce cas, il faudrait renvoyer un message d'erreur plutôt qu'une 502, en fonction de l'erreur que renvoie pandoc.
2. les erreurs 504 pourraient venir de preview d'articles qui ont été supprimées (ou pas, mais cas à prévoir et message d'erreur à implémenter là aussi).

A part ces deux exemples, on n'a pas reproduit le.s bug.s.

**Comment by ggrossetie** [comment]
Je ferme, merci de réouvrir si le problème réapparait.
