### ISSUE TITLE
Est-ce que vous souhaitez être cités (par vos noms et prénoms) dans un billet de blog à venir ?

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#261]
@oncletom @Mogztter il est prévu un post de blog sur https://humanum.hypotheses.org/ pour la sortie de Stylo sur HumanId. Souhaitez être nommément cités ? On prévoit cette phrase : 

> Stylo a été conçu et développé par l'équipe de la _Chaire de recherche du Canada sur les écritures numériques_ (CRC-EN), Arthur Juchereau, Thomas Parisot, Guillaume Grossetie, avec le support d'[Érudit](https://www.erudit.org) et de la TGIR Huma-Num.

Merci

**Comment by ggrossetie** [comment]
@lakonis C'est OK pour moi. Pour info, Thomas est hors-ligne jusqu'à fin octobre, tu n'auras donc surement pas de réponse de sa part avant cette date.

**Comment by lakonis** [comment]
Même question pour toi @PookMook ? (et Salut!)

**Comment by lakonis** [comment]
Je comptais faire un renvoi vers votre compte github, souhaitez vous le faire ailleurs (site perso, société) ?

**Comment by ggrossetie** [comment]
GitHub c'est OK pour moi

**Comment by thom4parisot** [comment]
OK pour moi, avec un lien vers [détour.studio](https://détour.studio). C'est sympa, merci !

**Comment by ggrossetie** [comment]
Billet publié : https://humanum.hypotheses.org/6311 :tada: 

@lakonis Est-ce que je peux fermer ?
