### ISSUE TITLE
L'API d'export fournit 2 versions d'un document stylo au lieu d'une version

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#264]
Nouveau bug que je ne m'explique pas en décryptant le code de export.js : 

L'endpoint `curl -o intro.zip https://stylo.huma-num.fr/export/article/5dc05e9c21cedb001958b55a/zip` fournit un zip contenant 6 fichiers au lieu de 3.

Je pensais initialement que c'était parce que le document avait été édité mais l'utilisateur n'avait pas déclaré de nouvelle version. Mais le probleme se répète pour d'autres articles n'ayant pas de version en cours d'édition.

Le zip contient en fait les deux dernières versions (dont celle en cours s'il y en a une) 

Idéalement il ne faudrait avoir que la version en cours, comme le fait la preview html par exemple.

**Comment by lakonis** [comment]
En fait, l'endpoint sert de mutiples versions, mais je ne sais pas pourquoi.. 
exemple sur une série d'articles : 

```bash
tree
.
├── annexe
│   ├── 5f914be34be552001159a7f1.bib
│   ├── 5f914be34be552001159a7f1.md
│   └── 5f914be34be552001159a7f1.yaml
├── annexe.zip
├── chapitre1
│   ├── 5f666018fd0417001a2e339f.bib
│   ├── 5f666018fd0417001a2e339f.md
│   ├── 5f666018fd0417001a2e339f.yaml
│   ├── 5f90924a4be552001159a7ae.bib
│   ├── 5f90924a4be552001159a7ae.md
│   └── 5f90924a4be552001159a7ae.yaml
├── chapitre1.zip
├── chapitre2
│   ├── 5f6a1116fd0417001a2e33ea.bib
│   ├── 5f6a1116fd0417001a2e33ea.md
│   ├── 5f6a1116fd0417001a2e33ea.yaml
│   ├── 5f86fd0f4be552001159a1fb.bib
│   ├── 5f86fd0f4be552001159a1fb.md
│   ├── 5f86fd0f4be552001159a1fb.yaml
│   ├── 5f9092694be552001159a7b8.bib
│   ├── 5f9092694be552001159a7b8.md
│   └── 5f9092694be552001159a7b8.yaml
├── chapitre2.zip
├── chapitre3
│   ├── 5f7c818c4be5520011599c2e.bib
│   ├── 5f7c818c4be5520011599c2e.md
│   ├── 5f7c818c4be5520011599c2e.yaml
│   ├── 5f86ff0b4be552001159a1ff.bib
│   ├── 5f86ff0b4be552001159a1ff.md
│   ├── 5f86ff0b4be552001159a1ff.yaml
│   ├── 5f9092864be552001159a7ba.bib
│   ├── 5f9092864be552001159a7ba.md
│   └── 5f9092864be552001159a7ba.yaml
├── chapitre3.zip
├── chapitre4
│   ├── 5f7437cca066a800112f198e.bib
│   ├── 5f7437cca066a800112f198e.md
│   ├── 5f7437cca066a800112f198e.yaml
│   ├── 5f86fc574be552001159a1f7.bib
│   ├── 5f86fc574be552001159a1f7.md
│   ├── 5f86fc574be552001159a1f7.yaml
│   ├── 5f9092644be552001159a7b6.bib
│   ├── 5f9092644be552001159a7b6.md
│   └── 5f9092644be552001159a7b6.yaml
├── chapitre4.zip
├── chapitre5
│   ├── 5f6a1086fd0417001a2e33e8.bib
│   ├── 5f6a1086fd0417001a2e33e8.md
│   ├── 5f6a1086fd0417001a2e33e8.yaml
│   ├── 5f86fb934be552001159a1f5.bib
│   ├── 5f86fb934be552001159a1f5.md
│   ├── 5f86fb934be552001159a1f5.yaml
│   ├── 5f90925f4be552001159a7b4.bib
│   ├── 5f90925f4be552001159a7b4.md
│   └── 5f90925f4be552001159a7b4.yaml
├── chapitre5.zip
├── chapitre6
│   ├── 5f68c13ffd0417001a2e33da.bib
│   ├── 5f68c13ffd0417001a2e33da.md
│   ├── 5f68c13ffd0417001a2e33da.yaml
│   ├── 5f86fac74be552001159a1f3.bib
│   ├── 5f86fac74be552001159a1f3.md
│   ├── 5f86fac74be552001159a1f3.yaml
│   ├── 5f88a3094be552001159a375.bib
│   ├── 5f88a3094be552001159a375.md
│   ├── 5f88a3094be552001159a375.yaml
│   ├── 5f90929b4be552001159a7bc.bib
│   ├── 5f90929b4be552001159a7bc.md
│   └── 5f90929b4be552001159a7bc.yaml
├── chapitre6.zip
├── chapitre7
│   ├── 5f68c0d5fd0417001a2e33d8.bib
│   ├── 5f68c0d5fd0417001a2e33d8.md
│   ├── 5f68c0d5fd0417001a2e33d8.yaml
│   ├── 5f86d3094be552001159a1d9.bib
│   ├── 5f86d3094be552001159a1d9.md
│   ├── 5f86d3094be552001159a1d9.yaml
│   ├── 5f90925a4be552001159a7b2.bib
│   ├── 5f90925a4be552001159a7b2.md
│   └── 5f90925a4be552001159a7b2.yaml
├── chapitre7.zip
├── conclusion
│   ├── 5f7b841c4be5520011599bc7.bib
│   ├── 5f7b841c4be5520011599bc7.md
│   ├── 5f7b841c4be5520011599bc7.yaml
│   ├── 5f9041d54be552001159a75c.bib
│   ├── 5f9041d54be552001159a75c.md
│   ├── 5f9041d54be552001159a75c.yaml
│   ├── 5f9092cc4be552001159a7c4.bib
│   ├── 5f9092cc4be552001159a7c4.md
│   ├── 5f9092cc4be552001159a7c4.yaml
│   ├── 5f9139e14be552001159a7eb.bib
│   ├── 5f9139e14be552001159a7eb.md
│   └── 5f9139e14be552001159a7eb.yaml
├── conclusion.zip
├── glossaire
│   ├── 5f9092d24be552001159a7c6.bib
│   ├── 5f9092d24be552001159a7c6.md
│   └── 5f9092d24be552001159a7c6.yaml
├── glossaire.zip
├── introduction
│   ├── 5f665f42fd0417001a2e339d.bib
│   ├── 5f665f42fd0417001a2e339d.md
│   ├── 5f665f42fd0417001a2e339d.yaml
│   ├── 5f9038d34be552001159a75a.bib
│   ├── 5f9038d34be552001159a75a.md
│   └── 5f9038d34be552001159a75a.yaml
├── introduction.zip
├── metadonnees
│   ├── 5f914a4f4be552001159a7ef.bib
│   ├── 5f914a4f4be552001159a7ef.md
│   └── 5f914a4f4be552001159a7ef.yaml
├── metadonnees.zip
├── participants
│   ├── 5f9092b44be552001159a7be.bib
│   ├── 5f9092b44be552001159a7be.md
│   └── 5f9092b44be552001159a7be.yaml
├── participants.zip
├── remerciements
│   ├── 5f9092554be552001159a7b0.bib
│   ├── 5f9092554be552001159a7b0.md
│   └── 5f9092554be552001159a7b0.yaml
└── remerciements.zip
```

les ids sont les ids de version.

**Comment by antoinentl** [comment]
Est-ce que les différentes versions servies correspondraient à des versions majeures ? Ça expliquerait qu'il y ait de 2 à 4 versions.

**Comment by lakonis** [comment]
de ce que j'ai vu, c'était plutôt les deux dernieres versions : la derniere
dont je connaissais l'id + la version en cours d'édition.

mais c'est à revérifier. il faut comparer les ids que j'ai mis en
commentaires ci-dessus.

**Comment by ggrossetie** [comment]
@lakonis L'API d'export utilise un répertoire partagé. La commande zip ajoute uniquement les fichiers ayant un id particulier : 

```
zip chapitre4.zip ${id}.*
```

Mais le problème est que le service d'export ne supprime pas ce zip !
Par conséquent, lors d'un nouvel export, avec une version plus récente, les fichiers vont s'ajouter au fichier zip déjà existant.
Pour rappel, le nom du fichier zip est le titre de l'article.

Plus inquiétant encore, si quelque exporte un article ayant le même titre qu'un autre article (qui peut être édité par une autre personne), l'export va retourner les deux articles dans le même zip !
Autrement dit, on peut récupérer les articles d'une autre personne si on utilise le même nom d'article :scream: 

A noter que ce problème était peut être moins visible auparavant car le répertoire partagé est supprimé lors du redémarrage du conteneur.

En tout état de cause, il ne faudrait pas utiliser un répertoire partagé et éviter de lancer des commandes système.
Thomas a ouvert quelques issues sur ce sujet : 

- https://github.com/EcrituresNumeriques/stylo/issues/213
- https://github.com/EcrituresNumeriques/stylo/issues/253

@antoinentl Je pense que cette anomalie est assez problématique, on passe le point prioritaire ?

**Comment by antoinentl** [comment]
@lakonis je réouvre cette issue pour que tu re-testes quand tu as deux minutes.

**Comment by ggrossetie** [comment]
ping @lakonis  😉 🏓

**Comment by thom4parisot** [comment]
Surtout que ça sent le même endroit que le `sed` + export + `<id article|version>.bib`…
