### ISSUE TITLE
Ajouter une fonctionnalité d'autocomplétion pour l'ajout de références bibliographiques

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#271]
Suite à #401 l'objectif ici serait d'ajouter une fonctionnalité facilitant la saisie d'une référence bibliographique lors de la rédaction.

## Comportement attendu
Au moment où l'on écrit `[@` ou `@`, un menu déroulant s'affiche avec les 5 premières références (les clés) par ordre alphabétique, la sixième occurrence pourrait être trois petits points `…` dans le cas où il y a plus de 5 références. Dès que l'on continue à écrire les suggestions se mettent automatiquement à jour, toujours avec les `…` dans le cas où il y a plus de 5 références correspondantes.

## Détails importants
Évidemment pour que cela fonctionne il faut que la référence ait déjà été ajoutée dans les références disponibles.

Il ne s'agit pas d'un mini moteur de recherche mais bien d'une autocomplétion, ce qui signifie que si les lettres de la clé sont tapées dans le mauvais ordre ça ne pourra pas fonctionner.

**Comment by antoinentl** [comment]
Est-ce que la description est suffisamment détaillée @oncletom @Mogztter ? Ré-attribuez moi le ticket si ce n'est pas le cas.

**Comment by thom4parisot** [comment]
C'est fait avec #415
