### ISSUE TITLE
Sous-titre absent dans export PDF générique 

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#272]
Il semble que les export PDF à partir de Stylo ne présentent pas la section "Sous-titre" des Métadonnées.

**Comment by thom4parisot** [comment]
Tu as un identifiant de document sur lequel on peut observer ce comportement inattendu ?

**Comment by Mmellet** [comment]
Il y a le ED1560 : https://stylo-export.ecrituresnumeriques.ca/cgi-bin/exportArticle/exec.cgi?id=ED1560v2-0&version=5fbe69a54be552001159da79&processor=xelatex&source=https://stylo.ecrituresnumeriques.ca/&format=pdf&bibstyle=chicagomodified&toc=false

**Comment by marviro** [comment]
Je vais regarder @oncletom , j'imagine que ça depend du template pandoc - probablément on a changé le nom de la clé yaml?

**Comment by thom4parisot** [comment]
Qui est le "on" ?

**Comment by marviro** [comment]
C'est fixé. Il y avait un bug dans le template latex (mais donc ça veut dire que ça a jamais fonctionné...)
