### ISSUE TITLE
Mise en place de Matomo afin d'améliorer l'experience utilisateur

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#278]
Thomas suggère de brancher un serveur Matomo pour mesurer les actions dans l'interface de Stylo.
Matomo nous permettrait de mieux comprendre les différents parcours utilisateurs et d'avoir des statistiques sur les fonctionnalités qui sont pas, peu ou beaucoup utilisées.

A mettre en lien avec https://github.com/EcrituresNumeriques/stylo/issues/268 pour indiquer qu'on collecte des données.

**Comment by antoinentl** [comment]
J'ai fait une demande d'accès au Matomo d'Huma-Num, je vous tiens au courant quand j'ai un compte.

**Comment by thom4parisot** [comment]
> To setup Matomo on your system, you may need the following information:
> Matomo URL: https://analyseweb.huma-num.fr/
> Your site ID: 286 

```html
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://analyseweb.huma-num.fr/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '286']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by antoinentl** [comment]
Maintenant que Matomo est activé, est-ce qu'on peut intégrer le code dans l'application ? Est-ce que c'est si simple @oncletom @Mogztter ?

**Comment by thom4parisot** [comment]
Intégrer c'est fastoche, suivre les pages visitées aussi.

Y'a surement des trucs plus malins à faire par la suite (savoir si tels ou tels éléments d'interface sont utilisés — genre l'éditeur de tags ou autre). Ça permettrait de savoir combien de % de gens affichant la page d'accueil interagissent avec des fonctionnalités de cette page, etc.

**Comment by antoinentl** [comment]
Partons sur un fonctionnement _basique_, dans un mois nous pourrons déjà analyser les premiers résultats.
