### ISSUE TITLE
Probleme de preview current version 

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#285]
La preview des versions en cours ou mineures ou majeures de nombreux articles (à partir de comptes stylo différents) affiche un message d'erreur 

![Screenshot_2020-12-09 https via hypothes is](https://user-images.githubusercontent.com/40469215/101614662-3bdea480-39db-11eb-95c6-78f4fa449bf8.png)

(Le problème peut venir de moi)

**Comment by marviro** [comment]
j'ai ele même problème hier. comme si c'était un problème de ressources... ds idées?

**Comment by ggrossetie** [comment]
Je pense qu'il s'agit d'un problème sur via.hypothes.is qui utilise la librairie [Pywb](https://pywb.readthedocs.io/en/latest/manual/configuring.html).

Côté Stylo il n'y a pas eu de nouvelle version depuis un moment et le document s'affiche bien quand on supprime le préfixe via.hypothes.is de l'URL.

**Comment by ggrossetie** [comment]
Ou alors c'est une incompatibilité entre la "nouvelle" version de via.hypothes.is et ce qui est envoyé par Stylo mais l'erreur ne nous donne assez peu d'informations. Il faudrait sûrement contacter le support de via.hypothes.is.

**Comment by ggrossetie** [comment]
Je ne reproduis pas/plus l'erreur: https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/5efe6a345dac0b001a991d5f?preview=true
