### ISSUE TITLE
🐾 Un partage aisé des droits d'écritures

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#289]
Je suis perdu quand je veux partager des articles car :
- Je dois connaître partager et donc connaître le mail de la personne, et plus précisément le mail de son compte Stylo.
- Je ne sais pas bien où cliquer pour partager

Et lorsque j'ai partagé un article, je ne peux plus enlever les droits d'écritures ce qui m'ennuie.

**Comment by ggrossetie** [comment]
Je complète avec mes réflexions suite aux travaux engagés sur #464 et #159.
Je pense qu'il faudrait aussi clarifier les permissions accordées à la personne avec laquelle on partage un ou plusieurs articles : 
- Est-ce qu'elle peut modifier le titre de l'article ?
- Est-ce qu'elle peut modifier les tags ?
- Est-ce qu'elle peut partager l'article avec d'autres personnes ?

Il pourrait aussi être intéressant de filtrer la liste des articles pour afficher uniquement les articles que j'ai crée des articles qu'on m'a partagé. Dans la même idée, peut être distinguer un peu plus le créateur des personnes avec lesquelles j'ai partagé l'article. Cela pourrait nous permettre d'ajouter une action afin de retirer une personne de cette liste.

**Comment by ggrossetie** [comment]
@maiwann Il serait intéressant de réinterroger ces personnes une fois #508 déployé en production pour voir si les changements apportés leur conviennent.

**Comment by maiwann** [comment]
Question utilisateurs : Que pensez-vous des améliorations récentes ? Qu'est-ce qui manque ? Qu'est-ce qui est pas clair ?
