### ISSUE TITLE
💫 Le rêve de la collaboration synchrone

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#290]
J'aimerai pouvoir rédiger de façon synchrone mais, actuellement :
- Je peux perdre mon travail à cause de bugs
- Cela met le bazar dans les versions (les enregistrements se succèdent)
donc je ne le fais pas, je m'organise pour être tour à tour sur le document.

**Comment by thom4parisot** [comment]
Sur Confluence : 

![image](https://user-images.githubusercontent.com/138627/113710760-666c1000-96e4-11eb-9e98-0660548142fa.png)

Slate.js : 

![image](https://user-images.githubusercontent.com/138627/113716097-84d50a00-96ea-11eb-831c-353d0372c2a9.png)

Quill : 

![animation](https://raw.githubusercontent.com/reedsy/quill-cursors/master/assets/demo.gif)
