### ISSUE TITLE
🦉 Le décalage m'empêche de comparer mes versions.

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#294]
Lorsque je veux comparer mes versions, le contenu est décalé dès le début de la page et j'ai du mal à faire le comparatif puisque les paragraphes ne sont pas face à face.

**Comment by ggrossetie** [comment]
@antoinentl Est-ce qu'il faut conserver la coloration syntaxique (Markdown) quand on compare deux versions ou est-ce qu'on peut afficher le texte brut?

![image](https://user-images.githubusercontent.com/333276/119237012-e508f980-bb3a-11eb-9315-9c35ddd8acb3.png)


Dans mon example j'ai ajouté des "petits carrés" pour afficher/masquer les mots ou phrases supprimés : 

![image](https://user-images.githubusercontent.com/333276/119237089-6791b900-bb3b-11eb-844c-3c69920d53c4.png)

Quand on clique dessus on masque la suppression ce qui permet de conserver les paragraphes/sections alignés.

**Comment by thom4parisot** [comment]
Ce n'est plus le cas avec le nouveau comparateur introduit par https://github.com/EcrituresNumeriques/stylo/pull/512
