### ISSUE TITLE
Trouver un meilleur moyen de séparer les mots-clés

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#295]
Les mots-clés doivent être séparés par une virgule **et** un espace (`, `), malheureusement ce n'est pas clair pour tous le monde, et nous rencontrons actuellement les problèmes suivants :

- oubli de l'espace : ce qui fait que nous n'obtenons qu'un seul mot-clé
- virgule dans un mot-clé (oui bon c'est un peu étrange) : il faudrait pouvoir utiliser la virgule dans le mot-clé

Solution envisagée :

- clarifier le message d'aide
- changer le séparateur d'éléments
- changer le fonctionnement global d'ajout de mots-clés

**Comment by ggrossetie** [comment]
@antoinentl On n'utilise plus ce principe de fonctionnement sur le nouveau formulaire. Il faut cliquer explicitement sur un bouton "Ajouter+": https://stylo-dev.huma-num.fr/form/

L'intégration du nouveau formulaire dans l'éditeur (pull request #270) n'est plus déployée sur  https://stylo-dev.huma-num.fr. Est-ce que tu souhaites que je déploie à nouveau cette branche sur l'environnement de développement pour que tu puisses tester ?

**Comment by antoinentl** [comment]
@Mogztter Oui je veux bien que tu redéploies, merci !

**Comment by ggrossetie** [comment]
@antoinentl C'est déployé sur https://stylo-dev.huma-num.fr


![stylo-keywords](https://user-images.githubusercontent.com/333276/102507204-473d6a00-4084-11eb-959b-70156456ee2a.png)

**Comment by antoinentl** [comment]
Merci :pray:

**Comment by thom4parisot** [comment]
Fait dans #270
