### ISSUE TITLE
Comment reconnaître qu'un article a été modifié ?

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#297]
Actuellement la liste des articles, en page d'accueil de Stylo, est ordonnée selon le document le plus récemment modifié, **mais** cette modification en question ne concerne que le corps de texte et non le versionnement. Explications :

- si un article n'a que ses métadonnées de modifiées, et même s'il est versionné, alors il restera à la même place dans la liste après avoir été modifié ;
- un article qui n'a que son corps de texte de modifié changera de position (version attribuée automatiquement).

Solution envisagée : classer les articles toujours par ordre de modification, mais en prenant en compte la dernière version (même automatique).

**Comment by ggrossetie** [comment]
> si un article n'a que ses métadonnées de modifiées, et même s'il est versionné, alors il restera à la même place dans la liste après avoir été modifié ;

Ce n'est pas ce que je constate sur https://stylo-dev.huma-num.fr/ : 


![modifcation](https://user-images.githubusercontent.com/333276/156345967-4d65bedd-f6dc-46bc-993e-5d1b1642ebba.gif)


Dans cette vidéo, je modifie uniquement les métadonnées et en revenant sur la liste des articles, mon article apparait en premier.

@antoinentl Est-ce que tu confirmes ?

**Comment by antoinentl** [comment]
Hum non mes articles ne sont pas triés par date sur ma page d'accueil de Stylo sur stylo-dev :

![Capture d’écran de 2022-03-08 20-48-32](https://user-images.githubusercontent.com/6869488/157356392-7fe455cb-7677-4bbc-81d2-04c1d1302433.png)

**Comment by ggrossetie** [comment]
Je ne comprends pas comment/pourquoi cela fonctionnait quand j'ai testé avec mes deux articles "hypo1" et "hypo2" mais dans l'ensemble j'ai l'impression que les articles ne sont pas triés.
Au chargement des articles ils apparaissent dans un ordre qui ne semble pas tenir compte de la date de dernière modification. 

Peut être qu'on a changé quelque chose lorsqu'on a modifié la façon de récupérer les articles auxquels un compte a le droit ? Je vais investiguer un peu 🧐

**Comment by ggrossetie** [comment]
Avec 8244eeadd43509a514a18ea342d07cad9e3754a6 ça devrait être mieux.
@antoinentl Est-ce que tu peux s'il te plait tester à nouveau sur https://stylo-dev.huma-num.fr/articles ?

**Comment by antoinentl** [comment]
Oui c'est corrigé de mon côté !
