### ISSUE TITLE
ajout de la langue de l'article dans le yamlEditor

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#3]
Les articles sont potentiellement dans d'autres langues que le fr. Il faudrait donc pouvoir modifier la donnée `lang: fr` parmi la liste suivante : 
- fr (par défaut)
- en
- ita
- es
- pt
- de
- uk
- ar

**Comment by PookMook** [comment]
C'est ajouté, en test avant release!
