### ISSUE TITLE
[Responsive] Affichage/défilement sur fenêtre étroite

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#30]
## Problème
Lorsque la fenêtre fait moins de 1093 px de large, la zone d'édition est repoussée vers le bas, sous la barre latérale de gauche.

Avec le script qui garde la barre latérale toujours en vue, impossible de rester dans la boîte d'édition markdown – le script anime la page et repousse tout vers le bas.

![capture](https://user-images.githubusercontent.com/9596476/41373069-3703e596-6f1d-11e8-851b-b3af21df4217.jpeg)

## Solution proposée

Une manière simple de régler le problème serait simplement d'utiliser la propriété CSS `position: sticky` sur la barre latérale au lieu de gérer l'affichage par javascript:

```css
#writeComponent {
  position: sticky;
}
```

**Comment by PookMook** [comment]
Le probleme devrait être résolu, en attente du prochain batch de déploiement sur stylo.ecrituresnumeriques.ca
