### ISSUE TITLE
Supprimer la dépendance  sur Gatsby

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#301]
Gatsby ajoute un niveau de complexité supplémentaire alors qu'au final nous n'utilisons pas ou très peu les fonctionnalités offertes par cette librairie (parce que nous en avons pas besoin).

Le point le plus gênant est que Gatsby prend en charge le démarrage de l'application ce qui nous empêche de contrôler finement quand et comment les composants sont chargés.

Le build est aussi relativement long et il est compliqué de charger de la configuration au runtime (ce qui en théorie devrait être relativement simple).

Dans le code de l'application, nous utilisons le router Gatsby mais il est possible d'utiliser directement `react-router-dom`.

**Comment by antoinentl** [comment]
J'ai testé la version déployée sur Netlify (deploy-preview-303--stylo-dev), pour Stylo en lui-même ça me semble bon :+1: par contre les exports ne fonctionnent pas et la _preview_ pointe sur stylo-dev.huma-num.fr au lieu de stylo.ecrituresnumeriques.ca (toujours pour cette question des annotations...), normal ?

**Comment by ggrossetie** [comment]
> J'ai testé la version déployée sur Netlify (deploy-preview-303--stylo-dev), pour Stylo en lui-même ça me semble bon +1 par contre les exports ne fonctionnent pas 

Bien vu, il y a une typo dans la configuration Netlify:

```
SNOWPACK_PUBLIC_PROCESS_ENDPOINT = "hhttps://stylo-export.ecrituresnumeriques.ca"
```

(il y a un h en trop dans https)

> et la preview pointe sur stylo-dev.huma-num.fr au lieu de stylo.ecrituresnumeriques.ca (toujours pour cette question des annotations...), normal ?

Oui on utilise un autre domaine car c'est un environnement de tests/développement. Autrement dit, on ne peut associer des annotations au domaine de production "stylo.ecrituresnumeriques.ca".
La configuration est différente en fonction de l'environnement.
