### ISSUE TITLE
Utiliser NGINX pour servir l'application React (plutôt que le serveur de développement Gatsby)

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#302]
Pour cela il est possible d'utiliser un multi-stage.
La taille de l'image devrait considérablement être réduite. Actuellement l'image Docker (basée sur Alpine fait 750MB) alors que l'image Docker nginx:mainline-alpine fait 25MB.

Pour rappel, l'application React fait environ 5MB.

**Comment by thom4parisot** [comment]
Oui c'est ça, en pratique on peut "juste" livrer le résultat du "build" pour cette partie là (le contenu du répertoire `./public`).

Je m'en suis rendu compte en déployant sur Netlify.

+1 pour le multi-stage.

**Comment by ggrossetie** [comment]
> Oui c'est ça, en pratique on peut "juste" livrer le résultat du "build" pour cette partie là (le contenu du répertoire ./public).

Oui exactement !

> Je m'en suis rendu compte en déployant sur Netlify.

Oui j'ai vu c'est trop cool ça :clap: 
Est-ce que tu pourrais ajouter le fichier `netlify.toml` sur master pour qu'on puisse éditer la configuration sans passer par l'UI de Netlify ?

**Comment by thom4parisot** [comment]
Ça roule (je vais ouvrir une PR) :)

Sachant que si y'a un fichier `netlify.toml`, ça surcharge les réglages de l'interface, quoiqu'il arrive.

**Comment by ggrossetie** [comment]
Corrigé  4b6dc66
