### ISSUE TITLE
Vérification du BibLaTeX : ajout de types de document

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#306]
Le format BibLaTeX est un format plus riche que le BibTeX, et Pandoc le gère par défaut. Par contre l'outil de vérification n'accepte pas certains types de documents comme les vidéos `@video` ou les logiciels `@software`, est-ce que c'est faisable d'ajouter ce type d'item ?

**Comment by thom4parisot** [comment]
Ça semble déjà le cas si j'en crois ce [fichier de test](https://github.com/fiduswriter/biblatex-csl-converter/blob/master/test/fixtures/import/Export%20of%20creator-type%20fields%20from%20embedded%20CSL%20variables%20%23365.biblatex.bib), et le [résultat du parser en ligne](https://fiduswriter.github.io/biblatex-csl-converter/).

Par contre, on ne devrait utiliser le parseur que pour _vérifier_ la syntaxe (et peut-être en extraire quelques infos, pour présenter les infos dans la bibliographie), et préserver les saisies telles qu'elles sont (sous forme de texte).

Ça éviterait toute perte de données/information à cause de la re-transformation — dans le bloc "raw", c'est le résultat du parsing Biblatex, vers CSL, puis reconverti en Biblatex… avec les choix et jugements réalisés par l'auteur de la lib.
