### ISSUE TITLE
Gestion de documents complexes : effectuer des tests avec BibLaTeX

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#307]

**Comment by thom4parisot** [comment]
Top !

Si tu les documentes (quelles attentes pour quels types de documents), c'est le genre de chose qu'on pourra ensuite tester automatiquement. Et éviter des régressions de code dans le futur.

**Comment by thom4parisot** [comment]
C'est fait ça, non ?

**Comment by antoinentl** [comment]
Oui je ferme !
