### ISSUE TITLE
Ajouter un placeholder lors de la création d'une nouvelle publication

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#310]
L'idée est de proposer un moyen d'accompagner les utilisateurs et les utilisatrices, de limiter l'angoisse de la page blanche, et notamment de résoudre les questions de niveaux de titre et de métadonnées minimales.

- [ ] rédiger un texte
- [ ] le faire valider/modifier par @maiwann 
- [ ] tester

**Comment by antoinentl** [comment]
Est-ce que cette fonctionnalité vous semble toujours pertinente @maiwann @Mmellet @marviro ? Je suis preneur de vos avis !

**Comment by Mmellet** [comment]
> Est-ce que cette fonctionnalité vous semble toujours pertinente @maiwann @Mmellet @marviro ? Je suis preneur de vos avis !

Je suis plus sûre de quoi on parle ... est ce qu'on peut rappeler précisément ?

**Comment by antoinentl** [comment]
@Mmellet Un _placeholder_ c'est un texte qui est placé dans l'éditeur de texte, et qui disparaît lorsque l'on commence à taper (comme dans les champs de formulaire pour aider à la saisie). L'idée est de ne pas laisser la zone de texte vide quand on crée un nouvel article, et de profiter de cet espace pour indiquer 2-3 rappels/aides. Est-ce que c'est plus clair ?

**Comment by Mmellet** [comment]
> @Mmellet Un _placeholder_ c'est un texte qui est placé dans l'éditeur de texte, et qui disparaît lorsque l'on commence à taper (comme dans les champs de formulaire pour aider à la saisie). L'idée est de ne pas laisser la zone de texte vide quand on crée un nouvel article, et de profiter de cet espace pour indiquer 2-3 rappels/aides. Est-ce que c'est plus clair ?

Oui c'est plus clair, merci. Mais tel que je le visualise, je crains que ce soit mêlant pour l'utilisateur. De quels types de rappel il s'agirait ?

**Comment by antoinentl** [comment]
@Mmellet Exemple de texte :

> Cliquez ici pour commencer à écrire votre article. L'éditeur de texte est basé sur la langage de balisage Markdown. Les panneaux latéraux vous permettent de gérer les données bibliographiques, les enregistrements ou encore les métadonnées. Un lien vers la documentation est disponible dans l'entête de cette page.

**Comment by Mmellet** [comment]
oh ok dans l'article ! oui d'accord ça fait plus de sens

**Comment by maiwann** [comment]
De mon coté, je pense que la solution du placeholder n'est pas la meilleure, et qu'il serait plus utile d'avoir une petite barre d'outils à la place, pour permettre aux personnes de découvrir le format du Markdown au moment où elles ont besoin ! (Un peu, par exemple, comme là sur Github)

**Comment by antoinentl** [comment]
Je ferme cette issue en déplaçant l'idée de départ (accompagnement à la découverte de l'outil) dans une note.
