### ISSUE TITLE
Formatter les métadonnées lors des exports

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#311]
Pourquoi : dans la continuité de #270, et indépendamment de #280.

La stratégie est de garder les schémas "purs" (#147, et #192) : on stocke la donnée une fois, on la duplique en sortie.

- [x] transformer `date` en `year` (`YYYY`), `month` (`MM`) et `day` (`DD`)
- [x] transformer `date` (`YYYY/MM/DD`) en `date` (`YYYY-MM-DD`, format ISO)
- [x] transformer `keywords` (formattage, liste concaténée)
- [x] le formattage des mots-clés doit résoudre #295
- [x] générer le `text` à partir de `text_f` en supprimant la syntax Markdown (on ne garde que le texte)

```yaml
keywords:
- lang: fr
  list:
    - **Tomme de Savoie**
    - Comté
```

en …

```json
{
	"keywords": [
		{
			  "lang": "fr",
			  "list": "Tomme de Savoie, Comté",
			  "list_f": "**Tomme de Savoie**, Comté"
		}
	]
}
```

---

Pour tester : 

- https://stylo.huma-num.fr/article/5d94d0b721cedb0019589532
- identifiant : PSP1515
- version publiée sur le site de Sens public : https://sens-public.org/dossiers/1515/

**Comment by thom4parisot** [comment]
@antoinentl je reprends la conversation ici — c'est difficile pour moi de suivre une conversation sur une PR déjà fusionnée (ça transforme une proposition de code terminée en "issue" qui collecte des feedbacks), et de planifier sa résolution.

**Comment by antoinentl** [comment]
Pour tester l'article la solution choisie avec @Mogztter ce serait de :

1. réintégrer cet article test avec ses métadonnées
2. tester l'export ZIP avec une comparaison du fichier YAML exporté et l'export HTML pour vérifier que les métadonnées sont toutes là
3. déployer en dev
4. tester à nouveau
5. déployer en production si c'est ok

**Comment by antoinentl** [comment]
Une question supplémentaire que nous avions abordée mais dont j'ai oublié la réponse : que va-t-il se passer pour les _anciens_ articles ? Il seront inchangés ?

**Comment by thom4parisot** [comment]
Exactement, les anciens articles sont inchangés : la sortie des métaonnées lors de l'export devrait donner le même résultat (je dis "devrais" au sens où c'est pas clair si on écrit les tests qui permettent de garantir cette intention).
