### ISSUE TITLE
Améliorer/ajuster le style sur les mots clé contrôlés

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#318]
Ci-dessous le rendu des mots-clés et des mots-clés contrôlés : 

:+1: 

![keywords](https://user-images.githubusercontent.com/333276/109192958-28500800-7798-11eb-9cf6-9e17e87f2096.png)

:-1: 

![keywords-ref](https://user-images.githubusercontent.com/333276/109192962-28e89e80-7798-11eb-8a4f-da131fcd04fd.png)

**Comment by thom4parisot** [comment]
C'est fait dans #329 !
