### ISSUE TITLE
Lorsque je sauve une version, je voudrais la nommer *après*

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#322]

**Comment by ggrossetie** [comment]
J'avoue que je ne me souviens plus de comment cela fonctionnait avant mais il n'est toujours pas possible de renommer une version existante.

Par exemple, dans la capture ci-dessous, je ne peux pas renommer les versions existantes pour leur donner un nom plus explicite :

![image](https://user-images.githubusercontent.com/333276/114269240-1fdd2500-9a06-11eb-82ed-8d54d2da941a.png)

Je ne sais pas si c'était ça l'idée ? 

//cc @maiwann @oncletom

**Comment by thom4parisot** [comment]
Ah oui ok ! C'était en "DONE" alors j'ai pas cherché plus loin. Ça coûterait pas cher d'avoir un "Rename" / bouton ✍️ à droite du label (comme pour les articles, & cie).

**Comment by maiwann** [comment]
Question utilisateurs : Que pensez-vous des améliorations récentes ? Qu'est-ce qui manque ? Qu'est-ce qui est pas clair ?
