### ISSUE TITLE
Je trouve la gestion multi-comptes fastidieuse

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#324]

**Comment by ggrossetie** [comment]
@maiwann On parle de la gestion/partage de compte Stylo ou d'avoir un compte HumanId, un compte Zotero et un compte Hypothesis ?

**Comment by thom4parisot** [comment]
J'aurais dis que c'était le "partage de compte", ou si une personne a 2 comptes Stylo sans avoir connaissance du partage de compte.

**Comment by maiwann** [comment]
C'est la partie "partage de compte" en effet !
Quand une personne se connecte et a accès à plusieurs comptes Stylo depuis sa page "profil"

Je vous aurais bien mis un screenshot mais…je n'ai qu'un compte Stylo ! 😄

**Comment by thom4parisot** [comment]
Je t'ai ajoutée comme personne qui peut basculer sur mon compte :-)
