### ISSUE TITLE
Si j'écris un article très long, ça rame et la table des matières est tronquée

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#325]

**Comment by thom4parisot** [comment]
Curieux de savoir si ça se reproduit avec la nouvelle version mise en production.

Si non, peux-tu obtenir une copie/URL du contenu qui pose problème ?

On a 2-3 idées des endroits où ça peut bloquer, avec des solutions pas forcément très coûteuses à mettre en œuvre.

**Comment by thom4parisot** [comment]
@maiwann est-ce que c'est en lien avec #262 ?

**Comment by maiwann** [comment]
Je pense que oui !
