### ISSUE TITLE
Je voudrais pouvoir faire Ctrl-Z

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#327]

**Comment by ggrossetie** [comment]
Cela fonctionne déjà sur l'éditeur de texte, est-ce qu'il y a un endroit en particulier où le ctrl-z ne fonctionne pas ?

**Comment by maiwann** [comment]
Non c'était bien là ! Du coup on peut fermer cette issue ? 🤔 🎉
