### ISSUE TITLE
Books m'amène sur le mode "lecture seulement" d'un article

### ISSUE THREAD

**Issue by maiwann** [EcrituresNumeriques/stylo#328]
Quand je clique sur le lien d'un Article dans Books, je suis amenée sur cet article (génial !) mais dans le mode "lecture seulement" alors que je trouverai plus naturel d'arriver sur le mode édition classique (comme si je cliquais dessus dans la page Articles)

**Comment by thom4parisot** [comment]
@maiwann un Book c'est forcément la version la plus récente de tous les articles qui le composent ?

**Comment by maiwann** [comment]
Actuellement, il me semble qu'on ne permet pas de choisir la version, du coup je dirais oui…
