### ISSUE TITLE
Rétablir l'ouverture d'une nouvelle fenêtre/onglet pour la prévisualisation depuis le page des articles

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#333]
Tout est dit dans le titre, il faut que les liens vers la prévisualisation s'ouvrent dans une nouvelle fenêtre, un nouvel onglet. C'était le cas avant le récent déploiement :upside_down_face:.

**Comment by ggrossetie** [comment]
Tu dois surement le savoir mais tu peux faire `<ctrl>` + clic sur un lien pour l'ouvrir dans une nouvelle fenêtre ou onglet (en fonction des préférences du navigateur). Cela peut être pratique en workaround le temps qu'on change le comportement par défaut sur ce lien.

**Comment by thom4parisot** [comment]
OK, parce que là si je comprends, ça s'ouvre dans le même onglet de navigateur ?

Et on est dac que ça concerne l'icône "œil", avec les annotations Hypothesis ?

![image](https://user-images.githubusercontent.com/138627/111668071-a773b180-8815-11eb-8e17-2f8d754bb294.png)

**Comment by antoinentl** [comment]
@Mogztter Oui certes mais on voudrait conserver une fonctionnalité dont on disposait (habitudes des utilisateurs·trices, toussa) et surtout avoir le même comportement sur la page des articles (oui c'est bien ça @oncletom ) et la page de _l'article_.
