### ISSUE TITLE
Réintégrer l'indication de la bibliographie dans les métadonnées en YAML

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#334]
Avec la restructuration des métadonnées l'indication de la bibliographie a disparu et l'export ne fonctionne plus.

Sur le principe cette donnée pourrait être gérée autrement, mais pour le moment nous ne souhaitons pas adapter le module d'export.

Il faudrait donc remettre cette indication :

```
bibliography: [version-de-l-article].bib
```
Exemple :

```
bibliography: 5fe10970732b1700185b813b.bib
```

En remplaçant `[version-de-l-article]` par l'identifiant de la version de l'article, le module d'export se charge ensuite de transformer cet identifiant par le nom de l'article mais ça c'est une autre histoire.

**Comment by antoinentl** [comment]
Simplement pour préciser que la plupart des exports sont actuellement bloqués à cause de ce point.

**Comment by thom4parisot** [comment]
Dac compris, aujourd'hui c'est l'identifiant de l'article qu'on met, tu me confirmes ?

https://github.com/EcrituresNumeriques/stylo/blob/63f4e7b9ef4ca5b03614964401d39d8c0adb56de/export/src/helpers/metadata.test.js#L6-L27

C'est pas grand chose à changer (je jette un œil demain matin).

**Comment by antoinentl** [comment]
Attention c'est l'identifiant de la _version_ de l'article, et non l'identifiant de l'article ! Dis moi @oncletom si ce n'est pas clair.

**Comment by thom4parisot** [comment]
Oui, j'ai compris :) On n'avait pas réalisé ça en créant le filtre de transformation. C'était sommairement intitulé "id" dans le code remplacé 😅

**Comment by thom4parisot** [comment]
Question complémentaire : si on référence la bibliographie par ID de version, quid du nom du fichier `.md` dans l'export zip : c'est l'ID de version, ou l'ID d'article ?

**Comment by marviro** [comment]
En principe il y a deux endpoint, un endpoint vesrion et un autre article. Dans le zip qu'on récupère depuis l'endpoint version les trois fichiers s'appellent avec le id de la version idVersion.md idVersion.bib idVersion.yaml et, évidemment idVersion.zip

L'endpoint article sert la dernière version - toujours et fonctionne pareil avec idArticle. Est-ce clair?

**Comment by thom4parisot** [comment]
Okay compris. Je réalise que les mêmes fonctions sont appelées dans des contextes différents (article, version), et que les `id` peut se référer à l'un ou à l'autre.

**Comment by antoinentl** [comment]
Oui tout à fait, c'est pour ça aussi que j'aurais dû mieux tester et que je prenne ensuite le temps de vous expliquer tout cela.

**Comment by thom4parisot** [comment]
En fait c'est pas clair : l'identifiant pour le champ `bibliography`, c'est toujours l'identifiant de la version, c'est ça ?

Mais selon ce qu'on exporte: 

- api/v1/articleHTML : 
	- `bibliography` = `[id-version].bib` 
- api/v1/versionHTML : 
	- `bibliography` = `[id-version].bib`
- api/v1/versionHTML : 
	- `bibliography` = `[id-version].bib` 
- `article/:id/zip`
	- `bibliography` = `[id-version].bib`
	- dans le zip, on retrouve : 
		  - `[id-article].md`
		  - `[id-article].bib`
		  - `[id-article].yaml`
- `version/:id/zip`
	- `bibliography` = `[id-version].bib` 
	- dans le zip, on retrouve : 
		  - `[id-version].md`
		  - `[id-version].bib`
		  - `[id-version].yaml`

C'est la foire aux identifiants, et j'ai du mal à me retrouver dans ce que l'application devrait faire, et ce qu'elle produit aujourd'hui.

**Comment by antoinentl** [comment]
Pour la bibliographie oui on peut partir sur l'identifiant de la version, ensuite il y a des transformations que nous gérons du côté du module de l'export.

**Comment by thom4parisot** [comment]
@antoinentl est-ce que ce que j'ai listé ci-dessus correspond à ce qui est attendu ?

**Comment by antoinentl** [comment]
@oncletom Pour l'instant on part avec ce que tu as listé, sur stylo-dev, je pourrai ensuite te confirmer cela :cat:
