### ISSUE TITLE
Lien vers la prévisualisation de la version courante depuis l'article

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#336]
Normalement le lien vers la prévisualisation de la version courante, depuis la page de l'article, est un lien du type :

`https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlArticle/[id-article]?preview=true`

Mais depuis le déploiement du 16 mars 2021 le lien est devenu :

`https://via.hypothes.is/https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/[id-version]?preview=true`

Il faut bien que le lien de la prévisualisation **de la version courante** soit composé avec l'_identifiant_, comme cela nous pouvons voir les annotations au fur et à mesure des différentes _versions_ de cet article. Je ne sais pas si cet usage est clair, je peux le détailler. Une option pourrait être d'ajouter un lien vers la prévisualisation de l'article (et non de la _version_ de l'article), mais nous avons une préférence pour l'option précédente (modifier le lien de la version courante).

Le lien est ici :

![stylo-preview](https://user-images.githubusercontent.com/6869488/111699610-bc007b80-880e-11eb-8e85-d17e3e143054.png)

Pour information le lien vers la prévisualisation est correct depuis la liste des articles.

**Comment by ggrossetie** [comment]
Intéressant, si je comprends bien ça ne fait pas de sens d'annoter une version ? Dans ce cas, est-ce qu'il ne faudrait pas afficher uniquement une prévisualisation (sans passer par `https://via.hypothes.is/`) quand on clique sur "Preview" et ajouter un bouton permettant de prévisualiser ET d'annoter en dehors de la liste des versions ?

On peut aussi supprimer uniquement la possibilité de pouvoir annoter des versions ? Dans ta capture d'écran cela se traduirait par le fait que le bouton "Preview" fasse uniquement une prévisualisation sur "Genesis", "proposition-initiale" et "texte-complet". Et le bouton "Preview" sur la version courante (i.e. "Autosave") fera une prévisualisation de l'article (et non de la dernière version) en passant par `via.hypothes.is` pour pouvoir annoter.

Est-ce que ce fonctionnement te convient ? Est-ce que tu veux ajouter un libellé explicite sur le bouton "Preview" pour faire la distinction ?  Est-ce qu'on ajoute un nouveau bouton "Annotate" quelque part ?

**Comment by marviro** [comment]
Il y a deux usages: annoter la version ou annoter l'article. Les deux doivent rester possibles. 

On annote un article quaqnd on veut suivre les modification - je fais un commentaire et je regarde ensuite s'il a été intégré. On annote une version quand on ne veut justement pas que le texte change. 

Ici on parle juste ergonomie: les usagers sont habitués à savoir que le bouton preview de la version en cours donne la preview de l'article.

Donc il faut garder l'annotation des versions
