### ISSUE TITLE
Un mot-clé vide ajoute une valeur `null` à `keywords.list_f`

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#339]
Et c'est interprété comme… un valeur `null`, et non une chaîne vide (`''`).

Quickfix dans f43dec3.

Le résultat c'est un export… qui ne fonctionne pas (aucun téléchargement proposé).

**Comment by ggrossetie** [comment]
Corrigé dans f43dec3 et inclus dans la release https://github.com/EcrituresNumeriques/stylo/releases/tag/v1.1.4

**Comment by thom4parisot** [comment]
Bah en fait je me demandais si la valuer "null" devait même figurer dans le "raw YAML". C'est étrange qu'un champ texte vide soit converti en "null".

**Comment by ggrossetie** [comment]
Effectivement, je réouvre pour qu'on puisse en discuter.
On pourrait peut être enlever la valeur dans 

https://github.com/EcrituresNumeriques/stylo/blob/f43dec374beb8888390aadfa43a45ca0406b7a66/front/gatsby/src/components/Write/metadata/yaml.js#L3

Ou déjà comprendre pourquoi et comment une chaîne vide se transforme en `null`
