### ISSUE TITLE
[Article] Le rendu de la page est gourmand

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#340]
Sur la page d'écriture, le changement d'une valeur est exponentiellement coûteux en temps/ressources machine utilisteur·ice à mesure que l'article grandit, contient des métadonnées et de la bibliographie.

Avec #290, ça démultipliera ce problème sur chaque collaborateur·ice synchrone.

cf. #325 

Plusieurs raisons à celà : 

- "l'état" du document est transféré à tous les composants ; dès qu'un bout du document change, tout est re-rendu
- les composants se re-rendent même si aucun de leur élément d'affichage est différent

Plusieurs pistes techniques : 

- [utiliser `React.memo()`](https://reactjs.org/docs/react-api.html#reactmemo) sur chaque composant (le rendu s'exécute seulement si une propriété change)
**Budget** : 💰 rapide à mettre en place
- se reposer sur le "store de données", émettre des événements, et re-rendre les composants souscrivant à des données modifiées
**Budget** : 💰💰 plus stratégique, plus long à mettre en œuvre

**Comment by ggrossetie** [comment]
Merci pour l'analyse 👍🏻

Je pense qu'on pourrait aussi envisager un travail ciblé sur la bibliographie. De monpoint de vue, afficher un grand nombre d'éléments dans le panneau latéral n'a pas beaucoup d'intérêt.
Peut être qu'on pourrait remplacer cette liste par une recherche de références bibliographiques ?

D'ailleurs, est ce qu'on fait toujours une validation de l'ensemble de la bibliographie quand on ouvre le panneau latéral ?

**Comment by marviro** [comment]
l'idéal serait de greffer la recherche bibliographique à l'éditeur de texte. Par ex, quand j'écris un `@` j'ai des suggestions en autocompletion. Mais on y réfléchira quand on sera arrivé à changer l'éditeur de texte.

**Comment by ggrossetie** [comment]
Effectivement, d'un point de vue experience utilisateur ça serait encore mieux 👍🏻

**Comment by thom4parisot** [comment]
Oui mais ça change rien au nœud : un changement de caractère dans le texte entraine le recalcul des 2 panneaux latéraux. Et inversement.

**Comment by thom4parisot** [comment]
C'est réactif sur un article de 114.331 mots / 939.799 caractères.

Y'a des micro lags mais rien qui m'empêche d'écrire.
