### ISSUE TITLE
Appel des métadonnées (preview et export) : modifier le comportement

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#342]
Suite de #341 

Si on appelle les métadonnées avec la commande `--metadata-file=` cela crée un nouveau problème : le paramètre des citations n'est pas pris en compte (All citations ou Only used), ce qui veut dire que quoi que fait l'utilisateur·trice, seules les références citées sont affichées en fin de document (dans la prévisualisation et les exports).
Cela est dû à la version (ancienne) de Pandoc que nous utilisons.

Nous ne pouvons pas mettre à jour la version de Pandoc pour les exports (ça va casser trop de choses), et nous referons l'export bientôt.

Une solution serait simplement d'inverser l'appel du YAML et du Markdown, ce qui corrigerait également #341 : il faut donc appeler d'abord le YAML puis le Markdown, cela résout nos problèmes et cela facilite grandement la mise à jour des exports (même comportement pour la preview et l'export).

Est-ce que vous seriez d'abord pour adopter ce fonctionnement @oncletom @Mogztter ?
À tester d'abord sur stylo-dev si on prend cette décision.

**Comment by thom4parisot** [comment]
Hm, je ne suis pas sûr de comprendre : sur une ancienne version de pandoc, le paramètre de citation est pris en compte seulement si on n’utilise pas l’argument « metadata file » ?

**Comment by ggrossetie** [comment]
Pareil, je ne comprends pas trop le pourquoi du comment 😅 
Est-ce que tu aurais le lien vers l'issue Pandoc ?

Pour info, voici la version qu'on utilise actuellement sur le service d'export : 

```console
$ pandoc --version
pandoc 2.6
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2, skylighting 0.7.5
Default user data directory: /root/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

Je crois que de votre côté [vous utilisez la version 2.4.1](https://framagit.org/stylo-editeur/process/-/blob/book/dockerfile#L9), c'est bien ça?

**Comment by thom4parisot** [comment]
Ouais ben, c'est exactement ça : "No bibliography items inserted when using `nocite: @*` in a metadata YAML file" cf. jgm/pandoc#6076

**Comment by antoinentl** [comment]
Je reviens sur ce problème, pour résoudre le problème de prise en compte du paramètre Bibliography > Display (only used ou all citations), il faut inverser l'appel du YAML et du Markdown : **il faut donc appeler d'abord le YAML puis le Markdown** dans le script de génération de la prévisualisation.

Pouvez-vous effectuer d'abord cette modification sur stylo-dev pour tester ? Merci !

**Comment by thom4parisot** [comment]
@antoinentl c'est fait, dis-nous ce que ça donne !

**Comment by antoinentl** [comment]
@oncletom Ça fonctionne sur stylo-dev, merci ! Dites-moi quand vous pourrez déployer en production.

**Comment by thom4parisot** [comment]
@antoinentl j'avais [préparé le brouillon de la release](https://github.com/EcrituresNumeriques/stylo/releases) : [déploiement en cours, et en ligne dans quelques minutes](https://github.com/EcrituresNumeriques/stylo/actions/runs/729908977).
