### ISSUE TITLE
Interprétation des exposants en Pandoc dans les résumés

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#343]
Jusqu'ici il était possible de mettre en forme les exposants dans les résumés avec le balisage suivant : `Au 18^e^ siècle`. À noter que cela fonctionne dans les exports.

**Comment by thom4parisot** [comment]
De quel(s) endroit(s) fais-tu référence ? (une capture d'écran m'aiderait à mieux cerner ce que tu vois, et où tu t'attends à autre chose)

**Comment by antoinentl** [comment]
Oups voici quelques précisions :

## Fonctionnement passé
Dans le champ résumé des métadonnées le balisage `^e^` permettait d'obtenir un exposant `ᵉ` dans la prévisualisation.

## Problème rencontré
Le balisage `^e^` n'est plus converti en `ᵉ`. Voir les deux captures ci-dessous :

![Capture d’écran de 2021-03-30 10-35-48](https://user-images.githubusercontent.com/6869488/113006947-ca6e6180-9143-11eb-82d5-f0b57b18c212.png)
![Capture d’écran de 2021-03-30 10-35-58](https://user-images.githubusercontent.com/6869488/113006965-ce01e880-9143-11eb-850f-23acaf679450.png)


## Comportement attendu
Transformation du balisage `^e^` en exposant `ᵉ` dans le champ résumé des métadonnées.

## Piste de résolution
La conversion est effectué pour l'export, est-ce que quelque chose pourrait différer pour la prévisualisation ?

**Comment by thom4parisot** [comment]
Et bien ce qui m'étonne c'est que le `_Titre_` d'après est lui bien converti en italique.

Et c'est le même module "export" qui gère la prévisualisation (avec `pandoc` derrière).

https://github.com/EcrituresNumeriques/stylo/blob/32b6a934de15039460779bbf1387ebfd2447fa8e/export/src/export.js#L62-L98

Là comme ça je dirais que c'est une limitation de Pandoc… qu'on peut contourner. Mais ça n'aurait jamais vraiment marché dans le passé…

Donc quand tu dis "À noter que cela fonctionne dans les exports" : de quels exports parles-tu ?

**Comment by lakonis** [comment]
Résolu : 
![image](https://github.com/EcrituresNumeriques/stylo/assets/9479788/2b772f00-86ee-4187-8972-0e39032025aa)
