### ISSUE TITLE
Problème de connexion sur Safari 11.1.2 ou 13.1.2

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#344]
Actuellement la page stylo.huma-num.fr ne s'affiche pas sur le navigateur Safari (versions testées : 11.1.2 et 13.1.2) :

- la page est blanche
- la console JavaScript indique :
```
SyntaxError: Unexpected token '?'
    promiseReactionJob
```

**Comment by thom4parisot** [comment]
C'est #303 qui en est probablement la cause.

@antoinentl, tu peux me dire si https://deploy-preview-345--stylo-dev.netlify.app/ affiche l'écran de connexion, et résoud le problème ?

**Comment by thom4parisot** [comment]
Sur Safari 13.1.2/Catalina, je ne rencontre pas le problème 🤷 

<img width="1440" alt="Screenshot 2021-04-01 at 02 43 27" src="https://user-images.githubusercontent.com/138627/113227956-1d572e80-9294-11eb-8d4c-abcc99f11f7a.png">

Sur la version 12.1 oui, y'a le souci, et je confirme que le fix proposé résout ça : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/113228076-5f807000-9294-11eb-9973-ba31cc89118e.png">

**Comment by thom4parisot** [comment]
Ceci dit je ne m'explique pas pourquoi le problème persiste sur stylo-dev.

Je viens de tester sur une précédente preview, sans le fix… et ça marche (Safari 11.1.2) : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/113231051-a83b2780-929a-11eb-952d-74f7f8235d21.png">

Y'a une différence que je ne m'explique pas entre l'environnement de preview, et stylo-dev/stylo.

**Comment by thom4parisot** [comment]
Verdict : c'est le build "production" qui déconne, et notamment la [built-in optimization](https://www.snowpack.dev/guides/optimize-and-bundle#option-1%3A-built-in-optimizations) : 

- elle optimise peut-être pour une version d'Ecmascript pas supportée par Safari 
- quand je spécifie comme cible `safari11`, l'optimiseur plante parce qu'il ne supporte pas 2-3 fonctionnalités qu'on utilise

**Comment by ggrossetie** [comment]
> quand je spécifie comme cible safari11, l'optimiseur plante parce qu'il ne supporte pas 2-3 fonctionnalités qu'on utilise

C'est des issues qui existent déjà sur GitHub: https://github.com/evanw/esbuild?
Safari 11 est cité en exemple dans la [documentation](https://esbuild.github.io/getting-started/#bundling-for-the-browser) donc je pense que ça vaut le coup de remonter ce qui ne fonctionne pas pour que cela soit corrigé.

Et c'est quelle option qu'il faut désactiver pour ne plus avoir de problème ? Je vois dans la documentation de Snowpack qu'on peut activer/désactiver:

- bundle
- minify
- treeshake
- splitting
- ...

**Comment by thom4parisot** [comment]
@antoinentl ça a l'air OK sur stylo-dev : 

![image](https://user-images.githubusercontent.com/138627/113975555-fb375080-983f-11eb-8c41-8c0462584404.png)
