### ISSUE TITLE
La compression n'est pas activée sur les deux environnements de déploiement

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#346]
Sur stylo/stylo-dev :

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/138627/113230531-75446400-9299-11eb-8f43-032c9e9e8a2d.png">

Sur les preview Netlify (avec source map) : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/113230565-8f7e4200-9299-11eb-9073-ad120cde4717.png">

**Comment by ggrossetie** [comment]
Effectivement, Netlify utilise une compression brotli compression alors qu'on a rien configuré sur NGINX donc pas de compression.

Brotli n'est pas inclus par défaut dans l'image Docker, on peut éventuellement l'ajouter (https://github.com/google/ngx_brotli) mais j'ai peur que ça ne soit pas si simple que ça.
Par contre, je pense qu'on peut activer une compression gzip assez facilement: https://docs.nginx.com/nginx/admin-guide/web-server/compression/

**Comment by ggrossetie** [comment]
Lien pour ajouter des modules à NGINX: https://github.com/nginxinc/docker-nginx/tree/master/modules#readme

**Comment by ggrossetie** [comment]
Et ça fonctionne ! 

![image](https://user-images.githubusercontent.com/333276/113983009-bca69380-9849-11eb-8c69-fdb3108734ec.png)

Bien vu @oncletom 😉

**Comment by thom4parisot** [comment]
J'adore, c'est sensiblement plus rapide.
