### ISSUE TITLE
Affichage des intitulés/champs des métadonnées : décaler vers la gauche

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#349]
Actuellement les champs sont _collés_ à droite alors qu'il y a de la _place_ sur le côté gauche (voir la flèche rouge ci-dessous qui indique la place disponible) :

![stylo-place](https://user-images.githubusercontent.com/6869488/113345543-9a1ff200-9300-11eb-8df5-c19b894a92f4.png)

Si vous avez besoin de compléments pour comprendre ce problème mal expliqué dites moi.

**Comment by thom4parisot** [comment]
Aligner à gauche ? Ou ajouter de l'espacement entre le libellé et le champ ?

**Comment by antoinentl** [comment]
Désolé je galère à exprimer ça clairement : réduire la marge entre le bord et les intitulés, exemple avec une marge plus réduite :

![Capture d’écran de 2021-04-01 16-44-42](https://user-images.githubusercontent.com/6869488/113351955-9fce0580-9309-11eb-86a7-5da580374747.png)

**Comment by thom4parisot** [comment]
Du coup c'est plié dans c2bb056abed555883af96fb8dbcfbdc83818636a / #353, et mis en ligne avec la [v1.1.7](https://github.com/EcrituresNumeriques/stylo/releases/tag/v1.1.7).
