### ISSUE TITLE
Serait-il possible d'uniformiser les éléments graphiques des deux volets ? (Fonds gris et bordures)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#350]
Je pense que vous avez prévu de travailler dessus, mais la question que nous nous posons est l'uniformisation des éléments mis en évidence dans les volets latéraux, typiquement les blocs avec fond gris pour le volet gauche et les blocs avec bordure noire pour le volet droit :

![Capture d’écran de 2021-04-01 16-08-21](https://user-images.githubusercontent.com/6869488/113348407-8a0a1180-9304-11eb-99c3-36762a6fd07c.png)

puis :

![Capture d’écran de 2021-04-01 16-08-30](https://user-images.githubusercontent.com/6869488/113348404-89717b00-9304-11eb-945f-7e698364e100.png)

L'objectif serait d'adopter une grammaire graphique commune entre les deux volets.

**Comment by ggrossetie** [comment]
Techniquement ce ne sont pas les mêmes éléments graphique. Dans un cas ce sont des "accordéons" et dans l'autre ce sont des légendes/titres de section dans un formulaire.

Par contre je te rejoins, il serait bien d'établir une convention graphique car je crois qu'on n'utilise pas toujours les mêmes styles.

Une autre piste serait d'utiliser des accordéons (plutôt que des titres de section) sur le formulaire dans le panneau de droite. De cette façon le comportement et le style seront identiques entre les deux panneaux.

Mais je m'en remets à @maiwann pour savoir ce qu'il est préférable de faire 🙇🏻‍♂️

**Comment by ggrossetie** [comment]
Fait et déployé en production
