### ISSUE TITLE
Bug sur le yamlEditor dans Stylo

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#36]
je cite une éditrice : 
>  j'ai un petit problème avec l'éditeur de yaml sur stylo. Quand je clique sur « metadata », dans les articles que j'ai créés, j'atterris sur une page blanche au lieu de voir l'éditeur apparaître. Il s'agit de SP1231, et j'ai le même problème avec 1338. Margot aussi a le même problème avec ses articles.

puis plus tard : 
>  L'article 1231 est sur Stylo, et son yaml est rempli, sauf que chaque changement des mots clés contrôlés changeait également les mots clés de l'autre article sur lequel je travaillais (1338). Les mots clés contrôlés ne sont donc pas les bons.

**Comment by lakonis** [comment]
ps: tim a mis à jour les données du sphub. peut-être vérifier que l'api sphub sert bien ce qu'on attend ?

**Comment by PookMook** [comment]
devrait être reglé pour stylo.ecrituresnumeriques.ca !

**Comment by PookMook** [comment]
pour la "page blanche", quel navigateur + si possible message de la console javascript?
