### ISSUE TITLE
Demander à Huma-Num, comment faire pour que l'accès à Stylo débloque automatiquement l'accès à Nakala

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#363]
Leur envoyer un email, et leur poser la question.

Ça veut aussi dire qu'on gagne un accès en écriture à Nakala.

Stéphane Pouyllau pourrait nous en dire plus.

**Comment by ggrossetie** [comment]
Email envoyé aujourd'hui à Stéphane

**Comment by ggrossetie** [comment]
Pas eu de retour encore, il faudrait que je relance Stéphane 😬

**Comment by antoinentl** [comment]
Pour l'ìnstant Huma-Num ne peut pas ouvrir automatiquement le service, il faut continuer l'expérimentation avant de pouvoir revoir cette décision.
