### ISSUE TITLE
Pas possible de se connecter 

### ISSUE THREAD

**Issue by JulieTD** [EcrituresNumeriques/stylo#37]
En tentant de me connecter à la plateforme, le système renvoie le message "Login status : false" sans dire si une information était erronée (user name ou password) ni permettre une option pour réinitialiser le mot de passe.

En tentant de contourner ce message d'erreur par la création d'un nouveau profil avec les mêmes informations de connection, je reçois le même message d'erreur sans plus d'explications.

Est-ce que c'est une issue connue? Est-ce que des nouveaux utilisateurs peuvent se créer un profil? (Je voulais justement envoyer le lien du projet à un testeur enthousiaste.)

**Comment by PookMook** [comment]
Est-ce que tu ne recois pas ce genre de message quand tu essaies de te connecter ou de créer un nouveau compte?
![screenshot from 2018-08-20 15-35-55](https://user-images.githubusercontent.com/14223903/44362403-e63f0080-a48e-11e8-91a3-302367eb3c63.png)
![screenshot from 2018-08-20 15-36-32](https://user-images.githubusercontent.com/14223903/44362404-e63f0080-a48e-11e8-88d4-1c6f656489ab.png)

Le reset password est pas très loin dans la liste des choses à faire, mais pas encore tout prês

**Comment by JulieTD** [comment]
Ça me donnaît plutôt ceci: 
<img width="182" alt="capture d ecran 2018-08-20 a 18 32 14" src="https://user-images.githubusercontent.com/14908747/44370281-899c0f80-a4a7-11e8-81ea-1931fdeb8d81.png">

Mais en réessayant ajd, la connexion est possible :)

**Comment by PookMook** [comment]
Parfait, certainement la connexion à la base de donnée qui était coupée
