### ISSUE TITLE
Impossible de connecter Zotero à Stylo

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#370]
Problème détecté aujourd'hui :

Lorsque l'on tente de connecter Stylo et Zotero (Manage Bibliography > Connect my account), nous accédons bien à l'interface de Zotero nous demandant de valider la "New Private Key", mais lorsque l'on clique sur "Accept Defaults" Stylo renvoie cette page avec le message "Internal Server Error" : https://stylo.huma-num.fr/authorization-code/zotero/callback?oauth_token=letoken&oauth_verifier=leverifier (j'ai masqué les identifiants dans cette URL).

**Comment by thom4parisot** [comment]
Je confirme le problème.

**Comment by ggrossetie** [comment]
Je viens de faire le test et cela fonctionne sur https://stylo-dev.huma-num.fr.
Cela dit, j'arrive bien à reproduire l'erreur sur la production.
Voici l'erreur qu'on obtient sur le serveur :

```
Error: Failed to find request token in session
    at SessionStore.get (/usr/src/app/node_modules/passport-oauth1/lib/requesttoken/session.js:13:44)
    at OAuthStrategy.authenticate (/usr/src/app/node_modules/passport-oauth1/lib/strategy.js:214:33)
    at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
    at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/app.js:152:10
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at SessionStrategy.strategy.pass (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:343:9)
```

**Comment by thom4parisot** [comment]
Ah, on aurait à nouveau ces histoires de cookies de session en prod ? (qui ne persistent pas entre deux appels)

**Comment by ggrossetie** [comment]
Cela y ressemble mais en comparant rapidement les configurations NGINX je n'ai pas vu de différence...
En plus, je crois qu'il n'y a que très peu de différences de code entre l'environnement de production et de développement 🤔

**Comment by ggrossetie** [comment]
Une différence est que sur l'environnement de développement on autorise plusieurs origines:

- Netlify deploy previews (i.e., https://deploy-preview-xyz--stylo-dev.netlify.app)
- https://stylo-dev.huma-num.fr

Par conséquent, on utilise la valeur `lax` pour l'attribut `SameSite`:

```js
const sameSiteCookies = allowedOrigins.length === 1 ? 'strict' : secureCookie ? 'none' : 'lax'
if (sameSiteCookies === 'none') {
  console.warn('Cookies are configured with `sameSite: none`.')
}
```

Je suis à peu près sûr que cela fonctionnerait en production si on utilisait la valeur `lax`.
Par contre, aucune idée de ce qu'il faudrait faire pour que cela fonctionne avec la valeur `strict`.

**Comment by thom4parisot** [comment]
Avec le recul, ce bug de cookies concernait l'authentification HumanID, pas Zotero.

Si la session persiste entre 2 requêtes, l'amorçage de la connexion OAuth à Zotero doit reboucler avec le retour de jeton. 🤔

**Comment by ggrossetie** [comment]
Pas faux... est-ce que tu te souviens qui à enregistrer l'application ? Je viens de remarquer qu'il y a une redirection http -> https.

On devrait surement utiliser https: 

https://github.com/EcrituresNumeriques/stylo/blob/747664e2cb8671550e4865babcfae2871b2ff157/infrastructure/inventories/prod#L28

EDIT: bon ça change rien mais ça évite un "hop" 😄

**Comment by ggrossetie** [comment]
Je confirme le changement en `lax` corrige le problème, je viens de faire le changement en production. 

@oncletom @antoinentl Est-ce que vous pouvez confirmer ? (À noter que j'ai du me déconnecter/reconnecter et vider mon cache).

**Comment by thom4parisot** [comment]
Oui ça fonctionne 🙌  me déconnecter et me reconnecter ont suffi 👍 

Par contre ça me fait dire que je n'ai pas compris toutes les subtilités de ce réglage :/

**Comment by thom4parisot** [comment]
Ok, y’a plus de détails ici https://web.dev/samesite-cookies-explained/#explicitly-state-cookie-usage-with-the-samesite-attribute sur cette option.


En Strict (valeur précédent le changement), si un clic ouvre une nouvelle fenêtre (notre popup de connexion), le cookie n’est pas envoyé… et donc on a une session différente avant et après l’autorisation Zotero).

La valeur Lax envoie le cookie de session dans ce cas de figure.

Je crois que j’ai compris maintenant :+1:

**Comment by ggrossetie** [comment]
> En Strict (valeur précédent le changement), si un clic ouvre une nouvelle fenêtre (notre popup de connexion), le cookie n’est pas envoyé… et donc on a une session différente avant et après l’autorisation Zotero).

J'ai l'impression que c'est surtout une question de domaine et de redirection non ?

On ouvre une nouvelle fenêtre sur le même domaine puisque l'adresse est: `stylo.huma-num.fr/login/zotero` mais le serveur renvoie une 302 FOUND sur `www.zotero.org/oauth/authorize`:


<img src="https://user-images.githubusercontent.com/333276/116778581-05c9bc00-aa73-11eb-9998-f34453b3be05.png" alt="cookie-strict" width="600">

Peut être qu'à partir de ce moment là le navigateur décide de ne plus envoyer les cookies.

Pour conserver la valeur strict je pense qu'on pourrait faire un appel à l'API pour obtenir l'adresse complète `www.zotero.org/oauth/authorize` et ouvrir la popup avec cette valeur (afin d'éviter le 302).

Apparemment il serait aussi possible de retourner une page HTML pour faire le redirect: https://stackoverflow.com/a/64216367/3600979


```html
<html>
<head>
<meta http-equiv="refresh" content="0;URL='https://www.zotero.org/oauth/authorize/...'"/>
</head>
<body><p>Moved to <a href="https://www.zotero.org/oauth/authorize/...">https://www.zotero.org/oauth/authorize/...</a>.</p></body>
</html>
```


----


Mon autre hypothèse c'est que le domaine Zotero va renvoyer une 302 FOUND (callback) et c'est peut être ça qui est considéré comme "unsafe":

<img src="https://user-images.githubusercontent.com/333276/116778740-175f9380-aa74-11eb-9b48-2631d3c452dc.png" alt="redirect-unsafe" width="600">

Mais j'y crois moins car certes c'est un autre domaine qui demande le redirect mais il demande un redirect sur le domaine d'origine.

**Comment by oncletom** [comment]
Je comprends, mais j'en suis pas aussi certain :

> However when the reader follows the link through to cat.html on your blog, that request will include the cookie.

Ce qui est le cas quand on ouvre la popup qui redirige vers Zotero.

> This makes Lax a good choice for cookies affecting the display of the site with Strict being useful for cookies related to actions your user is taking.

C'est exactement le fix que tu as testé.

**Comment by thom4parisot** [comment]
Je comprends, mais j'en suis pas aussi certain :

> However when following a link into your site, say from another site or via an email from a friend, **on that initial request the cookie will not be sent**. (…)

Ce qui est le cas quand on ouvre la popup qui redirige vers Zotero. Les sessions matchent pas avant/après l'envoi vers Zotero. C'est l'erreur qui est renvoyé (le token de retour ne matche pas le token pré-autorisation stocké en session, qui a un autre identifiant — même comportement qu'avec le problème HumanID qu'on avait).

> That's where SameSite=Lax comes in **by allowing the cookie to be sent with these top-level navigations**.

C'est exactement le fix que tu as testé.

---

`Strict` est strict, y compris avec le "first-party domain". `Lax` autorise des actions avec ce même domaine (`stylo(-dev).huma-num.fr`). Tandis que `None` autorise aussi le partage du cookie avec des domaines tiers (c'est pas notre cas, mais ça le serait si Stylo était embeddé en `<iframe>`, ailleurs).

**Comment by thom4parisot** [comment]
@antoinentl si tu te délogues/relogues ça devrait rouler.

**Comment by antoinentl** [comment]
Parfait merci pour la réactivité :ok_hand:
