### ISSUE TITLE
Ne pas ouvrir le panneau latéral gauche à l'ouverture d'un article

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#383]
Je trouve que ce comportement est assez irritant surtout quand on navigue d'un article à un autre et qu'on est plus ou moins obligé de le fermer pour voir le texte de l'article :rage3: 

@antoinentl @maiwann Est-ce que vous avez un avis sur la question ?

**Comment by marviro** [comment]
Mon avis: Quand l'écran est assez grand pour que le panel gauche n'empiète pas sur le texte, mieux vaut l'avoir ouvert. Sinon, peut-être fermé. Ou alors autre solution graphique (plus petit par ex, il me semble que les css devraient être optimisés pour résolutions intermédiaires - je pense qu'il y a une issue sur ça?).

**Comment by antoinentl** [comment]
Oui @marviro c'est la #69 que je viens de re-compléter :+1:
