### ISSUE TITLE
Abandonner l'url `via.hypothes.is/` pour la preview

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#384]
Je suggère plutôt d'ajouter ce code au template de preview pour lancer hypothes.is ([voir documentation](https://web.hypothes.is/for-publishers/#embedding)):

```html
<script src="https://hypothes.is/embed.js" async></script>
``` 
Plusieurs [options de configuration](https://h.readthedocs.io/projects/client/en/latest/publishers/config/#) sont possibles, avec des choses potentiellement intéressantes pour Stylo.

A titre d'exemple, l'ouverture de la sidebar par défaut:
```html
<script type="application/json" class="js-hypothesis-config">
  {
    "openSidebar": true
  }
</script>
<script src="https://hypothes.is/embed.js" async></script>
```

**Comment by lakonis** [comment]
Question: comment l'implémenter ?

- au niveau du template Pandoc &rarr; un travail pour @lakonis / @antoinentl / @marviro 
- au moment de servir la page &rarr; un travail pour @oncletom / @Mogztter

**Comment by thom4parisot** [comment]
C'est un travail déjà en cours dans #381.

**Comment by thom4parisot** [comment]
Et c'est en ligne 👍
