### ISSUE TITLE
Import Zotero : limitations constatées

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#385]
Je travaille actuellement sur un article dont la bibliographie Zotero (collection dans un groupe privé) contient 44 items, mais seuls 21 références sont importées.

## Problème constaté
Lorsque j'importe la bibliographie, l'interface m'indique que la collection Zotero contient 44 références, mais une fois l'import effectué je ne constate que 21 références (dans le panneau latéral et dans le BibTeX).

## Comportement attendu
Il faut que toutes les références de cette collection puisse être importée, sans exception.

## Problèmes connexes
Je me rends également compte que je ne vois pas tous mes groupes Zotero via Stylo (20/28), y aurait-il une limitation (récemment) imposée par Zotero ?

Par ailleurs lorsque j'importe une nouvelle collection, l'URL indiquée dans "Import by URL" reste la même quelque soit le changement effectué (ce qui est un peu confusant).

**Comment by ggrossetie** [comment]
@antoinentl est-ce que tu peux nous partager cette collection privée pour qu'on puisse reproduire l'anomalie ? ou alors est-ce que c'est possible de la rendre publique temporairement ?

> Je me rends également compte que je ne vois pas tous mes groupes Zotero via Stylo (20/28), y aurait-il une limitation (récemment) imposée par Zotero ?

Bonne question, là encore difficile à dire si on n'arrive pas à reproduire. Est-ce qu'il y a une configuration particulière sur les 8 collections qui ne remontent pas ? Peut être aussi qu'on ne remonte que la première page (20 premiers éléments). Je vais regarder... 🔍 

> Par ailleurs lorsque j'importe une nouvelle collection, l'URL indiquée dans "Import by URL" reste la même quelque soit le changement effectué (ce qui est un peu confusant).

Pas sûr de comprendre, voilà ce que j'obtiens : 

![question](https://user-images.githubusercontent.com/333276/118975130-f48a1600-b973-11eb-8761-5ec8d295c1b7.gif)

Est-ce que tu peux faire un screencast de ce que tu vois ?

Pour la prochaine fois, est-ce que tu pourra s'il te plait créer une issue par anomalie constatée sinon ça devient rapidement dur à suivre. Là par exemple il y a 3 anomalies distinctes (même si elles sont toutes plus ou moins liées à Zotero) : 

- certaines références d'une collection privée ne remontent pas (21 références sur 44)
- les groupes Zotero ne sont pas tous récupérés (seulement 20 sur 28)
- L'URL indiquée dans "Import by URL" reste la même

**Comment by ggrossetie** [comment]
@antoinentl est-ce que tu pourrais s'il te plait nous donner plus d'informations pour qu'on puisse reproduire et corriger le ou les anomalies ?

**Comment by antoinentl** [comment]
Pour information je vais créer une autre issue concernant les groupes manquants dans la liste.

**Comment by antoinentl** [comment]
@Mogztter Est-ce que tu arrives à importer les références du groupe que je viens de partager avec toi ? Pour ce groupe je n'arrive tout simplement pas à importer les références.

https://user-images.githubusercontent.com/6869488/123079885-5661f380-d3ea-11eb-99cc-6df3b4cec950.mp4

**Comment by antoinentl** [comment]
Pour information je parviens à importer une autre collection (collection = dossier) plus petite de ce groupe, de 11 items, donc la piste d'un blocage au bout de x items semble être la bonne.

**Comment by ggrossetie** [comment]
Sur la deuxième requête la `key` n'est pas envoyé et on a une 403 😬 

**Première requête**
```
https://api.zotero.org/groups/4330148/collections/5ZRCNQUD/items?format=bibtex&key=...
```

**Seconde requête où le paramètre `key` est absent**
```
https://api.zotero.org/groups/4330148/collections/5ZRCNQUD/items?format=bibtex&start=25 
```

Et on s'arrête à la première erreur donc on ne va pas plus loin.
Je regarde pour corriger.

**Comment by ggrossetie** [comment]
@antoinentl Je viens de pousser un correctif sur https://stylo-dev.huma-num.fr/ directement. Il faut que tu vides ton cache et normalement cela doit fonctionner : 

![load-from-group](https://user-images.githubusercontent.com/333276/123112713-39efa680-d43e-11eb-8af2-55cb8fb48462.gif)

**Comment by thom4parisot** [comment]
🔗 72c9c48104e58ed938453d626088b6d2a377cec6

Woah, c'était juste pas consistant de leur côté :-/

**Comment by thom4parisot** [comment]
Et aussi quand je lis 

> Je me rends également compte que je ne vois pas tous mes groupes Zotero via Stylo (20/28), y aurait-il une limitation (récemment) imposée par Zotero ?

Ça sent la présence d'une pagination qu'on ne suit pas dans notre appel à la liste des collections.

**Comment by ggrossetie** [comment]
> Ça sent la présence d'une pagination qu'on ne suit pas dans notre appel à la liste des collections.

En faite, c'est Zotero qui ne retourne pas de `Link` dans l'entête de la réponse quand on a une 403. On en peut malheureusement pas faire grand chose...

> Woah, c'était juste pas consistant de leur côté :-/

Oui le `Link` retourné ne contient pas le paramètre `key`. Peut être pour des raisons de sécurité mais c'est un peu étrange car c'est l'utilisateur de l'API qui positionne ce paramètre 🤔 

Bref, maintenant je positionne systématiquement le paramètre `key` pour être tranquille 😉

**Comment by antoinentl** [comment]
@Mogztter Plus de problème sur `devstylo` :ok_hand: J'ai même fait le test avec une collection de 600 références, ça passe avec une petite minute de chargement ( :warning: test absolument pas réaliste :grimacing: ).

**Comment by ggrossetie** [comment]
@antoinentl Super, merci pour la confirmation, je ferme. Le correctif sera déployé sur la prochaine release en production.
