### ISSUE TITLE
Temp réel : contenus doublés à chaque ouverture d'un article

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#386]
:warning: Attention suite à la PR 380 dès que l'on rentre puis on sort d'un article le contenu est doublé (même si on est seulement en lecture), pour tous les articles et utilisateurs qui testent ce matin. C'est un point très problématique ! Il faut retirer cette fonctionnalité de la production !

**Comment by ggrossetie** [comment]
@antoinentl Est-ce que tu peux préciser la manipulation ainsi que le navigateur utilisé ?

J'ai essayé plusieurs choses mais je ne reproduis pas l'anomalie : 

![no-duplicate](https://user-images.githubusercontent.com/333276/118994417-99adea00-b986-11eb-896f-9557311f13a4.gif)

🤔

**Comment by antoinentl** [comment]
On est passés sur 3 ordinateurs avec Firefox à chaque fois.

**Comment by ggrossetie** [comment]
Effectivement avec Firefox je reproduis le soucis même quand je suis seul 😱

**Comment by antoinentl** [comment]
Ok super, on a eu la même réaction :cold_face:

**Comment by ggrossetie** [comment]
Le déploiement en production est en cours: https://github.com/EcrituresNumeriques/stylo/actions/runs/860757738

**Comment by antoinentl** [comment]
:pray: Merci @Mogztter le déploiement semble fait, on teste la production.

**Comment by antoinentl** [comment]
Nous avons toujours l'indication "Online Writers:" même si quelqu'un est tout seul sur l'article, et toujours une duplication à chaque nouvelle ouverture. Est-ce qu'il faut forcer le rafraîchissement/le cache ?

**Comment by ggrossetie** [comment]
Oui il faut vider le cache, j'ai du ouvrir en navigation privée pour avoir la dernière version.

**Comment by antoinentl** [comment]
Ok merci ! Une autre idée que de vider le cache pour que les utilisateurs et utilisatrices voient la modification ?… (Je demande au cas où)

**Comment by thom4parisot** [comment]
C'est pas normal d'avoir à raffraichir le cache, c'est à nous de rendre cette action transparente.

**Comment by ggrossetie** [comment]
J'aurais dis la même chose... à noter que sur stylo-dev je n'ai pas eu à le faire mais j'ai l'impression que certains "identifiants" de chunks sont identiques: `chunk.HXALB4WR.js`... 🤔

**Comment by ggrossetie** [comment]
Je pense avoir compris la cause de ce dysfonctionnement.

Yjs utilise une base de données (LevelDB) afin d'enregistrer l'état d'un document. Quand un utilisateur ouvre sur un article, Yjs va renvoyer le delta entre l'état local et l'état "distant" du document (afin de faire converger tout le monde vers le même état).

Dans ce contexte, il n'y a plus vraiment d'état initial seul l'état actuel "de référence" est important et cet état est enregistré dans LevelDB.

Le contenu était dupliqué car on faisait : 

```js
const yText = doc.getText('codemirror')
yText.delete(0, yText.length)
yText.insert(0, initialText)
```

Le problème avec ce code (en plus de ce que j'ai décris au dessus) et que si l'état actuel n'a pas été synchronisé, on ne va rien supprimer car `yText.length` vaut 0 puis on va ajouter le texte "initial".
Autrement dit, à partir du moment où l'état existe dans LevelDB, le code ci-dessus va dupliquer le contenu de l'article à chaque fois que le client charge le document.

Cela peut fonctionner si l'état est synchronisé avant l'appel à `yText.delete(0, yText.length)`. Cependant c'est assez dangereux car cela va réinitialiser l'état et potentiellement perdre des changements.

Le créateur de Yjs recommande la chose suivante : 

> You can set the initial state. But you can do it only once.
If you set the initial state on the client-side several times, the clients won’t be able to synchronize changes.
If you want to set the initial state when the shared document is created initially, I recommend doing that in the y-websocket-server.

https://discuss.yjs.dev/t/prevent-hydration-on-page-reload/338/2

Et une discussion intéressante avec un exemple de code afin de charger l'état initial à partir d'une autre base de données : https://discuss.yjs.dev/t/how-to-fetch-init-data-in-server-side/158/6

Cela pourrait nous être utile afin de charger l'état initial à partir de MongoDB quand le document n'existe pas dans LevelDB.

À noter qu'on peut continuer d'enregistrer les documents dans MongoDB mais que l'éditeur utilisera LevelDB afin de récupérer l'état actuel et les changements lors de l'édition.

**Comment by ggrossetie** [comment]
Petite aparté, il existe un connecteur afin d'enregistrer l'état Yjs du document dans MongoDB mais ce projet n'est pas officiellement supporté par l'équipe Yjs: https://github.com/fadiquader/y-mongodb
