### ISSUE TITLE
Temp réel : désactivé l'affichage "Online Writers"

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#387]
Avec #380 la fonctionnalité d'édition en temps réel pose un problème : l'affichage "Online Writers" est présent même si on est seul sur un article. En soit rien de dramatique mais l'interface est tout de même modifiée (c'est perturbant) :

![Capture d’écran de 2021-05-20 11-11-24](https://user-images.githubusercontent.com/6869488/119004118-4626a680-b95c-11eb-8f4e-443a4b0a7caa.png)

Il faudrait au choix :

- revenir en arrière (ce qui semble le plus rapide)
- ne pas afficher cette interface si une personne est seule sur un article (peut-être plus long, et cela nécessiterait probablement un test sur dev avant de déployer en production)

**Comment by antoinentl** [comment]
Pour information je confirme que l'affichage est désactivé en production :+1:

**Comment by ggrossetie** [comment]
En lien avec https://github.com/EcrituresNumeriques/stylo/issues/392. Il faut décider de l'affichage en fonction des différents états.

**Comment by ggrossetie** [comment]
J'ai copié/collé ton commentaire dans #392 pour la solution "long terme". Je cloture ce bug car on a fait un retour arrière en production.
