### ISSUE TITLE
Il est nécessaire de vider son cache pour obtenir la dernière version de l'application

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#388]
Problème constaté lors du déploiement de la version 1.3.1 en production. Les utilisateurs ont du faire vider leur cache afin de récupérer la dernière version de l'application (sur Firefox).

Vérifier le bundle produit par Snowpack en mode production. Il faudra potentiellement utiliser Webpack pour produire le bundle de production. Pas l'option la plus rapide mais peut être la plus mature : https://www.snowpack.dev/guides/optimize-and-bundle

**Comment by ggrossetie** [comment]
Je viens de voir que sur https://stylo.huma-num.fr/ on utilise pas le mode "production":

![image](https://user-images.githubusercontent.com/333276/123047974-30464e80-d3fe-11eb-82aa-a646d967ff36.png)

@oncletom J'ai vu que tu as fais quelques changements sur `snowpack.config.cjs`, est-ce que cela correspond au résultat attendu ?

**Comment by ggrossetie** [comment]
Je pense que c'est lié à https://github.com/EcrituresNumeriques/stylo/commit/388471e1696557ffb33659386a82abfb80f1b83f#diff-d479c9427fb7647ea49bf198155c2c44a0958786a822f8e54a5291f1ec703365

On a passé `bundle` à `false`.

**Comment by thom4parisot** [comment]
Oui c'est ça, j'ai fait ça pour 2 raisons : 

- on est en mode http/2 donc le nombre de fichiers n'est pas trop un problème
- en passant à `true`, on perd des éléments de présentation — j'ai pas encore compris si une optimisation supprime du code, ou s'il y a une utilisation erronée des modules

**Comment by thom4parisot** [comment]
Ah oui et peut-être que ce bug est résolu avec la dernière version de Snowpack… qui sait.
