### ISSUE TITLE
Instabilité de l'application : temps de chargement des articles très long

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#390]
Depuis hier suite aux tests du déploiement du temps réel #380, et malgré les correctifs appliqués #386, il y a une instabilité dans l'application.

Le chargement des pages est deux fois plus long, l'accès à des versions de l'article prend un temps de chargement (ce qui n'était pas le cas avant).

**Comment by ggrossetie** [comment]
Il me semble que c'est un doublon de https://github.com/EcrituresNumeriques/stylo/issues/389
