### ISSUE TITLE
Permettre de plier/déplier des sections dans l'éditeur

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#393]
Je viens de découvrir que CodeMirror peut faire du "folding" sur un texte Markdown :

![code-folding](https://user-images.githubusercontent.com/333276/119256402-df55f700-bbc0-11eb-9086-035b4bcfd453.gif)

Est-ce que vous souhaitez activer cette fonctionnalité ?

**Comment by thom4parisot** [comment]
(Et du diff)

**Comment by antoinentl** [comment]
Bonne découverte, nous (Marcello, Margot et moi), ne savons pas si c'est une bonne idée de l'utiliser (pour l'utiliser il faut comprendre le système des numéros de ligne, un peu peur que cela crée de la confusion). Je peux peut-être passer le relais à @maiwann ?
