### ISSUE TITLE
La prévisualisation via Hypothesis modifie les liens de la table des matières (ouvre un nouvel onglet au lieu de naviguer vers l'ancre)

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#394]
Dans la preview d'un article, lorsqu'on clique sur un titre (n'importe quel niveau), un nouvel onglet s'ouvre. 

https://user-images.githubusercontent.com/40469215/119518956-01798180-bd47-11eb-94d4-b2fdfeaccbff.mp4

Il serait plus commode que l'on reste sur la même page et qu'on se déplace seulement au niveau de l'article voulu.

**Comment by thom4parisot** [comment]
Tu peux essayer sur https://deploy-preview-381--stylo-dev.netlify.app ?

Cette version : 

- intègre les annotations à Stylo (on reste dans la même interface)
- rend scrollable la table des matières de la preview

(et on ne passe plus par `via.hypothes.is`)

PS : top les vidéos, ça aide beaucoup :)

**Comment by ggrossetie** [comment]
Cela ressemble à une anomalie côté https://via.hypothes.is/ c'est bien ça ?
Je crois qu'on ne peut pas y faire grand chose à part intégré Hypothesis directement dans Stylo (i.e., qu'on ne passe plus par `via.hypothes.is` comme suggéré par Thomas).

**Comment by antoinentl** [comment]
Je confirme que c'est un bug lié à Hypothesis, #381 pourra le régler.
