### ISSUE TITLE
Récupération de l'ensemble des résultats via l'API Zotero

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#41]
sur l'article https://stylo.ecrituresnumeriques.ca/write/5bbf310b0e34ef0011467e9f/5bc4fccf9053e00017d4b17e
Il semblerait qu'il réfuse d'importer une référence (Meillassoux). Il l'avait importée, mais maintenant il ne la voit plus (je l'ai rajoutée à la main pour éviter une erreur de visualisation). Est-ce qu'il limite le nombre de références? Ou l'Api ne répond plus?

**Comment by marviro** [comment]
Je remarque que, à chaque fois que je rajoute un item, il m'en efface un autre. C'est comme s'il était limité à un nombre défini d'items

**Comment by marviro** [comment]
Voilà... avec plusieurs essais: il importe jamais toute la biblio.

Testé sur le groupe 322999 (248 item, il en importe une vingtaine)

Groupe 2239536 (il en importe 14 sur 17)

**Comment by ggrossetie** [comment]
Actuellement il est impossible de récupérer plus d'une quinzaine d’items via l'API Zotero car le code ne prend en compte la pagination. Il convient donc de trouver une solution pour récupérer toutes les données sans limite.

D'après @oncletom il faut récupérer cette notion dans l'entête `Link`. Voici un extrait de la documentation de l'API Zotero :

> rel=first/prev/next/last/alternate links for multi-object responses are now provided in the Link HTTP header.

https://www.zotero.org/support/dev/web_api/v3/changes_from_v2

Une librairie Node qui peut potentiellement nous aider à extraire des informations à partir de cet entête : https://www.npmjs.com/package/http-link-header

**Comment by antoinentl** [comment]
Premier test avec une bibliographie de 426 items ([ici](https://www.zotero.org/groups/925666/bibliothque_du_muse_saint-raymond/collections/KLIRSWJ2)), et je n'ai que 25 items en résultat. J'ai essayé avec une bibliographie moins volumineuse ([35 items](https://www.zotero.org/groups/322999/critures_numriques/collections/P4PRNB6V)), même résultat : 25 items. J'ai testé tout cela dans la version dev (https://stylo-dev.huma-num.fr).

**Comment by thom4parisot** [comment]
Réessaye, on a redéployé les développements sur cette instance de dev (idem pour #198)

**Comment by antoinentl** [comment]
Merci pour le redéploiement :+1: 

Pour une biblio de 35 items ça passe, même chose pour un groupe avec 63 items ou même 130, par contre pour les 426 ça ne passe pas, au bout d'une bonne minute la page devient blanche sans indication. Si vous voulez tester avec cette biblio : https://www.zotero.org/groups/925666/bibliothque_du_muse_saint-raymond/collections/KLIRSWJ2

**Comment by thom4parisot** [comment]
Merci !

Y'a une erreur applicative qui se produit : 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/138627/86454232-3c358e00-bd1f-11ea-9830-43281b4b53ba.png">


Ce qui m'étonne c'est que ça pagine sur beaucoup de pages : 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/138627/86454489-9d5d6180-bd1f-11ea-8a36-9cb7686cbfd8.png">

Et que des fois le résultat contient une réponse en base64, dont le contenu correspond à un seul élément. On dirait que c'est pour protéger du contenu non-ASCII, car certaines données ne sont pas stockées en UTF8 ?

**EDIT** : ce qui a l'air d'être confirmé dans ce thread https://forums.zotero.org/discussion/40131/bibtex-export-for-dotted-capital-i

**Comment by ggrossetie** [comment]
> Et que des fois le résultat contient une réponse en base64, dont le contenu correspond à un seul élément. On dirait que c'est pour protéger du contenu non-ASCII, car certaines données ne sont pas stockées en UTF8 ?

Est ce que dans ce cas l'entête de la réponse précise qu'il s'agit d'un contenu en base64?
Si c'est le cas on peut faire gérer le cas quand on récupère la réponse du serveur non? 🤔

**Comment by ggrossetie** [comment]
Apparemment Firefox ne fait pas de ungzip sur les réponses dans les DevTools. Avec Chrome, j'arrive bien à voir la réponse :

```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 313
Content-Type: application/x-bibtex
Date: Tue, 07 Jul 2020 06:21:41 GMT
Keep-Alive: timeout=5, max=100
Last-Modified-Version: 3048
Link: <https://api.zotero.org/groups/925666/collections/KLIRSWJ2/items/?format=bibtex>; rel="first", <https://api.zotero.org/groups/925666/collections/KLIRSWJ2/items/?format=bibtex&start=750>; rel="prev", <https://api.zotero.org/groups/925666/collections/KLIRSWJ2/items/?format=bibtex&start=800>; rel="next", <https://api.zotero.org/groups/925666/collections/KLIRSWJ2/items/?format=bibtex&start=800>; rel="last", <https://www.zotero.org/groups/925666/collections/KLIRSWJ2/items/>; rel="alternate"
Server: Apache/2.4.43 ()
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Total-Results: 825
Vary: Accept-Encoding
Zotero-API-Version: 3
Zotero-Schema-Version: 3

@book{rolley_sculpture_1994,
	address = {Paris},
	series = {Les manuels d'art et d'archéologie antiques},
	title = {La sculpture grecque ,  1 :  {Des} origines au milieu du {Ve} siècle},
	isbn = {978-2-7084-0448-9},
	shorttitle = {La sculpture grecque ,  1},
	language = {fre},
	publisher = {Picard},
	author = {Rolley, Claude},
	year = {1994},
	note = {ill. en noir et en coul. 29 cm. Bibliogr. p. 410-415. Index.},
	keywords = {Sculpture grecque archaïque}
```

Par contre certaines pages sont vides. Peut être parce que certaines références bibliographiques sont privées ?

**Comment by thom4parisot** [comment]
Alors on a trouvé le fautif, c'était ce "book section", qui faisait planter une expression régulière utilisée pour construire l'onglet "Citations" : 

<img width="873" alt="image" src="https://user-images.githubusercontent.com/138627/86789646-d2431e80-c067-11ea-8e77-aaa2fb93cc9e.png">

Avec #198, le parseur 1) lit sans planter et 2) ignore cette entrée. Quand j'importe la collection, j'ai désormais 415 items (416 - 1 "book section").

**Comment by antoinentl** [comment]
Super merci pour ces recherches et ces améliorations ! Désormais Stylo importe les références, mais nous avons plusieurs problèmes :

- nous sommes d'accord qu'il ne faut pas écarter les "book section", c'est un type de document fréquent, mais je n'ai pas l'impression qu'il y ait de problème de ce côté ;
- il y a clairement un problème sur une référence, mais cela arrivera forcément à un moment ou à un autre (on ne peut pas espérer avoir des collections parfaites), donc il faudrait trouver un scénario pour contourner ce problème ;
- la preview ne fonctionne pas chez moi (page blanche).

**Comment by thom4parisot** [comment]
On peut regarder à voir comment faire en sorte que le parseur l'accepte — il est absent des [types connus](https://github.com/fiduswriter/biblatex-csl-converter/blob/35d152935eba253ebadd00e285fb13c5828f167f/src/const.js#L289), et ça pourrait se régler en lui contribuant l'élément manquant.

Tu as une spec à nous montrer, qui indique quels sont les champs acceptés/obligatoires pour cet élément ?

On va checker pour la preview.
