### ISSUE TITLE
Preuve de concept de l'éditeur de texte avec Monaco pour remplacer CodeMirror, pour l'écriture en temps réel

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#415]
Peut-être qu'on n'a pas besoin d'avoir 2 éditeurs de texte différents, et que Monaco peut servir à la fois pour les textarea longs (raw YAML, raw Bibtex) et pour écrire du Markdown.

La preuve de concept devrait aider à :

- [ ] évaluer si la solution temps-réel yjs s'interface avec ([y-monaco](https://docs.yjs.dev/ecosystem/editor-bindings/monaco) semblerait indiquer qu'oui)
- [ ] évaluer si les interactions actuelles avec l'éditeur de texte sont réplicables, et à quel effort

Si ce n'est pas concluant, le travail mené sera utile à #406 — par exemple en envoyant des "signaux"/événements pour dire "déplace le curseur à tel endroit" plutôt que d'appeler directement l'API de CodeMirror ou autre.

**Comment by ggrossetie** [comment]
Le travail se poursuit dans https://github.com/EcrituresNumeriques/stylo/issues/481 ?

**Comment by thom4parisot** [comment]
Oui c'est ça :)
