### ISSUE TITLE
Connexion Zotero : tous les groupes ne sont pas visibles

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#419]
Actuellement je ne vois qu'une partie de mes groupes Zotero lorsque je tente de _fetcher_ les données depuis l'interface de gestion des données bibliographiques de Zotero, à peu près 20/29.

Je ne sais pas comment documenter autrement ce bug, je suis preneur de suggestions.

**Comment by ggrossetie** [comment]
On parle bien des groupes Zotero présents dans la liste "Import from my Zotero account" ?

![image](https://user-images.githubusercontent.com/333276/123615764-e72f3980-d805-11eb-88c4-e880f49960ae.png)

Est-ce que tu pourrais s'il te plait faire une capture d'écran de ton compte Zotero et de ce que tu vois dans la liste "Importe from my Zotero account" ?

Dans mon cas, on retrouve bien 3 groupes (sur la droite de la capture d'écran) : 

![image](https://user-images.githubusercontent.com/333276/123616019-278eb780-d806-11eb-96a3-9631ec7a62cb.png)

Est-ce que tu pourrais aussi regarder dans la console, peut être qu'il y a une exception. Sur Linux/Firefox, tu peux ouvrir les DevTools avec F12. En suite il faut regarder dans l'onglet "Console" et dans l'onglet "Network".

**Comment by thom4parisot** [comment]
Le nombre est rond (20), du coup je suppose qu'il y a une pagination dans l'API, et qu'on ne la suit pas.

**Comment by ggrossetie** [comment]
> Le nombre est rond (20), du coup je suppose qu'il y a une pagination dans l'API, et qu'on ne la suit pas.

Effectivement, il y a surement une pagination mais je viens de faire le test et l'API me retourne 23 groupes : 

![image](https://user-images.githubusercontent.com/333276/123620465-8e15d480-d80a-11eb-990b-8f4c84411f64.png)


![image](https://user-images.githubusercontent.com/333276/123620502-9a9a2d00-d80a-11eb-8063-990e88eaf81b.png)

**Comment by ggrossetie** [comment]
La limite par défaut est à 25 : 


![image](https://user-images.githubusercontent.com/333276/123621271-52c7d580-d80b-11eb-955c-e2c13be6e67d.png)

Et ensuite pour chaque groupe on fait une requête supplémentaire pour avoir la liste des collections. Si il n'y a aucune collection, on affiche pas le groupe.

**Comment by antoinentl** [comment]
Merci pour l'enquête @oncletom et @Mogztter ! Donc il faut adapter le script pour aller chercher plus de 20 groupes, j'ai bon ?

**Comment by ggrossetie** [comment]
> Donc il faut adapter le script pour aller chercher plus de 20 groupes, j'ai bon ?

Oui, plus de 25 groupes. Est ce que tu peux nous confirmer qu'il y a bien 25 groupes sur 29 qui remontent avec ton compte ? Sinon il y a peut être un autre soucis...
