### ISSUE TITLE
Fetching : No articles found

### ISSUE THREAD

**Issue by kbissonnette** [EcrituresNumeriques/stylo#42]
Salut,
Quand je me connecte avec redaction@sens-public.org, dans My Articles, aucun article n'apparaît, alors que tous devraient y être. Merci!

**Comment by ggrossetie** [comment]
Bonjour @kbissonnette 

Est-ce que ce problème est toujours d’actualité ?

**Comment by kbissonnette** [comment]
Bonjour @Mogztter, ce n'est plus du tout d'actualité. On peut fermer. Merci!
