### ISSUE TITLE
Option All-citation down

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#425]
L'option all-citation ne fonctionne pas :  l'export ne montre pas les références qui ne sont pas citées dans le texte (donc reste en mode only used).

**Comment by antoinentl** [comment]
Pour préciser le problème : l'export HTML fonctionne, mais pas les exports PDF, ODT ou TEI, qui ne semblent pas prendre en compte le paramètre `nocite: '@*'`, paramètre qui est censé permettre l'affichage de toutes les références bibliographiques. @marviro nous avons déjà rencontré ce bug.

Passer de `nocite: '@*'` à

```
nocite: |
  @*
```

ne change rien.

La commande Pandoc me semble correcte.

**Comment by thom4parisot** [comment]
Vous avez vérifié qu'avec une autre version de Pandoc le comportement était différent… ou le même ?

**Comment by ggrossetie** [comment]
Est-ce que c'est lié à https://github.com/EcrituresNumeriques/stylo/issues/342#issue-837969999 ?

**Comment by marviro** [comment]
Il faudrait préciser dans quel contexte d'export se produit le bug: export générique? Export sp? Depuis quand? Avez-vous un article d'exemple? Un bug signalé de cette manière générique me fait perdre beaucoup de temps juste pour le reproduire

**Comment by antoinentl** [comment]
@marviro Il s'agit de l'export générique depuis Stylo. Le bug a été signalé par @Mmellet hier. Tu peux tester sur n'importe quel article. Voilà ! :hugs:

**Comment by marviro** [comment]
Le bug semble dépendre de la position de la clé `nocite` dans le yaml. Normalement elle était la dernière clé. Ici elle se trouve après `month`. Si on ajoute dans l'en-tête de l'article le yaml suivant:

```
nocite: '@*'
```
cela fonctionne

Si je déplace à la main la clé dans le raw, stylo la remet après `month`.

Je n'ai aucune idée de pourquoi la place de la clé est importante. Probablement un bug de la version de pandoc utilisée dans l'export -mais je ne peux pas la tester en local. @Mogztter : est-ce que la place de la clé a été récemment changée?

**Comment by ggrossetie** [comment]
Pas vraiment, le changement a été fait le 25 février 2021: https://github.com/EcrituresNumeriques/stylo/commit/69c1bb95f1e8624851cacf66f3e527bd4f725c45

Présent en production depuis la version 1.1.0 qui a été déployée le 16 mars 2021.

**Comment by oncletom** [comment]
Et c'est lié à cette ligne : 

https://github.com/EcrituresNumeriques/stylo/blob/6ee112d560082f821911ae84310b071de30dec64/front/gatsby/src/components/Write/metadata/yaml.js#L33

**Comment by marviro** [comment]
Bon, on a le même problème aussi avec l'export Sens public - qui utilise la même commande...

Puisque je ne peux pas actuellement changer la version de pandoc dans l'export, il y a deux solutions:
1. Essayer de déplacer la clé dans le yaml final (à la fin du yaml)
2. 2. ajouter à la main le nocite en tête des articles

**Comment by marviro** [comment]
Pour la chronique: le problème est résolu si au lieu d'utiliser la commande `--metadata-file` j'enchaîne dans l'input le yaml et le md (ce qui par contre pose des problèmes de saut de ligne après le yaml).

J'en déduis qu'en effet le problème est là depuis 69c1bb9

**Comment by thom4parisot** [comment]
Merci @marviro pour ces précisions. Le fait de savoir que cette métadonnée doit toujours arriver en dernier est le "problème" qui m'a aidé à trouver une solution stable.

En pratique, le problème existe depuis qu'on a remplacé le formulaire dans #270, car depuis lors, il n'y avait plus de garantie d'ordre des métadonnées. Ordre qui était peut-être implicite avant.
