### ISSUE TITLE
Mettre à jour les images dans la documentation par rapport aux derniers changements d'interface

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#427]
La documentation contient quelques captures d'écran qui ne plus d'actualité par rapport aux derniers changements d'interface :

#### [Premier pas](https://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!pages/premierspas.md) ([source](https://github.com/EcrituresNumeriques/stylo/blob/master/docs/fr_FR/pages/premierspas.md))

- [x] L'écran de création d'un compte

Dans le tableau "Pour chaque article, plusieurs actions sont possibles" : 

- [x] L'icone permettant de "développer d'autres fonctions de l'article"
- [x] L'historique des versions
- [x] L'édition des tags

Dans "L'interface d'édition" : 

- [ ] La capture d'écran annotée de l'éditeur (peut être attendre qu'on fasse les changements sur les menus latéraux ?)

Dans "Nouvel article" :

- [x] L'ajout des tags

Dans "Versions" :

- [x] Les boutons "Preview", "Save Major", "Save Minor" et "Export"

Dans "Sommaire" : 

- [x] Le sommaire (peut être attendre qu'on fasse les changements sur les menus latéraux ?)

Dans "Bibliographie" : 

- [x] La liste des références bibliographiques

Dans "Statistiques" : 

- [x] Le panneau des stats (peut être attendre qu'on fasse les changements sur les menus latéraux ?)

#### [Gérer vos articles](https://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!pages/mesarticles.md) ([source](https://github.com/EcrituresNumeriques/stylo/blob/master/docs/fr_FR/pages/mesarticles.md))

- [x] Les volets permettant de "Éditer et gérer vos tags"
- [x] L'écran "Pages articles de votre compte"
- [x] L'historique des versions
- [x] L'édition des tags
- [x] Le renommage et l'enregistrement du renommage
- [x] Tager un article

Sur cette page, il y a des images qui ne sont pas résolues : 

![image](https://user-images.githubusercontent.com/333276/124717943-e5502f00-df05-11eb-94ab-ca24d3693b19.png)

![image](https://user-images.githubusercontent.com/333276/124717758-b9cd4480-df05-11eb-945b-2def58f2f91d.png)

**Comment by antoinentl** [comment]
Merci pour le rappel ! Je prépare cela, avec une mise en ligne dès que #420 et #421 seront fusionnés.

**Comment by DMathelier** [comment]
Bonjour à tous, j'ai proposé (dans la branche "issue-427-MAJ-captures") des captures actualisées et quelques corrections dans les passages de la documentation qui concernaient les tags.

**Comment by ggrossetie** [comment]
Top merci @DMathelier !
J'ai ouvert une pull request https://github.com/EcrituresNumeriques/stylo/pull/431 afin que l'on puisse avoir un aperçu des changements.

**Comment by ggrossetie** [comment]
Il me semble que tout est à jour maintenant, merci @DMathelier
