### ISSUE TITLE
disparition article

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#43]
Mon article 5bbf310b0e34ef0011467e9f a disparu - il est vide. Ou mieux: après la version 1.1 il y a une version 1.0 vide et le live est vide.
Pas grave car je l'ai en local - et en plus les versions sont là,, mais il serait bien de comprendre ce qui s'est passé. Peut-être le fait que Nico a essayé de le modifier sans être connecté?

**Comment by lakonis** [comment]
Pour préciser la suite des opérations : en cliquant sur ton lien envoyé hier sur slack, j'arrivais non connecté sur l'article à la version envoyée. En cliquant sur Live, l'article était d'abord vide, puis il s'est chargé et j'ai pu éditer et ajouter des contenus. Par contre, la sauvegarde version ou sous-version ne faisait rien. Et on a vérifié sur l'ordi de marcello en même temps, mes opérations non-logguées n'affectaient pas l'article depuis l'interface de marcello.
Mais malgré tout, il semble s'être passé quelque chose en base manifestement.

**Comment by ggrossetie** [comment]
Je ferme car il s'agit d'une anomalie qui a peut être été corrigée...
Si le problème survient à nouveau, ouvrir un nouveau ticket en détaillant les étapes permettant de reproduire cette anomalie afin que l'on puisse apporter une correction.
