### ISSUE TITLE
Article vide (version vide) après une déconnexion

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#44]
Il s'agit de l'article 1343. Si tu regarde l'historique des versions, s'est glissé une version 0.0 vide. La suite est un copier-coller des versions précédentes pour récupérer l'article.

On ne sait pas exactement ce qu'il s'est passé, possiblement 2 choses à la fois (mais c'est le à la fois qui n'est pas certain).
1. Le fork de cet article pour test (c'est moi qui faisait ca dans mon coin) (le fork s'est bien passé)
2. la déconnexion violente (!) d'internet alors qu'un éditeur était en train de travailler sur cet article. quand je vois l'historique, j'ai l'impression que l'article était ouvert à 2 endroits : user Senspublic + user Emma.

question : que se passe t il en base quand il y a un fork ? Quelle version est prise en compte ? Quel impact sur la version de l'article en cours ?

merci

**Comment by ggrossetie** [comment]
@lakonis je pense qu'on peut fermer ce ticket non ? La question est intéressante (i.e. que se passe t-il lors d'une édition concurrente ?), mais nécessitera surement un travail important...
