### ISSUE TITLE
Utiliser la version snapd de certbot, au lieu de la version d'Ubuntu 18.04

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#448]
Via https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx

```sh
apt remove certbot
apt install snapd
snap install core
snap refresh core
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot
```

À transposer dans Ansible avec le module [community.general.snap](https://docs.ansible.com/ansible/latest/collections/community/general/snap_module.html)

Le reste fonctionne pareil.
Mais on passe de la version `0.31.0` à la version `1.19.0`, avec une chaine de certificats qui n'est pas expirée.

**Comment by ggrossetie** [comment]
```
root@cchum-kvm-stylo-dev:~# certbot --version
certbot 1.24.0
```

Et c'était déjà fait en production:

```
root@cchum-kvm-stylo:~# certbot --version
certbot 1.24.0
```
