### ISSUE TITLE
Bug Mode Édition 

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#456]
Quand je passe en mode édition, Stylo bloque sur une page blanche 

https://user-images.githubusercontent.com/40469215/142270107-1e027481-3205-4ac3-858e-c5be39ad0555.mp4

**Comment by antoinentl** [comment]
Merci pour le signalement !

Je n'arrive pas à reproduire ton problème. Est-ce que tu peux essayer de forcer le rafraîchissement de la page d'édition de l'article ?

**Comment by Mmellet** [comment]
J'ai fait : la page se relance (on voit très brièvement le loading) puis repart sur du blanc

**Comment by antoinentl** [comment]
@Mmellet Est-ce que tu peux préciser ton navigateur et sa version ? @oncletom et @Mogztter on va avoir besoin de vous.

**Comment by Mmellet** [comment]
J'utilise Firefox 90.0 (64-bit)

J'ai testé le bug n'est pas là avec Chrome.

**Comment by antoinentl** [comment]
Ok merci. C'est une piste, est-ce que tu utilises un outil de blocage/filtrage (publicité, scripts, etc.) ?

**Comment by Mmellet** [comment]
adBlock mais j'ai essayé de désactiver et cela n'enlève pas le bug : j'ai le bug avec la version de firefox sur tous les comptes stylo et tous les articles.

**Comment by antoinentl** [comment]
En navigation privée aussi ?

**Comment by Mmellet** [comment]
non en navigation privée cela fonctionne bien

**Comment by antoinentl** [comment]
Ok donc il y a probablement quelque chose resté coincé en cache.

**Comment by thom4parisot** [comment]
C'est lié au cache du navigateur, c'est-à-dire #388. 

On y est confronté lors des mises en ligne, ce qui n'était pas arrivé depuis cet été.

On était bloqué sur un bug de l'outillage, on va voir si c'est résolu et vous évite de subir de désagrément bien fâcheux.
