### ISSUE TITLE
Option Share and Send : affichage à clarifier

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#459]
La page de partage et d'envoi à d'autres utilisateurs est moins claire qu'avant : on a du mal à distinguer les différents utilisateurs

![Screenshot 2021-11-18 at 09-04-11 Stylo](https://user-images.githubusercontent.com/40469215/142440007-b90051eb-9dfc-40c2-9ccd-42d195924361.png)
. 
Il faudrait peut-être réinsérer une ligne de séparation entre les comptes utilisateurs pour bien démarquer les groupes.

**Comment by ggrossetie** [comment]
Je pense qu'on a du faire des changements (ultérieurs) qui ont impacté (sans le vouloir) cet écran car le rendu actuel ne correspond pas aux évolutions réalisées sur cet écran.

Pour rappel, voici le rendu suite aux évolutions sur cet écran :

![124437139-0d5d5800-dd77-11eb-9d10-0934781ba11f.png](https://user-images.githubusercontent.com/333276/142441770-921f7fae-36fe-4eff-94a8-7960964800ce.png)
