### ISSUE TITLE
Bug général de Stylo

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#461]
Depuis ce matin, Stylo semble bloquer sur une page en éternel loading 

![Screenshot 2021-11-19 at 11-40-37 Stylo](https://user-images.githubusercontent.com/40469215/142659428-5b296bbd-a3df-47ed-a5be-5003552c1371.png)
: 

(c'est un peu urgent, j'ai des étudiants qui doivent rendre des devoirs avec stylo et N,y ont plus accès)

**Comment by thom4parisot** [comment]
@Mmellet j'ai remis le service en ligne. Il a planté à cause d'un bug nouvellement découvert lors de la connexion d'un utilisateur. Documenté dans #462.
