### ISSUE TITLE
Refondre la gestion des utilisateurs

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#464]
Les utilisateur·ices sont gérées dans 2 collections : 

* users
	* email
	* tags
	* acquintances
	* articles
	* tokens
	* passwords
	* displayName (pas obligatoire)
	* admin
	* firstName
	* lastName
	* institutions
	* zoteroToken
	* yaml
* user_passwords
	* users
	* password (pas obligatoire…)
	* username
	* email
	* unlock
	* active
	* expiresAt

Un début de proposition : 

1. supprimer la table "user_passwords"
2. transformer `user.passwords` en `user.password`, et y stocker un mot de passe chiffré
3. créer `user.authorizedUsers` pour référencer les users qui ont droit d'impersonner sa session (l'équivalent de `user_passwords.user`
4. supprimer `users.articles`

Vu que le displayName n'est pas obligatoire, ne pas en faire un identifiant, sinon ça nous oblige à le rendre unique.

**Comment by thom4parisot** [comment]
À remixer avec #159

**Comment by ggrossetie** [comment]
> supprimer users.articles

À vérifier mais je crois que cela sert à partager des articles entre utilisateurs ?

> créer user.authorizedUsers pour référencer les users qui ont droit d'impersonner sa session (l'équivalent de user_passwords.user

Dans #159, je propose d'utiliser des permissions avec des scopes.

Par exemple, pour dire que l'utilisateur a le droit d'accèder aux données de l'utilisateur `5eb3cbbefb180e06fb679ac0`:

```json
{
  "permissions": [ {"scope": "user", "userId": "5eb3cbbefb180e06fb679ac0"} ]
}
```

Et avec la même logique on peut aussi donner le droit d'accèder à un article avec:

```json
{
  "permissions": [ {"scope": "article", "articleId": "5e82f7f9033c070012bd05e4"} ]
}
```

Au passage, on ne devrait plus faire "d'impersonation" mais uniquement donner accès aux données de l'utilisateurs (articles, books, tags?).
Au besoin, on pourrait trouver un indicateur visuel permettant de distinguer les données de l'utilisateur connecté, des données des autres utilisateurs. (Peut être pas utile car on a déjà la notion du "créateur").

On pourrait aussi considérer que le fait d'être admin est une permission:

```json
{
  "permissions": [ {"scope": "admin"} ]
}
```

Pour le reste 👍🏻

**Comment by thom4parisot** [comment]
J'aime bien l'histoire des scopes 👍🏻 

> supprimer users.articles
> > À vérifier mais je crois que cela sert à partager des articles entre utilisateurs ?

Et bien y'a `articles.owners`, je croyais que ça avait le même effet.

Centraliser les permissions au niveau du user c'est pas mal. 

S'il s'agit de lister les articles auxquels on a accès, avoir un `articles.sharedWith` permettrait de faire — en une requête — la liste des articles qu'on "own" et "partagés avec nous".

```
db.articles.find({ $or: { owners: { $in: [userId] }, { sharedWith: { $in: [userId] } } })
```

Un truc du genre.

Si c'est la permission est positionnée au niveau de `users`, ça nécessite davantage d'aller-retours dans la base de données pour constituer la liste des articles auxquels on a droit.
