### ISSUE TITLE
Bug bibliographie lorsqu'on fetch un repo privé

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#467]
Bonjour,
j'ai une erreur récurrente sur la bibliographie, lorsque je tente de mettre à jour les références à partir d'un répertoire zotero privé : L'outil de management fetch correctement les références. Elles sont ensuite bien disponibles pour éditer le document. Je peux lancer une preview et tout semble fonctionner. Mais si je continue d'éditer, ou si je ferme et rouvre l'article, alors je perds la bibliographie, ou plutôt je la retrouve dans un état antérieur avant la mise à jour de la bibliographie. 

Actuellement sur cet article : 619b5ef0c52c3d001264dda5 la bibliographie est coincée sur 8 références au lieu des 23 du répertoire Zotero.

Je pensais avoir trouvé une astuce en éditant le bibtex raw après le Fetch. Mais rien n'y fait : le fichier bibtex stocké en base demeure une ancienne version.

Je n'ai pas testé sur un répertoire zotero public.

**Comment by ggrossetie** [comment]
J'arrive à reproduire cette anomalie qui n'est pas strictement liée à la récupération à partir d'une collection privée. En effet, l'anomalie peut se reproduire en éditant le BibTeX manuellement.

![issue-467](https://user-images.githubusercontent.com/333276/143033909-2a1e154e-9564-4acb-a605-c43a37d61ff7.gif)

Le problème vient du fait que lorsqu'on enregistre le texte de l'article (par exemple en ajoutant une lettre) le BibTeX est lui aussi mis à jour avec l'état antérieur.

On est en train de revoir en profondeur cette logique, qui était source d'une grande complexité de code mais aussi de bugs, dans la pull request : https://github.com/EcrituresNumeriques/stylo/pull/458

Les opérations deviennent indépendantes et, lorsqu'il y a un changement, on enregistre le BibTeX, les métadonnées et le texte de l'article indépendamment. Autrement dit, si on modifie le texte de l'article on met à jour uniquement le texte de cet article (plutôt que de mettre à jour l'ensemble des informations de l'article avec l'état "actuel")

//cc @oncletom

**Comment by thom4parisot** [comment]
> Le problème vient du faire que lorsqu'on enregistre le texte de article (par exemple en ajoutant une lettre) le BibTeX est lui aussi mis à jour avec l'état antérieur.

😨

**Comment by lakonis** [comment]
Bien reçu. Merci beaucoup. Donc selon l'ordre des opérations (édition bib, édition texte, création de version), on peut "stabiliser" le bibtex en cours. Je ne sais pas comment j'ai fait, mais mon document Stylo est complet maintenant.

Hâte de la prochaine version ! Merci!

**Comment by ggrossetie** [comment]
@lakonis en solution de contournement, tu peux recharger l'article (en appuyant sur F5) quelques secondes après avoir modifié le BibTeX et seulement après le rechargement tu peux modifier le texte de l'article 😬

**Comment by antoinentl** [comment]
@Mogztter `protip`
