### ISSUE TITLE
Bug bibliographie : efface les nouvelles entrées

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#468]
En lien avec l'issue #467 : Je me suis aperçue que les dernières références rentrées dans ma biblio avaient été effacées. J'ai fait la démarche de les rajouter mais elles s'effacent encore : même si j'ai save une nouvelle version. 

https://user-images.githubusercontent.com/40469215/143906165-0c4396a9-f373-4cfe-ab81-f2506d30b1d9.mp4

**Comment by ggrossetie** [comment]
Il faudrait recharger l'article pour voir ce qui est réellement enregistré en base de données pour cet article (mon adresse sur stylo est ggrossetie+stylo arobase gmail point com).
Est-ce qu'il est possible d'avoir accès à cet article pour que je puisse regarder ? ou d'avoir l'identifiant de l'article en format texte pour que je puisse le retrouver dans la base de données ? (il est présent dans la vidéo mais c'est assez fastidieux de le recopier).
Merci !

**Comment by Mmellet** [comment]
Je te l'ai partagé, n'ayant pas ce problème avec mes autres articles, peut-être que c'est une question de grandeur de la biblio, j'ai testé de rechargé l'article entre temps,  toujours le même résultat.

**Comment by ggrossetie** [comment]
J'arrive bien à reproduire le problème : 
1. Ajouter une nouvelle référence bibliographique dans l'onglet "Raw BibTex"
2. Cliquer sur "Save"
3. Enregistrer une nouvelle version mineure ou majeure de l'article
4. Recharger l'article (F5)
5. La référence bibliographique ajoutée à l'étape 1 n'est pas dans la liste des références bibliographiques

**Comment by ggrossetie** [comment]
La solution de contournement décrite ici https://github.com/EcrituresNumeriques/stylo/issues/467#issuecomment-976662815 fonctionne aussi pour ce problème.

Il faut attendre quelques secondes après l'ajout/suppression/modification du BibTeX puis recharger l'article avec F5. La bibliographie sera correctement enregistrée sur la version courante.

**Comment by Mmellet** [comment]
Oui en effet ça fonctionne avec cette solution merci !

**Comment by thom4parisot** [comment]
@Mmellet si on te demande de tester un correctif sur stylo-dev mercredi 1er octobre matin (Montréal) / aprem (France) ; ça serait possible pour toi ?

**Comment by Mmellet** [comment]
oui bien şur si en décembre :)

**Comment by thom4parisot** [comment]
Pardon… oui je pensais au 1er décembre, pas au 1er octobre 😅

**Comment by ggrossetie** [comment]
Potentiellement corrigé par https://github.com/EcrituresNumeriques/stylo/pull/458

**Comment by Mmellet** [comment]
Bel et bien corrigé par #458
