### ISSUE TITLE
Fermeture de la fenêtre de partage : croix cachée

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#469]
Actuellement la croix `X` de fermeture de la fenêtre de partage est cachée par le bouton "Add", il y a un petit ajustement à faire :

![Capture d’écran 2021-11-29 à 20 38 26](https://user-images.githubusercontent.com/6869488/143970153-97e7bf27-7484-4183-8182-3896f663c7f2.png)

**Comment by ggrossetie** [comment]
Déjà corrigé sur la branche `master` (déployé sur https://stylo-dev.huma-num.fr): https://github.com/EcrituresNumeriques/stylo/commit/4af4e0aa32a431ff4c9865a3d066cbc0ce770217
