### ISSUE TITLE
Définir une phrase par défaut pour les versions

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#478]

**Comment by antoinentl** [comment]
Je ne sais pas si cette formulation est la plus claire :

You should save your article to create your first version.

**Comment by ggrossetie** [comment]
Actuellement, le libellé du bouton est "Create new Version" donc pas sûr que "You should save your article" soit très clair:

![create-version](https://user-images.githubusercontent.com/333276/145113883-a66490dc-8976-42e2-8caf-c64053a49025.png)

**All changes are automatically saved.**
You should create a new version to capture a snapshot at a specific time, or record a specific set of changes of your article.

**Comment by ggrossetie** [comment]
On peut faire plus court si besoin:

**All changes are automatically saved.**
You should create a new version to record a specific set of changes.

**Comment by antoinentl** [comment]
Je n'avais pas réagi mais cette formulation est bien mieux, merci @Mogztter !
