### ISSUE TITLE
Permettre à un utilisateur de récupérer un token JWT afin d'utiliser l'API GraphQL

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#479]
Quelques questions / remarques : 

- Avec un compte Stylo (username + password), il est possible de faire un `POST https://stylo-dev.huma-num.fr/login` avec: 
  ```json
  {
    "username": "oncletom",
    "password": "$ecret"
  }
  ```
  Dans la réponse au format JSON, on peut récupérer la valeur de `token`.

- Jusqu'à peu il était aussi possible d'utiliser l'API GraphQL avec `login`:
  ```graphql
  { 
    login(username:"oncletom", password:"$secret") {
      token
    }
  }
  ```
  Peut être qu'il faut réintroduire cette méthode ?
- Comment faire quand on utilise un compte HumanID (i.e. quand on a pas de username + password Stylo) ?
- Est-ce qu'on permet de générer un token à partir de l'interface, par exemple sur la page `/credentials` (où on affiche des informations sur le compte de l'utilisateur) ?

**Comment by thom4parisot** [comment]
> Est-ce qu'on permet de générer un token à partir de l'interface, par exemple sur la page /credentials (où on affiche des informations sur le compte de l'utilisateur) ?

👍🏻 

(en plus ça règle tous les cas de figure cités plus haut)

**Comment by marviro** [comment]
> > Est-ce qu'on permet de générer un token à partir de l'interface, par exemple sur la page /credentials (où on affiche des informations sur le compte de l'utilisateur) ?

Yes! Cool!

**Comment by thom4parisot** [comment]
Le token est affiché dans la page `/credentials` depuis `stylo@1.7`.
