### ISSUE TITLE
Mots-clés contrôlés manquants

### ISSUE THREAD

**Issue by kbissonnette** [EcrituresNumeriques/stylo#48]
Des mots-clés contrôlés semblent être absents sur Stylo. C'est le cas avec télévision, (théorie de la) lecture... 
Merci Arthur!

**Comment by kbissonnette** [comment]
Salut, un article serait prêt à être mis sur spip, mais des mots-contrôlés (ceux ci-dessus) sont absents. Possible d'avoir un horizon de temps ou une alternative? Merci encore.

**Comment by ggrossetie** [comment]
@lakonis @kbissonnette Toujours d'actualité ?

**Comment by lakonis** [comment]
on peut fermer.
