### ISSUE TITLE
Utiliser l'éditeur de texte Monaco pour les zones de texte 

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#481]
Suite de #415.

Important notamment là où il y a beaucoup de volumétrie :

- [x] Éditeur de bibliographie (Bibtex)
- [x] Éditeur de métadonnées (YAML)
	- [x] Dans l'article
	- [x] Dans `/credentials`
- [x] ~~Éditeur de texte (Markdown) + Mode diff~~ #623

**Comment by thom4parisot** [comment]
@Mogztter https://blog.replit.com/code-editors#head-to-head

**Comment by ggrossetie** [comment]
Oui j'ai vu passé cette article 😉 

On utilise CodeMirror 6 sur la nouvelle version d'asciidoc.org et je peux confirmer que le mainteneur est très réactif! Il y a encore quelques petit bugs (notamment sur Chrome) mais globalement ça fonctionne bien et le découpage en modules est bien fichu.

Dans notre cas, je pense qu'on peut oublier l'utilisation de Stylo sur mobile. De mon point de vue, Monaco reste un bon choix mais je te laisse aussi évaluer et t'amuser un peu avec Monaco/CodeMirror 6. Je ne veux pas imposer/forcer le choix.
