### ISSUE TITLE
Certains livres provoquent un crash applicatif

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#484]
En me rendant sur https://stylo-dev.huma-num.fr/books, je déplie tous les livres. Certains roulent, et d'autres… plantent l'appli.

J'ai du mal à capter ce qui ne va pas. 
Mais des fois, en retirant des articles d'un tag, un livre qui provoquait un crash fonctionne à nouveau.

Je sèche pour aujourd'hui.

**Comment by ggrossetie** [comment]
Sûrement un livre maudit 👻😀

**Comment by ggrossetie** [comment]
J'arrive à reproduire : 

```
index.8f6a3bca.js:16 Uncaught TypeError: Cannot read properties of undefined (reading 'version')
`````

C'est surement lié au fait que certains articles dans le "book" n'ont pas de version:

https://github.com/EcrituresNumeriques/stylo/blob/3735f565aff25bbb380e74692bb224d4b9e4099e/front/gatsby/src/components/Chapter.jsx#L41-L42

`props.versions` correspond à la liste des versions d'un article et peut être vide.
