### ISSUE TITLE
Déplacer l'enregistrement du BibTeX dans le store redux

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#486]
Afin d'être cohérent avec les autres actions qui enregistrent le texte de l'article et les métadonnées de l'article.
Il faudrait aussi homogénéiser le déclenchement des "états liés" comme la date de dernier enregistrement et l'état de l'article : "enregistré", "en cours d'enregistrement", "erreur" (si on a pas réussi à enregistrer).

**Comment by thom4parisot** [comment]
Ouaip ! Et quand même le maintenir dans le "state" tant que c'est un bixtex brouillon/non-sauvegardé dans `workingVersion`.
