### ISSUE TITLE
Dernière version perdue après essai export

### ISSUE THREAD

**Issue by Bepron** [EcrituresNumeriques/stylo#49]
Je ne sais pas si le lien entre les deux événements est certain mais après une tentative d'export l'article est revenu à un état antérieur, pas moyen de retrouver les modifications réalisées la veille au soir.
Je ne sais pas comment préciser de quel article il s'agit, je ne trouve pas de numéro ou d'identifiant.

**Comment by PookMook** [comment]
Mhh, nous avons eu quelques retour de versions disparaissant,
La source est incertaine, la cause n'est encore pas certaine mais un point commun est la durée des sesions, nous sommes en train de remodeler le backend (coté serveur) de stylo pour mieux gérer les longues sessions et également passer d'un système de sauvegarde automatique qui écrase la précédente vers des mise a jour de version (si la nouvelle version est vide, rien ne change, contrairement au système actuel qui remplace la dernière (bonne) version par une vide)
