### ISSUE TITLE
no cite ne fonctionne pas

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#50]
L'option no-cite (citations: all citations) ne fonctionne pas car elle ajoute dans le yaml une mauvaise syntaxe.
La bonne syntaxe est
```
nocite: |
  @*
```

**Comment by PookMook** [comment]
corrigé via https://github.com/EcrituresNumeriques/stylo/commit/076b9a9ca541bdd9859292f72844723830a946be
Déployé sur le live
