### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#502]
Un article de 1879636 caractères ne peut pas être enregistré, car le serveur répond avec `413 Request Entity Too Large`.

![image](https://user-images.githubusercontent.com/138627/145405110-768bd116-8618-4641-9f2d-91c781595c28.png)

**Comment by ggrossetie** [comment]
Surement NGINX qui retourne cette erreur. Il me semble que la valeur par défaut de `client_max_body_size` est 1 MiB.
Comme on a la main sur la configuration on peut augmenter cette valeur.

Au passage il faudrait plutôt afficher le code retour et/ou le message de la réponse (plutôt que de retourner une erreur qui dit qu'on a pas réussi à `JSON.parse`).
