### ISSUE TITLE
Retour sur version en édition

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#503]
Soit j'ai la vue qui baisse (ce qui demeure une possibillité) mais je ne parviens pas, après avoir été consulté une version, à revenir sur ma version en édition... 

https://user-images.githubusercontent.com/40469215/145471577-ed79e094-f352-45e0-9e16-318e227cd7ab.mp4

Autre problème qui se pose, mais je pense pas que ce soit lié, par défaut lorsque je me connecte je suis sur le compte de sens public, lorsque je souhaite changer mon utilisateur Margot comme utilisateur par défaut, j'ai ce pop-up : 

![Screenshot from 2021-12-09 15-31-24](https://user-images.githubusercontent.com/40469215/145471360-199580f9-7008-410d-b7fe-b9afe208447e.png)

**Comment by ggrossetie** [comment]
Pour le retour en édition, on a remis le bouton mais la version n'était pas publiée.

Je viens de lancer la release : https://github.com/EcrituresNumeriques/stylo/releases/tag/v1.6.2
D'ici quelques minutes, la nouvelle version devrait être disponible sur https://stylo.huma-num.fr/

![image](https://user-images.githubusercontent.com/333276/145476079-5842a690-0241-4130-97bf-7d5e4d085b72.png)


Est-ce que tu peux s'il te plait ouvrir une nouvelle issue pour l'autre problème ? C'est plus facile pour nous de suivre si il y a un problème par issue GitHub.

Merci 😸

**Comment by Mmellet** [comment]
C'est bon pour le retour en mode édition ! merci ! 

(merci @oncletom pour avoir séparer les bugs!)
