### ISSUE TITLE
Ne plus afficher "Filter by tags" quand il n'y a pas de tag

### ISSUE THREAD

**Issue by marieflorescontact** [EcrituresNumeriques/stylo#505]
<img width="402" alt="Capture d’écran 2021-12-10 à 11 40 54" src="https://user-images.githubusercontent.com/73853856/145561235-4755e688-517a-4c9b-afdc-09d73341d2f5.png">

**Comment by marieflorescontact** [comment]
je peux soumettre un pr pour cette evolution

**Comment by thom4parisot** [comment]
Allez 🙂 

Fais signe si tu as besoin d'aide pour avancer dans ta contribution.

Merci de ta proposition !

**Comment by marieflorescontact** [comment]
hello,
avant d'ouvrir la pr il y a des tests ou quelque chose a faire? (j'ai lancé le linter)
merci!

**Comment by thom4parisot** [comment]
On n'a pas encore intégré de tests dans l'interface.

On en ajoute petit à petit pour des trucs dont la logique est critique (typiquement, le parsing des métadonnées). Y'a quelques fichiers en `.test.js` pour les modules concernés.

À première vue, je dirais que t'es tranquille pour cette issue.
