### ISSUE TITLE
Erreur à l'ouverture de la version annotée

### ISSUE THREAD

**Issue by belett** [EcrituresNumeriques/stylo#51]
Bonjour,

Quand j'essaye d'ouvrir la version annotée sur https://hypothes.is/ (peu importe le moyen, que ce soit par le lien Anotate ou en tapant directement l'URL), j'obtiens une erreur. Au lieu d'ouvrir la page, il me propose d'ouvrir un fichier 5c07acfce2d41a0010748c4d.error (qui est un fichier HTML local qui ne contient pas les annotations...)

Le problème survient sur Windows et Linux Ubuntu, avec comme navigateur : Firefox 63, Opera 56 ou Chrome 70.

**Comment by marviro** [comment]
Merci pour ce retour. Ce type d'erreur survient quand il y a un problème dans le markdown ou dans le bibtex. Typiquement, si vous avez cité une référence bibliographique qui n'est pas disponible dans le bibtex.

Vous pouvez ouvrir le fichier HTML et chercher "???". Si vous le trouvez, c'est la référence manquante. Si vous n'arrivez pas à identifier le problème, vous pouvez nous donner la clé de la version de votre article et on verra si on arrive à le debuguer.

**Comment by marviro** [comment]
@PookMook : on pourrait trouver un système pour que le browser signale cette erreur? Un message d'erreur lors de l'export?

**Comment by PookMook** [comment]
yes, le passage à graphQL pour le backend va séparer le backend de la génération du HTML, on va pouvoir mettre le html dans un process quelconque qui deviendrait beaucoup plus locace!

**Comment by ggrossetie** [comment]
Je ferme, le code de l'application a pas mal évolué et ce problème est surement corrigé.
Si ce n'est pas le cas, réouvrir avec un exemple récent.
