### ISSUE TITLE
Bouton "Add" du partage inactif

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#511]
## Problème rencontré
Lorsque l'on essaye d'ajouter une adresses mail avec qui partager un article, le bouton "Add" ne déclenche pas d'action (il ne se passe rien).

## Comportement attendu
Après l'indication d'une adresse courriel, le bouton "Add" doit ajouter l'adresse dans la liste.

**Comment by ggrossetie** [comment]
Il manque `type=submit` sur le bouton "Add" (associé au formulaire).

*protip:* tu peux appuyer sur la touche "Entrée" de ton clavier pour soumettre le formulaire 😉 
Normalement, le commit https://github.com/EcrituresNumeriques/stylo/commit/dccc3e9ae346a0067815ee91e8d7dd96df2e58a5 devrait résoudre ce problème.

**Comment by thom4parisot** [comment]
Oups, c'est le changement que j'ai introduit dans 7993f9c3edb4d00573f9d61eff40289a9f83b8db.
(quand y'avait des boutons "Fermer" dans une modale ça faisait un submit…)

**Comment by ggrossetie** [comment]
> Oups, c'est le changement que j'ai introduit dans 7993f9c.
(quand y'avait des boutons "Fermer" dans une modale ça faisait un submit…)

Si la valeur n'est pas renseigné, cela devrait fonctionner tout seul. Il faudrait renseigner `type` uniquement il est explicitement renseigné sur `<Button>`.

> `submit` : Le bouton soumet les données du formulaire au serveur. C'est la valeur par défaut si l'attribut n'est pas spécifié pour les boutons associés à un `<form>`, ou si l'attribut est une valeur vide ou invalide.

https://developer.mozilla.org/fr/docs/Web/HTML/Element/Button

@antoinentl Est-ce que tu peux confirmer que c'est corrigé sur https://stylo-dev.huma-num.fr/ ?

**Comment by thom4parisot** [comment]
C'est bien le problème : parce que les boutons de "fermeture" étaient dans des modales, ça soumettait le formulaire automatiquement. S'il y avait un `onSubmit` sur le formulaire, ça le déclenchait.

De manière générale, il devrait explicitement y avoir _un seul_ bouton de validation de formulaire. Et on ne devrait pas avoir à s'inquiéter qu'un bouton d'annulation le soumette.

**Comment by ggrossetie** [comment]
> C'est bien le problème : parce que les boutons de "fermeture" étaient dans des modales, ça soumettait le formulaire automatiquement. S'il y avait un onSubmit sur le formulaire, ça le déclenchait.

Je pensais que ça s'appliquait uniquement si le `<button>` était enfant de `<form>` mais d'après ce que tu dis si ce n'est pas le cas ?

> De manière générale, il devrait explicitement y avoir un seul bouton de validation de formulaire. Et on ne devrait pas avoir à s'inquiéter qu'un bouton d'annulation le soumette.

Oui je suis d'accord, dans ce cas par défaut il faudrait être à `type=button` et je préfère ajouter un `type=submit` explicitement plutôt que d'avoir la règle `props.primary ? 'submit' : 'button'` (le fait d'être le bouton "primaire" n'implique pas forcement de "submit" un formulaire).

**Comment by antoinentl** [comment]
@oncletom Je confirme que ça fonctionne sur stylo-dev !

**Comment by antoinentl** [comment]
Désolé mais le problème persiste après la v1.6.3...

**Comment by ggrossetie** [comment]
@antoinentl Je viens de tester et chez moi ça fonctionne 🤔 Est-ce que tu peux tenter de vider ton cache et refaire un test ?

![working](https://user-images.githubusercontent.com/333276/146595501-68e30c8f-84de-40df-ac79-e8ff698a2756.gif)

**Comment by ggrossetie** [comment]
@antoinentl Est-ce que tu peux nous confirmer que l'anomalie est résolue ?

**Comment by ggrossetie** [comment]
Je ferme, tu peux réouvrir si tu constates toujours l'anomalie.
