### ISSUE TITLE
Envoi et duplication ne fonctionne plus : contenu de l'article par défaut qui est envoyé ou dupliqué

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#513]
Actuellement les fonctions de duplication ou d'envoi ne fonctionnent plus correctement : le contenu partagé est l'article par défaut.

À noter que le partage, lui, fonctionne (contenu, bibliographie et métadonnées sont bien partagées).

**Comment by thom4parisot** [comment]
Oups, je vois d'où ça vient : [on ne copie pas les contenu de l'article lors de son initialisation](https://github.com/EcrituresNumeriques/stylo/pull/458/files#diff-0b1cc2f2063f788b29e18dbe164546ab2c5f8c8d124c8318cf159841d4b9763eR126).

Je déploie un correctif dans la journée.

**Comment by thom4parisot** [comment]
Corrigé avec 12bdf8c1bf14737c3adad6d12c9643354ca83d33 et 1c394a4b9c5018e0e8bbbcad882998310ab439de.
