### ISSUE TITLE
Bug export Page Articles pour Article sans version

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#516]
Je renseigne ici un double bug : 

1. La fonction export pour un article sans version à partir de la page articles ne fonctionne pas (l'export pour ce même article sans version à partir de la page edit de l'article fonctionne)

https://user-images.githubusercontent.com/40469215/148550394-df2ac9a8-4fe5-4764-9d52-610c35a4e1e9.mp4

2. problème que j'avais déjà présenté je crois : je ne peux plus set l'utilisateur Margot comme utilisateur par défaut et je suis renvoyée par défaut au compte stylo de Sens public.

**Comment by thom4parisot** [comment]
C'est noté.

Ton deuxième point est consigné dans #504, et ça sera corrigé dans le courant du mois avec #508.

**Comment by thom4parisot** [comment]
Ah et du coup, #519 correspond à ce bug.

**Comment by antoinentl** [comment]
Pour compléter : la prévisualisation des _books_ ne fonctionnent pas si les articles ont simplement _une_ version ("Genesis(0.0)" qui est censé être la version par défaut avant la modification de Stylo), la prévisualisation fonctionne après une "New version" sur tous les articles d'un book.
