### ISSUE TITLE
Bug Stylo import

### ISSUE THREAD

**Issue by meric96** [EcrituresNumeriques/stylo#517]
Je renseigne ici un possible bug :

Le module de la conversion d'un document en docx ne marche pas correctement. J'avais dépose un document (docx) sur Dropbox pour lui convertir en md. Par contre j'ai toujours eu un fichier docx à la fin qui ne s'ouvre pas.

Voici, vous pouvew trouver également le document que j'avais essayé de convertir : 

[test1.docx](https://github.com/EcrituresNumeriques/stylo/files/7838380/test1.docx)

**Comment by thom4parisot** [comment]
Si je comprends bien, tu utilises Dropbox pour importer un document et en obtenir une version en Markdown, c'est ça ?

---

En tentant d'ouvrir ce document, il m'est signalé comme invalide par mon outil d'édition. LibreOffice y arrive mais ça ne ressemble pas à du texte : 

<img width="1133" alt="Screenshot 2022-01-10 at 12 15 00" src="https://user-images.githubusercontent.com/138627/148757328-d9f8c755-8936-45ed-b3f3-1aeba90ecf2f.png">

**Comment by meric96** [comment]
En effet c'est le document converti par le Stylo. Voici, vous pouvez trouver trouver le lien de Dropbox : https://www.dropbox.com/scl/fi/5luutnakiuhpygh7r9day/2022-01-04_notes_references_-Stylo_-Markdown-1.docx?dl=0&rlkey=5xlufswvzww3cse0eirb7dpmb

Et oui, je voulais obtenir une version en Markdown

**Comment by marviro** [comment]
en effet, il y a un bug dans le module d'import, on dirait. Je vais regarder ça aujourd'hui

@oncletom : il faudra qu'on discute d'un import plus propre que mon script bash ;)
https://stylo-export.ecrituresnumeriques.ca/importdocx.html

**Comment by thom4parisot** [comment]
J'ai ouvert #518 pour entamer une discussion, peut-être davantage d'un point de vue usages que technique.

**Comment by marviro** [comment]
Bon, je n'arrive pas à debugguer l'import. Cela est dû à un problème de wget (aucune idée de pourquoi, car en local ça fonctionne).
Je vais essayer de développer au plus vite une autre fonctionnalité d'import

**Comment by marviro** [comment]
Ok, c'est bon, ça marche maintenant:
essayez avec ce lien: https://www.dropbox.com/scl/fi/jf6f7c0cpkqf41czzcf7a/2022-01-04notesStylo.docx?dl=0&rlkey=uwo12oikqm3n4rncouzu4rkbo

Le problème était lié à des caractères spéciaux dans le nom du fichier. Dans la mesure du possible il faut éviter les caractères spéciaux dans la nomenclature d'un fichier.

**Comment by meric96** [comment]
Ah oui, exactement ! Si j'ai bien compris, on ne peut pas utiliser le tiret-bas dans le nommage, n'est pas ? Par contre dans plupart de fichier, il est commun d'utiliser le tiret-bas. Ça peut être intéressant de mentionner les caractères spéciaux non-valable soit le dans le page [Stylo import](https://stylo-export.ecrituresnumeriques.ca/importdocx.html) soit dans la documentation.

**Comment by meric96** [comment]
Ah... c'était à cause du croisillon ! Bien noté :) Je vous remercie pour votre attention !

**Comment by thom4parisot** [comment]
@marviro en utilisant [`pattern`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) dans le champ `<input>` qui va bien, ça serait un _quickfix_ qui prémunirait de ce genre de situations.
