### ISSUE TITLE
Bug Export renvoi un page blanc

### ISSUE THREAD

**Issue by meric96** [EcrituresNumeriques/stylo#519]
Je renseigne ici un possible bug :

Depuis le matin, j'ai réalisé que le bouton Export nous renvoi à un page blanc. Normalement, il n'y avait pas un soucis à propos de l'exportation sauf celle en format PDF. L'exportation en PDF causait un souci.  

Voici, vous pouvez voir l'enregistrement de l'écran :  
https://user-images.githubusercontent.com/60181424/148771580-1c3f9e28-2274-465c-9299-34911c14c006.mov

**Comment by thom4parisot** [comment]
Merci @meric96 de dénicher ces bugs 🙂 

@Mogztter la trace dans la console est : 

```
Uncaught TypeError: e.versions[0] is undefined
```

**Comment by antoinentl** [comment]
@meric96 Une précision pour régler le problème de façon temporaire (en attendant que ce soit résolu définitivement) :

- créer une version en cliquant sur "New version" (donner un nom quel qu'il soit, et indiquer "minor" ou "major" au choix) ;
- refaire l'export.

Cette manipulation devrait fonctionner. Actuellement les articles _sans version_ ne peuvent pas être exporter.

**Comment by meric96** [comment]
Oui, vous avez raison !  Maintenant ça marche correctement sauf l'export en PDF que je l'avais mentionné. J'ajoute l'enregistrement de l’écran ci dessous : 

https://user-images.githubusercontent.com/60181424/148780139-c1883ead-efa5-46fc-83e0-a69e9a908253.mov

**Comment by antoinentl** [comment]
Déjà c'est super si le premier point est résolu ! Pour le second, cela peut être un problème d'image dans la source, est-ce que vous pouvez vérifier que vos images sont bien au format PNG ? S'il y a toujours un problème nous pouvons échanger par mail : antoine.fauchie@umontreal.ca

**Comment by meric96** [comment]
Vous avez encore raison ! J'avais oublié que les images doivent être au format PNG. 

Pourtant, même si j'enleve l'image, ça ne résoudre pas le problème : 

https://user-images.githubusercontent.com/60181424/148783898-3af92e55-63ec-47ab-9855-1febf7173b1b.mov

 J'ai testé d'autres solutions mais cette fois-ci, le site me renvoi à un page 404 : 

https://user-images.githubusercontent.com/60181424/148784081-3d87e4b1-0f56-4555-b9fd-0d3908442fbf.mov
