### ISSUE TITLE
Problème insécable 

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/stylo#52]
Petits problèmes avec la nouvelle version des insécables, certains sont pris en comptes, d'autres non. 

Ici tout semble bien : 
![image](https://user-images.githubusercontent.com/14794908/49526591-22e80980-f87e-11e8-8e92-6534d6753000.png)

Mais si on ouvre sur Atom : 

![image](https://user-images.githubusercontent.com/14794908/49526499-ed432080-f87d-11e8-86bc-ff0af3072b8f.png)

la majorité des insécables sont bien formés, mais pour certains ça ne fonctionne pas, aucune idée pourquoi.

**Comment by PookMook** [comment]
Mhh, il y a deux types d'espaces insécables: 
ceux ajouter par l'utilisateur via ctrl+shift+espace et ceux que l'éditeur ajoute quand tu mets plusieurs espaces de suite sur le format espace/espace insécable/espace/espace insécable/espace/etc/etc/...
Seuls ceux de la première catégorie devraient être dans le document final.
Est-ce que ton expérience corresponds à ce que je décris?
