### ISSUE TITLE
La prévisualisation d'un Book sans version ne fonctionne pas

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#522]
Décrit par @antoinentl dans #516 :

> la prévisualisation des books ne fonctionnent pas si les articles ont simplement une version ("Genesis(0.0)" qui est censé être la version par défaut avant la modification de Stylo), la prévisualisation fonctionne après une "New version" sur tous les articles d'un book.

**Comment by ggrossetie** [comment]
Effectivement, je reproduis avec https://stylo-dev.huma-num.fr/books/606dac7d6b4ec500180cdf04/preview

```
TypeError: Cannot read properties of undefined (reading 'md')   
    at /usr/src/app/src/export.js:198:75
    at Array.map (<anonymous>)
    at getBookExportContext (/usr/src/app/src/export.js:198:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exportBookHtml (/usr/src/app/src/export.js:288:33)
```

**Comment by ggrossetie** [comment]
Le code tente d’accéder à la dernière version des "chapitres" en utilisant l'index `length -1` dans le tableau des versions (qui dans ce cas est vide !)

https://github.com/EcrituresNumeriques/stylo/blob/33c72cfa4dba72530e3f3057915ee08d1ab4b4bd/export/src/export.js#L198-L199

https://github.com/EcrituresNumeriques/stylo/blob/33c72cfa4dba72530e3f3057915ee08d1ab4b4bd/export/src/export.js#L201


Il faut plutôt utiliser : 

```js
c.versions.length > 0 ? c.versions[c.versions.length - 1] : c.workingVersion
```

À partir de Node.js 16.6.0, on peut aussi utiliser `c.versions.at(-1)`: https://nodejs.org/ja/blog/release/v16.6.0/
