### ISSUE TITLE
Impossible de modifier le mot de passe d'un compte Stylo (non HumanID)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#552]
Actuellement le _bouton_ "Change" de la page https://stylo.huma-num.fr/credentials ne permet pas de valider le nouveau choix. Il s'agit peut-être d'un simple problème de validation du _bouton_.

**Comment by thom4parisot** [comment]
Est-ce que ça correspond à #531 ?

**Comment by antoinentl** [comment]
En partie, j'ai modifié le titre ici pour plus de clarté. Il faudrait en fait ajouter une phrase d'explication pour distinguer les deux types de compte :thinking:

**Comment by thom4parisot** [comment]
Ça tombe bien, on a ajouté des bricoles qui explicitent ça au niveau du code/données dans #508 🙂
