### ISSUE TITLE
Problème d'export PDF lié à l'URL de l'image utilisée dans l'article How to Stylo

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#553]
diff. problèmes rencontrés/remarqués pendant une formation :

1. pendant une formation, plusieurs personnes n'ont pas réussi à ouvrir le How to par défaut. D'autres oui. Il s'agissait pour tous de nouveaux utilisateurs (nouveaux comptes). Je me demande si le how to n'utilise pas un vieux yaml. Peut être à mettre à jour.
2. l'image d'exemple utilisée est celle-ci `![Titre de mon image](https://avatars2.githubusercontent.com/u/16691667?s=200&v=4)`. Or cette url ne pointe pas vers un fichier (*.jpg ou autre). Ce qui fait que l'export du howto bug en PDF. Ce qui est probablement le 2eme ou 3eme truc testé par les utilisateurs. Il faudrait, 
   1. rapidement utiliser une autre image dans le how to par défaut, de manière à ce que l'export fonctionne.
   2. consolider l'export PDF pour intégrer les url d'images sans fichier. Ça permettra notamment aux images NAKALA intégrées en `/data/` de fonctionner (elles non plus ne pointent pas vers un fichier).

**Comment by ggrossetie** [comment]
> pendant une formation, plusieurs personnes n'ont pas réussi à ouvrir le How to par défaut. D'autres oui. Il s'agissait pour tous de nouveaux utilisateurs (nouveaux comptes). Je me demande si le how to n'utilise pas un vieux yaml. Peut être à mettre à jour.

Est-ce qu'il y avait des erreurs visibles sur la page ? dans la console (DevTools) ?
Est-ce que les personnes utilisent le même navigateur ? Est-ce que les personnes utilisent des comptes locaux ou HumanID ? 

> l'image d'exemple utilisée est celle-ci `![Titre de mon image](https://avatars2.githubusercontent.com/u/16691667?s=200&v=4)`. Or cette url ne pointe pas vers un fichier (*.jpg ou autre).

C'est une image PNG, ce n'est pas supporté par l'export PDF ?

**Comment by lakonis** [comment]
> Est-ce qu'il y avait des erreurs visibles sur la page ? dans la console (DevTools) ?

Désolé je n'ai pas pu vérifier (en formation)

> Est-ce que les personnes utilisent le même navigateur ? Est-ce que les personnes utilisent des comptes locaux ou HumanID ?

De ce que j'ai vu il y avait du chrome et du Firefox. Pas mal de Windows 

Je n'ai pas demandé si compte local ou humanid. 

Désolé de ne pas pouvoir aider davantage.

**Comment by lakonis** [comment]
> C'est une image PNG, ce n'est pas supporté par l'export PDF ?

Le PNG est bien géré mais l'URL ne comporte pas l'image (seule sa résolution permet d'accéder à l'image). Et je pense que le script (Bash) d'export cherche un fichier PNG ou jpg ou autre. Il faudrait consolider le script avec ce cas précis qui est assez récurrent.

**Comment by ggrossetie** [comment]
> pendant une formation, plusieurs personnes n'ont pas réussi à ouvrir le How to par défaut. D'autres oui. Il s'agissait pour tous de nouveaux utilisateurs (nouveaux comptes). Je me demande si le how to n'utilise pas un vieux yaml. Peut être à mettre à jour.

Quand tu dis "non't pas réussi à ouvrir le How to par défaut", tu veux dire éditer le document en cliquant sur le bouton "Edit" dans la liste des articles ? 

![image](https://user-images.githubusercontent.com/333276/156325206-22b0b647-b623-48cf-91bc-cbbb863d54d4.png)


Ou alors ils n'ont pas réussi à l'ouvrir le fichier (PDF ?) suite à un export ?

> Et je pense que le script (Bash) d'export cherche un fichier PNG ou jpg ou autre. Il faudrait consolider le script avec ce cas précis qui est assez récurrent.

Si c'est lié au service d'export, il y a un travail en cours afin de l'améliorer. @davidbgk travaille sur une nouvelle version en Python qui devrait prochainement remplacer les scripts Bash.

**Comment by davidbgk** [comment]
> Le PNG est bien géré mais l'URL ne comporte pas l'image (seule sa résolution permet d'accéder à l'image).

En fait, c'est l'extension qui ne fait pas partie de l'URL, en Python [cela a été résolu de manière peu élégante](https://gitlab.huma-num.fr/marviro/styloexportpython/-/blob/main/styloexport/article.py#L159-170) en vérifiant l'URL dans un premier temps puis en vérifiant le header `Content-Type`. Dans le cas où il y aurait une différence, c'est le header qui fait foi (s'il existe).

C'est contraignant au niveau de la logique car cela ne permet pas de considérer facilement qu'une image est en cache (téléchargement requis à chaque export).

**Comment by lakonis** [comment]
> Quand tu dis "non't pas réussi à ouvrir le How to par défaut", tu veux dire éditer le document en cliquant sur le bouton "Edit" dans la liste des articles ?

Oui, c'est cela. Ils n'ont jamais pu l'afficher. Mais je n'ai pas assez d'éléments pour savoir si c'est dû à une évolution du yaml par exemple qui fait que les nouveaux comptes accéderaient à un document "obsolète" côté Stylo ? Ou si c'est uniquement un pb de plateforme (OS, browser, etc.) ? Et je n'ai pas vu de mes yeux le problème. @ServanneMo par contre a pu le constater avec les personnes présentes.

**Comment by lakonis** [comment]
@davidbgk on a hâte de voir ce nouvel export en production. Une idée du délai ?

**Comment by davidbgk** [comment]
> @davidbgk on a hâte de voir ce nouvel export en production. Une idée du délai ?

C'est un embryon pour l'instant et il y a beaucoup de choses à discuter avant. Je ferai probablement une démo le 16 👍

**Comment by ggrossetie** [comment]
> En fait, c'est l'extension qui ne fait pas partie de l'URL, en Python [cela a été résolu de manière peu élégante](https://gitlab.huma-num.fr/marviro/styloexportpython/-/blob/main/styloexport/article.py#L159-170) en vérifiant l'URL dans un premier temps puis en vérifiant le header Content-Type

👍🏻 

> C'est contraignant au niveau de la logique car cela ne permet pas de considérer facilement qu'une image est en cache (téléchargement requis à chaque export).

Tu peux éventuellement faire une requête HEAD (si supporté) afin de récupérer les headers mais sans télécharger l'image. Sur GitHub cela fonctionne:

```console
$ http head https://avatars2.githubusercontent.com/u/16691667
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: max-age=300
Connection: keep-alive
Content-Length: 7682
Content-Security-Policy: default-src 'none'
Content-Type: image/png
Date: Wed, 02 Mar 2022 17:05:57 GMT
ETag: "d81e25bbd3b0a1361f347353928c9b647a8d6fbb7235a39b8b6d6a37789f7e8d"
Expires: Wed, 02 Mar 2022 17:10:57 GMT
Last-Modified: Mon, 19 Oct 2020 18:34:01 GMT
Source-Age: 0
Strict-Transport-Security: max-age=31557600
Vary: Authorization,Accept-Encoding
Via: 1.1 varnish
X-Cache: MISS
X-Cache-Hits: 0
X-Content-Type-Options: nosniff
X-Fastly-Request-ID: ef016b43a8f0ac94e74a9ff5a81adda5ca10afe7
X-Frame-Options: deny
X-GitHub-Request-Id: 63B2:1244:250637:58BC4A:621FA3F4
X-Served-By: cache-cdg20728-CDG
X-Timer: S1646240757.227624,VS0,VE168
X-XSS-Protection: 1; mode=block
timing-allow-origin: https://github.com
```

> Oui, c'est cela. Ils n'ont jamais pu l'afficher. Mais je n'ai pas assez d'éléments pour savoir si c'est dû à une évolution du yaml par exemple qui fait que les nouveaux comptes accéderaient à un document "obsolète" côté Stylo ? Ou si c'est uniquement un pb de plateforme (OS, browser, etc.) ? Et je n'ai pas vu de mes yeux le problème. @ServanneMo par contre a pu le constater avec les personnes présentes.

Ca va être compliqué à troubleshoot, je pense qu'il est préférable d'ouvrir une autre issue quand vous aurez plus d'éléments. J'ai essayé de reproduire l'anomalie en créant des nouveaux comptes mais tout fonctionne sur mon poste.

**Comment by thom4parisot** [comment]
Ou utiliser l'URL `https://github.com/<username>.png` 🙂
