### ISSUE TITLE
Credentials Account VS authentification Zotero

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#554]
J'ai deux accès Stylo : un "compte" local avec mon email perso, et un "compte" HumanID. 

J'ai aussi un compte Zotero utilisant mon email perso.

Lorsque A/ j'utilise Stylo en tant qu'utilisateur HumanID et B/ je me connecte à Zotero via le gestionnaire de références pour récupérer une collection zotero, alors {

→ l'interface bascule sur mon utilisateur "local", et je me retrouve avec le document en cours d'édition sans pouvoir l'éditer ou sauvegarder ce que j'étais en train de faire (en tant qu'utilisateur HumanID).

}

Donc en quelque sorte, pendant l'édition d'un document, il y a eu un changement involontaire d'utilisateur m'empêchant de poursuivre (et sauvegarder) mon travail.

**Comment by thom4parisot** [comment]
Est-ce que tu utilises la fonctionnalité de bascule de compte ? Ou tu te connectes/déconnectes pour passer d'un compte Stylo à l'autre ?

**Comment by ggrossetie** [comment]
Est-ce que le fait qu'on utilise password pour le callback Zotero (authentification OAuth) pourrait remplacer l'utilisateur en session?

https://github.com/EcrituresNumeriques/stylo/blob/819883d05a5171e2b095dcdcb978291446d570d3/graphql/app.js#L219-L241

J'ai l'impression que Nicolas dit qu'il a un compte Stylo et un compte Zotero qui utilise l'adresse "foo@example.org" et un compte HumaID qui utilise l'adresse bar@example.org.
Quand il se connecte avec "bar@example.org" (donc via HumanID) puis qu'il se connecte à Zotero pour récupérer une collection, Stylo bascule sur son compte "foo@example.org".

Mon hypothèse c'est que le callback OAuth Zotero remplace l'adresse email en session par "foo@example.org" (adresse email du compte Zotero) et qu'on finisse par regénérer un token avec cette adresse email et donc par basculer sur "foo@example.org" alors qu'on était connecté sur "bar@example.org" 😱

**Comment by lakonis** [comment]
Merci @Mogztter c'est exactement ça.

**Comment by thom4parisot** [comment]
Oh yeah! 🙃 

Bah ça va être résolu par #508 dans ce cas.

**Comment by thom4parisot** [comment]
Déploiement du correctif prévu le 9 mars aprem.

**Comment by thom4parisot** [comment]
@lakonis curieux de savoir si tu rencontres le problème avec le nouveau déploiement du jour.

**Comment by thom4parisot** [comment]
À priori ça n'est plus d'actualité avec les workspaces.
