### ISSUE TITLE
Basculer de compte au niveau de la liste d'articles

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#555]
Dans la lignée de #508, #533 et #529 — et suite à un appel avec @antoinentl et @Mmellet toute à l'heure — il faudrait procéder à des changements sur la liste d'articles : 

1. [x] rétablir le comportement initial de la liste (articles dont on est le `owner` et/ou `contributor`
2. [x] remplacer le filtre case à cocher par une liste de sélection autocomplétable, pour choisir le compte auquel on a accès
3. [ ] quand on choisit ce compte, ce compte est mémorisé (pour la liste d'articles), et la liste d'articles correspond à celle que verrait le compte partageant sélectionné

![Screenshot 2022-02-10 at 17 52 20](https://user-images.githubusercontent.com/138627/153477848-d0730f21-4943-4557-82c2-8f662ee4d1d6.jpeg)

Également : 

1. [ ] remplacer la mention "by xxx and shared with xxx" par "by xxx, xxx and xxx" (tout le monde au même niveau)
2. [ ] procéder à une double confirmation pour le partage de compte ("Grant access" -> "Yes, I grant access to my xxx articles" -> "Revoke access")

---

D'un point de vue technique, j'ai l'impression que ça le ferait au niveau de la requête GraphQL : 

- soit en ayant une requête sans user (auquel cas, c'est celui déterminé par le token)
- soit en ayant un user explicite (auquel cas, le contrôleur vérifie que le user explicite contient le user déterminé par le token dans sa liste des _grantee_)

**Comment by ggrossetie** [comment]
> rétablir le comportement initial de la liste (articles dont on est le owner et/ou contributor

@thom4parisot Est-ce que tu peux expliciter ce que tu entends par comportement initial ? Il me semble qu'on affiche déjà uniquement les articles dont on est le owner et/ou contributor non ?

**Comment by thom4parisot** [comment]
Non, on affiche tous nos articles, et tous les articles des comptes auxquels on a droit.

# Le changement de comportement qu'on avait introduit

![image](https://user-images.githubusercontent.com/138627/154282198-00d240db-4dc8-419c-a4de-0018d8670444.png)

# Ce que je comprends comme étant attendu

![image](https://user-images.githubusercontent.com/138627/154282313-b4af9f5b-ccd4-4c9d-aa41-70e33ac83854.png)
