### ISSUE TITLE
La fonction `askGraphQL()` devrait indiquer le message d'erreur

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#560]
Aujourd'hui, c'est `TypeError: Response.text: Body has already been consumed.` qui est systématiquement affiché.

En partie parce que `response.text()` est appelé après avoir déjà consommé la réponse au format JSON quelques lignes plus haut.

https://github.com/EcrituresNumeriques/stylo/blob/b01a6604ed67ec4a33f529a34ad5838c0271f7bc/front/src/helpers/graphQL.js#L28-L32

**Comment by ggrossetie** [comment]
Apparemment la solution c'est le clone !

https://developer.mozilla.org/en-US/docs/Web/API/Response/clone

Un exemple d'implémentation qui adresse ce problème avec `clone` : https://github.com/mozilla/addons-frontend/pull/1702/files

**Comment by thom4parisot** [comment]
Ce qui est confus c'est que le problème peut tant venir du parsing JSON de la réponse que du fait que ça re-jette une erreur après avoir réussi à parser la réponse JSON.

**Comment by ggrossetie** [comment]
> Ce qui est confus c'est que le problème peut tant venir du parsing JSON de la réponse que du fait que ça re-jette une erreur après avoir réussi à parser la réponse JSON.

Oui exact le code n'est pas bon car on catch l'exception 😬
