### ISSUE TITLE
Dédoublement annotations entre previews de différents articles

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#564]
J'ai remarqué hier un bug un peu bizarre : 

Dans la preview d'un de mes articles (compte Margot), il y a les annotations d'un autre article (autre compte). 
L'annotateur n'avait pas accès à mon article et a bien annoté l'autre article si l'on va voir sa page Hypothesis. 

https://user-images.githubusercontent.com/40469215/156194353-3e12ac1a-0637-41c3-abad-be56e96b3d0f.mp4

Cela ne le fait pas pour tous les articles mais on a noté un autre cas de ce phénomène.

**Comment by ggrossetie** [comment]
Merci d'avoir pris le temps de faire une vidéo ça permet de rapidement trouver la cause du problème. 
Je pense que c'est parce que la balise meta `dc:identifier` est identique entre les deux articles :

```html
<meta property="dc:identifier" content="2104-3272">
```

Pour la prochaine fois, pense à ajouter le lien vers les articles ça permet en un clic d'aller voir la prévisualisation ou de copier/coller l'identifiant pour récupérer des informations dans la base de données.

- https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/6217b9eb5aeb010013e41f1a?preview=true
- https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/61a5345183301d0013ed7940?preview=true

**Comment by ggrossetie** [comment]
Le template utilise la valeur de `ISSN` pour renseigner cette balise : 

https://framagit.org/stylo-editeur/templates-stylo/-/blob/master/templateHtml5-preview.html5#L66


![image](https://user-images.githubusercontent.com/333276/156198017-3a38076c-6a8e-439b-b029-e4f4d9f2c461.png)

**Comment by ggrossetie** [comment]
Et la documentation Hypothesis sur le sujet : https://web.hypothes.is/help/how-to-establish-or-avoid-document-equivalence-in-the-hypothesis-system/

> Resilience to URL change
There are three change-resilient ways for Hypothesis to associate annotations with documents:
> (...)
> For other HTML documents: If the target is neither an HTML page with a DOI nor a PDF, Hypothesis can use the dc.identifier / dc.relation.ispartof syntax. An example URL-independent identifier: urn:x-dc:elifesciences.org/blog-article/e3d858b3.

**Comment by Mmellet** [comment]
Ok pour les liens à fournir à l'avenir, 

Cependant je ne suis pas sûre de comprendre et je m'excuse par avance si tu y as répondu : l'ISSN est commun à tous les articles sens public, mais le problème ne se pose pas pour tous les articles. Pourquoi ceux-là ? Pourquoi maintenant ? dans la mesure où on fonctionne comme ça depuis longtemps.

**Comment by ggrossetie** [comment]
>  l'ISSN est commun à tous les articles sens public, mais le problème ne se pose pas pour tous les articles. Pourquoi ceux-là ? Pourquoi maintenant ? dans la mesure où on fonctionne comme ça depuis longtemps.

C'est une bonne question mais je n'ai pas la réponse 😅 
Soit ce n'est pas la source du problème, soit Hypothesis a modifié l'ordre de priorité pour prendre en priorité `dc.identifier` plutôt que l'URL, soit il y a une configuration/utilisation particulière sur ces articles qui fait que le problème ne se reproduit pas sur les autres articles.

> l'ISSN est commun à tous les articles sens public

Dans ce cas il ne faudrait pas utiliser l'ISSN en tant que `dc.identifier` car l'identifier doit être unique (d'après ce que je comprends de la documentation d'Hypothesis)

**Comment by ggrossetie** [comment]
On peut voir que dans la requête de récupération des annotations envoyées à Hypothesis (par le script Hypothesis) il y a deux URI:

```
uri: https://stylo.ecrituresnumeriques.ca/api/v1/htmlVersion/61a5345183301d0013ed7940?preview=true
uri: urn:x-dc:true/2104-3272
```

Ce qui tend à confirmer mon hypothèse. On peut d'ailleurs retrouver les annotations de `dbelanger` si on consulte l'API Hypothesis en utilisant `urn:x-dc:true/2104-3272` : https://hypothes.is/api/search?limit=50&sort=created&order=asc&_separate_replies=false&group=__world__&uri=urn%3Ax-dc%3Atrue%2F2104-3272

La valeur `true` correspond à `dc.relation.ispartof` qui malheureusement n'est pas correctement configuré dans le template et prend la valeur "true" :

https://framagit.org/stylo-editeur/templates-stylo/-/blob/master/templateHtml5-preview.html5#L56

**Comment by ggrossetie** [comment]
J'arrive à reproduire ce comportement en créant un nouvel article et en lui assignant le ISSN `2104-3272` : 


![issn](https://user-images.githubusercontent.com/333276/156211229-ca1d039d-2146-4645-8b20-1d705352d319.gif)

https://stylo.huma-num.fr/article/621e4ceb5aeb010013e41fb5/preview

**Comment by loup-brun** [comment]
**EDIT**: La balise ISSN serait peut-être `isPartOf`? La balise ressemblerait à `<meta property="dcterms:isPartOf" content="urn:ISBN:<numéro>" >`, voir Example 1 Journal article :

https://www.dublincore.org/specifications/dublin-core/dc-citation-guidelines/

**Comment by antoinentl** [comment]
A minima, sur vos suggestions très justes @loup-brun et @Mogztter, il faut modifier le template de la preview pour utiliser `<meta property="dcterms:isPartOf" content="urn:ISBN:<numéro>: >`, je m'en occupe.

**Comment by antoinentl** [comment]
J'ai mis à jour le template (attention il s'agit de la branche `book`) : https://framagit.org/stylo-editeur/templates-stylo/-/blob/book/templateHtml5-preview.html5#L66 @Mogztter tu me diras si tu peux récupérer cela et quand tu peux merger : peut-être faire un passage par stylo-dev pour tester (on n'est jamais trop prudent).

**Comment by ggrossetie** [comment]
Le submodule git utilise déjà la branche `book`. Je vais faire une mise à jour pour utiliser le dernier commit et déployer en dev.

J'ai aussi quelques doutes sur l'utilisation de `url_article` en tant que `dc.identifier`.
Il me semble que sur certains articles la valeur est `/articles/1515`. 
Si le `isPartOf` ne contient pas un domaine unique on peut rapidement se retrouver avec des doublons.

Je pense que c'est une bonne idée de s'affranchir de l'URL quand on travaille avec Hypothesis mais il faut absolument s'assurer que l'identifiant sera unique.

Je ne suis pas sûr qu'on devrait laisser l'utilisateur renseigner le `dc.identifier` et `isPartOf` ou alors il faudrait être très explicite sur le formulaire afin de s'assurer que l'utilisateur renseignera quelque chose d'unique (sous peine de voir apparaître des annotations Hypothesis d'autres utilisateurs sans aucun rapport).

À défaut, on peut utiliser l'identifiant de l'article stylo en tant que `dc.identifier` avec un `isPartOf` qui correspond au nom de l'application `stylo`. On peut même rajouter le domaine pour être sûr que ça soit unique `ecrituresnumeriques.ca/stylo`.

**Comment by ggrossetie** [comment]
Un exemple d'utilisation trouvé dans la documentation Hypothesis :

```html
<meta name="dc.identifier" content="blog-article/e3d858b3″>
<meta name="dc.relation.ispartof" content="elifesciences.org">
```

Dans notre cas on aurait :

```html
<meta name="dc.identifier" content="stylo/article/e3d858b3″>
<meta name="dc.relation.ispartof" content="ecrituresnumeriques.ca">
```

Qui nous donne l'identifiant unique :

```
urn:x-dc:ecrituresnumeriques.ca/stylo/article/e3d858b3
```

**Comment by ggrossetie** [comment]
Mise à jour du submodule git dans https://github.com/EcrituresNumeriques/stylo/commit/46f230f0abd34ea3d00dbd006a298c1e9549a0d8. C'est en cours de déploiement sur https://stylo-dev.huma-num.fr/

**Comment by ggrossetie** [comment]
@antoinentl Dans le template, on utilise `dc:relation.isPartOf` et `DC.relation.isPartOf`, est-ce qu'il y a une raison ?

**Comment by ggrossetie** [comment]
Je confirme qu'on peut à présent utiliser le même `ISSN` sans partager les annotations mais on peut reproduire le soucis en utilisant la même valeur pour "URL of the article":

![image](https://user-images.githubusercontent.com/333276/156324047-fdf2c7ae-0397-4ddd-8628-a3e9819897f4.png)


Une petite vidéo où je récupère les annotations d'un autre article en utilisant le même "URL of the article" : 

![annotation-url](https://user-images.githubusercontent.com/333276/156324542-de15f481-d547-44fa-a788-b6a4b5e92814.gif)

**Comment by antoinentl** [comment]
Pour résumer, et pour _patcher_ rapidement :

- ta solution @Mogztter me semble être la bonne : on regarde comment l'implémenter dans tous les templates et pas que la preview
- on ne peut pas récupérer l'identifiant _facilement_ pour l'injecter via le template preview, on regarde comment implémenter ça à terme
- pour l'instant je supprime les mentions de `dcterms:isPartOf` et de `DC.identifier` par sécurité, comme ça on force Hypothesis à ne prendre en compte que l'URL.

Ça te semble pertinent @Mogztter ? Merci pour tout ça !

**Comment by ggrossetie** [comment]
@antoinentl oui je pense que c'est la bonne solution si vous n'avez pas d'identifiant unique il est préférable de supprimer `dcterms:isPartOf` et de `DC.identifier`. Dans un second temps on pourra voir comment passer ces informations au service d'export/preview.

**Comment by antoinentl** [comment]
C'est disponible sur `templates-stylo`, @Mogztter tu me diras si ça peut être déployé bientôt :pray:
