### ISSUE TITLE
Impossible d'afficher la liste des articles : message d'erreur après connexion

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#577]
Actuellement lorsque je me connecte à Stylo un message s'affiche avec le message suivant :

> Error: Executor error during find command :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.

![Capture d’écran de 2022-03-09 14-18-21](https://user-images.githubusercontent.com/6869488/157515630-33f6b70b-fb7f-416c-8a2e-d9da96579ccd.png)

Et la liste des articles n'est pas affichée.

**Comment by antoinentl** [comment]
J'ai l'impression que cette erreur apparaît avec un compte non-huma-num :thinking:

**Comment by ggrossetie** [comment]
D'après l'erreur c'est MongoDB qui refuse de faire un tri. La solution préconisée est d'ajouter des index. J'ai ajouté en production les index suivants : 

```
db.articles.createIndex({ 'updatedAt': -1 })
db.tags.createIndex({ 'name': -1 })
db.tags.createIndex({ 'createdAt': -1 })
db.versions.createIndex({ 'createdAt': -1 })
```

Cela correspond aux champs sur lesquels on fait des tris.

**Comment by ggrossetie** [comment]
Je laisse ouvert pour qu'on inclus la création des index dans des scripts (ou au démarrage du serveur)

**Comment by thom4parisot** [comment]
En vrai y'a peut-être des champs sur lequel on fait des `.find()` à indexer également. Je ne me rends pas compte.

**Comment by ggrossetie** [comment]
Oui je pense que ça peut améliorer les performances dans certains cas. Par exemple on peut rajouter un index sur le `Tag.owner` et `Article.owner`. On peut aussi voir comment ajouter un index sur `Article.contributors` et `User.permissions`.

Il me semble que les champs uniques (comme `User.email`) sont déjà indexés.
