### ISSUE TITLE
Partage et Suppression impossibles sur compte en passerelle

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#578]
Je ne sais plus exactement ce que l'on s'était dit mais : 

pour les comptes en passerelles (exemple je suis sur mon compte personnel Margot et j'ai accès au compte de Sens public) lorsque je sélectionne senspublic dans ma page article à partir de mon compte stylo Margot, je ne peux pas ni supprimer ni partager les articles. 

![Screenshot 2022-03-10 at 08-56-20 Stylo](https://user-images.githubusercontent.com/40469215/157678484-ceb4421e-d1af-4ef3-b0a0-9ad27065fc80.png)

Cela pose un peu des difficultés pour notamment des comptes de type revues : pour la coordination de la revue, la personne pour partager/supprimer un article doit se déconnecter de son compte personnel et se reconnecter avec le compte de la revue. 

Pour le partage d'articles (qui est assez fréquent pour une revue) cela complexifie un peu la démarche (pour le cas de la suppression, cela me semble moins grave si cela reste en l'état mais j'aimerai savoir ce que @antoinentl  en pense).

**Comment by thom4parisot** [comment]
Ok, on peut considérer qu'un compte en passerelle a les mêmes droits que si c'était l'auteur·ice de l'article 👍🏻

**Comment by ggrossetie** [comment]
> pour les comptes en passerelles (exemple je suis sur mon compte personnel Margot et j'ai accès au compte de Sens public) lorsque je sélectionne senspublic dans ma page article à partir de mon compte stylo Margot, je ne peux pas ni supprimer ni partager les articles.

J'ai l'impression que dans ce cas on est dans de la delegation d'accès plus que dans du partage d'articles. Pourquoi est-ce que senspublic te donne les droits de suppression sur *ses articles*? Pourquoi est-ce que tu veux partager un article de senspublic qui ne t'appartient pas à d'autres personnes?
Je me fais l'avocat du diable pour être sûr de bien comprendre l'organisation actuelle et le flux de travail.

> Cela pose un peu des difficultés pour notamment des comptes de type revues : pour la coordination de la revue, la personne pour partager/supprimer un article doit se déconnecter de son compte personnel et se reconnecter avec le compte de la revue.

Cela veut dire que le compte "revue" n'est pas vraiment associé à une personne. J'ai l'impression que c'est plus une façon d'organiser/de regrouper un ensemble d'articles ?
Autrement dit, est-ce que si tu pouvais regrouper *tes articles* dans un dossier "senspublic" et partager ce dossier avec une personne de senspublic, est-ce que tu aurais besoin d'avoir accès au compte "senspublic"?

> Pour le partage d'articles (qui est assez fréquent pour une revue) cela complexifie un peu la démarche (pour le cas de la suppression, cela me semble moins grave si cela reste en l'état mais j'aimerai savoir ce que @antoinentl en pense).

Peut être que tu as deux casquettes et donc deux comptes sur lesquels tu jongles afin d'administrer les articles de senspublic (que tu dois l'autrice ou non de l'article) et ton compte personnel ?

**Comment by Mmellet** [comment]
>J'ai l'impression que dans ce cas on est dans de la delegation d'accès plus que dans du partage d'articles. Pourquoi est-ce que senspublic te donne les droits de suppression sur ses articles? Pourquoi est-ce que tu veux partager un article de senspublic qui ne t'appartient pas à d'autres personnes?
Je me fais l'avocat du diable pour être sûr de bien comprendre l'organisation actuelle et le flux de travail.

En fait dans le cadre d'une utilisation de Stylo type revue, c'est systématique qu'on veuille partager des articles à d'autres personnes. Ce n'est pas vraiment une question de "ce qui t'appartient ou non". Cas d'usage le plus courant :  

Margot a un compte personnel stylo. Margot est coordinnatrice de la revue Sens public. Sens public donne donc accès à Margot à son compte (passerelle) pour que Margot puisse coordonner les articles depuis son compte sans avoir à se déconnecter et se reconnecter sur le compte de la revue. 
Dans la chaine de publication d'un article, Margot va être amené à partager un article du compte de la revue avec d'autres personnes, notamment des éditeurs pour qu'ils modifient l'article, en fassent l'édition, etc. 
On est d'accord que l'article *appartient* toujours à Sens public, c'est juste qu'il est géré par des comptes personnels (Margot coordinnatrice). 

>Cela veut dire que le compte "revue" n'est pas vraiment associé à une personne. J'ai l'impression que c'est plus une façon d'organiser/de regrouper un ensemble d'articles ?
Autrement dit, est-ce que si tu pouvais regrouper tes articles dans un dossier "senspublic" et partager ce dossier avec une personne de senspublic, est-ce que tu aurais besoin d'avoir accès au compte "senspublic"?

Le compte revue n'est en effet pas associé à une personne *réelle*, c'est plus une entité qui regroupe des articles en effet. 

Ce que tu proposes en fait me semble problématique : même si on peut le voir comme un regroupement, le compte de sens public est aussi un compte avec lequel les auteurs peuvent partager leur articles comme mode de soumission. On pourra en reparler mais il me semble important de conserver le type compte stylo revue.

**Comment by ggrossetie** [comment]
> Ce que tu proposes en fait me semble problématique : même si on peut le voir comme un regroupement, le compte de sens public est aussi un compte avec lequel les auteurs peuvent partager leur articles comme mode de soumission. On pourra en reparler mais il me semble important de conserver le type compte stylo revue.

Pourquoi est-ce que cela te semble problématique ?
Je trouve au contraire assez intéressant de faire la distinction entre un partage d'article entre compte utilisateurs Stylo et la soumission d'un article à une revue (organisation).
Actuellement, on utilise un partage d'article alors qu'on veut soumettre un article à une revue et on donne accès à son compte alors qu'on veut ajouter une personne en tant que coordinatrice d'une revue.

D'ailleurs tu parles de "compte stylo de type revue" comme pour faire la distinction avec les "comptes stylo classique/utilisateur" ? On est donc sur un cas d'usage différent mais on utilise le même concept de compte utilisateur.

Cela dit, ce n'est probablement pas quelque chose que l'on pourra mettre en place dans un future proche mon but était surtout de mieux comprendre le cas d'usage et que tu puisses éventuellement imaginer les possibilités offertes si on organisait les choses un peu différemment.

**Comment by Mmellet** [comment]
Je disais problématique dans l'éventualité où on déciderait de gérer les articles sens public uniquement avec des tags et des partages, et d'abandonner/supprimer le compte "sens public". 

C'est intéressant ce que tu dis parce qu'en effet pour le cas d'une revue, on utilise les fonctionnalité de partage de compte ou d'article dans des sens différents.
