### ISSUE TITLE
Serveur https://stylo.ecrituresnumeriques.ca actuellement down (502)

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#579]
Le (bout de) serveur `https://stylo.ecrituresnumeriques.ca` est actuellement indisponible (erreur 502), ce qui signifie que les preview de Stylo ne fonctionnent pas, c'est-à-dire que la prévisualisation ne s'affiche pas et renvoie une page indiquant une erreur 502.

**Comment by thom4parisot** [comment]
Je suis connecté dessus à l'instant même.

![image](https://user-images.githubusercontent.com/138627/157688975-0a522b54-f26f-4309-bac0-7861d5225bc7.png)


Techniquement stylo.ecrituresnumeriques.ca est physiquement le même serveur que stylo.huma-num.fr.

Si ça ne fonctionne pas à cette heure-ci, et que tu as un VPN, tu peux tester depuis un autre pays ?

**Comment by antoinentl** [comment]
Mon explication n'était pas claire, désolé, il s'agit plus spécifiquement de la preview, exemple : [https://stylo.huma-num.fr/article/622a19220f5acb0012d1fa9f/preview](https://stylo.huma-num.fr/article/622a19220f5acb0012d1fa9f/preview)

Et résultat :

![Capture d’écran de 2022-03-10 10-31-10](https://user-images.githubusercontent.com/6869488/157695822-8b84b699-1537-4b4c-9936-241ee3fdc720.png)

**Comment by thom4parisot** [comment]
Okay ! Effectivement le service est tombé. Je viens de le relancer — il va peut-être retomber à l'avenir, je ne sais pas encore dans quelles conditions.

@Mogztter l'erreur dans les logs : 

```
export-stylo     | ClientError: Cannot return null for non-nullable field RootQuery.article.: {"response":{"errors":[{"message":"Cannot return null for non-nullable field RootQuery.article.","locations":[{"line":2,"column":5}],"path":["article"]}],"data":null,"status":500,"headers":{}},"request":{"query":"query ($articleId: ID!) {\n    article (article:$articleId) {\n      _id\n      title\n\n      workingVersion {\n        bib\n        yaml\n        md\n      }\n    }\n  }","variables":{"articleId":"620e6e345aeb010013e41d82"}}}

…

export-stylo     | node:events:498
export-stylo     |       throw er; // Unhandled 'error' event
export-stylo     |       ^
export-stylo     |
export-stylo     | Error [ERR_STREAM_WRITE_AFTER_END]: write after end
export-stylo     |     at new NodeError (node:internal/errors:371:5)
export-stylo     |     at write_ (node:_http_outgoing:748:11)
export-stylo     |     at ServerResponse.write (node:_http_outgoing:707:15)
export-stylo     |     at Archiver.ondata (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:681:20)
export-stylo     |     at Archiver.emit (node:events:520:28)
export-stylo     |     at addChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)
export-stylo     |     at readableAddChunk (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)
export-stylo     |     at Archiver.Readable.push (/usr/src/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
export-stylo     |     at Archiver.Transform.push (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:139:32)
export-stylo     |     at Archiver.afterTransform (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:88:10)
export-stylo     | Emitted 'error' event on ServerResponse instance at:
export-stylo     |     at emitErrorNt (node:_http_outgoing:726:9)
export-stylo     |     at processTicksAndRejections (node:internal/process/task_queues:84:21) {
export-stylo     |   code: 'ERR_STREAM_WRITE_AFTER_END'
```

C'est pas encore clair dans ma tête pourquoi on écrit 2 fois la réponse… (peut-être une condition qui retourne 2 tentatives de `response.send()` ?

**Comment by ggrossetie** [comment]
@thom4parisot Est-ce que tu fais référence à ce bout de code ?

https://github.com/EcrituresNumeriques/stylo/blob/455ca3bc8d2c0c8ccbcc56eb89b2d8304615d05b/export/src/export.js#L245-L256

On avait mis ça en place car avec la notion de `workingVersion` on passe soit un identifiant de version, soit un identifiant d'article. De mémoire le service d'export "legacy" utilise cette route et pour éviter des changements côté Marcello on a mis en place cette verrue.

D'après l'erreur, je dirais que `620e6e345aeb010013e41d82` est un identifiant de version et non un identifiant d'article, c'est la raison pour laquelle on a l'erreur `Cannot return null for non-nullable field RootQuery.article.` car l'article n'est pas trouvé.
On passe donc dans le `catch` et l'exception est de type `FindByIdNotFoundError`. On récupère la version et on tente de renvoyer un zip dans la réponse. Apparemment la réponse (stream) est déjà fermée et on ne peut pas écrire dedans mais je ne sais pas l'expliquee...

**Comment by thom4parisot** [comment]
Je crois que j'ai capté : 

- `createZipArchive()` doit surement générer une erreur, ce qui fait entrer dans ce bloc: https://github.com/EcrituresNumeriques/stylo/blob/455ca3bc8d2c0c8ccbcc56eb89b2d8304615d05b/export/src/export.js#L192-L194
- les fonctions `exportXxxYYY()` contiennent un `try/catch`, dont le `catch()` contient un `errorHandler()` qui tente d'écrire la réponse (à nouveau)

**Comment by VanessaClothildeB** [comment]
![erreur502_stylo](https://user-images.githubusercontent.com/101780868/158727922-ca829ed8-1d7e-434d-8aac-b0137854f058.JPG)
Bonsoir,
j'ai eu une erreur 502 quand je cliquais sur _Connect with Huma-Num_ au niveau de la page d'accueil _Welcome to Stylo _ (le login de Stylo en fait). Ça vient juste de se débloquer, vers 23h (après une heure de stress et de tragédie). Je suis au Canada, à Montréal. C'était juste pour le signaler.
En m'excusant du dérangement,
Bon courage!
Vanessa
