### ISSUE TITLE
Mélange entre Comptes partagés et partages 

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#580]
On a remarqué une chose étrange : 

![Capture d’écran, le 2022-03-10 à 15 45 05](https://user-images.githubusercontent.com/40469215/157687399-65d2ea1e-8eee-4f0d-a471-9a45d146fbd5.png)

Dans les partages de l'article sont mélangés : 

- les comptes stylo avec lesquels l'article "1625" a été partagé (du type Romain Roszak)
- les comptes qui ont accès au compte stylo de sens public (du type Margot Mellet) 

Ça me semble charger beaucoup l'article, je serai pour conserver seulement les comptes avec lesquels l'article a été partagé

**Comment by thom4parisot** [comment]
C'est exactement ce qu'il se passe.

C'est un bout de logique auquel on n'avait pas repensé depuis #555, facile à mettre en œuvre.
