### ISSUE TITLE
Preview de l'application Stylo via Netlify : impossible d'accéder à la liste des articles

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#581]
Lorsque je tente de me connecter aux versions de Stylo en _prévisualisation_ sur les environnements de démo sur Netlify, j'arrive sur cette erreur :

![Capture d’écran de 2022-03-10 11-11-46](https://user-images.githubusercontent.com/6869488/157706288-57bcfc1b-3f27-4e75-a36c-9ba8f62de5e3.png)

**Comment by thom4parisot** [comment]
J'ai `git rebase` la branche de #550 pour qu'elle soit calée sur les récents développements.

L'erreur n'apparait plus.

**Comment by antoinentl** [comment]
Merci ! Est-ce que tu me donner la liste des commandes Git pour le `git rebase`, j'aimerai essayer de faire cette modif sur la branche/pr 512 :)

**Comment by thom4parisot** [comment]
```
git remote add Mogztter https://github.com/Mogztter/stylo.git
git fetch Mogztter issue-271-autocompletion
git switch --track Mogztter/issue-271-autocompletion
git fetch origin
git rebase origin master
```

Et ensuite pour repousser chez Guillaume, je suis moins sûr, pas essayé 🙈  : 

```
git push Mogztter issue-271-autocompletion
```

**Comment by antoinentl** [comment]
Merci !

**Comment by ggrossetie** [comment]
@antoinentl je viens de faire le rebase de https://github.com/EcrituresNumeriques/stylo/pull/512
