### ISSUE TITLE
Duplicate article with the wrong permission

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#585]
Lorsque j'affiche les articles de mon compte HumaNum, et que je souhaite dupliquer un article, la copie de l'article est créée sous un autre compte Stylo (email personnel). Pour m'en rendre compte, il me faut basculer d'un compte vers l'autre.

_note: don't close this issue too fast, it makes open issues a round number (100)_

**Comment by thom4parisot** [comment]
Ce que je comprends, c'est que tu as basculé sur un autre compte (compte B), mais la duplication se fait au nom du compte A. C'est ça ?

**Comment by lakonis** [comment]
Exactement.
