### ISSUE TITLE
Révoquer un partage alors qu'une personne est connecté en ce nom plante l'interface

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#588]
![image](https://user-images.githubusercontent.com/138627/158574093-5609b2c3-446d-4e71-8cc4-694607e8bf9c.png)

**Comment by ggrossetie** [comment]
Surement parce qu'on a encore le compte partagé dans le localStorage c'est ça ?

**Comment by thom4parisot** [comment]
Exactement, et on n'a pas prévu de roue de secours 🚗

**Comment by thom4parisot** [comment]
Ce n'est plus d'actualité avec les workspaces.
