### ISSUE TITLE
Appuyer sur la touche ESC/ECHAP ferme une modale ouverte

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#591]
Aujourd'hui il faut cliquer sur la croix en haut à droite de la modale, ou sur un bouton "Cancel".

Dans le composant `Modal.jsx`, j'imagine qu'il faudrait

- souscrire aux événements clavier de `window.document` dans un `useEffect()`
- si une touche identifiée comme étant ESC/ECHAP, la fonction `cancel()` est appelée
- annuler l'écouter des événements clavier dans la fonction de nettoyage du `useEffect()` ([cf. example](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1))

**Comment by antoinentl** [comment]
À ma connaissance toutes les modales peuvent désormais être fermées avec la touche ESC/ECHAP and it's beautiful :keyboard:
