### ISSUE TITLE
Problème dans la numérotation des versions

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#597]
ON a remarqué un petit bug dans la numérotation des versions : comme c'est un peu compliqué à expliquer je mets une capture : 
![Screenshot 2022-03-22 at 08-55-31 Stylo](https://user-images.githubusercontent.com/40469215/159487057-0b592125-a8de-4b01-8dcd-92a3338f5b67.png)

**Comment by thom4parisot** [comment]
J'en déduis que si tu écris un libellé de version, l'incrément de numéro ne se fait pas ?

**Comment by Mmellet** [comment]
l'incrémentation se fait si je fais une majeure (on passe de 0.1 à 1.0) mais quand je fais une mineure dessus : on passe de 1.0 à 0.2, et si je fais une mineure dessus une mineure : 0.2 sur 0.2

**Comment by thom4parisot** [comment]
Okay compris, merci 🙂

**Comment by ggrossetie** [comment]
Je dirais que c'est lié au fait que les versions ne sont pas triées ici: 

https://github.com/EcrituresNumeriques/stylo/blob/fb861eaf19528408b288bb77466c6b93aac6a873/graphql/resolvers/versionResolver.js#L23

Ou plus précisément la "dernière version" (dans le tableau) est _toujours_ la première version `0.1`, donc si on crée une version majeure on passe à 1.0 et si on crée une version mineure on passe à 0.2. On reste toujours à 1.0 ou 0.2 car on part toujours de la version 0.1.

Solution : trier les versions de la plus récente à la plus ancienne ici : 

https://github.com/EcrituresNumeriques/stylo/blob/fb861eaf19528408b288bb77466c6b93aac6a873/graphql/models/article.js#L90

En utilisant cette syntaxe : 

https://github.com/EcrituresNumeriques/stylo/blob/b9b47776817d1c4ce054c90557f09fb505ee5a54/graphql/models/article.js#L80
