### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#6]
Le versionnage a n comportement bizare. Plusieurs versions avec le même nom (par ex 0.1) sont produites si on continue à travailler sur une version sans la sauvegarder avec un nouveau nom.

**Comment by PookMook** [comment]
![image](https://user-images.githubusercontent.com/14223903/40854431-6f5232fe-659f-11e8-93ac-bba6d8838e66.png)

**Comment by ggrossetie** [comment]
Je ferme, si le ou les problèmes sont encore présents il faudrait détailler précisément les étapes permettant de les reproduire.
