### ISSUE TITLE
Pouvoir partager un article qui nous  a été partagé

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#612]
Lorsqu'un article est partagé du compte A au compte B, il faut que le compte B puisse le partager à son tour (avec C par exemple) : nous sommes dans une optique d'édition ouverte, et donc nous ne souhaitons pas limiter les usages. (Nous comprenons les potentiels problèmes que cela pourrait poser, par exemple le fait que A ne choisit pas de partager son article avec C.)

**Comment by ggrossetie** [comment]
j'espère que https://github.com/EcrituresNumeriques/stylo/commit/7d1820ffe6c546d8751905262e7163d1833c04e1 est suffisant

**Comment by Mmellet** [comment]
j'ai des difficultés à partager : 

![Screenshot from 2022-04-13 13-27-36](https://user-images.githubusercontent.com/40469215/163236952-ad77207e-9f7b-45cc-9e81-7be79ed30159.png)

**Comment by ggrossetie** [comment]
Mince on doit faire un contrôle côté serveur :/
Je pense que l'article n'est pas trouvé car tu n'es pas l'autrice (i.e., c'est un article qu'on t'a partagé).

**Comment by ggrossetie** [comment]
comme mentionné dans https://github.com/EcrituresNumeriques/stylo/issues/615 cela pose aussi des problèmes car la liste des contacts est celle de l'utilisateur connecté (et non la liste des contacts associé au compte qui nous a partagé ces articles).

**Comment by antoinentl** [comment]
En dehors de #615 il faudrait que l'on puisse partager un article qui nous a été partagé, c'est un besoin urgent.

**Comment by ggrossetie** [comment]
Je ne reproduis pas l'anomalie sur https://stylo.huma-num.fr/.

J'ai deux comptes ggrossetie et grossetie2.

- ggrossetie2 partage ces articles avec ggrossetie.
- je me connecte avec ggrossetie (je peux donc voir les articles de ggrossetie2)
- je repartage un article de ggrossetie2 avec margot

![repartage](https://user-images.githubusercontent.com/333276/166650328-89ef0996-7524-4f3f-9e53-e3568dc28bfa.gif)

@Mmellet @antoinentl Est-ce que vous pouvez tester de votre côté et décrire précisément le scénario qui ne fonctionne pas ?

**Comment by ggrossetie** [comment]
Je viens de réussir à reproduire l'anomalie !
Il faut pour cela 3 utilisateurs. Prenons Margot, Antoine et Thomas:

- Margot partage l'ensemble de ces articles avec Antoine.
- Antoine partage l'ensemble de ces articles avec Thomas.
- Thomas va voir les articles d'Antoine avec les articles de Margot (par effet de cascade).
- Si Thomas tente de repartager un article de Margot il aura une erreur. Par contre il peut repartager un article d'Antoine.

Pour résumé, on ne partage pas uniquement *ses* articles, on partage l'ensemble des articles auxquels on a le droit. Est-ce que vous souhaitez conserver ce fonctionnement ou est-ce que le partage doit se limiter à *ses* articles ?

L'affichage des articles sur le compte de Thomas sera un peu particulier. Dans le menu déroulant, Thomas peut choisir d'afficher les articles d'Antoine mais dans la liste on a aussi l'article de Margot : 

![image](https://user-images.githubusercontent.com/333276/166655642-17e19675-9704-43a0-a2d8-e0ece80d5f6e.png)

**Comment by ggrossetie** [comment]
Voici les changements que je préconise afin de régler les anomalies rencontrées concernant le partage des articles tout en conservant la logique de la fonctionnalité :

- La duplication d'un article se fera toujours avec l'utilisateur connecté (i.e. qu'on duplique un de ses articles ou un article qu'on nous a partagé l'article, on en devient le propriétaire)
- La création d'un article se fera toujours avec l'utilisateur connecté
- Les changements effectués sur un article se font toujours avec l'utilisateur connecté
- Le partage des articles concerne uniquement ses articles. Autrement dit, si Thomas partage ses articles avec Antoine et Antoine partage ses articles avec Margot, cette dernière ne verra que les articles d'Antoine.
   - On peut imaginer une nouvelle fonctionnalité permettant à Antoine de partager les articles de Thomas à Margot. Cette action aura pour effet d'ajouter Margot dans la liste des contacts de Thomas et d'activer le partage des articles. Thomas pourra voir que ces articles sont aussi partagés avec Margot.

**Comment by Mmellet** [comment]
@Mogztter Merci pour ces précisions, pour être sûre : comment définit-on "utilisateur connecté" ?

**Comment by ggrossetie** [comment]
> comment définit-on "utilisateur connecté" ?

@Mmellet c'est l'utilisateur qui s'est authentifié sur la page d'accueil de Stylo. L'utilisateur connecté ne change jamais sauf si on se déconnecte avec le bouton "Log out".

**Comment by antoinentl** [comment]
On reprend le travail sur ce bug. Déjà merci pour les explications très claires ici et là #615 !

## Résultat attendu
Pour reprendre l'exemple avec Thomas, Antoine et Margot :

- Thomas crée un article
- Thomas partage cet article avec Antoine
- Antoine doit pouvoir le partager avec Margot

Pour prolonger avec un autre exemple : Thomas, Antoine, Margot et Senspublic :

- Antoine crée un article
- Antoine partage cet article avec Senspublic
- Margot se connecte et change de compte pour sélectionner Senspublic
- Margot doit pouvoir le partager à Thomas sans se déconnecter de son compte tout en étant sur le compte de Senspublic (est-ce que c'est confus ?…). **Actuellement c'est ça qui n'est pas possible.**

Cette fonctionnalité est vraiment importante pour nous ! Il faut trouver un moyen de l'_activer_, quitte à changer une partie du fonctionnement actuel.

## Problèmes constatés
Margot ne peut pas partager à Thomas un article partagé avec elle par Antoine, lorsqu'elle est utilisateur connecté Margot mais en utilisant le compte Senspublic. Erreur indiquée : "Unable to find article"

## Questionnements
Est-ce que cela est lié à #615 ? Puisque l'erreur indiquée que l'article n'est pas trouvé et non que le contact de partage n'est pas dans la liste :thinking: 

Si c'est nécessaire d'en parler de vive voix on organise une visio :hugs:

**Comment by ggrossetie** [comment]
> Est-ce que cela est lié à https://github.com/EcrituresNumeriques/stylo/issues/615 ? Puisque l'erreur indiquée que l'article n'est pas trouvé et non que le contact de partage n'est pas dans la liste 🤔

Oui c'est lié. 
Je pense qu'il faudrait déjà répondre à la question suivante afin de savoir comment on adresse ce problème: "Est-ce qu'on remplace la fonctionnalité de partage d'articles par une délégation de compte ? Est-ce qu'on ajoute une fonctionnalité supplémentaire afin de faire la distinction entre un partage d'articles et une délégation de compte ?"

Et si on repart sur une délégation de compte il faudra clarifier certains points notamment sur la gestion des contacts.

**Comment by ggrossetie** [comment]
Comme vu avec @antoinentl on reste sur un partage d'articles et non sur une délégation de compte.

D'un point de vue technique, le partage de l'ensemble des articles du compte est problématique par son aspect "récursif". Prenons un exemple, Antoine partage l'ensemble des articles de son compte avec Margot qui partage l'ensemble des articles de son compte avec Thomas.
Afin de récupérer la liste des articles auxquels Thomas a accès, il faut regarder si une personne partage son compte avec lui. Dans notre exemple, il s'agit de Margot. Puis de vérifier si une personne partage son compte avec Margot (ici, Antoine).
En résumé si on a 5 utilisateurs A, B, C, D et E qui partage leur compte : 

- A partage à B
- B partage à C
- C partage à D
- D partage à E

Il faut qu'on fasse 4 requêtes afin de récupérer l'ensemble des articles auxquels l'utilisateur E a accès.
Un autre façon de le représenter :
 
```
A -> B -> C -> D -> E
```

D'un point de vue fonctionnel, l'utilisateur A partage ces articles avec B mais ne sait pas qu'en réalité ces articles seront aussi partagé avec C, D et E.

Une solution alternative consiste à calculer la liste des personnes avec lesquels on va partager les articles de son compte au moment où on fait le partage.
Cela permet de conserver les relations de partage à plat.

```
A -> B,C,D,E
B -> C,D,E
C -> D,E
D -> E
E ->
```

Si E decide de partager ces articles avec F, on aura alors : 

```
A -> B,C,D,E,F
B -> C,D,E,F
C -> D,E,F
D -> E,F
E -> F
```

L'utilisateur A pourra voir que ces articles sont partagés à B, C, D, E et F.

Si Z décide de partager ces articles à A, on aura alors : 

```
A -> B,C,D,E,F,Z
B -> C,D,E,F,Z
C -> D,E,F,Z
D -> E,F,Z
E -> F,Z
Z ->
```

L'inconvénient c'est qu'on perd la notion de hiérarchie. Imaginons que Margot partage les articles de son compte avec Sens Public et que Sens Public partage les articles de son compte avec 50 personnes. Si Margot souhaite arrêter de partager les articles de son compte, il faut quelle annule le partage avec 51 personnes.

**Comment by ggrossetie** [comment]
Il y a la notion de `$graphLookup` qui pourrait permettre de reconstruire l'arbre des relations : https://www.mongodb.com/docs/manual/reference/operator/aggregation/graphLookup

**Comment by ggrossetie** [comment]
Voici un exemple de ce qu'on arrive à récupérer avec des `$graphLookup` et `$lookup`:

```json
{
  "_id": "636e494e916c4049de3be3f7",
  "sharedUserAccounts": [
    {
      "_id": "636e4922916c4049de3be3eb",
      "email": "antoine@domain.org",
      "displayName": "antoine"
    },
    {
      "_id": "636e493a916c4049de3be3f1",
      "email": "margot@domain.org",
      "displayName": "margot"
    },
    {
      "_id": "636e4c576b9e8a6528daabdf",
      "email": "roch@domain.org",
      "displayName": "roch"
    }
  ],
  "myArticles": [
    {
      "_id": "636e494e916c4049de3be3f8",
      "title": "Article Guillaume",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "contributors": [],
      "owner": "636e494e916c4049de3be3f7",
      "createdAt": "2022-11-11T13:08:30.762Z",
      "updatedAt": "2022-11-11T13:08:30.762Z",
      "__v": 0
    }
  ],
  "contributedArticles": [
    {
      "_id": "636e4922916c4049de3be3ec",
      "title": "Article Antoine",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "owner": "636e4922916c4049de3be3eb",
      "createdAt": "2022-11-11T13:07:46.681Z",
      "updatedAt": "2022-11-11T13:52:10.330Z",
      "__v": 1
    },
    {
      "_id": "636e575c30e176847140ccf5",
      "title": "Article Maiwann",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "owner": "636e575c30e176847140ccf4",
      "createdAt": "2022-11-11T14:08:28.643Z",
      "updatedAt": "2022-11-11T14:08:55.246Z",
      "__v": 1
    }
  ],
  "sharedUserArticles": [
    {
      "_id": "636e4922916c4049de3be3ec",
      "title": "Article Antoine",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "owner": "636e4922916c4049de3be3eb",
      "createdAt": "2022-11-11T13:07:46.681Z",
      "updatedAt": "2022-11-11T13:52:10.330Z",
      "__v": 1
    },
    {
      "_id": "636e493a916c4049de3be3f2",
      "title": "Article Margot",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "owner": "636e493a916c4049de3be3f1",
      "createdAt": "2022-11-11T13:08:10.370Z",
      "updatedAt": "2022-11-11T13:08:10.370Z",
      "__v": 0
    },
    {
      "_id": "636e4c576b9e8a6528daabe0",
      "title": "Article Roch",
      "zoteroLink": "",
      "versions": [],
      "tags": [],
      "owner": "636e4c576b9e8a6528daabdf",
      "createdAt": "2022-11-11T13:21:27.341Z",
      "updatedAt": "2022-11-11T13:21:27.341Z",
      "__v": 0
    }
  ],
  "contributedOwners": [
    {
      "_id": "636e4922916c4049de3be3eb",
      "email": "antoine@domain.org",
      "displayName": "antoine"
    },
    {
      "_id": "636e575c30e176847140ccf4",
      "email": "maiwann@domain.org",
      "displayName": "maiwann"
    }
  ]
}
```

Dans cet exemple `guillaume` avec l'identifiant `636e494e916c4049de3be3f7` demande la liste des articles auxquels il a accès.

- `guillaume` a crée un article avec l'identifiant `636e494e916c4049de3be3f8` et le titre "Article Guillaume", il apparaît dans la liste `myArticles`
- `antoine` a partagé de manière unitaire l'article  `Article Antoine` (id `636e4922916c4049de3be3ec`) avec `guillaume`
- `maiwann` a partagé de manière unitaire l'article `Article Maiwann` (id `636e4922916c4049de3be3ec`) avec `guillaume`
- ces deux articles apparaissent dans la liste `contributedArticles`

De plus :
- `antoine` partage l'ensemble de ces articles avec `margot`
- `margot` partage l'ensemble de ces articles avec `guillaume` et `antoine`
- `roch` partage l'ensemble de ces articles avec `guillaume`
- `maiwann` ne partage avec personne l'ensemble de ces articles

Chaque utilisateur a un seul article nommé `Article` et suffixé par le nom de l'utilisateur (i.e., `antoine` -> `Article Antoine`...).

Dans la liste `sharedUserArticles`, on retrouve : 
- l'article de `roch` car `roch` partage l'ensemble de ses articles avec `guillaume`
- l'article de `margot` car `margot` partage l'ensemble de ses articles avec `guillaume`
- l'article de `antoine` car `antoine` partage l'ensemble de ses articles avec `margot` qui partagent l'ensemble de ses articles avec `guillaume`


Les listes `sharedUserAccounts` et `contributedOwners` permettent d'avoir des informations sur les personnes qui nous ont partagé un article.

**Comment by thom4parisot** [comment]
> j'espère que [7d1820f](https://github.com/EcrituresNumeriques/stylo/commit/7d1820ffe6c546d8751905262e7163d1833c04e1) est suffisant

Après réévaluation du problème "ce matin", qualifié de bloquant parce que des personnes ont arrêté l'utilisation de Stylo car leur éditorialisation était impossible, ça ne suffit pas.

Parce que côté `async shareArticle()` on ne cherche l'article que sur son owner.
Je m'en occupe cette aprem 🙂

**Comment by ggrossetie** [comment]
À noter que les espaces de travail sont une façon de répondre à ce besoin et que normalement le (re)partage unitaire fonctionne.
Autrement dit, la fonctionnalité de partage de compte va disparaitre au profit de partage dans des espaces de travail.
