### ISSUE TITLE
Rafraichir la page nécessaire pour Revoke access d'un article

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#613]
Essayant de révoquer l'accès à un article, j'ai réalisé que pour le faire, il me fallait rafraîchir la page :

https://user-images.githubusercontent.com/40469215/162977729-a7bc11fe-5c70-42b9-805e-6b5f7dd308b4.mp4

**Comment by thom4parisot** [comment]
Ouaip bien vu, on ne raffraichit pas les données après coup avoir fermé la modale 👍🏻

**Comment by ggrossetie** [comment]
@thom4parisot tu as fais le changement/correctif récemment ? Je ne reproduis pas sur stylo-dev ou sur mon poste ? 🤔

**Comment by Mmellet** [comment]
de ce que j'ai vu c'est réglé dans stylo-dev :+1:  :fireworks:

**Comment by thom4parisot** [comment]
🙌🏻
