### ISSUE TITLE
Liste des comptes de partage

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#615]
Nous avons remarqué un élément concernant le fonctionnement du partage ou de l'envoi d'un article qui est dû au nouveau fonctionnement de passerelle entre compte : 

SI je suis sur mon compte et que je passe sur le compte par exemple revue sens public, pour le partage ou l'envoi d'un article la liste des comptes stylo qui m'est proposée n'est pas celle du compte sens public mais ma liste personnelle : 
![Capture d’écran, le 2022-04-14 à 20 18 37](https://user-images.githubusercontent.com/40469215/163466230-eacc5e12-d717-4f4b-acd4-6a5ff1628ec9.jpeg)
C'est un peu problématique dans l'optique de la gestion d'articles pour la revue, et puis cela semble créer l'incohérence que je pourrai partager ou envoyer un article à un compte alors depuis la liste des articles du même compte : dans l'exemple je pourrai partager l'article du compte sens public ... avec le compte sens public.

**Comment by ggrossetie** [comment]
On revient sur notre discussion à propos de la délégation d'accès. Nous avons implémenté un système qui permet de partager des articles mais ce que tu souhaites faire c'est gérer les articles à la place de Sens Public (ou en tant que Sens Public).

Il y a des similitudes entre les deux mais ce n'est pas le même cas d'utilisation. Par exemple, tu vas pouvoir ajouter des contacts au compte "Sens Public" ce qui va plus loin qu'un simple partage d'articles.

Est-ce qu'on remplace la fonctionnalité de partage d'articles par une délégation de compte ? Est-ce qu'on ajoute une fonctionnalité supplémentaire afin de faire la distinction entre un partage d'articles et une délégation de compte ?

**Comment by ggrossetie** [comment]
D'ailleurs, si on fait ça, comment est-ce que ça se passe si tu veux repartager un article de Sens Public avec _tes_ contacts ?

**Comment by thom4parisot** [comment]
Ce que je comprends c'est que quand on bascule sur un compte B, les contacts sont ceux associés à ce compte B, et non au compte A, à l'origine de la bascule.

**Comment by ggrossetie** [comment]
> Ce que je comprends c'est que quand on bascule sur un compte B, les contacts sont ceux associés à ce compte B, et non au compte A, à l'origine de la bascule.

Non je crois que c'est l'inverse, les contacts sont toujours ceux du compte avec lequel on est connecté. Si je visualise les articles du compte B (à partir du compte A), les contacts sont ceux associés au compte A.

**Comment by Mmellet** [comment]
> D'ailleurs, si on fait ça, comment est-ce que ça se passe si tu veux repartager un article de Sens Public avec _tes_ contacts ?

Je ne suis pas sûre de bien comprendre la question, est-ce que tu peux préciser ?

**Comment by antoinentl** [comment]
Pour préciser le scénario :

1. A se connecte à son compte Stylo
2. A change de _compte_ avec le menu déroulant pour choisir le compte B
3. elle souhaite partager des articles qui ont été partagés avec le compte B, avec la liste de contacts du compte B

Est-ce que c'est plus clair ?

**Comment by ggrossetie** [comment]
Oui je pense que c'est clair.

> Je ne suis pas sûre de bien comprendre la question, est-ce que tu peux préciser ?

Pour reprendre l'exemple d'Antoine, on va dire que le compte A a un contact : Thomas et que le compte B a deux contacts : Marie et Antoine.

Comme dans l'exemple d'Antoine A "change de compte" avec le menu déroulant pour choisir le compte B. À noter que ce n'est pas tout à fait exact car on ne change pas de compte, la fonctionnalité actuelle est d'afficher les articles du compte B tout en restant connecté avec le compte A mais passons.

Suite à ce "changement de compte", on imagine qu'on affiche les contacts de B (et non les contacts de A). Tu peux donc partager l'article de B avec les contacts de B comme par exemple avec Marie ou Antoine mais comment est ce que cela se passe si tu veux partager un article de B avec Thomas (qui est un contact de A) ? Je suppose que tu vas rajouter Thomas dans les contacts de B ?

**Comment by ggrossetie** [comment]
Comme vu avec @antoinentl c'est le comportement attendu. La liste des contacts sera toujours celle de l'utilisateur connecté. Autrement dit, on gère toujours sa liste de contacts et on partage toujours des articles avec sa liste de contacts.

> C'est un peu problématique dans l'optique de la gestion d'articles pour la revue, et puis cela semble créer l'incohérence que je pourrai partager ou envoyer un article à un compte alors depuis la liste des articles du même compte : dans l'exemple je pourrai partager l'article du compte sens public ... avec le compte sens public.

Effectivement, on va rajouter un contrôle afin de désactiver le partage dans ce cas précis.

**Comment by Mogztter** [comment]
Je viens de réussir à reproduire l'anomalie !
Il faut pour cela 3 utilisateurs. Prenons Margot, Antoine et Thomas:

- Margot partage l'ensemble de ces articles avec Antoine.
- Antoine partage l'ensemble de ces articles avec Thomas.
- Thomas va voir les articles d'Antoine avec les articles de Margot (par effet de cascade).
- Si Thomas tente de repartager un article de Margot il aura une erreur. Par contre il peut repartager un article d'Antoine.

Pour résumé, on ne partage pas uniquement *ses* articles, on partage l'ensemble des articles auxquels on a le droit. Est-ce que vous souhaitez conserver ce fonctionnement ou est-ce que le partage doit se limiter à *ses* articles ?

L'affichage des articles sur le compte de Thomas sera un peu particulier. Dans le menu déroulant, Thomas peut choisir d'afficher les articles d'Antoine mais dans la liste on a aussi l'article de Margot : 

![image](https://user-images.githubusercontent.com/333276/166655642-17e19675-9704-43a0-a2d8-e0ece80d5f6e.png)

**Comment by ggrossetie** [comment]
Il y a aussi un autre "problème" concernant le fait de révoquer un accès.
Exemple avec Margot, Antoine, Thomas et Guillaume : 

- Margot partage un article avec Antoine et Thomas
- Antoine repartage l'article de Margot avec Guillaume
- Guillaume a comme contact Antoine et Thomas
- Guillaume révoque l'accès d'Antoine et Thomas

L'article de Margot initialement partagé avec Antoine et Thomas est maintenant partagé uniquement avec Guillaume. Margot n'ayant pas Guillaume dans sa liste de contact elle ne peut même pas lui révoquer l'accès !

À noter qu'on ne conserve pas l'information de qui à partager à qui.

**Comment by ggrossetie** [comment]
Je viens aussi de voir un autre problème. Imaginons deux utilisateurs, Thomas et Antoine : 

- Thomas partage ses articles avec Antoine.
-  Antoine se connecte et consulte les articles de Thomas.
- Guillaume duplique un article de Thomas (l'auteur de l'article dupliqué est Thomas)
- Impossible de supprimer l'article dupliqué (avec erreur "Unable to find article")

**Comment by ggrossetie** [comment]
Je me rends compte aussi que lorsque l'on consulte les articles d'un autre compte et que l'on crée un nouvel article, le nouvel article sera crée en tant que cet utilisateur. Par exemple :

- Thomas partage ces articles avec Antoine
- Antoine se connecte à son compte et consulte les articles de Thomas
- Antoine crée un nouvel article, l'auteur sera "Thomas" et l'article apparaîtra dans les articles de Thomas
- Si Antoine se positionne sur ces articles, alors l'article sera crée avec l'auteur "Antoine"
