### ISSUE TITLE
Personnalisation du nouvel éditeur de code Monaco

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#622]
Lister les choix à faire ici.

**Comment by RochDLY** [comment]
Le nouvel éditeur fonctionne très bien, les seuls couacs que je trouve sont au niveau des volets sur les côtés de l'éditeur : 

- Les volets mordent un peu sur l'editeur, il y a peu de marges à gauche et à droite.
![screenshot-1](https://user-images.githubusercontent.com/43650596/167421313-c6b7ccc6-5961-4549-89b4-8d58a172db1c.png)

- Dans le diff (qui fonctionne très bien dans ce mode là), les volets mordent completement sur le texte : 
![screenshot-2](https://user-images.githubusercontent.com/43650596/167421498-5eb3fe83-6063-417b-b780-ea4c19fc7b2a.png)

- Enfin, toujours dans le diff, lorsqu'on enlève les volets, il n'y a plus de bouton visible pour stopper la comparaison, excepté dans le menu déroulant pour choisir la version à comparer. 
![screenshot-3](https://user-images.githubusercontent.com/43650596/167421741-e78b9435-e309-45fc-8717-3525398d3118.png)

**Comment by ggrossetie** [comment]
Merci pour ces retours !
Je n'ai pas passé trop de temps sur les volets car nous sommes en train de les modifier dans #500.

> il n'y a plus de bouton visible pour stopper la comparaison, excepté dans le menu déroulant pour choisir la version à comparer.

Concernant le diff, j'ai repris le fonctionnement actuel avec le "Stop compare" qui est dans la liste déroulante : 

![image](https://user-images.githubusercontent.com/333276/167447091-7405fe9d-13a3-485f-bedf-4af52879879c.png)

Mais effectivement je pense qu'il serait mieux d'avoir un bouton permettant de revenir sur l'article en édition. Invocation de @maiwann si tu as des recommendations sur le sujet 😉
