### ISSUE TITLE
Tests du nouvel éditeur de texte Monaco

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#623]
Depuis la v1.7.7 il est possible de choisir l'éditeur de texte Monaco au lieu de Codemiror, cela se passe dans https://stylo.huma-num.fr/credentials il y a une case à cocher "Use experimental text editor".

Merci d'indiquer ici vos commentaires, notamment :

- @marviro les temps de chargement et de réaction
- @RochDLY et @Mmellet les fonctionnalités de l'éditeur, et notamment vous pouvez afficher les nombreux raccourcis avec F11
- le rendu graphique

Précision : certaines fonctionnalités peuvent être désactivées, on va essayer de noter cela dans #622.

**Comment by Mmellet** [comment]
Je n'ai pas testé tous les raccourcis, mais jusqu'ici je n'ai pas de commentaires particuliers, j'aime bien

**Comment by lakonis** [comment]
Je suis super convaincu par cet éditeur, par les outils de search/replace :sunglasses:  qu'il propose (on retrouve le même module que dans Codium), et par le comparateur de version :heart_eyes:

**Comment by thom4parisot** [comment]
@Mogztter  Du coup on est bon ? Ou les commentaires de #622 font qu'on ne peut pas mettre Monaco en éditeur par défaut ?

**Comment by lakonis** [comment]
Si je peux intervenir, je pense que le problème des volets est indépendant de l'éditeur. Je me trompe peut-être. Monaco est une telle amélioration dans tous les cas.

**Comment by antoinentl** [comment]
On peut effectivement fermer cette issue, il reste du travail sur #622 pour préciser certains fonctionnements et affichages, ça n'a pas été fait par manque de temps…
