### ISSUE TITLE
Création d'un nouvel utilisateur depuis HumanID

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#628]
Bonjour !
J'ai ce monsieur qui me dit avoir fait sa demande d'accès à Stylo via son humanid.huma-num.fr mais je n'arrive pas à lui partager un document (rien ne se passe lorsque j'ajoute son email).
La demande d'accès est automatique pour Stylo il me semble, mais peut-être que l'utilisateur doit se connecter à stylo pour que son compte soit réellement créé ? Qu'en est-il ?  
Je peux fournir l'email en question en MP (ca existe sur github ?)

**Comment by ggrossetie** [comment]
Oui c'est exact, il faut une première connexion à Stylo (en cliquant sur le bouton "Connect with Huma-Num") pour que le compte soit créé sur Stylo.

**Comment by lakonis** [comment]
Merci! Je ferme.
