### ISSUE TITLE
Problèmes multiples liés à l'export en PDF

### ISSUE THREAD

**Issue by joseph-staline** [EcrituresNumeriques/stylo#629]
Pour une raison qui m'est inconnue, certains de mes documents Stylos exportés en pdf s'arrêtent subitement au bout de 4 pages, quels que soient les paramètres d'export que je choisis. Ouvrir un nouveau document et y copier-coller mon contenu fonctionne parfois, mais c'est souvent temporaire, et c'est plutôt rébarbatif.

Les quelques exports PDF de "books" que j'ai tentés étaient encore plus chaotiques : là aussi l'export est tronqué, il ne fait que 16 pages alors que mes documents assemblés doivent faire en gros 150 pages. De plus, le sens des chapitres semble être inversé, malgré le fait que je les ai numérotés et qu'ils s'affichent dans le bon ordre dans l'interface d'export. À noter que la prévisualisation du book inverse également l'ordre des chapitres.

<img width="511" alt="Screenshot 2022-06-13 at 19 48 24" src="https://user-images.githubusercontent.com/104915084/173413701-146f2f8d-8236-4aa5-a058-7c41966c7dbb.png">

J'avais déjà rencontré ces problèmes d'export lorsque j'avais commencé à utiliser Stylo il y a quelques mois, mais ils n'étaient pas si fréquents. Cette fonction est globalement devenue quasi-inutilisable pour moi :(

Quelqu'un·e a-t-il déjà rencontré des problèmes similaires ?
Serait-il possible d'y jeter un oeil bientôt ?

Merci d'avance, et toute ma gratitude pour ce merveilleux outil d'écriture 🌈

**Comment by antoinentl** [comment]
Merci d'avoir pris le temps de décrire ce problème !
Oui il nous est arrivé de rencontrer des difficultés similaires, ici j'identifie deux problèmes différents :

- un problème d'export PDF, cela peut venir :
  - d'un balisage présent dans les métadonnées, typiquement une note dans le résumé ;
  - d'un format d'image non pris en compte, il faut du PNG ;
  - de l'absence d'une ligne vide en fin de fichier : il faut une ligne vide dans chacun des articles (nous essayons de résoudre le problème pour ne pas ajouter cette contrainte côté rédaction) ;
- un problème dans l'usage de la fonctionnalité `book`, mais là il faudrait rentrer dans les détails.

Le plus simple serait d'en discuter de vive voix, la prochaine permanence Stylo a lieu ce jeudi à 11h :canada: / 17h :fr: , on peut aussi trouver un autre créneau pour discuter.
En fonction des problèmes identifiés j'ajouterai de la documentation ici.

**Comment by joseph-staline** [comment]
Ah oui c'est très clair merci beaucoup pour cette réponse.

Je ne savais pas pour la ligne vide à la fin et je n'en avais pas ajouté, au temps pour moi !

J'étais au courant pour le format PNG, mais comme je n'ai pas de stockage en ligne pour conserver mes images (et que je trouve le processus d'insertion un peu laborieux), j'utilise la balise de manière un peu détournée pour avoir des blocs image vides en ICML, que je pourrai remplir dans Indesign. Le problème vient donc certainement de là ↓

<img width="377" alt="Screenshot 2022-06-15 at 21 28 33" src="https://user-images.githubusercontent.com/104915084/173908716-aea2e942-0eeb-469a-92dd-e6999133b2ba.png">

L'export pdf est surtout un confort pour moi, parce que je refais une mise en page à partir de l'export ICML, donc ce n'est pas trop pénalisant. Mais ce serait chouette que ça fonctionne même avec des balises d'image détournées :) Ça ne rend d'ailleurs pas si mal en preview ↓

<img width="664" alt="Screenshot 2022-06-15 at 21 34 43" src="https://user-images.githubusercontent.com/104915084/173909688-471f7543-89d6-4e81-95d4-5781d11341cc.png">

Merci et à bientôt !

**Comment by antoinentl** [comment]
Nous notons cet usage détourné, très intéressant. Je ferme le ticket mais si vous rencontrez d'autres problèmes vous pouvez en ouvrir de nouveaux (de préférence un ticket par problème), et vous pouvez aussi m'écrire : antoine.fauchie@umontreal.ca
