### ISSUE TITLE
Problème de fonctionnement de tag lors de passerelle compte

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#630]
Lorsque Margot connectée sur son compte stylo Margot va sur le compte stylo de la Revue en passerelle (donc sans se déconnecter), la sélection des articles par les tags ne fonctionne pas (Margot clique sur Tag1 par exemple et rien ne se passe dans sa page article). 

(j'espère que c'est clair)

**Comment by ggrossetie** [comment]
Oui c'est très clair merci !
Juste une précision :

> Margot clique sur Tag1 par exemple et rien ne se passe dans sa page article

On parle bien du filtre sur les tags ? 

![image](https://user-images.githubusercontent.com/333276/174659919-65a8cefd-fd92-4c3e-b5d1-a7bc8644e045.png)

D'ailleurs on peut noter qu'il n'y a pas les cases à cocher. Si on clique dessus, je confirme que rien ne se passe.

**Comment by Mmellet** [comment]
oui c'est bien ça ! mercii

**Comment by ggrossetie** [comment]
Je viens de jeter un coup d’œil dans le code et la raison est qu'on utilise le même composant "tag d'un article" pour filtrer par tags mais aussi pour associer/dissocier un tag à un article.

Il y a une condition dans le code qui interdit à l'utilisateur connecté d'associer/dissocier un tag sur un article dont il n'est pas le "propriétaire".
Pour reprendre ton exemple, c'est le cas où Margot connectée sur son compte stylo Margot va sur le compte stylo de la Revue en passerelle. Dans ce cas Margot ne pourra pas associer/dissocier un tag sur un article de la Revue.

C'est intéressant car cela rejoint nos discussions sur les permissions et de qui a le droit de faire quoi.

Pour corriger le problème, je vais rendre le comportement configurable pour qu'il soit toujours possible de filtrer.
