### ISSUE TITLE
Problème de versionning lorsque le comparateur de version est ouvert 

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#638]
En utilisant le nouvel éditeur (je ne sais pas si cela est déterminant), lorsque le comparateur de version est ouvert (comparaison "edit mode"/version x), il semble que la création d'une nouvelle version ne sauvegarde pas la version en édition, mais réécrit la dernière version sauvegardée. 

On perd ensuite la version en cours d'édition.

**Comment by ggrossetie** [comment]
Effectivement c'est une anomalie liée au nouvel éditeur (ou en tout cas je ne reproduis pas en utilisant l'ancien éditeur)

**Comment by marviro** [comment]
Dans stylo-dev, les changements apportés pendant le compare ne sont pas enregistrés

**Comment by thom4parisot** [comment]
> Dans stylo-dev, les changements apportés pendant le compare ne sont pas enregistrés

Pourquoi tu signales ce problème dans cette issue si ce n'est pas la même chose ?

**Comment by marviro** [comment]
> > Dans stylo-dev, les changements apportés pendant le compare ne sont pas enregistrés
> 
> Pourquoi tu signales ce problème dans cette issue si ce n'est pas la même chose ?

je pensais que ça relevait du même problème, mais si ce n'est pas le cas, je vais en ouvrir une autre

**Comment by thom4parisot** [comment]
C'est plus facile pour nous de gérer des doublons d'issues que d'avoir 2 problèmes listés dans une même issue.

Je t'accorde qu'il faut diagnostiquer pour distinguer ça 😅
À ce stade là, j'en sais rien non plus. Les mots que tu poses ont l'air différents de l'intitulé, à première vue.

**Comment by lakonis** [comment]
Je pense que c'est le même problème. Exprimé autrement :)
