### ISSUE TITLE
Article How To Stylo vide dans création de nouveaux comptes avec HumaNum

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#639]
J'ai remarqué avec mes étudiants qui ont créé des nouveaux comptes stylo avec HumaNum que l'article How To Stylo était vide. 

Je ne sais pas si le problème vient de nous ou d'HumaNum

**Comment by thom4parisot** [comment]
Non ça vent de nous.

**Comment by ggrossetie** [comment]
> Non ça vent de nous.

💨

**Comment by thom4parisot** [comment]
C'est le calendrier de la vent, un bug par jour jusqu'à la mise en prod !
