### ISSUE TITLE
Erreur 502 sur la preview html dans Stylo

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#641]
J'ouvre un ticket à propos de ce bug dans la preview pour en garder trace (même si nous le connaissons tous) et tenter de trouver une solution plus pérenne que celle actuelle : 

Depuis plusieurs semaines, et de manière récurrente, la preview de Stylo ne fonctionne plus et le navigateur affiche le message "502 Bad Gateway" aux utilisateurs.

**Comment by thom4parisot** [comment]
C'est #634 qui cause le problème (non-résolu à l'heure actuelle)

**Comment by ggrossetie** [comment]
> C'est https://github.com/EcrituresNumeriques/stylo/issues/634 qui cause le problème (non-résolu à l'heure actuelle)

Oui c'est exactement ça 👍🏻 

Je pense que le YAML est vide, c'est le seul cas où `doc` peut être `undefined`. Pour corriger cette anomalie, il faut rajouter une précondition afin de retourner `''` si le YAML est vide.

```js
const docs = YAML.loadAll(yaml, 'utf8')
// contains only a single document
const doc = docs[0]
```

Il serait aussi intéressant de savoir pourquoi est-ce que le YAML est vide ? 🤔 

Et tant qu'à faire, Il faudrait donc faire un `try` / `catch` car la méthode `YAML.loadAll` peut renvoyer une exception de type `YAMLException` si le YAML est invalide.

**Comment by ggrossetie** [comment]
Par contre je vois qu'on a déjà fait un travail permettant d'attraper les exceptions dans les routes async... 23a50078d6f2499986e8d3a0bd8624c1669803cd

**Comment by ggrossetie** [comment]
Je crois comprendre, l'erreur est toujours `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`.

J'ai ajouté une protection supplémentaire, rendu la méthode `prepare` plus robuste et déplace l'appel à cette méthode du `Promise.all`. Normalement le serveur ne devrait plus planter.
