### ISSUE TITLE
Problème de partage d'article (partage simple), après avoir partagé un compte puis annulé ce partage de compte

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#648]
Nous avons un problème de partage d'articles assez étrange, voici un résumé des problèmes rencontrés :

1. quelqu'un·e essaye de partager un article avec plusieurs personnes ;
2. au bout de plusieurs partages (ici 6), l'écran de partage présente plusieurs problèmes :
    - tous les contacts (habituels) ne sont plus affichés : il n'y a plus que 2 contacts affichés (au lieu d'une douzaine habituellement) ;
    - les intitulés de partage ne sont plus les mêmes "already shared via full access" avec un lien qui mène à `/credtials` (voir capture plus bas) ;
    - après une déconnexion/reconnexion il y a toujours que 2 contacts **mais** le message est le bon, sans que les _boutons_ ne fonctionnent ;
3. l'article semble bien partagé avec les 6 premières personnes ;
4. le partage des autres articles semble également atteint après ce problème : les contacts sont modifiés (plus que 2 contacts), et il est impossible de partager l'article.

![stylo--](https://user-images.githubusercontent.com/6869488/200345352-9ade196a-0186-4a3f-88e3-dd26652c1243.png)

Une piste qui me semble la plus plausible : le compte en question a d'abord partagé l'accès à son compte/à tous ses articles aux deux contacts qui restent visibles, puis ce partage a été annulé. Il semblerait que cette annulation n'ait pas été prise en compte…

Ce que nous avons essayé en cas de problème de cache (tentatives qui n'ont rien résolu) :

- déconnexion-reconnexion ;
- changement de navigateur (passage de Firefox à Chrome).

C'est un problème bloquant.

**Comment by ggrossetie** [comment]
> tous les contacts (habituels) ne sont plus affichés : il n'y a plus que 2 contacts affichés (au lieu d'une douzaine habituellement) ;

est-ce que les 2 contacts affichés étaient des contacts existants de la personne ?

> les intitulés de partage ne sont plus les mêmes "already shared via full access" avec un lien qui mène à /credtials (voir capture plus bas) ;

Avec la typo ou `/credentials` ?

**Comment by antoinentl** [comment]
@Mogztter Oui les deux contacts affichés étaient des contacts existants ! Et oups ça renvoie bien vers `/credentials` désolé pour la typo !

**Comment by thom4parisot** [comment]
@antoinentl tu me diras si tu constates toujours ce problème sur stylo-dev ? Avec les dernières modifs (qui accumulent les utilisateurs partagés), je me demande si ça ne l'a pas réglé au passage.

**Comment by antoinentl** [comment]
Voici mon test et les constats :

- antoine-01 crée un article, l'article 01, il le partage avec antoine-02
- antoine-02 peut modifier l'article, le versionner, etc.
- antoine-02 partage l'article 01 avec antoine-03
- antoine-03 peut voir l'article et le modifier également
- par contre antoine-02 peut révoquer son propre accès à l'article 01. :thinking: Je ne sais pas si c'est normal mais ça me semble très intéressant (ne plus vouloir du partage)

Tout semble fonctionner.

Je tente un dernier test :

- antoine-01 crée un nouvel article (non partagé), l'article 02
- antoine-01 partage son compte avec antoine-02
- antoine-02 bascule sur le compte antoine-01 (nécessite un rafraîchissement de la page)
- antoine-02 peut partage l'article 02 avec antoine-04

**Comment by thom4parisot** [comment]
Ouais 🙌🏻 

> par contre antoine-02 peut révoquer son propre accès

On peut dire que ça a été fait exprès par hasard !
