### ISSUE TITLE
Problème d'apposage de tags sur des articles partagés

### ISSUE THREAD

**Issue by mattheyje** [EcrituresNumeriques/stylo#649]
Bonjour!
Nous avons le problème suivant ; nous recevons, en partage, des articles de la part de plusieurs auteurs différents. 
Nous souhaitons en faire un book ; pour cela, nous devons apposer un tag identique sur chacun de ces articles.
Nous ne pouvons pas modifier les tags des articles dont nous ne sommes pas les auteurs.
Est-il possible de lever cette limitation? Complètement, ou alors en ne permettant que l'ajout de tags (et pas le retrait).
Merci!

**Comment by ggrossetie** [comment]
Je pense que les tags ne devraient pas être lié à un article mais à un article et un utilisateur. Autrement dit, l'article ne porte pas directement les tags.

Cela permet d'avoir une gestion des tags par utilisateur, l'utilisateur Antoine peut avoir les tags "Yellow" et "Important" sur l'article A et l'utilisateur Thomas peut avoir les tags "Blue" et "Book" sur ce même article (i.e., sans voir les tags de l'utilisateurs Antoine)

@antoinentl qu'est-ce que tu en penses ?

**Comment by thom4parisot** [comment]
@mattheyje est-ce que tu veux _voir_ les tags de l'auteur en partage ? Ou, tu voudrais dire "je veux le même tag, et l'ajouter à cet article" ?

**Comment by thom4parisot** [comment]
Après discussion avec @mattheyje, il en ressort que : 

- les tags servent à collaborer/communiquer lors d'un partage d'article
- il y a de la valeur à **voir** les tags de l'autre (c'est sa manière de ranger les choses)
- il y a de la valeur à **ajouter** ses propres tags (genre ceux de SensPublic qui disent "revue en cours", "ok", "édition 250", etc.

Ajouter ses propres tags sur un article partagé, c'est aussi une manière de créer des Books à partir d'articles qu'on nous partage.

💡 Ce qui me ferait presque revoir une conception : les Tags devraient être un concept "central", associé à un User ou Workspace. Plusieurs tags de plusieurs origines peuvent ainsi cohabiter sur un même article (Tag du User/owner, Tag du User/collaborator, Tag du Workspace).

Ma résolution sur ce point en particulier serait de dire : 

- je peux ajouter mes propres tags à un article partagé
- on voit d'abord nos tags à nous
- on voit ensuite les tags des autres (sur lesquels on ne peut pas interagir)

**Comment by ggrossetie** [comment]
> il y a de la valeur à voir les tags de l'autre (c'est sa manière de ranger les choses)

Je me demande dans quel(s) cas cela est vraiment intéressant ?

> il y a de la valeur à ajouter ses propres tags (genre ceux de SensPublic qui disent "revue en cours", "ok", "édition 250", etc.

👍🏻 

> Ajouter ses propres tags sur un article partagé, c'est aussi une manière de créer des Books à partir d'articles qu'on nous partage.

Je vois bien le besoin mais je ne pense pas qu'il faut le lier aux tags puisqu'on est déjà en train de réflechir à d'autres façons de créer des groupements d'articles/corpus.

> Ce qui me ferait presque revoir une conception : les Tags devraient être un concept "central", associé à un User (...)

👍🏻 

> (...) ou Workspace. 

Je me demande si c'est utile, surtout si les tags des utilisateurs sont visibles sur les articles partagés dans un workspace.

> Plusieurs tags de plusieurs origines peuvent ainsi cohabiter sur un même article (Tag du User/owner, Tag du User/collaborator, Tag du Workspace).

Cela peut être intéressant mais je me demande si c'est une information qu'on souhaite affiche au même plan que nos tags à nous ? J'ai peur que ça fasse des informations supplémentaires qui ne seront que peu ou pas utilisées. Exemple, Thomas partage un article à Guillaume, puis Guillaume le partage à Margot et enfin Margot le partage à Nicolas. Dans ce cas, Nicolas va récupérer un article avec les tags de Thomas, Guillaume et Margot. Est-ce que ça lui sera vraiment utile ? Est-ce qu'il veut filtrer les articles auxquels il a accès avec les tags de Thomas ou Guillaume ? Est-ce qu'il va s'y retrouver ? Est- ce qu'on ne va pas devoir ajouter une option afin de masquer les tags des autres afin de ne pas en avoir trop ?

Si on décide que c'est utile, on pourrait éventuellement reprendre ton concept de hiérarchie sur les tags avec `ggrossetie:senspublic` ou `tparisot/senspublic` (préfixe par le username).

> je peux ajouter mes propres tags à un article partagé

👍🏻

**Comment by thom4parisot** [comment]
> Je me demande dans quel(s) cas cela est vraiment intéressant ?

Si j'avais pas vu les 380 articles de Sens Public, j'aurais pas pu répondre à cette question 😅  Ça tient beaucoup au workflow éditorial : 

- une personne collaboratice crée un article en son nom (et le tag avec ses tags genre "Politique", "Code")
- elle partage l'article avec le compte "Relecture Sens Public"
- Eugénie bascule sur le compte "Relecture Sens Public"
- le compte "Relecture Sens Public" travaille sur les articles partagés, et aurait envie de dire "Relecture en cours", "Article publié" — ce qui informe la personne ayant écrit l'article d'où ça en est

La limitation exprimée dans le premier message est qu'arbitrairement, on ne permet pas d'ajouter des tags à un autre article (alors qu'on voit les tags de l'autre).

Les peurs que tu exprimes ne sont pas exprimées par les personnes qui utilisent Stylo et qui se trouvent "limitées".

La philosophie de Stylo est : y'a pas de hiérarchie, chaque user qui a accès à quelque peut faire la même chose que les autres.
