### ISSUE TITLE
problème avec l'ajout de bibliographie

### ISSUE THREAD

**Issue by EmmanuelleLescouet** [EcrituresNumeriques/stylo#65]
Lors de l'ajout de bibliographie (bibtex), aussi bien par "+ add reference" que par "see source", quand je clique sur "confirm" la fenêtre devient blanche (intégralement) et je dois revenir en arrière ou relancer stylo pour revenir à l'article.

**Comment by PookMook** [comment]
salut,
est-ce qu'il est possible de nous copier ici le bibtext que tu essaies d'ajouter, ainsi que l'erreur dans la console (clique-droit "inspect element" puis dans le tab console tu devrais voir des gros messages en rouges)
Merci

**Comment by EmmanuelleLescouet** [comment]
Salut, 
Voici le bibTex


Le message quand je clic sur « confirm » :

TypeError: "e.match(...) is null"
Ahttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:6:512855Ahttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:6:512714beginWorkhttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:21092Ahttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:33560uhttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:34076chttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:34551batchedUpdateshttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:37413whttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:4664yhttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:4600batchedUpdateshttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:52190dispatchEventhttps://stylo.ecrituresnumeriques.ca/main.78578868628303a6c948.js:16:53039 react-dom.production.min.js:187:180
[Afficher/Masquer les détails du message.] TypeError: e.match(...) is null[En savoir plus] Biblio.jsx:34:34

**Comment by EmmanuelleLescouet** [comment]
Ca a marché ! 

Je ne sais pas pourquoi mais ce coup-ci la biblio s’est affichée !

Merci pour votre aide :D

Emma
