### ISSUE TITLE
nocite n'est pas pris en compte

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#653]
On a un problème déjà remarqué qui est de retour ! 

L'option nocite dans les métadonnées n'est pas pris en compte : 

donc si j'ai mon article qui a une bibliographie de 32 références et qui n'en cite dans le corps du texte que 30 (donc 2 références sont dans la bibliographie mais ne sont pas utilisées dans l'article), même si l'auteur sélectionne "all citations" dans les métadonnées, des formats d'exports (PDF, HTML, XML) présenteront une bibliographie de 30 références. 

Pour l'instant on bypasse le problème en ajoutant 

```
---
nocite: "@*"
---
```

au début de l'article mais on va devoir refaire tous nos exports pour la revue...

**Comment by thom4parisot** [comment]
Zut.

Quand tu sélectionnes "all citations" dans les métadonnées, et que tu bascules en "raw", y'a pas le `nocite` qui apparait ?

(cette valeur est indépendante des 30 citations manuelles insérées dans l'article en question)

**Comment by marviro** [comment]
si, le nocite est dans le raw. Je vais tester moi aussi pour comprendre ce qui se passe

**Comment by marviro** [comment]
Le problème vient du module d'export. Même si je n'arrive pas à en expliquer la raison. Le nocite est bien dans le yaml, mais pandoc l'ignore. Ce qui est surprenant est que en rajoutant le nocite au début de l'article, ça fonctionne. J'ai essayé avec plusieurs syntaxes. Je ne suis pas capable de debugguer. Vu que le nouvel export arrive, je laisserais tomber. Ajoutez le nocite en tête d'article. Désolé

**Comment by marviro** [comment]
Ok, j'ai compris d'où vient le problème, mais je ne vais pas le résoudre: avant le script d'export fonctionnait en donnant yaml et md comme sources. par ex: `pandoc monarticle.yaml monarticle.md -o lala.html`. Maintenant on utilise `--netadata-file`. Apparemment dans la vieille version de pandoc qu'on utilise dans l'export, cette manière de passer les metadonnées fait ignorer le nocite. Pour le faire fonctionner je devrais rechanger toutes les occurrences de la commande pandoc dans l'export (une centaine...). Et en plus on pourrait avoir d'autres problèmes dans la gestion des métadonnées qui se manifesteraient à cause du changement.
