### ISSUE TITLE
Modifications des métadonnées dans Stylo

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#655]
## Contexte

Afin de concorder avec les métadonnées de Métopes, Stylo doit augmenter les métadonnées disponibles dans l'application pour le [Mode : éditeur].

## Ajout des métadonnées

- [x] Surtitre ;
- [x] Titre traduit (avec le choix de la langue, voir par exemple le fonctionnement des mot-clefs) ;
- [x] Courriel de l'auteur
- [x] Funder (+id)

## Modification de métadonnées existantes

- [x] "directors" --> "journal directors"

## Création de classes `CSS`

Certaines des métadonnées Métopes peuvent être encapsulées dans des classes `CSS` (balises `<span>` une fois en HTML) directement dans l'éditeur Stylo : 

- Dédicace
- Chapô
- Épigraphe

**Comment by antoinentl** [comment]
Il reste le titre traduit à ajouter ! (Note à moi-même et à @RochDLY)

**Comment by RochDLY** [comment]
Le titre traduit a été rajouté, mais une erreur persiste et fait planter les articles.

**Comment by RochDLY** [comment]
Je réponds ici sur les bugs rencontrés dans la preprod (stylodev) : nous rencontrons en ce moment une série de problème allant de la page blanche lors de l'ouverture du volet des métadonnées dans l'éditeur ou lors de la création d'un article dans la page d'accueil de Stylo Dev, voir image : 
![Screenshot from 2022-12-16 08-19-11](https://user-images.githubusercontent.com/43650596/208107848-3679960e-8a47-4ba6-8b5f-4006b5ffe041.png)

**Comment by thom4parisot** [comment]
Ah trop bien l'erreur ! Elle doit être liée à #682 : tu as combien d'articles ?

Les autres trucs soulevés sont résolus par #693

**Comment by thom4parisot** [comment]
J'ai consigné le problème de performances spécifiquement dans #701.
