### ISSUE TITLE
Bug sur l'export (module actuel) d'image

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#657]
Cas particulier d'une image qui va faire bugger la regex :

```markdown
...
![Fonctionnalités](https://hnlab.huma-num.fr/hnso/ouvrage-in/Images/clarin.jpg){#fig:clarin}
...
```
Le fait que le nom de fichier et l'id de l'image soient les mêmes va générer l'export markdown suivant: 

```markdown
![Fonctionnalités](media/ChapitreInfrastructures-latest-img5}
```

**Comment by thom4parisot** [comment]
Quel est le bug ? Tu attendais quel résultat ?

Je n'arrive pas à comprendre où est le comportement inattendu dans ton message.

**Comment by lakonis** [comment]
Sorry, c'était pas clair en effet.
La syntaxe image n'est pas correct. La regex prend en compte les deux clarin de l'exemple et on se retrouve avec une fin de ligne incorrecte : pas d'extension de fichier et une accolade fermante au lieu d'une parenthèse.

**Comment by marviro** [comment]
C'est un problème de ma regex dans l'export actuel @thom4parisot - donc ça ne vous concerne pas.
Ce type de problèmes devrait être réglé avec le nouvel export - au moins il devrait signaler le problème dans le log

**Comment by lakonis** [comment]
C'est ce qu'il me semblait. Mais bon à mentionner selon la manière dont fonctionne le prochain export. 
++

**Comment by antoinentl** [comment]
Merci pour le signalement @lakonis ! Le ticket est référencé sur le dépôt dédié → https://gitlab.huma-num.fr/ecrinum/stylo/stylo-export/-/issues/4

**Comment by antoinentl** [comment]
Par ailleurs @lakonis tu cherches à appliquer un identifiant (`id`) à l'image avec un id qui a deux points _dedans_ ? Voici le résultat de Pandoc :

```
<figure>
<img src="https://hnlab.huma-num.fr/hnso/ouvrage-in/Images/clarin.jpg"
id="fig:clarin" alt="Fonctionnalités" />
<figcaption aria-hidden="true">Fonctionnalités</figcaption>
</figure>
```

Je ne sais pas si tu pourras faire quelque chose de `fig:clarin` :thinking:

**Comment by lakonis** [comment]
Oui, ça pour le coup ça marche bien. Initialement c'est une récupération de latex, d'où l'identifiant `fig:`
Cf https://hnlab.huma-num.fr/hnso/ouvrage-in/introduction.html

**Comment by antoinentl** [comment]
Ok je comprends, le but n'était pas d'utiliser l'id en CSS. Bonne idée pour LaTeX !
