### ISSUE TITLE
impossible d'exporter en XML

### ISSUE THREAD

**Issue by EmmanuelleLescouet** [EcrituresNumeriques/stylo#66]
Je ne parviens plus à obtenir l'export XML (Erudit) dont je me servais pour passer les articles sous In Design...
ça indique "Generating XML erudit file, please wait" mais ne dépasse pas ce stade même en restant ouvert des heures.

**Comment by PookMook** [comment]
en ouvrant la console, est-ce qu'il y a des erreurs qui s'affiche?
Sinon, la génération des XML du coté client va bientôt être remplacé par la génération du coté serveur, donc ca devrait aller mieux très prochainement! @marviro

**Comment by EmmanuelleLescouet** [comment]
Il n’y a pas moyen de charger la console :

**Comment by lakonis** [comment]
ca devrait être bon maintenant. @EmmanuelleLescouet tu testes et eventuellement ferme l'issue ?

**Comment by EmmanuelleLescouet** [comment]
effectivement maintenant ça fonctionne !
