### ISSUE TITLE
Retourner les tags des articles via une requête GraphQL

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#681]
J,ouvre cette issue pour commencer à réfléchir à des améliorations possibles de l'api graphql.

Je vais lister des exemples pour le moment:

La query:

```
{
  user {
    
      articles{
      title
      _id
      }
      
    
  }
}
```
me donne `null` pour les titres. Dommage... Donc je dois refaire une query par article pour chopper les titres

Question analogue pour les `tags` dans la liste articles: pas implémenté.

Donc je dois faire une query sur les tags d'abord et puis aller chercher les articles qui ont ce tag.

**Comment by marviro** [comment]
Question: est-ce qu'on pourrait aussi implementer:

```
{user{articles{tags{_id name}}}}
```

?

**Comment by marviro** [comment]
Utile pour avoir les tags des articles...

**Comment by thom4parisot** [comment]
Oui, c'est un oubli. Je renomme l'issue pour refléter ça.
