### ISSUE TITLE
how to stylo : document par défaut vide

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#688]
Dans une formation donnée aujourd'hui, les nouveaux utilisateurs avaient bien un document How to dans la liste de leurs articles, mais ce document est vide.

100% d'erreur aujourd'hui pour les nouveaux venus.

**Comment by antoinentl** [comment]
C'est noté pour le How to, en revanche je ne comprends pas ce que tu veux dire pas "100% d'erreur aujourd'hui pour les nouveaux venus."…

**Comment by antoinentl** [comment]
@lakonis J'ai besoin d'une précision : les nouveaux utilisateurs se sont créés un compte Huma-Num ou Stylo ?

**Comment by lakonis** [comment]
- 100% d'erreur, c'est-à-dire que tous les utilisateurs ont rencontré l'erreur.
- sur le type de compte, c'est une bonne question, mais je n'ai pas demandé aux participants !

**Comment by thom4parisot** [comment]
Margot a déclaré ce bug dans #639.
