### ISSUE TITLE
How to stylo : lien qui ne renvoit à une interface vide

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#689]
Outre un how-to vide (voir #688), certains utilisateurs on tenté d'ouvrir le document how to listé, mais n'obtenaient alors qu'une interface vide, sans navigation, sans volet, juste une page blanche avec un curseur clignotant mais non utilisable. 

Comme si le lien renvoyait vers rien, mais sans créer non plus de 404 ou d'erreur visible.

J'ai demandé rapidement les configs concernés, il y avaient un peu de tout, mais notamment du Chrome, du Safari, j'ai pas entendu de firefox.

**Comment by thom4parisot** [comment]
Sur stylo-dev ou en prod ?

Si c'est sur stylo-dev, c'est lié à #686.

Si c'est en prod, tu peux indiquer l'URL d'un document sur laquelle ça se produit ?

**Comment by lakonis** [comment]
C'est en prod et c'est sur des articles nouvellement créés par des nouveaux utilisateurs. Je ne l'ai jamais observé avec mon compte.

**Comment by thom4parisot** [comment]
> Si c'est en prod, tu peux indiquer l'URL d'un document sur laquelle ça se produit ?

**Comment by lakonis** [comment]
Malheureusement je ne suis pas en contact avec les participants d'hier. Tu pourrais les retrouver sur les créations de compte depuis avant-hier mais j'ose pas trop donner de nom ici.

**Comment by thom4parisot** [comment]
Testé sur stylo-dev, corrigé avec 13a5c961dc79e661dc97007d8fce7cd28b3d369a et a28fa7c301e334f428709fa2de2d2b1d6786ba10
