### ISSUE TITLE
Améliorer comportement du volet gauche

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#69]
Suite à des retours utilisateurs, il faudrait que le volet repousse la marge à droite et pousse le corps de texte sans le déformer. Plutot que de s'afficher dessus.

> je me demandais s'il était normale que le corps de texte et la section gauche (biblio, versions) s'affichent différemment? Pour travailler directement dans le corps de texte, je dois fermer la section en question à défaut de pouvoir lire ce que j'écris (cf. capture d'écran en pj).

![image](https://user-images.githubusercontent.com/9479788/55742969-1ed02200-59ff-11e9-9fbe-4afb549b37c3.png)

**Comment by ggrossetie** [comment]
Ce n'est pas tout à fait la même chose mais c'est lié à https://github.com/EcrituresNumeriques/stylo/issues/144

Dans un premier temps, on va essayer de réduire la largeur des colonnes. Si ça ne suffit pas on peut effectivement pousser le texte (quand il y a la place) et qu'un seul volet est ouvert.

**Comment by lakonis** [comment]
Entendu. Le vrai pb côté utilisateur, c'est que certain ne comprenne pas en arrivant sur un article pour la première fois que la zone de texte centrale est une zone éditable, car le curseur d'édition est caché par le volet de gauche. C'est pour cela que je suggérais que le bord gauche de l'éditeur soit toujours visible.

**Comment by ggrossetie** [comment]
Effectivement ce n'est pas idéal. 
Est-ce qu'il est vraiment utile d'afficher systématiquement le panneau gauche à l'ouverture du document ?
Je trouve ça aussi assez perturbant que le curseur soit positionné à la fin du document. 

| Actuel | Proposition |
| ---- | ----- |
| ![welcome-current-1024](https://user-images.githubusercontent.com/333276/86237723-93f7bc00-bb9c-11ea-96b4-ef0f838a0dfe.png)| ![welcome-next-1024](https://user-images.githubusercontent.com/333276/86237732-98bc7000-bb9c-11ea-8ae3-1ec624414789.png)|

Je trouve le "open" et "Metadata" pas très visible et surtout ils passent au dessus de la barre d'entête : 

![hide](https://user-images.githubusercontent.com/333276/86237917-eafd9100-bb9c-11ea-9123-93571feaf6f6.png)

Et au dessus du texte : 
![hide1](https://user-images.githubusercontent.com/333276/86237920-eb962780-bb9c-11ea-8b61-138d10874b4e.png)

Peut être que quelque chose comme ça serait mieux : 

![menu-right](https://user-images.githubusercontent.com/333276/86237953-fbae0700-bb9c-11ea-9e77-cbed45eaff2b.png)

Ou un de chaque côté : 

![ttt](https://user-images.githubusercontent.com/333276/86237964-04064200-bb9d-11ea-9f99-e9be5c525d27.png)

Les pictogrammes sont surement à revoir et au survol de l'icone il faudrait afficher un texte : 

![expand](https://user-images.githubusercontent.com/333276/86238594-0ddc7500-bb9e-11ea-86b4-b0429bd436da.png)

**Comment by ggrossetie** [comment]
Une autre idée serait d'avoir une barre d'action sticky en bas de l'écran (ou en haut) : 


![bottom](https://user-images.githubusercontent.com/333276/86238960-c0acd300-bb9e-11ea-8701-3c8fa60bd9ec.png)

**Comment by antoinentl** [comment]
Sur ce point ce qui est sûr :

- il ne faut pas que le volet gauche chevauche la zone centrale (ce qui est le cas sur beaucoup de résolutions) ;
- il faut que le curseur soit placé en haut du document par défaut.

Les questions (@marviro nous avons besoin de ton avis) :

1. je ne pense pas qu'il soit nécessaire d'avoir le volet gauche ouvert par défaut ;
2. je suis pour des pictogrammes accompagnés de texte et placés en haut (à gauche et à droite) de façon plus subtile comme proposé par @Mogztter .
3. il faut trouver une solution pour indiquer que la zone centrale est éditable, un curseur qui clignote (je pense que ça a un autre nom :thinking: ) placé en haut serait une solution ?

**Comment by antoinentl** [comment]
Un petit up sur cette issue avec les rappels suivants :

- [ ] il ne faut pas que le volet gauche chevauche la zone centrale (ce qui est le cas sur les résolutions supérieures à 1800px de large) ;
- [ ]  si le volet gauche ne chevauche pas la partie centrale alors on peut le garder ouvert par défaut, sinon on le ferme tout en suggérant qu'il y a des _volets_ ;
- [ ] je suis pour des pictogrammes accompagnés de texte et placés en haut (à gauche et à droite) de façon plus subtile comme proposé par @Mogztter.

**Comment by thom4parisot** [comment]
S'il fallait _nommer_ le volet gauche, ça serait quoi ? Vu que le volet droit s'appelle "Metadata".

**Comment by ggrossetie** [comment]
> il ne faut pas que le volet gauche chevauche la zone centrale (ce qui est le cas sur les résolutions supérieures à 1800px de large) ;

Cela va forcement chevaucher à un moment ou alors le menu va s'afficher au dessus ou en dessous de l'éditeur. 
Je pense que c'est compliqué de faire moins de 300 pixels de large pour les volets latéraux et il faudra surement ajuster un peu la taille de la police.
La question c'est plutôt quelle doit être la largeur minimum de l'éditeur ? Ou alors quelle est la résolution minimale où l'on souhaite ne pas avoir de chevauchement ? Par exemple, si on veut qu'il n'y ait pas de chevauchement sur une résolution de 1024 pixels, il faudra accepter que la zone de texte fasse 700 pixels.

> si le volet gauche ne chevauche pas la partie centrale alors on peut le garder ouvert par défaut, sinon on le ferme tout en suggérant qu'il y a des volets ;

Est-ce que c'est pertinent de l'afficher à l'ouverture d'un nouvel article ? Est-ce que c'est pertinent de l'ouvrir systématiquement ? Quel est l'intérêt ? Le cas d'usage le plus fréquent est de saisir du texte non ?

On pourrait surement ajouter Matomo pour avoir des statistiques mais je pense que 80% du temps (voir plus), le panneau latéral est fermé dans les 10 secondes après l'ouverture de l'article.

Quelques pistes, on pourrait déplacer les statiques dans le pied de page sur une ligne :

![image](https://user-images.githubusercontent.com/333276/118810836-9f370180-b8ac-11eb-9e84-9735c254724d.png)

On pourrait conserver uniquement la table des matières dans le menu et déplacer les éléments moins fréquemment utilisés (ou du moins plus contextuels) comme les citations/bibliographies et l'historique des versions ailleurs.

> je suis pour des pictogrammes accompagnés de texte et placés en haut (à gauche et à droite) de façon plus subtile comme proposé par @Mogztter.

Si on ne souhaite pas afficher les deux panneaux latéraux en même temps, je pense qu'il est préférable de les regrouper du même côté.
Est-ce que pour les métadonnées on souhaite aussi voir l'article ou non ? Autrement dit, est-ce qu'une popup plus large au milieu de l'écran c'est gênant ? La saisie du formulaire sera plus agréable car on sera en "plein écran" plutôt que dans un coin de l'écran.

**Comment by ggrossetie** [comment]
> S'il fallait nommer le volet gauche, ça serait quoi ? Vu que le volet droit s'appelle "Metadata".

On peut aussi se poser la question sur le volet droit qui s'appelle "open" 😉

**Comment by antoinentl** [comment]
Merci de soulever toutes ces questions pertinentes :

- la résolution minimal pourrait être 1200px (ce qui correspond à des ordinateurs portables de 13 pouces, relativement récents sans être dernier cri) ;
- en terme d'usage nous (à la Chaire) conservons pour la majorité le volet gauche ouvert (personnellement je ne suis pas fan de la popup, mais afficher des infos en pied de page est une très bonne idée) ;
- pour une vision plus réaliste des usages j'aurais envie de dire que @maiwann pourrait peut-être enquêter, je crains de ne pas être très objectif.

**Comment by lakonis** [comment]
> On pourrait surement ajouter Matomo pour avoir des statistiques mais je pense que 80% du temps (voir plus), le panneau latéral est fermé dans les 10 secondes après l'ouverture de l'article.

- Comme Antoine, je pense au contraire que ce volet reste ouvert la plupart du temps.

- Un pied de page pourrait être investi pour certains aspects (enregistrement de version par exemple, un peu comme sur un éditeur gitlab/github), mais je n'en ferais pas trop car en mode rédaction de texte, plus l'espace vertical est démuni, plus l'esprit est libre et focalisé sur le texte. Pas très bien exprimé, mais le mode "zen" ou l'interface minimale que l'éditeur offre plus ou moins déjà devrait être conservé autant que possible.

  Ce qui me fait penser qu'un éditeur (outillé ++) n'aura pas les mêmes besoins qu'un auteur (zen + biblio).

- Le pb du nom du volet de gauche est symptomatique. Peut-être devrait-on pouvoir ouvrir module par module ? 

  Proposition: Positionner les titres de module en haut, les rendre clicables, un clic sur "versions" ouvre le module versions, un autre sur biblio ouvre la biblio, etc.

**Comment by lakonis** [comment]
> Si on ne souhaite pas afficher les deux panneaux latéraux en même temps, je pense qu'il est préférable de les regrouper du même côté.

C'est une piste intéressante. Ca fonctionnerait avec ma proposition précédente. Et ca laisserait plus de place à la comparaison de version.

[edit] c'est plus ou moins ce qui était proposé en début d'issue par @Mogztter :  

![proposition Mogztter](https://user-images.githubusercontent.com/333276/86237953-fbae0700-bb9c-11ea-9e77-cbed45eaff2b.png)

**Comment by lakonis** [comment]
> Est-ce que pour les métadonnées on souhaite aussi voir l'article ou non ? Autrement dit, est-ce qu'une popup plus large au milieu de l'écran c'est gênant ? La saisie du formulaire sera plus agréable car on sera en "plein écran" plutôt que dans un coin de l'écran.

Pas trop pour... Car ce cas, on pourrait aussi accéder à l'édition des métadonnées depuis la home (liste d'articles) ? Mais je ne pense pas qu'il faille dissocier à ce point l'article et ses métadonnées éditoriales. Au contraire, les penser comme une continuité d'actions sur l'article me semble plus porteur et plus en phase avec notre discours sur Stylo.

**Comment by ggrossetie** [comment]
> la résolution minimal pourrait être 1200px (ce qui correspond à des ordinateurs portables de 13 pouces, relativement récents sans être dernier cri) ;

OK.
Donc en dessous de 1200px il pourra y avoir un chevauchement c'est bien ça ? Le panneau latéral fait 400 pixels, en comptant une marge et de bordures, l'éditeur pourrait faire 750 pixels. Est-ce que c'est suffisant ?
À noter qu'il y aura un effet de "push" si on veut conserver l'éditeur centré quand le panneau n'est pas visible. Exemple en image :

![push](https://user-images.githubusercontent.com/333276/118846170-bd145e80-b8cc-11eb-945d-9e1998f0b1aa.gif)

Est-ce que c'est ce que vous avez en tête ?

> en terme d'usage nous (à la Chaire) conservons pour la majorité le volet gauche ouvert (personnellement je ne suis pas fan de la popup, mais afficher des infos en pied de page est une très bonne idée) ;
> Comme Antoine, je pense au contraire que ce volet reste ouvert la plupart du temps.

Question subsidiaire, qu'est ce que vous utilisez (souvent) dans le volet de gauche pour que vous ayez besoin de l'avoir toujours sous les yeux ?

> Le pb du nom du volet de gauche est symptomatique. Peut-être devrait-on pouvoir ouvrir module par module ?
Proposition: Positionner les titres de module en haut, les rendre clicables, un clic sur "versions" ouvre le module versions, un autre sur biblio ouvre la biblio, etc.

C'est une bonne idée mais cela à plusieurs implications :
- Quelles sont les panneaux à ouvrir par défaut ?
- Il n'est plus possible de tout masquer/tout afficher en un clic (sauf si on ajoute un nouveau bouton)
- Est-ce quand on clique sur "Biblio", on doit conserver "Versions" ouvert ou est-ce qu'il faut le refermer?

> C'est une piste intéressante. Ca fonctionnerait avec ma proposition précédente. Et ca laisserait plus de place à la comparaison de version.

👍🏻 

> Pas trop pour... Car ce cas, on pourrait aussi accéder à l'édition des métadonnées depuis la home (liste d'articles) ? 


Potentiellement oui.
Si on a pas besoin de voir le contenu de l'article pour renseigner les métadonnées alors cela peut avoir du sens.

Cela pourrait aussi permettre de donner les droits à quelqu'un afin qu'il puisse éditer les métadonnées mais sans lui donner accès à l'article.

> Mais je ne pense pas qu'il faille dissocier à ce point l'article et ses métadonnées éditoriales. Au contraire, les penser comme une continuité d'actions sur l'article me semble plus porteur et plus en phase avec notre discours sur Stylo.

Je suis d'accord mais est-ce que renseigner les métadonnées éditoriales se fait en même temps que la rédaction de l'article ? Est-ce qu'on a besoin de voir le contenu de l'article pour renseigner les métadonnées ?

Par exemple, quand on ajoute des références bibliographiques (liées à un article) on ne le fait pas dans un panneau latéral mais dans une popup.

**Comment by thom4parisot** [comment]
Voici des guidelines trouvées ici et là : 

- [Sidebars LibreOffice](https://wiki.documentfoundation.org/Design/Guidelines/Sidebar)
- https://uxdesign.cc/vertical-navigation-layout-usability-principles-10e55b596997

Une double navigation pourrait avoir du sens, pour éviter le scroll notamment : 

![image](https://user-images.githubusercontent.com/138627/120200605-d00c2480-c224-11eb-8dfc-e33fc995ac39.png)

**Comment by lakonis** [comment]
> Une double navigation pourrait avoir du sens, pour éviter le scroll notamment

Ca me semble tout à fait adapté comme solution.

> Je suis d'accord mais est-ce que renseigner les métadonnées éditoriales se fait en même temps que la rédaction de l'article ? Est-ce qu'on a besoin de voir le contenu de l'article pour renseigner les métadonnées ?
>
> Par exemple, quand on ajoute des références bibliographiques (liées à un article) on ne le fait pas dans un panneau latéral mais dans une popup.

Oui, l'accès à l'article pendant le renseignement des métadonnées est important, notamment pour catégoriser l'article (mot-clés, catégories, travail du titre, etc.). Le volet métadonnées fonctionne assez bien en vertical. Reste à savoir si on le réintègre dans le volet de gauche avec cette double navigation. Je serais plutôt pour!

**Comment by ggrossetie** [comment]
J'ai l'impression qu'on commence à converger vers une solution. Pour nous permettre d'avancer il faudrait valider ces choix et décrire de manière précise la liste des changements nécessaires.

Une maquette de @maiwann pourrait aussi nous permettre de mieux nous projeter. Qu'est-ce que tu en penses ?
L'idée serait de voir comment combiner au mieux les deux volets latéraux

**Comment by maiwann** [comment]
Hello ici,

Je suis frileuse à l'idée de faire des maquettes tant que je n'ai pas enquêté pour pouvoir avoir une idée un peu plus large des différents usages :) Peut-être que ça pourrait commencer par vérifier les différentes hypothèses de cette conversation en questionnant les utilisateurs ? On en discute au prochain point @antoinentl si ça te va ?

**Comment by antoinentl** [comment]
Pour synthétiser les différents points évoqués dans cette issue qui grandit :

- nous avons un problème initial : afficher les volets sans surimpression sur la zone de texte ;
- la discussion s'est élargie sur un autre affichage possible avec beaucoup d'options différentes, très pertinentes mais qui prennent plus de temps ;
- peut-être que le problème initial pourrait être réglé _simplement_ :
    - point de rupture défini par exemple à 1850px ;
    - passage de la colonne de gauche de 400px à 300px ;
    - passage de la colonne de droit de 400px à 300px ;
    - passage de la zone centrale de 1080px à 700px
    - diminution de la taille du texte dans les colonnes latérales et dans la zone centrale ;
    - résultat possible :

![Capture d’écran 2021-06-04 à 12 06 04](https://user-images.githubusercontent.com/6869488/120627586-cf94a900-c431-11eb-80d4-9418a3bb25a8.png)

- nous pouvons ensuite imaginer d'autres affichages pour l'agencement de ces différentes zones.

Qu'en pensez-vous ?
