### ISSUE TITLE
Profiler les requêtes MongoDB pour améliorer les performances

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#701]
Certaines requêtes n'aboutissent pas, ou sont lentes lorsqu'il y a beaucoup d'articles ([cf.](https://github.com/EcrituresNumeriques/stylo/issues/655#issuecomment-1354761387))

![Screenshot from 2022-12-16 08-19-11](https://user-images.githubusercontent.com/43650596/208107848-3679960e-8a47-4ba6-8b5f-4006b5ffe041.png)

## Profiling

J'ai activé le profiling sur stylo-dev et stylo-prod pour voir ce que ça repère :

```bash
> db.setProfilingLevel(1)
{ "was" : 0, "slowms" : 100, "sampleRate" : 1, "ok" : 1 }
```

Et, vu sur [Finding slow queries in MongoDB](https://www.oodlestechnologies.com/blogs/Finding-slow-queries-in-MongoDB/) : 

```mongo
# Query for the recent 10 entries
db.system.profile.find().limit(10).sort( { ts : 1 } ).pretty()

# Collection with the slowest queries(No. Of queries)
db.system.profile.group({key: {ns: true}, initial: {count: 0}, reduce: function(obj,prev){ prev.count++;}})

# Collection with the slowest queries(No. Of millis spent)
db.system.profile.group({key: {ns: true}, initial: {millis: 0}, reduce: function(obj, prev){ prev.millis += obj.millis;}})

# Most recent slow query
db.system.profile.find().sort({$natural: -1}).limit(1)
 
# Single slowest query(Right now)
db.system.profile.find().sort({millis: -1}).limit(1)
```

## Pistes identifiées

En regardant les requêtes du schéma Mongoose, du côté des `sort()` et des `find()` et des `populate()` :

- [x] ajouter un index sur `versions.createdAt`
- [x] ajouter un index sur `tags.createdAt`
- [ ] ajouter un index composite sur `tags.{_id, owner}`
- [ ] ajouter un index composite sur `articles{owner, contributors.user}`
- [ ] ajouter un index composite sur `articles{_id, owner, contributors.user}` ❓ 
- [ ] ajouter un index composite sur `articles{_id, owner}` ❓ 
- [ ] ajouter un index sur `user.permissions{ user, scope, roles }`
- [ ] supprimer l'index `tags.updatedAt`
- [ ] supprimer l'index `versions.updatedAt`

**Comment by ggrossetie** [comment]
30Mb pour un tri en mémoire en sachant que le contenu de l'article est dans la collection articles ça me paraît pas déconnant.

Je pense que l'ajout d'un index sur `updatedAt` sur la collection articles devrait corriger le problème : 

https://github.com/EcrituresNumeriques/stylo/blob/beb82382181b08e12e7c761a04ab7dccadf0f2ae/graphql/models/article.js#L78

**Comment by ggrossetie** [comment]
Apparemment ça serait déjà le cas :

```
db.articles.createIndex({ 'updatedAt': -1 })
```

🤔

**Comment by thom4parisot** [comment]
On fait des sorts sur les versions des articles dans le tableau de bord principal. @RochDLY doit avoir suffisamment de versions ou d'articles pour faire exploser un tri sur un champ non-indexé 😎

**Comment by thom4parisot** [comment]
Les indexes créés par `20220316-sorting-indexes.js` n'existaient pas sur stylo-dev. J'ai lancé le script pour voir.

**Comment by ggrossetie** [comment]
@thom4parisot Je n'ai plus revu cette erreur, je pense que la simplification du schéma MongoDB et le fait qu'on ait rajouté des index a corrigé le problème. Est-ce qu'on cloture ?

**Comment by thom4parisot** [comment]
Dac 👍🏻
