### ISSUE TITLE
La valeur d'état `live` ne reflète pas des données à jour dans l'interface

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#708]
Je m'en suis rendu en mettant à jour la bibliographie : la valeur `live.md` n'est pas actualisée avec la nouvelle valeur (qui diffère donc de `store.workingVersion.bibliography`.

Y'a plein de valeurs calculées dans le composant `Write` qui mériteraient peut-être une autre stratégie de traitement.

**Comment by ggrossetie** [comment]
@thom4parisot je dirais que ce n'est plus d'actualité avec les changements que l'on a fait ces dernières années/mois ?

**Comment by thom4parisot** [comment]
Ouaip 👍🏻
