### ISSUE TITLE
Monaco charge des dépendances externes via cdn.jsdeliver.net

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#709]
Cf. https://github.com/suren-atoyan/monaco-react/issues/168#issuecomment-762336713

L'effet produit est qu'il est impossible d'afficher l'éditeur de texte en local, sans connexion Internet.

Cf. [comment utiliser `monaco-editor` en tant que module npm](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package).

**Comment by ggrossetie** [comment]
😱 😱 😱
