### ISSUE TITLE
Le message d'erreur d'une requête sans jeton n'est pas explicite

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#711]
Ça devrait lancer une erreur 40x (401 ?) en cas d'accès inauthentifié à des routes nécessitant une authentification (ce qu'on ne flèche pas au niveau de l'API, si ce n'est en commentaire). 

❓ est-ce que GraphQL permet de documenter ça autrement ? Les validateurs ?

```json
{
  "errors": [
    {
      "message": "Cast to ObjectId failed for value \"undefined\" (type string) at path \"user\" for model \"User\"",
      "locations": [
        {
          "line": 19,
          "column": 3
        }
      ],
      "path": [
        "articles"
      ]
    },
    {
      "message": "Forbidden",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "user"
      ]
    }
  ],
  "data": {
    "user": null,
    "articles": null,
    "userGrantedAccess": []
  }
}
```

Quand `Authorization: Bearer …` est correct ça roule sans problème.

- [x] `Cast to ObjectId failed for value \"undefined\"` quand jeton absent
- [x] `  "error": "Unexpected token < in JSON at position 0"` quand la signature du jeton est invalide

**Comment by ggrossetie** [comment]
J'avais utilisé la classe `ApiError` pour renvoyer une exception fonctionnelle quand l'objet n'existe pas: https://github.com/EcrituresNumeriques/stylo/blob/fd0833efa8e35c7276b298dba309844812bf579c/graphql/helpers/errors.js#L1

Je ne sais pas trop si cela peut aussi s'appliquer à l'authentification... 🤔

**Comment by ggrossetie** [comment]
Est-ce que tu peux s'il te plait partager la requête GraphQL qui retourne cette réponse ?

**Comment by thom4parisot** [comment]
C'est en partie résolu avec [27d14aa](https://github.com/EcrituresNumeriques/stylo/pull/703/commits/27d14aad1befd947da6902631f248b143ba533aa) et [464a693](https://github.com/EcrituresNumeriques/stylo/pull/703/commits/464a693fb69dbf2169c71fb65b02c126f9147a48)

**Comment by thom4parisot** [comment]
> Est-ce que tu peux s'il te plait partager la requête GraphQL qui retourne cette réponse ?

On essayait avec @davidbgk de lister les article d'un user (la requête sur `/articles`).

Et j'ai tenté avec un jeton valide mais dont la signature ne matche pas avec le serveur (2ème erreur listée dans l'issue).

**Comment by ggrossetie** [comment]
Sur un compte partagé j'ai l'erreur suivante : 

<img width="471" alt="Capture d’écran 2023-01-09 à 12 47 46" src="https://user-images.githubusercontent.com/333276/211311464-6aacab66-a723-4d73-a99b-346e66658a9d.png">


```
Error: Forbidden [context [ 'args.user', 'token._id', 'user.id' ]]
```

**Comment by ggrossetie** [comment]
Petit hors sujet, mais ça me fait penser que tu as mentionné dans une pull request que la gestion des erreurs de l'API GraphQL est centralisée dans le frontend. Cela pourrait être pas mal de remplacer les `alert` par un message d'erreur plus "user-friendly" 😉

**Comment by thom4parisot** [comment]
Top merci, c'est carrément une régression causée par #704 

Bien vu, merci :-)

Tout à fait dac avec l'amélioration des `alert`es :-)
