### ISSUE TITLE
Les utilisateur·ices de Stylo ne créent pas de versions et se retrouvent embêter au moment de la relecture car il n'y a pas d'historique

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#721]
Les utilisateur·ices de Stylo n'utilisent pas le bouton "Créer une nouvelle version", donc ça complique le travail de relecture. Il n'y a pas de diff possible.

Une solution discutée aujourd'hui serait de créer automatiquement une version mineure lorsqu'on sort de l'article (lorsqu'on passe de `/article/*` à autre chose, ou lorsqu'on ferme l'onglet).

Dans ce fonctionnement : 
- si le contenu de la version la plus récente (md, bib, yaml) est identique à la `workingVersion` (md, bib, yaml)
  - alors la nouvelle version mineure n'est pas crée ;
  - sinon elle est créée

**Comment by RochDLY** [comment]
## Notes sur le comportement des versions
(conversation entre @marviro et @RochDLY)

- Dès qu'on ouvre un article, une nouvelle version (v0.1) est créee et tout le travail est automatiquement enregistré sur cette version.

Maintenant 2 possibilités:

1. Tout le monde quitte l'article **sans** enregistrer une version --> la version restera telle quelle (version 0.1 créée automatiquement à l'ouverture de l'article) et tout le travail y sera enregistré ;
  - dès que quelqu'un rouvre le même article il verra la version automatique comme enregistrée et pas modifiable et il sera sur une nouvelle version automatique
2. On enregistre une version (0.2) pendant que la version automatique (0.1) est ouverte -> la version automatique est écrasée avec la version enregistrée et une nouvelle version automatique est créee


Pour faire court: on remplace la workingversion avec une version automatique qui est freezée en version non modifiable dès que tout le monde a quitté l'article



**Question**: que se passe-t-il si quelqu'un reste inactif sur une version automatique (donc il ne sort pas, mais il ne travaille plus) ?

Est-ce qu'on décide qu'au bout de 5 ou 10 min d'inactivité on jette déhors?

**Comment by ggrossetie** [comment]
Je pense que c'est une mauvaise idée : 

- La notion de version correspond à un état à un moment précis. Si le contenu de la version change (i.e., son état change) c'est une version de travail.
- Pour moi la création d'une version doit correspondre à une action de l'utilisateur (surtout qu'on "duplique" le contenu, les métadonnées et la bibliographie sur chaque versions)
- La création de versions pose des problèmes lors de l'édition collaborative. Mettre en place des systèmes qui crée automatiquement des versions va amener des effets de bords. C'est d'ailleurs une des raisons pour laquelle on avait tant de problème lorsqu'on a mis en place l'édition collaborative pour la première fois.

Pour moi c'est une problème d'interface / d'utilisation.
Si les utilisateurs.rices n'enregistrent pas de versions c'est peut être que : 

- ils/elles ne voient pas l'intérêt
- ils/elles ne savent pas comment faire une version
- ils/elles pensent qu'une version se créent automatiquement

Peut être aussi que le terme "version" n'est pas le bon.
Peut être que le bouton "New version" devrait plutôt être dans l'entête et se nommer "Save edits" ou "Save my editing session". On pourrait d'ailleurs ouvrir une popup qui indique un peu plus le fonctionnement des versions / copie de travail.

On peut aussi avoir un bouton qui permet de "Quitter la session" et qui demande si on veut créer une version ou non.

**Comment by RochDLY** [comment]
Merci pour ces précisions. 

Effectivement la version doit se comporter comme tu l'as mentionné.
L'enjeu de cette fonctionnalité est trouver des manières pour montrer à l'utilisateur l'intérêt des versions (et pourquoi il est important d'en faire), sans en automatiser tout le fonctionnement (au risque de le cacher : si tout est automatisé et que Stylo le fait tout seul, pourquoi s'embêter à comprendre ?)
L'objectif est de trouver des stratégies pour montrer aux utilisateurs l'intérêt des versions, du coup toutes les stratégies que nous pouvons mettre en place sont bonnes à prendre : 

- voir les modifications de l'interface que tu proposais (avec un visuel de l'historique des versions); 
- remplacer "new version" par "save edits" (ou autre) ; 
- lorsque un utilisateur reste inactif sur sa session (et ça arrive souvent) plus de X minutes (par exemple 5 minutes) : afficher un message qui indique qu'une version automatique sera enregistrée dans X secondes, puis la session se ferme ?
- ajouter un bouton pour quitter et sauvegarder.

@marviro @antoinentl est-ce que j'oublie qqch ?

**Comment by marviro** [comment]
Petit suivi avec la demande d'une utilisatrice:

>si un auteur a modifié son article sans créer de version par après, je n'ai aucun moyen d'avoir un suivi des modifications ?

**Comment by ggrossetie** [comment]
- Enregistrement à la fin d'une session (collaborative ou solo)
- Identifier les "versions" crées automatiquement pour faire la distinction avec les versions crées manuellement
- Si la personne se fait kick d'une session solo (on enregistre ces changements dans une nouvelle version et on démarre une "nouvelle" version pour l'utilisateur qui a kick)

**Comment by ggrossetie** [comment]
Déployé sur stylo-dev
