### ISSUE TITLE
Normalisation valeurs yaml

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#723]
Les métadonnées renseignées dans le Yaml sont utilisée à différents endroits. Typiquement, dans le HTML, certaines valeurs sont utilisées dans le corps du texte _et_ dans les métadonnées.

Cela provoque un problème: si la valeur contient un formatage en md, cela est traduit avec des balises HTML qui ne peuvent pas être insérées dans les métadonnées.

Cela concerne particulièrement le champ `abstract`, `title`, `subtitle`, `acknowledgements`.

Avant les champs `title` et `subtitle` étaient doublés en `title` et `title_f`. Maintenant, je ne sais pas depuis quand, les champs `title` et `subtitle` n'existent plus, il y a juste `title_f` et `subtitle_f`

Je pense qu'il faudrait générer à la volée pour chaque champ (ces 4) une valeur normalisée, sans formatage.

Ex:

```
title: Mon _italique
```

devrait générer:

```
title_f: Mon _italique_
title: Mon italique
```

**Comment by thom4parisot** [comment]
C'est ce qu'on fait dans l'export Legacy : 

https://github.com/EcrituresNumeriques/stylo/blob/1a422d88031295cb31e69f9ee5b529eb9772200a/export/src/helpers/metadata.test.js#L75-L95

Peut-être que tu cherches à faire ça dans un autre contexte, genre les requêtes GraphQL ? Ou sinon, tu peux préciser où tu constates cette absence ?

**Comment by marviro** [comment]
Yes: requêtes graphql, vu que le nouvelle export est basé sur ça.

Mais outre que réintégrer la normalisation pour title et subtitle il faudrait l'ajouter pour abstract et aknoledgements

**Comment by thom4parisot** [comment]
Dac. On n'effectuait ces remplacements que dans l'export legacy, pas au niveau de l'API GraphQL.

Je vois comment transporter cette fonctionnalité à l'identique 👍🏻

**Comment by davidbgk** [comment]
Ah ça explique probablement pourquoi je suis obligé de faire des bidouilles de cet ordre là

https://gitlab.huma-num.fr/ecrinum/stylo/stylo-export/-/blob/main/styloexport/article.py#L159-168

**Comment by marviro** [comment]
Je me permets de rouvrir la issue car je suis en train de tester la rêquete:

```
query ($id:ID!){
  article(article:$id){
    workingVersion{yaml
     yamlReformated}
  }
  
}
```

et j'ai l'erreur suivante:

```
{'errors': [{'message': 'Cannot query field "yamlReformated" on type "WorkingVersion".',
   'locations': [{'line': 5, 'column': 6}]}]}
```

Désolé si c'est juste moi qui me trompe

**Comment by davidbgk** [comment]
Il faut maintenant mettre `yaml (options: { strip_markdown: true })`

**Comment by marviro** [comment]
merci!
