### ISSUE TITLE
Auto-complétion des références bibliographiques sur le caractère @ uniquement

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#728]
Dans stylo-dev: si on insère la première fois une référence biblio avec seulement un `@` sans `[`, les suggestions n'apparaissent pas. Par contre si on mets le `[@` elles apparaissent et par la suite elles apparaissent aussi si on met seulement le `@`.

Comportement souhaité: les suggestions devraient apparaître aussi si on met seulement un `@`, même la première fois.

**Comment by ggrossetie** [comment]
> Dans stylo-dev: si on insère la première fois une référence biblio avec seulement un @ sans [, les suggestions n'apparaissent pas. Par contre si on mets le [@ elles apparaissent et par la suite elles apparaissent aussi si on met seulement le @.

Je pense que c'est plus un bug qu'autre chose que l'auto-complétion s'affiche quand on saisie uniquement `@`.

> Comportement souhaité: les suggestions devraient apparaître aussi si on met seulement un @, même la première fois.

Je pensais qu'il fallait obligatoirement avoir le format `[@key]` pour insérer une référence bibliographique, cela fonctionne aussi avec `@key` ?

**Comment by marviro** [comment]
oui: deux comportements différents dans la conversion:

@blabla donne Blabla (année) tandis que [@blabla] donne (blabla année)
