### ISSUE TITLE
Déclencher l'auto-complétion bibliographique juste en commençant à taper @

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#732]

**Comment by ggrossetie** [comment]
je ne l'avais pas fait afin ne pas perturber l'écriture si on tape `@` dans un autre contexte. C'est peut être possible de contrôler que le `@` n'est pas au milieu de quelque chose pour ne pas déclencher la bibliographie si on tape une adresse email `foo@`

**Comment by thom4parisot** [comment]
Oui, genre le caractère précédent soit un `\W` (début de ligne, espace, parenthèse, etc.) ?

**Comment by ggrossetie** [comment]
> Oui, genre le caractère précédent soit un \W (début de ligne, espace, parenthèse, etc.) ?

Oui exactement 👍🏻 
En sachant que généralement il est aussi possible de "forcer" l'auto-complétion avec une combination de touches (genre <kbd>ctrl</kbd> + <kbd>@</kbd>) pour les cas particuliers/à la marge
