### ISSUE TITLE
Accès impossible à un article

### ISSUE THREAD

**Issue by vinber** [EcrituresNumeriques/stylo#742]
bonjour,
j'ai ajouté une image, je veux afficher les metadata, cela bloque. Je n'arrive plus à voir la partie édition.

La seule possibilité pour revoir l'éditeur est de me déconnecter et de me reconnecter.

https://stylo.huma-num.fr/article/63bd25601fc97a001483e776

PS : quelle découverte que stylo, merci

**Comment by thom4parisot** [comment]
C'est une conjonction de 2 bugs je crois : #639 (article créé sans métadonnées) et #686 (formulaire qui crash en cas de problème). Normalement résolu par #693, pas encore déployé.

**Comment by thom4parisot** [comment]
> PS : quelle découverte que stylo, merci

Ah oui ? Pourquoi ça ?

**Comment by vinber** [comment]
> Pourquoi ça ?

parce que cela fait un moment que je m'interroge sur le parcours d'écriture et la séparation du contenu et de la forme.
et donc les réponses qui me font dire quelle découverte
 - Le markdown
 - zotero qui est aussi une direction que je voulais creuser
 - et les possibles que je n'ai pas encore creusé sur la collaboration, l'annotation
 - le versionning même si je ne sais pas trop pour moi aujourd'hui si cela a du sens :)

et évidemment https://github.com/EcrituresNumeriques/stylo/blob/master/LICENSE

**Comment by vinber** [comment]
et "quelle découverte" c'est aussi parce que c'est par ton blog :) 

ne pas hésiter à fermer si c'est résolu dans le prochain déploiement, cela me va évidemment !

**Comment by thom4parisot** [comment]
Je confirme que c'est corrigé par 13a5c961dc79e661dc97007d8fce7cd28b3d369a et a28fa7c301e334f428709fa2de2d2b1d6786ba10.
