### ISSUE TITLE
Typo dans la doc

### ISSUE THREAD

**Issue by vinber** [EcrituresNumeriques/stylo#744]
je ne sais pas "corriger"
![image](https://user-images.githubusercontent.com/890869/212348941-7b8c2fb3-cba1-45c0-8eaa-76857f8f03ad.png)

http://stylo-doc.ecrituresnumeriques.ca/fr_FR/#!pages/premierspas.md

c'est hy**p**othes.is

**Comment by thom4parisot** [comment]
👀 [`docs/fr_FR/pages/premierspas.md`](https://github.com/EcrituresNumeriques/stylo/blob/master/docs/fr_FR/pages/premierspas.md)

**Comment by vinber** [comment]
oups, thanks https://github.com/EcrituresNumeriques/stylo/pull/745

**Comment by thom4parisot** [comment]
T'étais pas "censé savoir", c'est correct 🙂
