### ISSUE TITLE
[StyloDev] problème de versionnement

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#746]
Lors de la création d'une version d'un article sur Stylodev la page est devenue blanche et l'erreur "b is null" est apparue dans la console. 
![bugVersionsStyloDev](https://user-images.githubusercontent.com/43650596/212701305-1fda6b62-f2e5-4417-a73a-244f9ca14adb.png)

**Comment by thom4parisot** [comment]
@RochDLY tu peux retester voir ? A priori la version était créée, mais la valeur retour était incorrecte côté API.

**Comment by RochDLY** [comment]
ça fonctionne de mon côté, @marviro est-ce que pour toi ça fonctionne ?

**Comment by marviro** [comment]
Super, oui!
