### ISSUE TITLE
[StyloDev] Bouton "Annotate" non fonctionnel

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#747]
Dans Stylodev, lors du clic sur le bouton Annotate dans la partie centrale de l'interface la page devient blanche et une erreur apparaît. L'URL donne bien l'id de l'article mais pas sa version (il me semble que normalement le clic sur Annotate récupère par défaut la dernière version de l'article). 
PS : les boutons "Annotate" de chaque version dans le volet de gauche fonctionnent bien.

![annotateStylodev](https://user-images.githubusercontent.com/43650596/212702202-d1f6ce8f-eae9-4af4-85cf-aa3bfc7e94bb.png)

**Comment by thom4parisot** [comment]
Ça devrait être OK désormais. Tu confirmes ?
