### ISSUE TITLE
Quand je change de collection Zotero, le bouton "Replace bibliography" reste inerte

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#754]
Repéré par @Mmellet ce matin.

**Comment by RochDLY** [comment]
L'erreur qui apparait dans la console est la suivant : 

Something went wrong while fetching bibliography from Zotero: null TypeError: URL constructor: null/items is not a valid URL.

**Comment by thom4parisot** [comment]
> L'erreur qui apparait dans la console est la suivant :
> 
> Something went wrong while fetching bibliography from Zotero: null TypeError: URL constructor: null/items is not a valid URL.

Heu, quand tu fais quoi avec la biblio ? En donnant un identifiant ? En sélectionnant une collection dans la liste déroulante ? En te connectant à Zotero ?

Là, l'issue c'est qu'on ne peut pas appuyer sur le bouton.

**Comment by RochDLY** [comment]
Oui c'est la même erreur, j'ajoute des screenshots pour illustrer ainsi qu'un peu de détails : 

- Au niveau de la fonctionnalité : dans la gestion de la bibliographie, je peux importer une collection (via l'API Zotero), lorsque j'ouvre le menu déroulant "Pick a collection" j'ai la possibilité de choisir une collection Zotero liée à mon compte (qu'il s'agisse d'un nouveau choix ou d'une modification c'est le meme processus).
- Une fois la collection choisie je dois appuyer sur le bouton "Replace bibliography with this private collection" (c'est le même bouton pour un nouvel article ou un ancien à modifier)
- Dans Stylodev le bouton est grisé et lorsque j'ouvre la console j'obtiens l'erreur mentionnée ci-dessus 
![Screenshot from 2023-01-18 20-15-02](https://user-images.githubusercontent.com/43650596/213273433-b06f3a0f-62a0-4a47-bfdd-d139f172f6ce.png)

**Comment by thom4parisot** [comment]
Aaah ok, merci pour les précisions 🙂 

Je m'occupe de la résolution demain.
