### ISSUE TITLE
La bascule de compte n'est pas prise en compte dans `/books`

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#756]
- [x] proposer la même interface que dans `/articles`
- [x] honorer le choix utilisateur·ice, en ne voyant que les tags du compte bascule

À faire à la suite de #751

**Comment by thom4parisot** [comment]
@Mmellet 

![image](https://user-images.githubusercontent.com/138627/213030445-eaa43184-f4c0-48c9-95a5-b4487e0e8687.png)

**Comment by ggrossetie** [comment]
Ça me fait penser qu'il faut que j'intègre cette fonctionnalité de groupement d'articles dans les workspaces
