### ISSUE TITLE
Référence par défaut dans le module export 

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#759]
En l'état la référence par défaut est celle de Goody - *La Raison Graphique. La Domestication de la Pensée Sauvage*

![Screenshot from 2023-01-17 11-47-47](https://user-images.githubusercontent.com/40469215/212960695-c2b4ffd1-e046-466c-99a9-d3f27db72ab2.png)

Ce qui est un peu délicat...

Donc je propose de la changer pour : 

```
@book{woolf_chambre_2020,
	address = {Paris},
	series = {Le livre de poche},
	title = {Une chambre à soi: ou les femmes et la littérature},
	isbn = {9782253102007},
	shorttitle = {Une chambre à soi},
        language = {fre},
	number = {35881},
	publisher = {le Livre de poche},
	author = {Woolf, Virginia and Chiari, Sophie and Bastide, Lauren},
	year = {2020},
        origyear = {1929},
}
```

**Comment by thom4parisot** [comment]
@Mmellet #753 te conviendrait comme solution ?
