### ISSUE TITLE
Faire la liste des styles bibliographiques nécessaires et non-inclus dans la catégorie `humanities` de Zotero

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#760]
Annule et remplace #737

Les styles seront ajoutés dans l'image `stylo-export`.

**Comment by thom4parisot** [comment]
@davidbgk t'avais l'air de dire que c'était quelque chose que vous aviez adressé avec @marviro. Vu que des réserves avaient émises par @antoinentl, c'est quelque chose qui est réglé ?

**Comment by davidbgk** [comment]
@thom4parisot j'en ai parlé un peu [par ici](https://gitlab.huma-num.fr/ecrinum/stylo/stylo-export/-/merge_requests/10#note_62757), pour moi c'est en attente de constitution de la liste réduite pour pouvoir déterminer quelle serait l'interface adéquate.
