### ISSUE TITLE
Pousser plus loin les vertus d'apprentissages de l'article "How to Stylo"

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#762]
En complément de #761 : 

- [x] proposer un identifiant de collection/groupe Zotero avec des références bibliographiques (`2464757/collections/PLXDF42M`)
- [x] enregister une version majeure par défaut (pour illustrer le mécanisme de version, pour ne pas "perdre sa dent de lait")

Sur une idée/discussion avec @MathildeVrst et @mattheyje et @Mmellet.

**Comment by ggrossetie** [comment]
C'est une très bonne idée 👍🏻
