### ISSUE TITLE
Champ en doublon dans les métadonnées

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#773]
Sur stylo-dev on peut voir dans l'onglet "Metadata" que le champ "Translated title" est en double :

<img width="302" alt="Capture d’écran 2023-01-19 à 23 47 16" src="https://user-images.githubusercontent.com/333276/213587126-65e4faad-2f6f-4afd-aa6e-561bc48055f0.png">

Je pense que ce n'est pas voulu ?

**Comment by RochDLY** [comment]
Il me semble que ce problème n'est plus présent.
