### ISSUE TITLE
Grouper par tags

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#779]
Sur la liste d'articles, "apprendre" une nouvelle syntaxe de tags : `group:value`.

Par exemple, si on a `senspublic:issue/101` et `senspublic:issue/102`, on afficherait un seul tag : `senspublic`. Et quand le tag serait coché, il y aurait 3 groupes visuels : `issue/101` et `issue/102` et les articles pas dans des groupes.

Ça fonctionnerait pareil dans les Workspaces, pour ranger et organiser des contenus "par lot".

**Comment by ggrossetie** [comment]
Avec @maiwann on est en train de créer une distinction entre la classification par tags et un regroupement d'articles (corpus).

 > Et quand le tag serait coché, il y aurait 3 groupes visuels : issue/101 et issue/102 et les articles pas dans des groupes.

Est-ce que tu pourrais créer ce composant sur Figma ou le dessiner pour qu'on ait une idée du rendu ?

Après il y a encore des inconnues, est-ce qu'il ne serait pas préférable de créer un espace de travail "senspublic" et d'avoir des corpus issue/101, issue/102...? Est-ce qu'il y a beaucoup d'issues ? Est-ce que les mêmes personnes contribuent à l'ensemble des issues ? Si ce n'est pas le cas, on serait plutôt sur des espaces de travail spécifiques.

**Comment by ggrossetie** [comment]
Cela ne veut pas dire qu'il n'est pas utile d'avoir une hiérarchie dans les tags mais je pense qu'il faudrait valider avec @maiwann afin d'avoir quelque chose de cohérent entre tags/sous tags, corpus et espace de travail.

**Comment by ggrossetie** [comment]
Le format me fait penser à une recherche :

```
tag:senspublic tag:issue/101 brésil
```

☝🏻 recherche d'articles contenant le mot "brésil" avec le tag senspublic et issue/101

**Comment by thom4parisot** [comment]
Des entretiens avec @mattheyje aideraient à clarifier ce que j'ai posé par écrit oui (qui est une interprétation de ce que je comprends de bouts de conversations et de questions de surface).

**Comment by maiwann** [comment]
Je ne comprends pas du tout cette conversation :D Est-ce qu'on peut en papoter de vive voix ?

**Comment by ggrossetie** [comment]
D'après les discussions d'aujourd'hui je pense que l'on peut clôturer. Les espaces de travail devrait répondre au cas d'usage de Margot (distinguer les tags perso, des tags spécifiques à un groupe d'étudiants, une revue...). À valider avec @mattheyje que cela correspond aussi à son besoin.

**Comment by thom4parisot** [comment]
Oui et si on en a besoin on revisitera à l'occasion.
