### ISSUE TITLE
Distinguer les concepts de Tags et de Books

### ISSUE THREAD

**Issue by thom4parisot** [EcrituresNumeriques/stylo#781]
Un tag est une étiquette liée à un espace de travail (compte perso, compte partagé et workspace). Iel sert à étiquetter et organiser des contenus (workflow éditorial, etc.).

Un book est un ensemble d'articles : 

- dont l'ordre est défini manuellement
- avec son propre titre
- ses propres tags
- ses propres collaborateur·ices
- ses propres workspaces (?)
- ses propres métadonnées (+ cascade des métadonnées de chaque article ?)
- sa propre bibliographie (+ accumulation des bibliograhies de chaque article ?)
- et dont le contenu est l'accumulation du markdown de chaque article

**Comment by ggrossetie** [comment]
### Proposition "corpus"

Un corpus a :

- un titre
- des métadonnées
- une liste d'articles dans un ordre défini

<img width="1028" alt="Capture d’écran 2023-01-20 à 20 52 40" src="https://user-images.githubusercontent.com/333276/213803090-f80e5666-683a-4ffe-b72b-65c9f74fde28.png">

Un corpus peut être créer dans son espace personnel ou dans un espace de travail partagé.
Les collaborateurs sont gérés au niveau de l'espace de travail.
Pas de gestion de tags.

Pour la bibliographie je n'y ai pas réfléchi, je ne sais pas si ça fait sens de gérer la bibliographique au niveau du corpus ?

**Comment by thom4parisot** [comment]
Oui ça fait sens, et ça se recoupe. Y'a des entretiens à avoir avec @marviro, @RochDLY, @Mmellet, et @davidbgk (parce que discussions le 17/01 matin :canada: et jeudi 12/01 matin :canada:) et (il me semble), des personnes qui écriraient leur thèse avec Stylo.

Après la notion de "Corpus" ne dit pas "ce que ça fait" — c'est un nom d'interface/abstraction — alors que Books est un concept qui se décrit de lui-même, je trouve.

cc @maiwann

**Comment by ggrossetie** [comment]
Corpus : "Ensemble fini de textes choisi comme base d'une étude."

Si on applique ça à Stylo c'est un regroupement d'articles. La terminologie chapitre et livre ne correspond pas toujours, notamment si on écrit des cours ou des articles pour une chronique ou un dossier Sens public.
C'était une façon d'utiliser un terme plus générique qui à l'avantage d'être le même mot en français et en anglais 😄 

Après si le terme "Corpus" est peu parlant on peut trouver autre chose ou rester sur book si ça convient mieux.

**Comment by ggrossetie** [comment]
Comme pour les workspaces je vais travailler sur le modèle des données et sur l'API GraphQL. On pourra ensuite décider de la terminologie la plus appropriée et l'UI/UX.

**Comment by thom4parisot** [comment]
Ok 🙂

**Comment by RochDLY** [comment]
Commentaire après quelques échanges (pour plus tard) : 

À première vue il semble pertinent d'avoir une bibliographie du corpus mais de pouvoir en gérer des sous-ensemble pour chaque article. Pour résoudre ça je vois deux possibilités : soit l'accumulutation des biblio de chaque article, soit on associe un corpus à un groupe zotero au sein duquel on peut créer différentes collections qui peuvent être fetch par le gestionnaire bibliographique. 

exemple : on peut récupérer un groupe zotero via l'api : https://api.zotero.org/groups/4560891/ au niveau du corpus et ne rendre accessible aux articles du corpus et que les collections de ce groupe Zotero et les items qu'elles contiennent (https://api.zotero.org/groups/4560891/collections ou https://api.zotero.org/groups/4560891/items)
