### ISSUE TITLE
Problème de connexion sur Stylo Dev

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#782]
Lors d'une tentative de connexion sur Stylodev avec le compte de @marviro, une erreur est apparue sur l'écran d'accueil avec l'impossibilité de récupérer les articles associés au compte (même problème avec le compte de @Mmellet). 

L'erreur qui s'affiche dans la console est la suivante :  

```
GEThttps://example.matomo.cloud/piwik.js
[HTTP/2 403 Forbidden 183ms]

Loading failed for the <script> with source “https://example.matomo.cloud/piwik.js”. stylo-dev.huma-num.fr:1:1

```
L'erreur dans la pop-up de Stylo est la suivante : 

![Screenshot at 2023-01-23 08-29-20](https://user-images.githubusercontent.com/43650596/214065245-f31e1207-38fd-4f12-ab27-4a538894e7cf.png)

**Comment by ggrossetie** [comment]
Je ne reproduis pas avec mon compte et je ne pense pas que l'erreur Matomo soit liée, est-ce qu'il y a une stacktrace dans la console ?

**Comment by thom4parisot** [comment]
Le `.concat()` doit venir de la méthode `$inFromGrantees` dans un contexte pas pris en charge :-/ Un compte sans partage/partageur·se ?

**Comment by marviro** [comment]
nope: en console j'ai juste l'erreur matomo. Tout bon en network. Mais le problème persiste même en changeant de navigateur (et d'ordi) Si tu veux je peux te donner mon compte pour tester?

**Comment by thom4parisot** [comment]
L'URL Matomo n'est pas la bonne. Ça devrait être `https://analyseweb.huma-num.fr/`.

Mais ça me semble être sans incidence sur l'erreur de l'`alert` affichée en screenshot.

**Comment by RochDLY** [comment]
Je ne sais pas si c'est lié à une manip' en cours mais là j'ai une 502 lors d'une tentative de connexion (voir screen). Si ce n'est pas lié j'ouvre une autre issue.

![Screenshot from 2023-01-23 20-52-20](https://user-images.githubusercontent.com/43650596/214136605-99b200f7-c169-4df9-85bf-a9008a29c95a.png)

**Comment by ggrossetie** [comment]
> Je ne sais pas si c'est lié à une manip' en cours mais là j'ai une 502 lors d'une tentative de connexion (voir screen). Si ce n'est pas lié j'ouvre une autre issue.

Surement un déploiement en cours.
Bad Gateway 502 ça traduit que le service est down. Si c'est une erreur que tu ne reproduis pas c'est surement qu'au moment ou tu faisais des tests le service a été redémarré.

**Comment by thom4parisot** [comment]
Dans les logs du conteneur, c'est tombé avec l'erreur décrite dans https://github.com/EcrituresNumeriques/stylo/issues/786
