### ISSUE TITLE
Problème lors de la déconnexion de Stylodev

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#783]
Lorsque je me déconnecte de mon compte Stylodev, la page devient blanche et le message "Internal Server Error" s'affiche en haut de la page.
![Screenshot from 2023-01-23 15-34-23](https://user-images.githubusercontent.com/43650596/214065844-acd5c687-2b8e-4dbf-9955-b503d529b0ee.png)

**Comment by ggrossetie** [comment]
Normalement corrigé avec https://github.com/EcrituresNumeriques/stylo/commit/f0d1753f0d49df94b0c6dd5de1e6d5ebcd7c1c3a
