### ISSUE TITLE
Comportement erratique de l'autocomplétion des références biblio

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#785]
Lors de tests de cette fonctionnalité deux comportements sont apparus : 

- autocomplétion qui propose toutes les références dès que j'écris : [@ 
- autocomplétion partielle qui ne propose rien avec [@ et des proposition aléatoire avec [@ + une lettre ( [@a par exemple) : sauf que la lettre ne correspondait pas forcément à la première lettre de la référence (une lettre au hasard parmis toutes celles composant la clef de citation). Ce comportement ne permettait pas de récupérer les bonnes références (ex: [@v ne trouvait rien, alors que j'avais une clef de citation @vitali-rosati_ecrire_2020).

**Comment by ggrossetie** [comment]
> autocomplétion qui propose toutes les références dès que j'écris : [@

Je dirais que c'est "normal", qu'est-ce qui te choque dans ce comportement?

> autocomplétion partielle qui ne propose rien avec [@ et des proposition aléatoire avec [@ + une lettre ( [@A par exemple) : sauf que la lettre ne correspondait pas forcément à la première lettre de la référence (une lettre au hasard parmis toutes celles composant la clef de citation). Ce comportement ne permettait pas de récupérer les bonnes références (ex: [@v ne trouvait rien, alors que j'avais une clef de citation @vitali-rosati_ecrire_2020).

Si tu "annules" l'auto-complétion (i.e., que tu ne sélectionnes rien ou que tu appuies sur <kbd>Echap</kbd> ou que tu cliques à côté ou encore que tu saisies une lettre qui n'a pas de référence bibliographique) il faudra alors redemander l'autocomplétion explicitement avec <kbd>Ctrl</kbd> + <kbd>Space</kbd> (sur Linux)


[Auto-complétion de la bibliographie](https://user-images.githubusercontent.com/333276/217388819-eacfe99a-f795-4084-b62c-52abd4e24fd1.webm)

Dans cet exemple, je saisie `[@` qui s'autocomplète en `[@]` et qui déclenche l'auto-complétion de manière automatique. On peut voir que la recherche/filtre fonctionne bien jusqu'à ce que je saisisse "v". Je n'ai aucune référence bibliographique qui correspond donc l'auto-complétion s'arrête. Si je saisisse à nouveau "l" ou "a" ou "la" l'auto-complétion ne se déclenche plus, il faut que je fasse un <kbd>Ctrl</kbd> + <kbd>Space</kbd> (sur Linux) pour l'activer à nouveau.

**Comment by ggrossetie** [comment]
@RochDLY normalement c'est corrigé, tu confirmes ? on ferme ?
