### ISSUE TITLE
Niveau de titres

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#8]
Actuellement, le sommaire automatique considère que les titres de section sont les # et que les ## sont des titres de sous-section. Or, dans les pratiques d'écriture de Sens public on utilise les ## comme titres de section car on considère que le # est le titre de l'article et qui n'est donc pas utilisé dans le corps du texte (mais selement en métadonnées). Si @lakonis est d'accord, je propose qu'on change le sommaire en prenant en compte les ## comme titres de section

**Comment by PookMook** [comment]
Correction appliquée, en test avant release!
