### ISSUE TITLE
La largeur de l'onglet Raw Mode du panneau Metadata est parfois trop petite

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#810]
L'onglet Raw Mode est trop petit par rapport aux deux autres, une vidéo vaut mieux que 1000 mots :

[Capture vidéo du 2023-01-30 15:44:34.webm](https://user-images.githubusercontent.com/6869488/215591165-1b9e8bb7-8e68-46eb-a102-01ebeef1bc0e.webm)

(@ggrossetie je te l'attribue car il me semble que c'est toi qui avait les mains dans le CSS pour ceci)

**Comment by ggrossetie** [comment]
Dans la vidéo tu cliques sur l'onglet raw mode puis editor mode c'est ça ?

> je te l'attribue car il me semble que c'est toi qui avait les mains dans le CSS

Yes, parfait 👌

**Comment by ggrossetie** [comment]
@antoinentl je n'arrive pas à reproduire sur macOS avec Firefox ou Chrome. Peut être une question de taille d'écran mais la largeur de l'onglet "Raw mode" doit normalement être de 300px. Cela permet de conserver un éditeur texte d'au minimum 600px sur des écrans de 1280px.

Je n'ai pas d'écran plus large/grand sous la main, est-ce que tu peux tester avec une fenêtre de 1280px ?

**Comment by antoinentl** [comment]
@ggrossetie Je précise que l'onglet Raw Mode ne se comporte pas comme les deux autres, Basic Mode et Editor Mode, c'est juste ça mon problème. Tu peux tester sous Firefox avec CTRL+MAJ+M pour redimensionner à 1500px de large par exemple. Effectivement avec 1280px pas de souci.

(Je précise aussi que cette issue est de l'ordre du détail, rien d'urgent.)

**Comment by ggrossetie** [comment]
J'arrive à reproduire 👍🏻 
Je corrige ça.
