### ISSUE TITLE
Latence lors du chargement des articles

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#818]
Comportement remarqué par @marviro : Lorsqu'un compte a beaucoup d'articles, la page [Articles] de Stylo met plusieurs dizaines de secondes avant d'afficher les résultats de la requête. 
Est-il possible d'optimiser la requête pour un affichage plus rapide ?

**Comment by marviro** [comment]
Pour être plus précis: 120 articles, 18 secondes d'attente pour charger la page avec la liste des articles ;)

Avec @thom4parisot on s'est dit qu'il serait possible de limiter les requêtes. Deux pistes:

1. paginer (prendre les dernier 20 articles par ex et avoir un bouton pour charger les autres, ou alors charger lors du scroll). Le problème de cette option est ce qui se passe au moment de la recherche par titre...
2. Chercher pour chaque article seulement les informations nécessaires (titre? date? à définir) et charger les infos supplémentaire seulement lorsqu'on clique dessus (typiquement les versions)

**Comment by ggrossetie** [comment]
> Pour être plus précis: 120 articles, 18 secondes d'attente pour charger la page avec la liste des articles ;)

Cela me semble vraiment lent pour 120 articles. On fait combien de requêtes ? Est-ce que ce n'est pas à cause des partages de compte que c'est lent ?

**Comment by marviro** [comment]
Il est possible que mon ordinateur soit un peu coupable. Mais avec un ordi plus récent 8 secondes... donc tjs trop.

Je crois qu'il y a des requêtes sur toutes les versions de tous les articles...

Les partages de comptes : je sais pas, mais je crois que non, car les requêtes sont faite juste au moment où on clique... Au moins c'est ce que j'imagine

**Comment by antoinentl** [comment]
Je rajoute mon retour :

- stylo-dev : 14 secondes pour 173 articles, avec un ordinateur relativement récent et puissant
- stylo-prod : 4 secondes pour 172 articles, même situation

**Comment by ggrossetie** [comment]
A faire : 
- Mesurer précisément le temps de chargement (i.e., où est ce qu'on passe le plus de temps ?)
- Trouver des pistes d'optimisations

Questions ouvertes : 
- Est-ce qu'il serait envisageable de ne charger que les X derniers articles (par date de modification) et de charger le reste des articles de manière asynchrone ?
- Est-ce qu'il serait envisageable d'afficher uniquement X articles avec un button permettant d'en charger plus (ou une pagination) ?

**Comment by ggrossetie** [comment]
Je pense que les performance sont maintenant acceptable. Il faudrait refaire des tests sur les comptes ayant beaucoup d'articles afin de mesurer le gain et voir comment on peut continuer d'améliorer le temps de chargement.
