### ISSUE TITLE
[Utilisation des tags] Les articles taggés ne sont pas pris en compte par le filtre par tag sans réactualisation de la page

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#820]
Lorsque je "coche un tag" sur un article puis que dans la foulée je souhaite filtrer sur ce même tag, la liste renvoyée n'inclut pas l'article que je viens de cocher (idem si j'en coche plusieurs, aucun n'est retourné). De plus, lorsque je décoche le tag filtre, les articles cochés juste avant sont décochés automatiquement. 

Si je veux que le tag soit bien effectif sur un article, je dois réactualiser la page avant de filtrer. 

Est-il possible de ne pas passer par cette réactualisation de la page ?

**Comment by thom4parisot** [comment]
Oui c'est possible.

J'ai supprimé l'appel à une fonction qui faisait exactement ça, ne comprenant pas trop sa portée. Maintenant oui 😅

**Comment by ggrossetie** [comment]
@RochDLY je pense que ce n'est plus le cas, est-ce que tu confirmes ?

**Comment by ggrossetie** [comment]
Je cloture!
