### ISSUE TITLE
Les clés BibTeX ne sont pas formatées dans la "Preview"

### ISSUE THREAD

**Issue by giuliaferretti12** [EcrituresNumeriques/stylo#821]
La Preview stylo-dev affiche la clé BibTeX et non la citation intertextuelle affichée dans Stylo prod : Nom de l'auteur Date, le tout entre parenthèses. La date devrait être liée à l'entrée bibliographique correspondante par un lien interne.

**Comment by thom4parisot** [comment]
Es-ce que tu peux faire une capture d'écran de ce que tu décris ?

J'ai l'impression de comprendre mais je ne suis pas sûr où tu constates ça dans l'application.

**Comment by giuliaferretti12** [comment]
Oui!

<img width="568" alt="Screenshot_20230206_204917" src="https://user-images.githubusercontent.com/94019203/217070508-2c15e14f-781e-42c9-8ab1-9f6f2dc85e88.png">
<img width="403" alt="Screenshot_20230206_204949" src="https://user-images.githubusercontent.com/94019203/217070511-15f36577-f569-4ef1-85a3-1651fb735ea9.png">

**Comment by giuliaferretti12** [comment]
alors que sur stylo prod les références apparaissent comme ceci :
<img width="722" alt="Screenshot_20230206_205412" src="https://user-images.githubusercontent.com/94019203/217071584-0e540497-496f-4992-ba0b-253b95cde4ed.png">

**Comment by thom4parisot** [comment]
Super merci :)

**Comment by Mmellet** [comment]
Une chose que je remarque et que je pense lié : dans la v2, les références n'apparaissent pas dans la preview à la fin de l'article

**Comment by marviro** [comment]
Cette issue pour moi est celle qui a la plus haute priorité. Je te l'assigne @thom4parisot , mais je ne sais pas si c'est toi ou @ggrossetie ;) En tout cas c'est le patch le plus "urgent"

**Comment by thom4parisot** [comment]
On utilise une version plus récente qu'avant sur la preview-legacy, ça affecte peut-être la manière dont la bibliographie est intégrée. Le commentaire de Margot laisse à penser qu'elle n'est pas prise en compte, donc les références pas résolues.

PS : et de manière générale, j'aime pas qu'on m'assigne du travail sans vérification au préalable. Ça crée une attente de disponibilité, plutôt qu'à chercher comment/quand on la résoud (discussion).

**Comment by marviro** [comment]
> PS : et de manière générale, j'aime pas qu'on m'assigne du travail sans vérification au préalable. Ça crée une attente de disponibilité, plutôt qu'à chercher comment/quand on la résoud (discussion).

Pardon, c'était pas pour t'assigner le travail, juste pour entamer la discussion. Désolé si c'était pas la bonne manière de faire. C'est noté pour la suite

**Comment by Mmellet** [comment]
Le problème se pose encore mais dans un mode "moins pire" : 
![Screenshot from 2023-03-21 09-31-00](https://user-images.githubusercontent.com/40469215/226621306-552c7c65-f031-4f25-a182-0314b6b9b7f6.png)

**Comment by antoinentl** [comment]
@Mmellet Est-ce que les références en question sont bien dans les données bibliographiques ? Dans l'article How To ça n'est pas le cas (ce qui me semble par ailleurs étonnant).

**Comment by Mmellet** [comment]
@antoinentl  en effet elles ne sont pas dans les références. Désolée de ne pas avoir assez bien vérifié ! :trollface:

**Comment by antoinentl** [comment]
Ok le problème est identifié : il n'est pas possible de disposer plus de 10 références bibliographiques. Si j'importe une collection de 58 références alors je n'ai que 10 références importées. Le problème est plus grave : mes articles qui avaient plus de 10 références n'en n'ont apparemment plus que 10…

Je précise que les références ne sont pas non plus dans le fichier `.bib` exporté.

**Comment by antoinentl** [comment]
@Mmellet Non mais elle devraient être là, le problème est plus grave.

**Comment by ggrossetie** [comment]
@antoinentl je peux fermer cette issue ?

**Comment by antoinentl** [comment]
Oui, je précise donc qu'il n'y a pas de problème de formatage, je vais ouvrir une issue pour l'autre problème mineur dans lequel je me suis pris les pieds :upside_down_face:
