### ISSUE TITLE
Test export PDF sur Windows : Le fichier pdf n'apparaît pas dans le dossier zip.

### ISSUE THREAD

**Issue by giuliaferretti12** [EcrituresNumeriques/stylo#822]
En utilisant Stylo-dev sur un ordinateur Windows, je ne vois pas le document pdf dans le dossier zip généré par le module d'export, pas même lorsque je sélectionne le format pdf.

<img width="554" alt="Screenshot_20230206_165435" src="https://user-images.githubusercontent.com/94019203/217065436-62a2adcd-29a7-4888-9887-a713e8c1d629.png">
<img width="832" alt="Screenshot_20230206_165705" src="https://user-images.githubusercontent.com/94019203/217065437-b1f0b42a-1b4b-47aa-829a-4652c6b112d1.png">

**Comment by antoinentl** [comment]
Après un test sur Windows et une analyse du zip téléchargé, le PDF est bien produit.

Le problème, qui n'est pas du tout lié à Stylo, est que l'explorateur de fichiers Windows a un comportement _trompeur_ :

1. par défaut les extensions des fichiers ne sont pas affichées, le dernier fichier du zip dans la capture d'écran ci-dessus est bien un PDF
2. dans la colonne "Type" (ou "Tipo" en italien), c'est indiqué que c'est un fichier HTML parce que c'est Chrome par défaut qui ouvre les PDFs

**Comment by thom4parisot** [comment]
Woah, le piège…
