### ISSUE TITLE
Erreur lors d'un export répété (sous plusieurs formats)

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#823]
Quand je suis sur un article et que je veux l'exporter dans un format, disons en PDF, je récupère automatiquement le zip (ca c'est ok).
La fenetre des exports ne se ferme pas une fois le zip récupéré. Si je clique sur un autre format d'export à ce moment là (XML Métopes), l'export plante : Un onglet Stylo Export s'ouvre et une grosse boite orange indique : "Erreur pendant la génération de "nomDuFichier"."
Avec l'erreur suivante dans la console : "Uncaught TypeError : select is null"

**Comment by Mmellet** [comment]
Je note mon erreur ici même si je pense qu'elle est plus extrême : 

À partir d'un article qui fonctionne sur stylo-prod pour l'export PDF : je fais l'export PDF sur stylo-dev et cette page s'ouvre sans qu'aucun zip ait été téléchargé 


![Screenshot 2023-02-07 at 08-49-38 Stylo export](https://user-images.githubusercontent.com/40469215/217271223-71033584-22c3-4cad-8a29-23313839575c.png)

Id de l'article : 61a5130e83301d0013ed7932

**Comment by marviro** [comment]
pourriez-vous nous donner les id des articles?

**Comment by marviro** [comment]
Il faudra probablement déplacer la issue sur le repos de l'export
