### ISSUE TITLE
Documentation moins accessible

### ISSUE THREAD

**Issue by Mmellet** [EcrituresNumeriques/stylo#830]
Je ne suis pas sûre du nouvel emplacement de l'onglet Documentation : 

1. il est possible que cela dérange les habitués (moi j'ai mis du temps à le trouver)
2. ça rajoute un clic 

![Screenshot 2023-02-13 at 10-32-46 Stylo](https://user-images.githubusercontent.com/40469215/218501898-337e5dbc-19d4-4075-9255-7d5d88fa6af1.png)

Or si on l'enlève, en l'état, le menu User ne contient que la page des paramètres et la déconnexion (en attente de l'espace Worshop, qui, si je me souviens bien, devrait être placé ici). 

Mais j'ouvre ici à la discussion selon ce que l'on trouve plus logique. :speaking_head:

**Comment by antoinentl** [comment]
Même si je ne suis probablement pas représentatif je rencontre le même problème, conserver un _lien direct_ me semble pertinent, d'autant plus avec une nouvelle version qui s'en vient. Un avis @mattheyje, @MathildeVrst ou @giuliaferretti12 ?

**Comment by ggrossetie** [comment]
Le lien est aussi disponible dans le pied de page.

//cc @maiwann

**Comment by thom4parisot** [comment]
Ce que j'entends de la demande c'est que les dispositions actuelles des liens vers la documentation rendent plus difficile l'accès à une information considérée comme étant du même niveau que les éléments d'interface du menu principal.

**Comment by ggrossetie** [comment]
J'ai compris la même chose 👍🏻 
J'ai ping Maïtané car ça fait partie des changements d'interface qu'on a prévu avec l'arrivée des espaces de travail.

Le mot "Documentation" dans la barre d'entête prend pas mal de place (plus que "Articles" et "Books" ou "Corpus"). Peut être qu'une icône après le menu "utilisateur" suffit ?
Ou peut être utiliser le mot "Aide" / "Help" ?

<img width="52" alt="Capture d’écran 2023-02-13 à 17 19 52" src="https://user-images.githubusercontent.com/333276/218513123-1d58f029-d400-49f7-a9df-c33ce423c167.png">

**Comment by mattheyje** [comment]
> Même si je ne suis probablement pas représentatif je rencontre le même problème, conserver un _lien direct_ me semble pertinent, d'autant plus avec une nouvelle version qui s'en vient. Un avis @mattheyje, @MathildeVrst ou @giuliaferretti12 ?

Je suis d'accord! Je préfère aussi l'appellation Documentation car bilingue d'office (comme « articles » et éventuellement « corpus »).

**Comment by maiwann** [comment]
Effectivement je trouve pertinent de sortir Documentation de l'espace de navigation principal, car il n'en fait pas partie + "documentation" est un mot long qui rend le lien assez pregnant à coté de "Articles" et "Books" ou "Corpus"

Au vu de vos réactions, on va tenter de le laisser dans le header mais le décaler des 2 liens principaux. On verra plus tard (et bien après la sortie de la v2) si on le cache davantage ou non :)

**Comment by thom4parisot** [comment]
Avec cette disposition mise en place, c'est OK ?

![image](https://user-images.githubusercontent.com/138627/219450048-c02f3016-627a-4226-9136-edaf4c2bfd3d.png)

**Comment by ggrossetie** [comment]
Trop bizarre, pourquoi le symbole unicode ne s'affiche pas chez toi ? 🤔 

![image](https://user-images.githubusercontent.com/333276/219450349-eab9bad6-6f61-4e3e-884e-1f188f2d6144.png)

**Comment by mattheyje** [comment]
> Trop bizarre, pourquoi le symbole unicode ne s'affiche pas chez toi ? 🤔
> 
> ![image](https://user-images.githubusercontent.com/333276/219450349-eab9bad6-6f61-4e3e-884e-1f188f2d6144.png)

Ah oui moi non plus il ne s'affiche pas (firefox sur mac).

**Comment by maiwann** [comment]
Oui faisons comme ça pour l'instant, y passons pas plus de temps ! Merci ^_^

**Comment by antoinentl** [comment]
Je ferme le ticket, si une amélioration doit être faite on rouvrira un autre ticket ou celui-ci.
