### ISSUE TITLE
Erreur 502 bad gateway lors de la connexion

### ISSUE THREAD

**Issue by joseph-staline** [EcrituresNumeriques/stylo#834]
Impossible de se connecter sur Stylo ce matin :

- Lorsque je tente de me connecter avec mon adresse mail et mot de passe habituels : "Error. Email or password is incorrect"
  <img width="509" alt="Screenshot 2023-02-17 at 08 25 14" src="https://user-images.githubusercontent.com/104915084/219577777-2f8927de-8de4-4374-91ed-e26227c3ee3f.png">
- Quand j'essaye de me connecter avec Huma-num, j'ai une erreur : `502 Bad Gateway nginx/1.14.0 (Ubuntu)`
- Lorsque je tente d'accéder à la preview d'un de mes documents, j'obtiens aussi une erreur 502 :
  `{"error":{"type":"ClientError","message":"GraphQL Error (Code: 502): {\"response\":{\"error\":\"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\",\"status\":502,\"headers\":{}},\"request\":{\"query\":\"query ($articleId: ID!) {\\n    article (article: $articleId) {\\n      _id\\n      title\\n\\n      workingVersion {\\n        bib\\n        yaml (options: { strip_markdown: true })\\n        md\\n      }\\n    }\\n  }\",\"variables\":{\"articleId\":\"63af01da1fc97a001482af75\"}}}","stack":"Error: GraphQL Error (Code: 502): {\"response\":{\"error\":\"<html>\\r\\n<head><title>502 Bad Gateway</title></head>\\r\\n<body bgcolor=\\\"white\\\">\\r\\n<center><h1>502 Bad Gateway</h1></center>\\r\\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\\r\\n</body>\\r\\n</html>\\r\\n\",\"status\":502,\"headers\":{}},\"request\":{\"query\":\"query ($articleId: ID!) {\\n    article (article: $articleId) {\\n      _id\\n      title\\n\\n      workingVersion {\\n        bib\\n        yaml (options: { strip_markdown: true })\\n        md\\n      }\\n    }\\n  }\",\"variables\":{\"articleId\":\"63af01da1fc97a001482af75\"}}}\n    at /usr/src/app/node_modules/graphql-request/dist/index.js:340:31\n    at step (/usr/src/app/node_modules/graphql-request/dist/index.js:63:23)\n    at Object.next (/usr/src/app/node_modules/graphql-request/dist/index.js:44:53)\n    at fulfilled (/usr/src/app/node_modules/graphql-request/dist/index.js:35:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}}`

Est-ce que les serveurs d'Huma-Num sont surchargés en ce moment ?

**Comment by ggrossetie** [comment]
Bonjour @viclaspic 

Nous avons déployé une nouvelle version mais il y a des instabilités c'est la raison pour laquelle il y a des erreurs 502. Nous sommes en train de travailler sur ce problème afin de le résoudre. 

La cause a été consignée dans https://github.com/EcrituresNumeriques/stylo/issues/835
