### ISSUE TITLE
Positionner la valeur du token dans le fichier stylo.env lors du déploiement

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#841]
Sinon la valeur se perd et le déploiement est en echec.

**Comment by thom4parisot** [comment]
Lequel de token ?

**Comment by ggrossetie** [comment]
> Lequel de token ?

`SE_GRAPHQL_TOKEN`

Corrigé avec https://github.com/EcrituresNumeriques/stylo/commit/7168445e5dbb2d2445d0800208def90993ecb02d
