### ISSUE TITLE
Popup qui tourne en rond lors de l'export

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#842]
(Désolé pour ce titre un peu énigmatique.)

Une personne nous a interpellé concernant un problème lors de l'export depuis Stylo : la popup qui s'affiche lors du clic sur le bouton export contient un "Loading" qui ne s'arrête pas, avec l'impossibilité de choisir le format d'export.
La personne est tout simplement bloquée.
Voici la capture d'écran que cette personne nous a transmise :

![image001](https://user-images.githubusercontent.com/6869488/226750828-a7b2d02b-9e7b-48f4-a523-26be3902db79.jpg)

Cette personne utilise Firefox, sous Windows, sans utilisation d'extension qui bloquerait éventuellement des scripts JS.

**Comment by ggrossetie** [comment]
Une hypothèse est qu'on se base sur le BibTeX et si il est mal formatté on peut avoir une erreur ? Il faudrait regarder dans la console, il devrait y avoir une erreur. 
Ou alors c'est le service qui ne répond pas... 🤔

**Comment by ggrossetie** [comment]
Je cloture car on n'a pas assez d’éléments pour proposer une solution. Avec l'ajout de Sentry dans la prochaine version (3.2) on devrait être en mesure de corriger ce problème (si il existe encore).

**Comment by thom4parisot** [comment]
C'est arrivé quand le thread de stylo-export est occupé à générer un contenu (typiquement, quand c'est long et/ou produit un _timeout_).
