### ISSUE TITLE
Problème de partage

### ISSUE THREAD

**Issue by marviro** [EcrituresNumeriques/stylo#843]
Je suis connecté en tant que marviro. Je suis dans l'espace senspublic. J'essaye de partager un article avec David. David n'apparaît pas dans la liste, malgré le fait que je l'ai ajouté auparavant. Si j'essaye de le rajouter j'ai l'erreur suivante:

```

Uncaught (in promise) Error: Email is already an acquintance
    jF https://stylo.huma-num.fr/assets/index-fc0c279e.js:67
```
Ce qui montre que j'ai bien ajouté David. Mais il n'est pas dans la liste ;)

**Comment by ggrossetie** [comment]
Le système actuel de partage de compte a des limitations et j'ai un peu l'impression qu'à chaque fois qu'on veut corriger une limitation/anomalie, on introduit une regression ou une nouvelle anomalie 😬 

Je préfère investir du temps sur les espaces de travail, où ce problème n'existera plus, plutôt que de remettre les mains dans cette logique avec un résultat incertain.

**Comment by marviro** [comment]
entendu! même si cela pourrait devenir bloquant pour sens public. mais on s'en reparle au cas où. Je laisse l'issue ouverte du coup, pour l'avoir en tête
