### ISSUE TITLE
Interface multilingue : Traduction de l'interface de Stylo

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#844]

**Comment by ggrossetie** [comment]
Je pense qu'il y aura un travail pour mettre en place une solution comme https://www.i18next.com/ afin d'extraire les textes dans des fichiers json pour que les textes soient facilement éditables.

**Comment by RochDLY** [comment]
Qu'est-ce que ça implique en terme d'implémentation de cette brique dans Stylo (temps / faisabilité) ?

**Comment by ggrossetie** [comment]
Faisabilité je pense qu'il n'y aura pas de soucis (peut être que sur les formulaires dynamiques ça sera un peu plus tricky à mettre en place).
Pour la question du temps, je ne sais pas trop, je n'ai jamais mis en place ce genre de solution. Je pense que ça doit représenter quelques jours de travail afin d'extraire l'ensemble des textes dans un fichier et ensuite il faudra faire la traduction.
Je ne sais pas si vous avez prévu un élément dans l'interface permettant de changer la langue ? Par défaut, il existe des solutions permettant de détecter automatiquement la langue (https://github.com/i18next/i18next-browser-languageDetector).

**Comment by RochDLY** [comment]
Super, merci pour les retours. On en discute de notre côté et on te revient vite à ce sujet !

**Comment by marviro** [comment]
De mon côté je préférerais que la langue ne soit pas détectée automatiquement, mais choisie manuellement. Ça m’énerve quand les plateformes décident pour moi. Mais c'est juste mon avis

**Comment by ggrossetie** [comment]
> De mon côté je préférerais que la langue ne soit pas détectée automatiquement, mais choisie manuellement

Dans ce cas, il faut quand même une langue par défaut non ? L'autre solution est de demander à l'utilisateur "dès que possible" de choisir la langue mais je trouve ça un peu "intrusif".

À mon avis, il faut donner la possibilité de changer la langue à partir du nouveau menu utilisateur. Est-ce qu'on affiche la page de login en anglais ou est-ce qu'on donne aussi la possibilité de changer la langue sur la page de login (et sur la page de création de compte) ? Je ping @maiwann qui aura peut être un avis sur le sujet ?

L'autre solution serait d'ajouter une entrée dans l'entête avec "en" / "fr" (éventuellement avec une petite icône comme https://commons.wikimedia.org/wiki/File:Translation_icon_cropped.svg#/media/File:Translation_icon_cropped.svg ou https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/VisualEditor_-_Icon_-_Language.svg/1024px-VisualEditor_-_Icon_-_Language.svg.png)

**Comment by thom4parisot** [comment]
En discutant avec des gens aux [JDLL](https://jdll.org/) (dont la team Paged.js !), j'ai entendu plusieurs fois de [Weblate](https://weblate.org/fr/). Les traductions peuvent se faire à la fois sur Git et une interface en ligne.

**Comment by ggrossetie** [comment]
@thom4parisot je savais pas que tu venais aux JDLL,si j'avais su je me serais motivé pour passer faire un coucou 🤗 

> j'ai entendu plusieurs fois de [Weblate](https://weblate.org/fr/). Les traductions peuvent se faire à la fois sur Git et une interface en ligne.

ça a l'air plutôt pas mal, je connaissais pas du tout 👍🏻

**Comment by RochDLY** [comment]
@marviro pour valider, mais vu que nous sommes pour l'instant à cheval entre France / Québec est-ce qu'on part sur le français comme langue par défaut ? (j'imagine que nous serons à temps de modifier ce paramètre plus tard de toute façon ?)

Quand tu dis menu utilisateur, tu parles de la barre noire en haut de l'interface ? (je vois bien un en / fr ou un petit menu déroulant tout à droite de cette barre sous le sigle de langue par défaut, si on a "fr" par defaut, en cliquant dessus on pourrait voir "en", "it", "es", etc.)

J'en profite pour ajouter une question : est-ce qu'on peut récupérer comme langue par défaut celle qui est choisie par l'utilisateur lorsqu'il paramètre son navigateur ? (par exemple moi j'ai tout en anglais, et même sur les sites .fr lorsqu'il y a une version anglaise du site, Firefox me l'affiche en anglais par defaut). Mais je ne sais pas si ce réglage peut aussi se faire depuis Stylo ? ou si c'est pertinent

**Comment by ggrossetie** [comment]
> J'en profite pour ajouter une question : est-ce qu'on peut récupérer comme langue par défaut celle qui est choisie par l'utilisateur lorsqu'il paramètre son navigateur ? (par exemple moi j'ai tout en anglais, et même sur les sites .fr lorsqu'il y a une version anglaise du site, Firefox me l'affiche en anglais par defaut). Mais je ne sais pas si ce réglage peut aussi se faire depuis Stylo ? ou si c'est pertinent


Oui on peut, je pense que cette information est transmise via un entête `accept-language`.
Mon navigateur envoie des requêtes avec  `accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7`.

Marcello n'était pas emballé par le fait que la langue soit choisie automatiquement mais comme il faut afficher quelque chose dans une langue par défaut autant utiliser celle configurée par l'utilisateur.
Après si l'utilisateur a configuré des langues qui ne sont pas supportée, il faudra quand même afficher dans une langue par défaut. Par exemple:  `accept-language: es-ES;q=0.9,it;q=0.8,ja;q=0.7`. Dans ce cas, et si l'interface n'est disponible ni en espagnol, ni en italien ni en japonais, il faut qu'on affiche le site avec une langue par défaut (anglais ? français ?).

**Comment by RochDLY** [comment]
on peut laisser le français par défaut si la langue n'est pas supportée. À termes, nous pourrons ajouter une liste conséquente de langues dans Stylo (fr / en / it / pt / es / latin pour les puristes =) )

**Comment by maiwann** [comment]
Comme on me demande mon avis, j'ai l'impression que dans les logiciels libres, j'ai toujours vu que la langue par défaut était celle du navigateur, avec possibilité de la changer ensuite, et je ne vois pas de point négatif à fonctionner comme ça.

J'ai déjà utilisé Weblate en ligne, j'approuve :)

**Comment by ggrossetie** [comment]
Exemple complexe : 


```jsx
<Trans i18nKey="corpus.addPart.note">
  To add a new chapter, go to the <Link to={activeWorkspaceId ? `/workspaces/${activeWorkspaceId}/articles` : '/articles'}>articles page</Link> and select this corpus.
</Trans>
```


```json
{
  "corpus.addPart.note": "Pour ajouter un chapitre, allez sur la <1>page des articles</1> afin de sélectionner ce corpus."
}
```
