### ISSUE TITLE
Le chargement de la page /articles prend plusieurs secondes sur les comptes qui ont une centaines d'articles

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#853]
- Mesurer précisément le temps de chargement (i.e., où est ce qu'on passe le plus de temps ?)
- Trouver des pistes d'optimisation
- Est-ce qu'il serait envisageable de ne charger que les X derniers articles (par date de modification) et de charger le reste des articles de manière asynchrone ?
- Est-ce qu'il serait envisageable d'afficher uniquement X articles et un button permettant d'en charger plus (ou une pagination) ?

**Comment by thom4parisot** [comment]
C'est un doublon de #818 ?

**Comment by ggrossetie** [comment]
Oui exact, j'avais oublié qu'on avait déjà un ticket sur le sujet 😓
