### ISSUE TITLE
Ne pas passer `undefined` en clé de version à l'export

### ISSUE THREAD

**Issue by davidbgk** [EcrituresNumeriques/stylo#857]
Ici https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/components/Export.jsx#L28 

On a `&version=${articleVersionId}` qui devient `&version=undefined` dans certains cas, ça serait mieux que ça devienne `&version=` (ça reste un paramètre requis)

**Comment by ggrossetie** [comment]
La version d'un article est optionnelle quand on est sur une version de travail 

> (ça reste un paramètre requis)

C'est à dire qu'il faut que `version` soit présent mais peut être vide ?

**Comment by davidbgk** [comment]
Oui c'est ça 👍
