### ISSUE TITLE
Problème affichage insécables

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/stylo#89]
Les insécables apparaissent ainsi "&NonBreakingSpace;" dans le HTML. Ça peut se régler avec un simple find/replace, mais si c'est pas long à régler, ce serait top. Merci !

**Comment by lakonis** [comment]
peux tu préciser " " stp ? un espace simple ?

d'où vient l'insécable qui pose problème, c'est-à-dire comment a t il été édité dans le markdown : ctrl+shift+espace ? encodé dans la conversion word > markdown ? `&nbsp;` ?

**Comment by lakonis** [comment]
(the medium is the message)

**Comment by lakonis** [comment]
liste des caractères problématiques :

- `&NonBreakingSpace;` 		>>   `&nbsp;`
- `&OpenCurlyDoubleQuote;`	>>   `&ldquo;`
- autre ?

**Comment by lakonis** [comment]
@ServanneMo 

solution ici : https://framagit.org/snippets/3554

@marviro j'intègre ça dans le bash export articleSP ? qu'en penses tu ?

**Comment by ggrossetie** [comment]
@lakonis est-ce que ce changement a été fait ? est-ce qu'on peut clôturer ?

**Comment by lakonis** [comment]
c'est tout bon, je ferme.
