### ISSUE TITLE
Remplacer les apostrophes dans les noms des articles par un tiret

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#898]
## Problème rencontré
Lorsqu'un article a dans son nom (il s'agit bien du nom, ou titre du document, et non du _titre_ ou `title_f` de l'article) une apostrophe `’`, celle-ci est placée dans l'URL renvoyée à l'export, ce qui fait planter l'export. Alors que les apostrophes `'` ne posent pas de problème. Problème rencontré sur les instances de production et de développement. Exemple d'article : `6174193a8786b6001a0f0dae`. Ticket d'abord ouvert [ici](https://gitlab.huma-num.fr/ecrinum/stylo/stylo-export/-/issues/40).

## Solution envisagée
Il faudrait ajouter une règle pour transformer toute `’` par un tiret.

Si le problème n'est pas suffisamment expliqué je peux essayer de préciser.

**Comment by davidbgk** [comment]
Je dirais que c'est ici qu'il manque `’` https://github.com/EcrituresNumeriques/stylo/blob/master/front/src/hooks/pandoc.js#L59

**Comment by ggrossetie** [comment]
Je ne sais plus trop pourquoi on n'avait pas remplacé cette fonction par une librairie qui s'occupe de faire le slug comme https://github.com/simov/slugify

Il y a aussi ce gist qui peut être intéressant : https://gist.github.com/codeguy/6684588

Il faut que je fasse quelques tests pour voir ce qui fonctionne le mieux.

**Comment by davidbgk** [comment]
Je ne crois pas que le gist prenne en compte notre cas présent (nativement) ?

**Comment by ggrossetie** [comment]
Effectivemen, tu as raison, il faudrait aussi avoir une règle afin de remplacer la ponctuation par vide ou un tiret : https://www.compart.com/fr/unicode/block/U+2000

**Comment by davidbgk** [comment]
Oui, c'est le genre de scenario où je préfère une lib qui gère déjà tous les cas aux limites pour moi :)

**Comment by ggrossetie** [comment]
Avec `slugify` j'obtiens: `L'acte-editorial-:-vers-une-theorie-du-geste` (le `’` a été remplacé par une quote `'`). En mode `strict` et `lower` j'obtiens: `lacte-editorial-vers-une-theorie-du-geste`.

Je pense qu'on devrait utiliser ce dernier mode, moins de risque que le nom pose problème.

**Comment by davidbgk** [comment]
Certains bugs sont là pour l'éternité 😬 https://github.com/simov/slugify/issues/60

**Comment by marviro** [comment]
> Certains bugs sont là pour l'éternité grimacing [simov/slugify#60](https://github.com/simov/slugify/issues/60)

La réponse de simon:

>You can define you own custom regex to filter that character.

:rolling_on_the_floor_laughing:

**Comment by ggrossetie** [comment]
ça me choque pas vraiment puisque `'` est supprimé en mode "strict" : 

```js
slugify("pumpkin's") // "pumpkin's"

slugify("pumpkin's", {strict: true}) // "pumpkins"
```
