### ISSUE TITLE
Impossible de supprimer un article

### ISSUE THREAD

**Issue by Bepron** [EcrituresNumeriques/stylo#90]
Bonjour,
Lorsque j'essaie de supprimer un article j'utilise le bouton Delete, deux fois, mais ensuite plus de réaction, je suis obligé de recharger la page... pour voir que l'article que j'essaie de supprimer est encore là.
Merci

**Comment by thom4parisot** [comment]
@Bepron est-ce que ce problème persiste ? J'ai l'impression qu'il a été corrigé depuis.

On réouvrira ce ticket si ce n'est pas le cas :-)
