### ISSUE TITLE
Latence lors du lancement du mode collaboratif d'un article

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#909]
Lorsqu'un article est passé en mode collaboratif, il y a un certain temps de latence avant que les autres utilisateurs ayant accès à cet article le voient en *live* (plusieurs secondes) et puissent y accéder en collaboratif. 

Est-ce qu'il y aurait possibilité de réduire ce temps-là ?

**Comment by ggrossetie** [comment]
> Lorsqu'un article est passé en mode collaboratif, il y a un certain temps de latence avant que les autres utilisateurs ayant accès à cet article le voient en live (plusieurs secondes) et puissent y accéder en collaboratif.

Il y a effectivement une latence avant que les autres utilisateurs voient cet article en live mais ils peuvent y accéder en collaboratif avant que l'article apparaisse en live.


> Est-ce qu'il y aurait possibilité de réduire ce temps-là ? 

La seule solution que je vois c'est de créer une websocket où on publie des événements. Je pense que rafraîchir périodiquement la liste des articles est une mauvaise idée car les performances et l'impact sur le backend seront terribles.

Comme il y a une limite sur le nombre de websockets qu'on peut ouvrir sur le serveur, je ne sais pas si il est judicieux de faire une websocket par utilisateur. Peut être une websocket globale ? Cela veut dire que l'ensemble des utilisateurs connectés vont recevoir un message quand un article passe en mode collaboratif même si ils n'ont pas accès à cet article.

**Comment by thom4parisot** [comment]
Y'a [ServerSent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) qui est moins gourmand, et en mode "lecture seule".

**Comment by ggrossetie** [comment]
Oui c'est une bonne idée ! Par contre il doit quand même y avoir une limite côté serveur puisqu'il y a une connexion ouverte entre le client et le serveur ?

**Comment by ggrossetie** [comment]
Fermé par erreur

**Comment by ggrossetie** [comment]
Solution déployée sur stylo-dev.
