### ISSUE TITLE
update preview.css

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#91]
mise à jour (non cruciale) de la css `preview.css` à récupérer sur la branche master de `template-stylo` pour l'affichage de la preview dans stylo.
`stylo-export` est déjà à jour.

merci.

**Comment by PookMook** [comment]
Est-ce qu'il est safe de mettre la branche master de template-stylo dans l'export? En ce moment elle est sur book.
Si elle n'est pas safe, il faut juste backporter tous les changement de master -> book sur framagit pour que je mette a jour le submodule

**Comment by lakonis** [comment]
Je pense que c'est bien la branche book qui est sur process (stylo-export).
Il me faudrait nettoyer et émerger avant de prendre master.
Mais j'avais deja mis a jour le submodule en utilisant book. Ca
fonctionnait .

**Comment by PookMook** [comment]
Stylo est sur la branche book en ce moment pour tout ce qui est export (previews, html envoyé a process etc), je vois que preview.css a reçu 2 commit pour la correction de l'allemand/portugais sur master, mais pas sur la branche book,
Sur master il y a pas mal d'autres commits sur d'autres fichiers dont je ne sais pas s'ils affectent l'export (sur le latex et le xsl), est-ce qu'on merge juste le preview.css de master -> book et on reste sur book, ou est-ce que master est bon tel quel et on passe stylo sur la branche master?

**Comment by ggrossetie** [comment]
@lakonis toujours d'actualité?

**Comment by lakonis** [comment]
on peut fermer.
