### ISSUE TITLE
Latence lors de la fin du mode collaboratif sur un article

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#910]
Lorsque le *owner* qui a lancé la session collaborative la ferme, il y a un temps de latence assez long avant que les autres contributeurs soient kick de l'instance collaborative. 
(Par contre ce qu'ils écrivent après que la session soit coupée n'est pas enregistré, ça ça fonctionne bien :+1:). 

Est-ce qu'il y aurait la possibilité de réduire un peu ce temps de latence entre le clic sur le bouton de fin de session et le moment où les contributeurs sont ejectés de la session ?

**Comment by ggrossetie** [comment]
ça devrait être mieux avec https://github.com/EcrituresNumeriques/stylo/commit/97b6b3c755d6685622875b5bf399ed8658daddbd
