### ISSUE TITLE
Impossible d'ajouter une référence bibliographique dans le gestionnaire des références

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#916]
Dans le gestionnaire bibliographique, que l'on soit dans le mode [citations] ou [Raw BibTeX] il est impossible d'ajouter des contenus dans le premier (en supprimer reste possible), et impossible d'en ajouter ou en supprimer dans le second.

![Screenshot at 2023-07-03 15-53-34](https://github.com/EcrituresNumeriques/stylo/assets/43650596/3fbb97df-8088-4751-8ee6-5069d5b5976d)
![Screenshot at 2023-07-03 15-54-19](https://github.com/EcrituresNumeriques/stylo/assets/43650596/e5f6aa78-9719-4541-a5fe-611a7ca18b2d)

**Comment by ggrossetie** [comment]
J'ai vu ça ce matin et je l'ai corrigé sur stylo-dev. Tu peux valider que
le correctif fonctionne ?

**Comment by RochDLY** [comment]
Il ne fonctionne pas complètement, dans le mode Raw on est bon, mais dans [Citations] je ne peux pas ajouter de référence (le bouton [Add references] reste grisé.
