### ISSUE TITLE
Impossible d'accéder à de nombreux articles

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#917]
## Problème constaté
De nombreux articles ne sont plus accessibles (en production), il s'agit d'articles non partagés. Voici quelques exemples (partageables) liés à mon compte hi[at]quaternum.net :

- `5d9f777221cedb0019589c87`
- `6149e3a9b1984100196425ed`
- `5e6687fc4f58270018f9ddad`

Le message est le suivant :

```
Error

Article not found.
```

## Comportement attendu
Je devrais pouvoir accéder à ces articles, et pas seulement dans la liste des articles.

## Solution envisagée
Nous pouvons accéder à ces articles via GraphQL (test effectué par @marviro avec `5af38ad0447c821700332175`), il s'agit probablement d'un problème dans l'interface.

**Comment by ggrossetie** [comment]
@antoinentl ça devrait être corrigé, est-ce que tu peux tester à nouveau ?

**Comment by antoinentl** [comment]
@ggrossetie je te confirme que j'ai retrouvé les accès à tous mes articles. @marviro une confirmation de ton côté aussi ?

**Comment by marviro** [comment]
c'est bon pour moi!
