### ISSUE TITLE
Le bouton "envoyer une copie" ne fonctionne pas

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#919]
**Version de Stylo**

Stylo 2.1.3

**Comportement attendu**

Dans mon espace personnel, sur la page des articles, lorsque je clique sur le bouton pour envoyer une copie à un utilisateur Stylo, celui-ci doit recevoir dans son espace personnel une [Copy] de mon article.

**Comportement actuel**

Le destinataire ne reçoit pas de copie de l'article.

**Étapes pour reproduire le comportement actuel**

- Appuyer sur le bouton pour envoyer une copie
- Cocher la case du contact à qui l'envoyer (taper son adresse mail dans le formulaire au préalable si le destinataire n'est pas dans les contacts)

**Informations supplémentaires**

- Clé de l'article : 64ad629ebdacfe0012dc3898

**Comment by ggrossetie** [comment]
Je pense que ça doit être corrigé sur la version déployée en production ?

**Comment by ggrossetie** [comment]
@RochDLY tu confirmes ?

**Comment by RochDLY** [comment]
Ce n'est pas corrigé sur la version en production.
Je viens de retester à nouveau. Lorsque j'appuie sur le bouton [send a copy], je vois bien un message en bas à droite de l'écran me disant que j'ai bien envoyé une copie à X, cependant X ne reçoit pas cette copie dans son espace personnel.

**Comment by ggrossetie** [comment]
Effectivement, je viens de faire le test en production entre le compte senspublic et mon compte et ça ne fonctionne pas... 🤔
