### ISSUE TITLE
soucis métadonnées

### ISSUE THREAD

**Issue by EmmanuelleLescouet** [EcrituresNumeriques/stylo#92]
impossible d'accéder au panneau : lorsque je clique, j'obtiens un écran blanc...
(vu sur les articles : 5d03f19ddac870001970e770 et 5d03ca51dac870001970e76a )

**Comment by PookMook** [comment]
Bonjour Emmanuelle, le soucis de métadonnées est maintenant corrigé sur la version publique! 
Au lieu de crasher lorsque le Yaml est mal formé, le mode "raw" est maintenant forcé avec un message d'erreur pour aider à corriger le soucis!
![image](https://user-images.githubusercontent.com/14223903/60376610-2b508f00-99de-11e9-8889-9bd934c21c29.png)
