### ISSUE TITLE
Statut d'édition collaborative des articles

### ISSUE THREAD

**Issue by mattheyje** [EcrituresNumeriques/stylo#921]
Ce problème comporte deux volets : 
1) La marque d'un statut en cours d'édition perdure après que l'une des personnes travaillant sur l'article ait quitté l'édition. Par exemple, Giulia a quitté son article, mais nous ne parvenons pas à modifier les métadonnées de son article car nous n'y avons accès *que* par le mode d'édition collaboratif.

Cet article apparaît en cours d'édition :
![Capture d’écran, le 2023-08-01 à 13 22 00](https://github.com/EcrituresNumeriques/stylo/assets/54909770/e86e7f02-314c-4b9e-aed8-991dd9980941)

Mais lorsqu'on y accède par l'édition collaborative, nous sommes les seuls en ligne.
![Capture d’écran, le 2023-08-01 à 13 21 33](https://github.com/EcrituresNumeriques/stylo/assets/54909770/e9b7616a-8025-4655-8478-36148cd7b5b6)

**Comment by ggrossetie** [comment]
Hello Eugénie, est ce que tu pourrais s'il te plaît créer une "issue" par problème constaté ?

Le fait que le statut "édition solo" soit conservé lors de la duplication d'un article est une anomalie et me semble assez simple à corriger.

Est ce que l'idée était de dupliquer l'article afin d'accéder à ces métadonnées ?

Le premier problème constaté est quant à lui plus compliqué à reproduire/corriger et il nécessitera certainement l'ajout de logs pour que je puisse avoir le déroulé des actions qui ont conduit à cet état.

**Comment by RochDLY** [comment]
Pour le deuxième problème voir l'issue [#922](https://github.com/EcrituresNumeriques/stylo/issues/922). Effectivement l'idée était d'accéder aux métadonnées de cette manière.

Pour le premier problème, est-ce que ça ne pourrait pas être résolu par le renvoi à un mode "lecture" si l'utilisateur qui edite est inactif depuis X minutes ? (comme tu le suggérais ?)

**Comment by ggrossetie** [comment]
Je cloture car j'ai fais pas mal de modifications sur le statut de l'édition collaborative.
Si le problème existe toujours, recréer une issue avec la procédure permettant de reproduire systématiquement le problème.
