### ISSUE TITLE
Plusieurs copies d'un article sont créées en même temps, entraînant un problème de nomenclature des copies

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#923]
**Version de Stylo**

Stylo 2.1.1

**Comportement attendu**

Appuyer sur le bouton pour envoyer une copie d'un article crée une seule copie de l'article original.

**Comportement actuel**

Le problème déclaré à l'issue [#922](https://github.com/EcrituresNumeriques/stylo/issues/922), semble entraîner un problème additionnel de nomenclature des copies des articles : ici, on peut voir qu'une copie de ED16584 créée à partir de l'article ED1684 ouvert dans deux fenêtres différentes existe en parallèle de la copie de ED1684 n'étant  pas en cours d'édition.
![Capture d’écran, le 2023-08-01 à 10 09 25](https://github.com/EcrituresNumeriques/stylo/assets/54909770/91acf5a6-c9d1-4f81-97ef-d248f210b474)

**Étapes pour reproduire le comportement actuel**

Appuyer sur le bouton pour envoyer une copie d'un article.

**Informations supplémentaires**

**Comment by ggrossetie** [comment]
Apporter des précisions sur comment reproduire ce problème.

**Comment by ggrossetie** [comment]
@RochDLY je dirais que ce n'est plus d'actualité ?

**Comment by RochDLY** [comment]
effectivement, on peut clore ce ticket !
