### ISSUE TITLE
Ajouter le lien vers la partie "Publications" dans le menu de la documentation

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#930]
La page "Ressources" de l'_ancienne_ documentation n'a pas été reprise dans la nouvelle, est-ce qu'il ne serait pas pertinent de la réintégrer ?

**Comment by loup-brun** [comment]
La page existe bien ici, mais elle n'est effectivement pas renseignée dans le menu : 
https://stylo-doc.ecrituresnumeriques.ca/fr/publications/

Le chemin de la page pourrait d'ailleurs être revu...

**Comment by antoinentl** [comment]
Oups désolé je n'avais même pas vérifié dans les sources… "Publications" me semble parfaitement convenir ! Je modifie l'objet du ticket.

**Comment by loup-brun** [comment]
TODO: ajouter une entrée dans le menu:

- [ ] en français: `src/fr/fr.json`
- [ ] en anglais: `src/en/en.json`
