### ISSUE TITLE
Changement d'email pour un utilisateur "HumanID"

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#931]
Bonjour, j'aurais besoin d'une vérification avant de procéder à un changement d'email sur mon compte HumanID. Je voudrais m'assurer qu'en modifiant l'email associé à mon compte HumanID, je vais pouvoir:

1. conserver les documents que j'ai créé
2. conserver l'accès aux documents qui m'ont été partagé à l'ancienne email
3. conserver les contacts de partage
4. que les utilisateurs qui ont ajouté mon ancienne email pourront toujours me partager des documents sans ajouter la nouvelle adresse : si c'est bien le cas, savez vous quelle adresse s'affichera pour eux au moment de partager ?

Merci par avance !

**Comment by ggrossetie** [comment]
On utilise l'adresse email afin de retrouver le compte Stylo lié au compte HumanID. Si tu veux changer ton adresse email sur ton compte HumanID il faut qu'on fasse une mise à jour dans la base de données de Stylo sinon tu n'auras plus accès à ton compte Stylo.

**Comment by lakonis** [comment]
Entendu c'est noté. Malheureusement je n'ai pas le choix car l'ancien email va être fermé. J'ai donc changé d'adresse sur HumanID. Est-ce que je peux communiquer la nouvelle adresse email ici ? Merci @ggrossetie !

**Comment by ggrossetie** [comment]
Tu peux aussi me DM sur framateam avec l'ancienne adresse et la nouvelle pour que je fasse le changement en base de données.
