### ISSUE TITLE
Permettre de prendre la main sur une session d'édition solo

### ISSUE THREAD

**Issue by ggrossetie** [EcrituresNumeriques/stylo#935]
Permettre de prendre la main sur une session d'édition solo. Cette fonctionnalité est utile quand un utilisateur oublie de fermer une session d'édition ou qu'il ferme son navigateur sans "quitter" l'article.

Une fenêtre contextuelle doit s'ouvrir afin de présenter les informations suivantes : 

- Une personne est déjà en édition sur cet article (préciser le nom de la personne). Est-ce qu'on précise aussi son adresse email ?
- Date de début de la session d'édition
- Date de dernière modification de la copie de travail (correspond à la date de dernière modification de l'article dans cette session d'édition). Il peut être intéressant d'afficher cette information au format "Pas d'activité depuis 5 heures".
- Si vous prenez la main sur l'édition de cet article, la session d'édition de la personne X sera terminée/cloturée.

Le bouton d'action doit indiquer qu'on prend la main sur l'édition de l'article (et qu'on termine la session d'édition en cours). Il faut aussi ajouter un bouton "Annuler" afin de revenir en arrière.

Est-ce qu'on ajoute un message afin d'indiquer que dans le doute, il est préférable d'envoyer un message à la personne avant de prendre la main sur la session en cours ?

**Comment by ggrossetie** [comment]
ping @RochDLY @antoinentl @marviro @mattheyje  si vous avez des remarques ou des suggestions sur la formulation je suis preneur.

**Comment by ggrossetie** [comment]
À noter qu'actuellement une session collaborative peut prendre la main sur un session d'édition solo. La différence c'est que la session d'édition solo n'est pas terminée, elle est mise en pause. La personne de la session solo ne peut plus faire de changements sur la copie de travail. Quand la session collaborative se termine, la personne de la session solo peut à nouveau faire des modifications.

Est-ce qu'on conserve ce comportement, est-ce que là aussi on doit terminer la session solo ?

**Comment by RochDLY** [comment]
J'aurais tendance à dire qu'on doit garder le même comportement que l'on soit dans la configuration solo / solo ou solo / multi.

Lors du passage de la session solo à multi est-ce qu'on propose à la personne en solo de rejoindre la session multi ?

**Comment by RochDLY** [comment]
Pour les questions du premier commentaire : je ne suis pas sûr que mettre l'email soit primordial. Exemple : je partage un article avec 3 personnes, je sais qui elles sont, si je prends la main sur l'article, je peux envoyer un message par un autre canal que par mail.

Est-ce que ce ne serait pas plus "pratique" d'avoir une pop-up du côté de la personne dont la session a été fermée pour indiquer ce changement ?

**Comment by ggrossetie** [comment]
> Lors du passage de la session solo à multi est-ce qu'on propose à la personne en solo de rejoindre la session multi ? 

Pas pour le moment.
Ca serait bien de faire un schéma de l'ensemble des états/interactions afin qu'on soit d'accord sur les actions/messages à afficher.

**Comment by ggrossetie** [comment]
Je pense qu'il est préférable de dissocier édition solo de l'édition collaborative car on n'a pas accès à l'ensemble des fonctionnalités en édition collaborative.

Par conséquent : 

- Si on accède à un article qui est déjà en édition, on propose soit de prendre la main, soit de rester en lecture seule
- Si on démarre une session collaborative sur un article qui est déjà en édition, on propose de prendre la main ou d'annuler l'opération
- On ne peut pas accéder à un article en édition solo quand l'article est en édition collaborative

Quand on prend la main sur l'utilisateur qui était en édition, on lui affiche un message lui indiquant qu'il ne peut plus faire de modification car il n'a plus la main sur l'article.

Afin d'éviter les blocages, je pense qu'il faut permettre à n'importe qui dans la session collaborative à la terminer.  Est-ce que la version qui sera créée doit être associée à l'utilisateur qui termine la session collaborative ou à l'utilisateur qui a démarré la session collaborative ?



![image](https://github.com/EcrituresNumeriques/stylo/assets/333276/52081db6-871f-48ae-b814-3098a15f4ff1)

**Comment by marviro** [comment]
Je suis d'accord avec le fonctionnement proposé par @ggrossetie 

Important: les notifications. Quand quelqu'un prend la main, les autres sont notifiés (bulle qui dit: tu peux plus rien faire, désolé, untel a pris la main)

N'importe qui peut terminer l'édition collaborative: oui d'accord

Du coup je dirais que la version est au nom de celui qui termine... ou de tous ceux qui ont participé?

**Comment by ggrossetie** [comment]
Déployé sur stylo-dev
