### ISSUE TITLE
Comportement étiquettes cochées

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#937]
Séquence d'actions:

1. je filtre ma liste d'articles en cochant une étiquette (A)
2. j'ouvre un article dans la liste filtrée
3. je reviens à ma liste d'article en cliquant sur le lien Articles
4. la liste d'articles est filtrée selon l'étiquette que j'avais cliquée (A), mais... l'étiquette n'est pas cochée.
5. si je coche l'étiquette en question, la liste d'articles n'est plus filtrée. Si je décoche, la liste est filtrée selon cette étiquette.
6. si je coche une autre étiquette (B), j'ai un filtre [A **et** B]

Comportement attendu : 
1. soit on revient sur une liste non-filtrée (et toute étiquette décochée)
2. soit on revient sur une liste filtrée (et étiquette A cochée)

**Comment by ggrossetie** [comment]
Je pense qu'il est préférable de garder l'état de la liste. Dans ton exemple, le comportement attendu serait le 2 avec la liste filtrée et l'étiquette A cochée.

Je remarque aussi que l'indicateur d'édition solo ne s'actualise pas (ce qui porte à confusion) : 

![image](https://github.com/EcrituresNumeriques/stylo/assets/333276/b4e873ee-1906-4014-9c28-40e3f21a1a52)

Je crois que c'est déjà mentionné dans une autre issue.

**Comment by ggrossetie** [comment]
Corrigé dans https://github.com/EcrituresNumeriques/stylo/pull/942
