### ISSUE TITLE
[Documentation] ajouter un toc sur chacune des pages

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#944]
Certaines pages de la documentation sont très longues, on pourrait ajouter un toc sur la droite pour pouvoir naviguer plus facilement dans les contenus : https://www.npmjs.com/package/eleventy-plugin-toc

**Comment by loup-brun** [comment]
Pour info, un espace «navigation» est actuellement prévu dans les gabarits, mais elle n'est simplement pas remplie, prête à accueillir une éventuelle TdM.


![Capture d’écran du 2023-09-29 11-48-29](https://github.com/EcrituresNumeriques/stylo/assets/9596476/f8bf7797-d94a-40d7-ae93-82390a33ad1f)

**Comment by RochDLY** [comment]
J'ai ajouté les plugins markdown-it et markdown-it-anchor pour créer des ancres sur les titres (réparation de certains hyperliens qui pointaient sur des titres et pré-requis pour faire le toc).
J'ai également installé le plugin-toc cité précédemment.

**Comment by RochDLY** [comment]
Il y a une table des matières insérée avec le plugin toc via un web component (toc.webc). Il reste à améliorer le css

**Comment by loup-brun** [comment]
Tel que signalé en commentaires de la PR:

- il serait souhaitable de colocaliser le CSS de la TDM dans le composant (et non dans `docs.webc`)
- il est recommandé de nommer les _web components_ avec un trait d'union (ex. `page-toc.webc`) pour les distinguer d'éventuels éléments HTML qui porteraient le même nom (sans trait d'union)
- le CSS doit effectivement être revu à plusieurs égards (pourtant, cette fonctionnalité a été mergée sans vérification dans #939)
- voir #948, qui est désormais un problème introduit par cette très grosse fusion
