### ISSUE TITLE
Documentation: suite à une récente mise à jour, les couleurs de titre ne sont pas bonnes

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#947]
Les couleurs de l'ancre principale ne sont plus bonnes, en date du 5 octobre 13h.

En schéma de couleurs clair:

![bug-documentation-stylo](https://github.com/EcrituresNumeriques/stylo/assets/9596476/80a52f68-99d4-4d9e-8585-ccc8e6e11ded)

---

En schéma de couleurs foncé:

![bug-documentation-stylo-sombre](https://github.com/EcrituresNumeriques/stylo/assets/9596476/1940dd3c-686e-485e-9730-3162256e1a2f)

**Comment by loup-brun** [comment]
Régression introduite par #939 en raison d'une mauvaise colocation des styles de TDM (résultant en un _side-effect_).

**Comment by RochDLY** [comment]
fix dans #962
