### ISSUE TITLE
Documentation: la TDM sur chaque page est fixe et se surimpose sur les viewports étroits.

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#948]
Bris depuis #939 avec l'introduction débridée du composant `toc`.

---

Capture d'écran:

![bug-stylo-toc](https://github.com/EcrituresNumeriques/stylo/assets/9596476/77417e98-3dde-4876-9596-d6878b6d5f59)

**Comment by RochDLY** [comment]
Problème : la table des matières est (position:fixed). Peu importe la taille de l'écran, ça crée une superposition.
