### ISSUE TITLE
Documentation: le style des liens de pied-de-page n'est pas cohérent

### ISSUE THREAD

**Issue by loup-brun** [EcrituresNumeriques/stylo#949]
Régression introduite par #939 @RochDLY (à cause d'une mauvasie colocation des styles de la TDM).

Les liens devraient être de la même couleur que le texte.

---

Capture d'écran:

![style-liens-pied-de-page](https://github.com/EcrituresNumeriques/stylo/assets/9596476/1173aef8-eef6-4764-bd44-eceaba6150ea)

**Comment by RochDLY** [comment]
fix dans #962
