### ISSUE TITLE
Pb affichage des auteurs/contributeurs (page liste articles)

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/stylo#95]
Lorsque les contributeurs sont nombreux, on a un chevauchement entre les articles. Pas grave mais pas très élégant. 

![image](https://user-images.githubusercontent.com/14794908/60387518-71efc900-9a72-11e9-87b0-0bab6b249ca9.png)

**Comment by PookMook** [comment]
Fix in 21e765a3eaee283735a4ed165599b75150f8c6b8
