### ISSUE TITLE
[Workspace] Disparition de la liste des articles

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#950]
La liste des articles rattachés à un espace de travail a disparu, ils ne sont plus accessibles dans l'espace de travail. Par contre ils existent toujours chez leur propriétaire.

Dans l'image ci-dessous, la liste des articles est bien à 0 alors qu'elle devrait comporter plusieurs articles.

<img width="1159" alt="Capture d’écran, le 2023-10-27 à 17 49 36" src="https://github.com/EcrituresNumeriques/stylo/assets/43650596/d126c57f-296a-403f-8816-18a314d18f90">

**Comment by ggrossetie** [comment]
@RochDLY est-ce que tu peux s'il te plait préciser l'environnement, le compte qui consulte les articles et voir si il y a des erreurs dans la console ?

**Comment by RochDLY** [comment]
@ggrossetie, il n'y a malheureusement pas d'erreur dans la console

**Comment by ggrossetie** [comment]
Erreur sur la requête GraphQL:

```json
{
    "errors": [
        {
            "message": "Cannot read properties of undefined (reading 'tags')",
            "locations": [
                {
                    "line": 19,
                    "column": 5
                }
            ],
            "path": [
                "workspace",
                "articles"
            ]
        }
    ]
}
```
