### ISSUE TITLE
[front] interface en-fr : traduction du footer

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#960]

**Comment by ggrossetie** [comment]
fixed in https://github.com/EcrituresNumeriques/stylo/commit/d22a780b8ae585d5eff77442f7f3516f055a6c0c

Tu peux ajouter "resolves #xyz" dans le commit pour clôturer automatiquement l'issue lorsque l'on fusionne les changements.

**Comment by RochDLY** [comment]
ça marche ! merci pour la précision, je ferai ça lors des prochains commits :)
