### ISSUE TITLE
Ajouter l'entrée yaml translatedTitle dans le mode éditeur

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/stylo#976]
@RochDLY  Serait-il possible d'ajouter la possibilité de sortir le titre en anglais ? Sur Lodel, par défaut, on demande la traduction de toutes les métadonnées. À l'heure actuelle, on a bien la trad du résumé, mot-clés etc. mais pas du titre lui-même. Merci !

**Comment by ServanneMo** [comment]
En fait on a trouvé !

**Comment by ServanneMo** [comment]
En fait, le *translated title* apparaît dans le *basic mode*  du yaml editor, mais pas dans le mode editor. Serait-il possible de l'ajouter à un moment (et peut-être de documenter en attendant). Merci !

**Comment by RochDLY** [comment]
Il ne peut pas y avoir en une entrée dans le mode basique et pas dans le mode éditeur : L'affichage du mode basique "cache" des éléments existant dans le mode éditeur. C'est juste qu'il est un peu perdu dans toutes les métadonnées (entre Funder et Dossier)
