### ISSUE TITLE
Choix d'export biblio ne s'affiche pas

### ISSUE THREAD

**Issue by ServanneMo** [EcrituresNumeriques/stylo#977]
Problème d'affichage de l'export biblio : on est en formation avec plusieurs personnes, et selon les machines le bug se produit ou non  (mais cela ne semble pas dépendre du navigateur).

![image](https://github.com/EcrituresNumeriques/stylo/assets/14794908/b2057a84-29dd-44c0-8cbc-152148b2a840)

**Comment by RochDLY** [comment]
problème résolu: le gestionnaire de refs biblio était vide.

**Comment by ggrossetie** [comment]
@RochDLY dans ce cas peut être qu'il faut afficher un message explicite afin de clarifier ? cc @maiwann

**Comment by maiwann** [comment]
Oui c'est toujours plus cool d'être explicite :)

**Comment by ggrossetie** [comment]
@RochDLY @maiwann je vous laisser créer une issue dédiée pour afficher un message quand la biblio est vide. Je crois qu'on affiche aussi une biblio vide si il y a une erreur de syntaxe dans le BibTeX. Potentiellement on pourrait aussi afficher un message indiquant qu'il y a un problème.
