### ISSUE TITLE
Bug affichage lors de la création d'une première version dans un article

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#978]
**Version de Stylo**

3.0.2

**Comportement attendu**

Lorsque je crée une première version dans un article (mineure ou majeure), la version devrait s'afficher dans l'arbre des versions.

**Comportement actuel**

Lorsque je crée la première version dans un article, il me faut rafraichir la page pour la voir s'afficher dans l'arbre des versions.

**Informations complémentaires**

![testVersion](https://github.com/EcrituresNumeriques/stylo/assets/43650596/f825dff1-0b36-4a60-b62f-6856a8b8a4e4)

**Comment by ggrossetie** [comment]
Est ce qu'il y a une erreur dans la console lors de la création de la première version ?

**Comment by RochDLY** [comment]
Nop pas d'erreur, et il y a même le toaster qui apparait avec le message "Nouvelle version créée" (je l'ai pas pris dans la capture)

**Comment by ggrossetie** [comment]
Je pense que c'est lié au fait que l'API GraphQL (suite à la création) retourne:

```json
{"data": {"article": {"createVersion": {"versions": []}}}}
```

Il faudrait qu'on retourne la version nouvellement créée.
