### ISSUE TITLE
Intégration du multilinguisme dans le volet des métadonnées de l'éditeur

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#979]

**Comment by RochDLY** [comment]
En lien avec #654

**Comment by RochDLY** [comment]
Les traductions me semblent ok !

**Comment by RochDLY** [comment]
Arilys et Adrien ont relu le volet anglais des métadonnées. Après discussion, il semblerait qu'il n'y ait pas de réelle différence entre dossier/issue pour les anglophones. Il y a une préférence pour le terme _issue_ plutôt que _dossier_.

J'ai modifié les valeurs des clefs correspondantes dans #1083.

**Comment by ggrossetie** [comment]
Disponible sur stylo-dev
