### ISSUE TITLE
yaml: titre dossier

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#98]
Il semblerait que si le titre du dossier n'est pas renseigné, le template yaml ne génère pas de `title_f` pour la donnée dossier. La valeur `title` devient Varia, mais la valeur `title_f` n'existe pas.

```
./SP1395/SP1395.yaml:dossier:
./SP1395/SP1395.yaml-  - title: Varia
./SP1395/SP1395.yaml-    id: ''
```
VS
```
./SP1408/SP1408.yaml:dossier:
./SP1408/SP1408.yaml-  - title: Autogouvernement
./SP1408/SP1408.yaml-    id: '470'
./SP1408/SP1408.yaml-    title_f: Autogouvernement
```

**Comment by ggrossetie** [comment]
Je suppose que ce n'est plus d'actualité car il me semble que le `title_f` est maintenant bien généré. Peut être que c'était un problème ponctuel sur un article en particulier ?

Dans tous les cas, je pense qu'il faut fermer ce ticket et en réouvrir un si le problème revient en précisant comment reproduire l'anomalie.

Qu'est-ce que tu en penses @lakonis ?
