### ISSUE TITLE
Module Export: problème récurrent de non affichage de le paramètre de style CSL

### ISSUE THREAD

**Issue by lakonis** [EcrituresNumeriques/stylo#980]
Bug observé la semaine dernière lors d'une formation stylo, puis à nouveau cette semaine lors d'une autre formation.

La semaine dernière le module d'export n'affichait pas (pas du tout) le paramètre de style CSL sur mon navigateur (Firefox à jour sur Manjaro à jour). Plusieurs utilisateurs indiquaient ne pas avoir le paramètre non plus. 

Cette semaine tout s'affichait bien chez moi, mais d'autres utilisateurs indiquaient ne pas avoir le paramètre.

Je retente ce matin, à nouveau, pas de paramètre de style : 

![image](https://github.com/EcrituresNumeriques/stylo/assets/9479788/4e804ad7-78e2-4a38-833f-f0f90a62c6ed)

Bug aléatoire ?

**Comment by marviro** [comment]
Je pense que ce n'est pas un bug: le style ne s'affiche pas s'il n'y a pas de références dans le bibtex. Ce qui était le cas dans l,article stylo en question. À suivre avant de fermer la issue. De mon côté, après la formation - et en tenant en compte seulement les articles avec au moins une référence bibliographique - je n'ai plus reproduit le bug

**Comment by lakonis** [comment]
En effet, je viens de tester sur plusieurs articles. Je ferme.
