### ISSUE TITLE
La prévisualisation HTML des corpus n'affiche pas la bonne version des articles

### ISSUE THREAD

**Issue by RochDLY** [EcrituresNumeriques/stylo#993]
**Version de Stylo**

Stylo 3.0.7

**Comportement acturel**

La prévisualisation des HTML d'un corpus affiche la première version d'un article (voir GIF dans les informations complémentaires).

**Comportement attendu**

La prévisualisation HTML d'un corpus doit afficher la dernière version (version de travail) de chaque article du corpus.

Questions : 
- aurait-on besoin de versionner les corpus ? exemple :  corpus version 1.0 = article 1 version 2, article 2 version 3.1, article 3 version 1.0
- aurait-on besoin de choisir les versions des articles à intégrer dans le corpus (soit depuis le gestionnaire des articles soit depuis le gestionnaire des corpus ?)

**Informations complémentaires**

GIF pour reproduire le problème

![testPreviewCorpus](https://github.com/EcrituresNumeriques/stylo/assets/43650596/df568dc3-f583-4157-ad6d-b1595c4c1d5d)

**Comment by ggrossetie** [comment]
Très bien le petit gif !
Il me semble qu'on avait convenu d'utiliser la working copy sur les corpus. Je suis assez surpris de ce comportement, il faut que je regarde de plus près... 👀

**Comment by ggrossetie** [comment]
Alors la logique c'est : 

```js
    const workingVersion = chapter.versions.length > 0
      ? chapter.versions[chapter.versions.length - 1]
      : chapter.workingVersion
```

Normalement les versions sont triées par date de création: `versions.sort((a, b) => b.createdAt - a.createdAt)`
